% t_cMosaicReassignCones
%
% Demo basic usage of how to reassign the identity of any cone(s) in a @cMosaic.
%
% Description:
%    Shows how to reassigne the identity of any cone(s) in a @cMosaic.
%

% History:
%    08/24/22  NPC  ISETBIO Team, Copyright 2022 Wrote it.


% Generate a small mosaic
c = cMosaic(...
    'sizeDegs', 2*[0.02 0.01], ...
    'noiseFlag', 'frozen', ...
    'randomSeed',3 );

% Visualize the mosaic, each time outlining one of the first 6 cones
hFig = figure(1); clf;
for iCone = 1:6
    ax = subplot(3,2,iCone);
    c.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'domain', 'microns', ...
        'domainVisualizationLimits', 2*[-3.5 3.5 -2.5 2.5], ...
        'outlinedConesWithIndices', iCone, ...
        'backgroundColor', [0 0 0], ...
        'plotTitle', sprintf('outline: cone %d', iCone));
end


% Let cones [2 and 4] be S-cones
c.reassignTypeOfCones([2 4], cMosaic.SCONE_ID);

% Let cone 1 be an M-cone
c.reassignTypeOfCones(1, cMosaic.MCONE_ID);

% Let cones [3 and 5] be L-cones
c.reassignTypeOfCones([3 5], cMosaic.LCONE_ID);

hFig = figure(2); clf;
for iCone = 1:6
    ax = subplot(3,2,iCone);
    c.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'domain', 'microns', ...
        'domainVisualizationLimits', 2*[-3.5 3.5 -2.5 2.5], ...
        'outlinedConesWithIndices', iCone, ...
        'backgroundColor', [0 0 0], ...
        'plotTitle', sprintf('outline: cone %d', iCone));
end
