function visualizeFittedMultiFocalRTVF(mosaicCenterParams, rfModelParams, opticsParams, varargin)
    
    validVisualizedComponents = { ...
        'cone quantal efficiencies and psfs', ...
        'retinal RFs and psfs', ...
        'stfs and psfs', ...
        'fitted locations' ...
        };

    % Parse input
    p = inputParser;
    p.addParameter('visualizedComponents', 'all', @(x)(ismember(x, validVisualizedComponents)));
    p.parse(varargin{:});

    visualizedComponents = p.Results.visualizedComponents;

    % Generate mosaic filename and directory
    [mosaicFileName, mosaicDirectory] = midgetRGCMosaicInspector.mosaicFileName(mosaicCenterParams);

    % Assemble R2CVFT filename
    R2VFTobjFileName = midgetRGCMosaicInspector.R2VFTobjFileName(mosaicFileName, opticsParams, rfModelParams.H1cellIndex);

    % Load the midgetRGCMosaic
    fprintf('\nLoading the midget mosaic file: %s\n', mosaicFileName);
    load(mosaicFileName, 'theMidgetRGCmosaic');

    % Load the list of fittted RTVF objects and the sampling grid
    fprintf('\nLoading the RTVF objects file: %s\n', R2VFTobjFileName);
    load(R2VFTobjFileName, ...
        'theRTFVTobjList', ...
        'theOpticsPositionGrid', ...
        'theConesNumPooledByTheRFcenterGrid', ...
        'theVisualSTFSurroundToCenterRcRatioGrid', ...
        'theVisualSTFSurroundToCenterIntegratedSensitivityRatioGrid');

    switch (visualizedComponents)
        case 'stfs and psfs'
            figNo = 100;
            RTVFmultifocal.visualizeFittedLocationsCombo(...
                mosaicDirectory, figNo, ...
                theMidgetRGCmosaic, ...
                theRTFVTobjList, ...
                theOpticsPositionGrid, ...
                theConesNumPooledByTheRFcenterGrid, ...
                'topPanelInfo', 'L-center STFs & L-weighted PSF', ...
                'bottomPanelInfo', 'M-center STFs & M-weighted PSF', ...
                'visualizedSpatialRangeArcMin', 6, ...
                'figPostfix', 'stfs');

        case 'retinal RFs and psfs'
            figNo = 100;
            RTVFmultifocal.visualizeFittedLocationsCombo(...
                mosaicDirectory, figNo, ...
                theMidgetRGCmosaic, ...
                theRTFVTobjList, ...
                theOpticsPositionGrid, ...
                theConesNumPooledByTheRFcenterGrid, ...
                'topPanelInfo', 'retinal L-center RF subregions & L-weighted PSF', ...
                'bottomPanelInfo', 'retinal M-center RF subregions & M-weighted PSF', ...
                'visualizedSpatialRangeArcMin', 6, ...
                'figPostfix', 'retinalRFs');
        
        case 'cone quantal efficiencies and psfs'
            figNo = 100;
            RTVFmultifocal.visualizeFittedLocationsCombo(...
                mosaicDirectory, figNo, ...
                theMidgetRGCmosaic, ...
                theRTFVTobjList, ...
                theOpticsPositionGrid, ...
                theConesNumPooledByTheRFcenterGrid, ...
                'topPanelInfo', 'retinal quantal efficiencies', ...
                'bottomPanelInfo', 'PSFs', ...
                'figPostfix', 'psfs');

        case 'fitted locations'
            figNo = 100;
            RTVFmultifocal.visualizeFittedLocations(...
                mosaicDirectory, figNo, ...
                theMidgetRGCmosaic, theOpticsPositionGrid, ...
                theConesNumPooledByTheRFcenterGrid);

        otherwise
            error('Not implemented')
    end

end
