function initializeSimulationParams(app)

    % visual field params
    app.visualFieldParams = struct(...
        'fieldOfViewDegs', 3.0, ...
        'polarEccentricityDegs', 30, ...
        'radialEccentricityDegs', 10.0, ...
        'eye', 'left eye', ...
        'magnificationFactorMicronsPerDeg', Inf ...
    );

    % cone mosaic params
    app.coneMosaicParams = struct(...
        'eccentricityDegs', [0 0], ...
        'sizeDegs', [0.2 0.2] ...
        );
    fprintf('In ''CSFgeneratorApp.%s()''\n', mfilename());
end
