function initializeSimulationParams(app)

    % visual field params
    app.visualFieldParams = struct(...
        'fieldOfViewDegs', 3.0, ...
        'polarEccentricityDegs', 30, ...
        'radialEccentricityDegs', 10.0, ...
        'whichEye', 'right eye', ...
        'magnificationFactorMicronsPerDeg', Inf ...
    );

    fprintf('In ''CSFgeneratorApp.%s()''\n', mfilename());
end
