function simulationParams(app)

    % Visual field params
    app.visualFieldParams = struct(...
        'fieldOfViewDegs', 1.0, ...
        'polarEccentricityDegs', 0, ...
        'radialEccentricityDegs', 1.0, ...
        'whichEye', 'right eye', ...
        'magnificationFactorMicronsPerDeg', Inf ...
    );

    % Cone mosaic params
    app.coneMosaicParams = struct(...
        'visualizationDomain', 'degrees');
    
    % Optics params
    app.opticsParams = struct(...
        'subjectDataset', 'Polans2015', ...
        'subjectID', 10, ...
        'pupilDiameterMM', 3, ...
        'subtractCentralRefraction', true, ...
        'visualizedWavelength', 550 ...
        );

    % Stimulus params
    app.stimParams = struct(...
        'presentationMode', 'counterphased', ...
        'durationSec', 50/1000, ...
        'temporalFrequencyHz', 4, ...
        'spatialEnvelope', 'smooth', ...
        'orientationDegs', 45, ...
        'spatialFrequencyCPD', 11.0, ...
        'sizeDegs', 1.0, ...
        'resolutionPixels', 128, ...
        'positionDegs', [-1 3], ...
        'mosaicCenteredPosition', true, ...
        'meanLuminanceCdM2', 150, ...
        'LconeContrast', 80, ...
        'MconeContrast', 80, ...
        'SconeContrast', 80, ...
        'wavelengthSupportMin', 400, ...
        'wavelengthSupportMax', 750, ...
        'wavelengthSupportStepSize', 50);

end
