function simulationParams(app)

    % visual field params
    app.visualFieldParams = struct(...
        'fieldOfViewDegs', 1.0, ...
        'polarEccentricityDegs', 30, ...
        'radialEccentricityDegs', 10.0, ...
        'whichEye', 'right eye', ...
        'magnificationFactorMicronsPerDeg', Inf ...
    );

    % Cone mosaic params
    app.coneMosaicParams = struct();
    
    % Optics params
    app.opticsParams = struct(...
        'PolansSubjectID', 10, ...
        'pupilDiameterMM', 3, ...
        'subtractCentralRefraction', true, ...
        'visualizedWavelength', 550 ...
        );
    fprintf('In ''CSFgeneratorApp.%s()''\n', mfilename());
end
