function simulationParams(app)

    % Where to export data
    app.exportDirectoryName = fullfile(strrep(sprintf('%s', isetRootPath), 'isettools', ''), ...
        'demoApps/CSFGenerator2/scripts/exportedPipelines');

    % Debug via visualization flags
    app.debugParams = struct(...
        'visualizeConeMosaicActivationComponents', true ...
    );
    
    % Region of interest params
    app.roiParams = struct(...
        'fieldOfViewDegs', 1.5, ...
        'polarEccentricityDegs', 30, ...
        'radialEccentricityDegs', 1.0, ...
        'radialEccentricityScaling', 'linear', ...
        'whichEye', 'right eye', ...
        'magnificationFactorMicronsPerDeg', Inf ...
    );

    % Cone mosaic params
    app.coneMosaicParams = struct(...
        'eccVaryingMacularPigmentDensity', true, ...
        'eccVaryingMacularPigmentDynamic', ~true, ...
        'eccVaryingConeAperture', true, ...
        'eccVaryingConeApertureBlur', ~true, ...
        'eccVaryingOuterSegmentLength', true, ...
        'tritanopicRadiusDegs', 0.15, ...
        'lConeRatio', 0.6, ...
        'mConeRatio', 0.3, ...
        'sConeRatio', 0.1, ...
        'integrationTimeSeconds', 5/1000 ...
        );
    
    % Optics params
    app.opticsParams = struct(...
        'subjectDataset', 'Polans2015', ...
        'subjectID', 10, ...
        'pupilDiameterMM', 3, ...
        'subtractCentralRefraction', true, ...
        'visualizedWavelength', 550 ...
        );

    % Stimulus params
    app.stimParams = struct(...
        'presentationMode', 'flashed', ...
        'durationSec', 50/1000, ...
        'temporalFrequencyHz', 4, ...
        'spatialEnvelope', 'disk', ...
        'orientationDegs', 90, ...
        'spatialFrequencyCPD', 3.0, ...
        'spatialPhaseDegs', 0.0, ...
        'sizeDegs', 1.0, ...
        'resolutionPixels', 128, ...
        'minPixelsNumPerCycle', 11, ...
        'positionDegs', [0 0], ...
        'mosaicCenteredPosition', true, ...
        'meanLuminanceCdM2', 100, ...
        'LconeContrast', 100, ...
        'MconeContrast', 100, ...
        'SconeContrast', 100, ...
        'wavelengthSupportMin', 400, ...
        'wavelengthSupportMax', 750, ...
        'wavelengthSupportStepSize', 25);

    % Psychometric function estimation params
    app.psychometricFunctionParams = struct(...
        'classifierType', 'ideal observer (Poisson)', ...
        'trainingTrials', 1, ...
        'testTrials', 128, ...
        'contrastLevels', 5, ...
        'log10ContrastMin', -5, ...
        'log10ContrastMax', 1, ...
        'log10ContrastDelta', 0.05, ...
        'slopeMin', 8, ...
        'slopeMax', 200, ...
        'slopeDelta', 2, ...
        'estimationMethod', 'adaptive (mQuest+)' ...
        );
    
    app.csfParams = struct(...
        'spatialFrequencyMin', 3, ...
        'spatialFrequencyMax', 60, ...
        'spatialFrequencySamples', 4, ...
        'constantParameter', 'constant size', ...
        'numberOfConstantCycles', 0.56, ...  % cycles/sigma. 0.56 gives a bandwidth of 1.0 octaves, as in Watson (2005), ModellFest stimuli #11-14
        'sourceSignal', 'cone excitations' ...
        );
    
    % View modes for different components
    app.viewModes = struct(...
        'coneMosaic', 'cone types', ...
        'coneMosaicActivationType', 'noise-free responses', ...
        'coneMosaicVisualizationDomain', 'degrees', ...
        'coneMosaicActivationSignal', 'excitations', ...
        'coneMosaicActivationDimensionality', '2D space', ...
        'opticsKeepConeMosaicActivationInSync', false ...
        );
    
    app.constants = struct(...
        'WatsonPyramidOfVisibilityGaborConstantSize',   [1.739 -0.060 0.391], ...
        'WatsonPyramidOfVisibilityGaborConstantCycles', [1.380 -0.091 0.391] ...
        );
end
