function swapInputsFromDestinationRFWithInputsOfNearbyDestinationRF(obj, ...
            destinationRFinputIndicesToBeSwapped, theDestinationRFindex, ...
            nearbyDestinationRFinputIndicesToBeSwapped, theNearbyDestinationRFindex)     
 
    for inputIndex = 1:numel(destinationRFinputIndicesToBeSwapped)
        obj.transferInputRFFromDestinationRFToNearbyDestinationRF( ...
            destinationRFinputIndicesToBeSwapped(inputIndex), ...
            theDestinationRFindex, theNearbyDestinationRFindex);
    end

    for inputIndex = 1:numel(nearbyDestinationRFinputIndicesToBeSwapped)
        obj.transferInputRFFromDestinationRFToNearbyDestinationRF( ...
            nearbyDestinationRFinputIndicesToBeSwapped(inputIndex), ...
            theNearbyDestinationRFindex, theDestinationRFindex);
    end

end
