function hFig = visualizeCurrentConnectivity(obj, figNo)

    hFig = figure(figNo); clf;
    subplotPosVectors = NicePlot.getSubPlotPosVectors(...
           'rowsNum', 2, ...
           'colsNum', 2, ...
           'heightMargin',  0.04, ...
           'widthMargin',    0.04, ...
           'leftMargin',     0.04, ...
           'rightMargin',    0.00, ...
           'bottomMargin',   0.05, ...
           'topMargin',      0.03);
    set(hFig, 'Color', [1 1 1], 'Position', [10 10 1650 1000]);

    % The input lattices on the rop-right plot
    ax = subplot('Position', subplotPosVectors(1,1).v);
    [~,~,XLims, YLims] = obj.visualizeInputLattices(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'thetaSamples', 30);
    set(ax, 'FontSize', 16);

    % The connectivity (pooling of destination lattice RFs) in the bottom-right plot
    ax = subplot('Position', subplotPosVectors(1,2).v);
    obj.visualizeDestinationLatticePooling(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'titleString', 'lattice wiring (stars: destination RFs with 0 inputs)', ...
        'titleWithPoolingStats', true, ...
        'XLims', XLims, ...
        'YLims', YLims);
    drawnow;


end

