function [theConeMosaicFrameSequenceResponses,theConeMosaicNullResponse] = inputConeMosaicResponseToStimulusFrameSequence(...
	theMRGCMosaic, theOptics, ...
	theNullStimulusScene, theStimulusFrameSequence, ...
	stimulusXYposDegs, computeConeMosaicModulationResponse, varargin)

	% Parse input
    p = inputParser;
    p.addParameter('visualizeResponse', false, @islogical);
    p.addParameter('visualizeStimulusSequence', false, @islogical);
    p.addParameter('visualizeStimulusOnMosaic', false, @islogical);
    p.addParameter('thePresentationDisplayForVisualizingOpticalSceneOrImage', [], @isstruct);
    p.addParameter('stimulusInfoString', '', @ischar);
    p.parse(varargin{:});

    visualizeStimulusSequence = p.Results.visualizeStimulusSequence;
    visualizeStimulusOnMosaic = p.Results.visualizeStimulusOnMosaic;
    visualizeResponse = p.Results.visualizeResponse;
    thePresentationDisplay = p.Results.thePresentationDisplayForVisualizingOpticalSceneOrImage;
    stimulusInfoString = p.Results.stimulusInfoString;

	% Compute the cone mosaic response to the null scene
    theConeMosaicNullResponse = theMRGCMosaic.inputConeMosaic.compute(...
    	oiCompute(theOptics, theNullStimulusScene), ...
    	'opticalImagePositionDegs', stimulusXYposDegs, ...
    	'nTrials', 1);

    % Compute the normalizing response
  	coneIndicesWithZeroNullResponse = find(theConeMosaicNullResponse == 0);
  	normalizingResponse = 1./theConeMosaicNullResponse;
  	normalizingResponse(coneIndicesWithZeroNullResponse) = 0;
  	normalizingResponse = reshape(normalizingResponse, [1 1 numel(normalizingResponse)]);

  	% Allocate memory for the cone mosaic response to the drifting grating frames
  	theConeMosaicFrameSequenceResponses = ...
  		zeros(numel(theStimulusFrameSequence), theMRGCMosaic.inputConeMosaic.conesNum, 'single');

  	if (visualizeResponse) && (~isempty(thePresentationDisplay))
  		theOpticalImageSequence = cell(1, numel(theStimulusFrameSequence));
  	end


    if (visualizeStimulusSequence)
        hFig = figure(211); clf;
  		set(hFig,'Position', [10 10 1800 900], 'Color', [1 1 1]);
        ax = subplot(1,1,1);
        for iFrame = 1:numel(theStimulusFrameSequence)
            theScene = theStimulusFrameSequence{iFrame};
            visualizeScene(theScene, ...
                'presentationDisplay', thePresentationDisplay, ...
                'displayContrastProfiles', true, ...
                'displayRadianceMaps', false, ...
                'avoidAutomaticRGBscaling', true, ...
                'showSRGBimages', true, ...
                'axesHandle', ax);
            title(sprintf('frame %d of %d',iFrame, numel(theStimulusFrameSequence)));
            drawnow
        end
    end

    if (visualizeResponse) || (visualizeStimulusOnMosaic)
  		dx = -1:0.2:1;
  		domainVisualizationTicks = struct(...
          		'x', theMRGCMosaic.eccentricityDegs(1)+dx, ...
          		'y', theMRGCMosaic.eccentricityDegs(2)+dx);
  		domainVisualizationTicksForSceneOrOpticalImage = struct(...
          		'x', dx, ...
          		'y', dx);

  		domainVisualizationLimits(1:2) = ...
  			theMRGCMosaic.inputConeMosaic.eccentricityDegs(1) + ...
  			0.6*[-1 1] * theMRGCMosaic.sizeDegs(1); % theMRGCMosaic.inputConeMosaic.sizeDegs(1);
  		domainVisualizationLimits(3:4) = ...
  			theMRGCMosaic.inputConeMosaic.eccentricityDegs(2) + ...
  			0.6*[-1 1] * theMRGCMosaic.sizeDegs(2); % * theMRGCMosaic.inputConeMosaic.sizeDegs(2);

  		domainVisualizationLimitsForSceneOrOpticalImage(1:2) = ...
  			domainVisualizationLimits(1:2) - theMRGCMosaic.inputConeMosaic.eccentricityDegs(1);
  		domainVisualizationLimitsForSceneOrOpticalImage(3:4) = ...
  			domainVisualizationLimits(3:4) - theMRGCMosaic.inputConeMosaic.eccentricityDegs(2);
  	end


  	% Compute mosaic responses to all frames
  	parfor iFrame = 1:numel(theStimulusFrameSequence)
  		theOI = oiCompute(theOptics, theStimulusFrameSequence{iFrame});

  		if (visualizeResponse) && (~isempty(thePresentationDisplay))
  			theOpticalImageSequence{iFrame} = theOI;
  		end

    	theConeMosaicFrameResponse = theMRGCMosaic.inputConeMosaic.compute(theOI, ...
      		'opticalImagePositionDegs', stimulusXYposDegs, ...
      		'nTrials', 1);
    	if (computeConeMosaicModulationResponse)
    		theConeMosaicFrameResponse = bsxfun(@times, ...
             		bsxfun(@minus, theConeMosaicFrameResponse, theConeMosaicNullResponse), ...
                	normalizingResponse);
    	end
    	theConeMosaicFrameSequenceResponses(iFrame,:) = single(theConeMosaicFrameResponse(1,1,:));
  	end % iFrame

  	temporalSupportMsec = ((1:numel(theStimulusFrameSequence))-1)*theMRGCMosaic.inputConeMosaic.integrationTime*1e3;
  	if (visualizeStimulusOnMosaic)
    	hFig = figure(220); clf
  		set(hFig,'Position', [10 10 1800 900], 'Color', [1 1 1]);
  		ax = subplot(1,1,1);
  		for iFrame = 1:numel(theStimulusFrameSequence)
    		theMRGCMosaic.inputConeMosaic.visualize(...
	  			'figureHandle', hFig, ...
	    		'axesHandle', ax, ...
	    		'withSuperimposedOpticalImage', oiCompute(theOptics, theStimulusFrameSequence{iFrame}), ...
				'withSuperimposedOpticalImageAlpha', 0.95, ...
	    		'domainVisualizationLimits', domainVisualizationLimits, ...
	        	'domainVisualizationTicks', domainVisualizationTicks, ...
	        	'plotTitle', sprintf('stimulus frame %d of %d (t = %2.1f msec)', iFrame, numel(theStimulusFrameSequence), temporalSupportMsec(iFrame)));
    		drawnow;
    	end

    end

  	if (visualizeResponse)
  		
  		hFig = figure(111); clf
  		set(hFig,'Position', [10 10 1800 1200], 'Color', [1 1 1]);
  		axMosaic = subplot(3,3,1);
  		axCmosaicResponse = subplot(3,3,2);
  		axSceneOrOpticalImage = subplot(3,3,3);
  		axSpatioTemporalResponse = subplot(3,3, [4 5 6]);
  		axAllResponses = subplot(3,3, [7 8 9]);

        minCenterConeWeight = mRGCMosaic.sensitivityAtPointOfOverlap;
  		theMRGCMosaic.visualize(...
  			'figureHandle', hFig, ...
	    	'axesHandle', axMosaic, ...
            'identifyInputCones', true, ...
            'identifyPooledCones', true, ...
            'inputConesAlpha', 0.25, ...
            'identifiedConeAperture', 'lightCollectingArea4sigma', ...
            'identifiedConeApertureThetaSamples', 16, ...
            'minConeWeightVisualized', minCenterConeWeight, ...
            'plottedRFoutlineEdgeColor',  [1 1 1], ...
            'plottedRFoutlineLineWidth', 1.0, ...
            'centerSubregionContourSamples', 32, ...
            'plotTitle', ' ', ...
            'backgroundColor', [0 0 0], ...
        	'domainVisualizationLimits', domainVisualizationLimits, ...
        	'domainVisualizationTicks', domainVisualizationTicks);


  		if (computeConeMosaicModulationResponse)
  			activationRange = max(abs(theConeMosaicFrameSequenceResponses(:))) * [-1 1];
  			plotTitle = sprintf('%s (Response range: [%2.2f .. %2.2f])', stimulusInfoString, activationRange(1), activationRange(2));
  		else
  			activationRange = int([min(theConeMosaicFrameSequenceResponses(:)) max(theConeMosaicFrameSequenceResponses(:))]);
  			plotTitle = sprintf('%s (Response range: [%2.0f .. %2.0f])', stimulusInfoString, activationRange(1), activationRange(2));
  		end


  		for iFrame = 1:numel(theStimulusFrameSequence)
  			dt = (temporalSupportMsec(2)-temporalSupportMsec(1))/2;
  			imagesc(axSpatioTemporalResponse, temporalSupportMsec, 1:theMRGCMosaic.inputConeMosaic.conesNum,  theConeMosaicFrameSequenceResponses');
  			set(axSpatioTemporalResponse, 'CLim', activationRange, 'XLim', [temporalSupportMsec(1)-dt temporalSupportMsec(iFrame)+dt], 'YLim', [1 theMRGCMosaic.inputConeMosaic.conesNum]);
  			xlabel(axSpatioTemporalResponse, 'time (msec)');
  			ylabel(axSpatioTemporalResponse, 'cone index')
  			colormap(axSpatioTemporalResponse, gray(1024));

  			plot(axAllResponses, temporalSupportMsec, theConeMosaicFrameSequenceResponses, 'r-');
  			set(axAllResponses, 'XLim', [temporalSupportMsec(1)-dt temporalSupportMsec(iFrame)+dt], 'YLim', activationRange);
  			xlabel(axAllResponses, 'time (msec)');
  			ylabel(axAllResponses, 'response')

  			drawnow;

	  		theMRGCMosaic.inputConeMosaic.visualize(...
	  			'figureHandle', hFig, ...
	    		'axesHandle', axCmosaicResponse, ...
                'labelConesInActivationMap', true, ...
                'coneslinewidth', 1.5, ...
	    		'activation', reshape(theConeMosaicFrameSequenceResponses(iFrame,:), [1 1 size(theConeMosaicFrameSequenceResponses,2)]), ...
	    		'activationRange', activationRange, ...
	    		'domainVisualizationLimits', domainVisualizationLimits, ...
	        	'domainVisualizationTicks', domainVisualizationTicks, ...
	        	'plotTitle', sprintf('%s\n(t = %2.1f msec)', plotTitle, (iFrame-1)*theMRGCMosaic.inputConeMosaic.integrationTime*1e3));
  			
  			if (~isempty(thePresentationDisplay))
  				showScene = false;
  				showOpticalImage = ~showScene;

  				if (showScene)
	  			RGCMosaicConstructor.visualize.sceneOrOpticalImage(theStimulusFrameSequence{iFrame}, ...
	    			thePresentationDisplay, axSceneOrOpticalImage, ...
	    			domainVisualizationLimitsForSceneOrOpticalImage, ...
	    			domainVisualizationTicksForSceneOrOpticalImage, ...
	    			'plotTitle', 'scene');
	  			end

	  			if (showOpticalImage)
	  			RGCMosaicConstructor.visualize.sceneOrOpticalImage(theOpticalImageSequence{iFrame}, ...
	    			thePresentationDisplay, axSceneOrOpticalImage, ...
	    			domainVisualizationLimitsForSceneOrOpticalImage, ...
	    			domainVisualizationTicksForSceneOrOpticalImage, ...
	    			'plotTitle', 'optical image');
	  			end
	  		end

  			drawnow;

  		end % iFrame
  	end

end