%
% RGCMosaicConstructor.helper.simulateExperiment.temporalTransferFunction
%
%
function temporalTransferFunction(theMRGCMosaic, theOI, ...
    TTFparamsStruct, theInputConeMosaicTTFResponsesFullFileName, ...
    theMRGCMosaicTTFResponsesFullFileName, varargin)

    p = inputParser;
    p.addParameter('computeInputConeMosaicResponses', false, @islogical);
    p.addParameter('computeInputConeMosaicResponsesBasedOnConeExcitations', true, @islogical);
    p.addParameter('computeInputConeMosaicResponsesBasedOnPhotocurrents', true, @islogical);
    p.addParameter('computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex', [], @(x)(isempty(x))||(isscalar(x)));
    p.addParameter('inspectInputConeMosaicResponses', false, @islogical);
    p.addParameter('computeMRGCMosaicResponses', false, @islogical);
    p.addParameter('mRGCsOperateOnBackgroundAdaptedPhotocurrents', false, @islogical);
    p.addParameter('debugInputConeMosaicPcurrentResponse', false, @islogical);
    p.addParameter('visualizeResponse', false, @islogical);
    p.addParameter('visualizeStimulusSequence', false, @islogical);
    p.addParameter('visualizeStimulusOnMosaic', false, @islogical);
    p.addParameter('nonLinearitiesList', [], @(x)(isempty(x))||(iscell(x))||(isstruct(x)));
    p.addParameter('photocurrentParams',[], @(x)(isempty(x))||(iscell(x))||(isstruct(x)));
    p.addParameter('validateScenes', false, @islogical);
    p.addParameter('visualizeCustomConeFundamentals', false, @islogical);

    % Execute the parser
    p.parse(varargin{:});
    computeInputConeMosaicResponses = p.Results.computeInputConeMosaicResponses;
    computeInputConeMosaicResponsesBasedOnConeExcitations = p.Results.computeInputConeMosaicResponsesBasedOnConeExcitations;
    computeInputConeMosaicResponsesBasedOnPhotocurrents = p.Results.computeInputConeMosaicResponsesBasedOnPhotocurrents;
    computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex = p.Results.computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex;
    inspectInputConeMosaicResponses = p.Results.inspectInputConeMosaicResponses;
    computeMRGCMosaicResponses = p.Results.computeMRGCMosaicResponses;
    mRGCsOperateOnBackgroundAdaptedPhotocurrents = p.Results.mRGCsOperateOnBackgroundAdaptedPhotocurrents;
    nonLinearitiesList = p.Results.nonLinearitiesList;
    photocurrentParams = p.Results.photocurrentParams;
    visualizeResponse = p.Results.visualizeResponse;
    visualizeStimulusSequence = p.Results.visualizeStimulusSequence;
    visualizeStimulusOnMosaic = p.Results.visualizeStimulusOnMosaic;
    debugInputConeMosaicPcurrentResponse = p.Results.debugInputConeMosaicPcurrentResponse;
    validateScenes = p.Results.validateScenes;
    visualizeCustomConeFundamentals = p.Results.visualizeCustomConeFundamentals;

    if (computeInputConeMosaicResponses)
        if (computeInputConeMosaicResponsesBasedOnConeExcitations)
            pCurrentTemporalResolutionSeconds = [];
            osBiophysicalModelWarmUpTimeSeconds = [];
            osBiophysicalModelTimeStep = [];
    
            % Check if we can write to file
            RGCMosaicConstructor.helper.utils.feasibilityOfWritingToFile(theInputConeMosaicTTFResponsesFullFileName);

            computeInputConeMosaicTTF(theMRGCMosaic, theOI, TTFparamsStruct, ...
                theInputConeMosaicTTFResponsesFullFileName, ...
                pCurrentTemporalResolutionSeconds, osBiophysicalModelWarmUpTimeSeconds, osBiophysicalModelTimeStep, ...
                visualizeResponse, visualizeStimulusSequence, visualizeStimulusOnMosaic, ...
                debugInputConeMosaicPcurrentResponse, inspectInputConeMosaicResponses, ...
                computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
                validateScenes, visualizeCustomConeFundamentals, ...
                'cone excitations');
        end
    
    
        if (computeInputConeMosaicResponsesBasedOnPhotocurrents)
    
            osBiophysicalModelWarmUpTimeSeconds = photocurrentParams.osBiophysicalModelWarmUpTimeSeconds;
            osBiophysicalModelTimeStep = photocurrentParams.osBiophysicalModelTemporalResolutionSeconds;
            pCurrentTemporalResolutionSeconds = photocurrentParams.temporalResolutionSeconds;
 
            % Check if we can write to file
            RGCMosaicConstructor.helper.utils.feasibilityOfWritingToFile(theInputConeMosaicTTFResponsesFullFileName);

            computeInputConeMosaicTTF(theMRGCMosaic, theOI, TTFparamsStruct, ...
                theInputConeMosaicTTFResponsesFullFileName, ...
                pCurrentTemporalResolutionSeconds, osBiophysicalModelWarmUpTimeSeconds, osBiophysicalModelTimeStep, ...
                visualizeResponse, visualizeStimulusSequence, visualizeStimulusOnMosaic, ...
                debugInputConeMosaicPcurrentResponse, inspectInputConeMosaicResponses, ...
                computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
                validateScenes, visualizeCustomConeFundamentals, ...
                'photocurrents');
        end
    end % computeInputConeMosaicResponses

    if (computeMRGCMosaicResponses)

        % Check if we can write to file
        RGCMosaicConstructor.helper.utils.feasibilityOfWritingToFile(theMRGCMosaicTTFResponsesFullFileName);

        computeMRGCmosaicTTF(theMRGCMosaic, ...
            theInputConeMosaicTTFResponsesFullFileName, ...
            theMRGCMosaicTTFResponsesFullFileName, ...
            nonLinearitiesList, ...
            mRGCsOperateOnBackgroundAdaptedPhotocurrents, ...
            computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex);
    end

    if (visualizeResponse)

        targetTemporalFrequencyHz = 0.5;

        visualizeInputConeMosaicResponses(theMRGCMosaic, theOI, ...
            theInputConeMosaicTTFResponsesFullFileName, ...
            computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
            mRGCsOperateOnBackgroundAdaptedPhotocurrents, ...
            targetTemporalFrequencyHz)
    end

    if (inspectInputConeMosaicResponses)
        contrastInputConeMosaicResponses(theMRGCMosaic, ...
            theInputConeMosaicTTFResponsesFullFileName, ...
            computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
            mRGCsOperateOnBackgroundAdaptedPhotocurrents);
    end

end



function computeMRGCmosaicTTF(...
            theMRGCMosaic, ...
            theInputConeMosaicTTFResponsesFullFileName, ...
            theMRGCMosaicTTFResponsesFullFileName, ...
            nonLinearitiesList, ...
            mRGCsOperateOnBackgroundAdaptedPhotocurrents, ...
            theTargetRGCindex)



     % Load all the responses
    [TTFparamsStruct, stimParams, ...
        theInputConeMosaicTTFresponses, ...
        theInputConeMosaicPhotocurrentTemporalSupportSeconds, ...
        theInputConeMosaicPhotocurrentTTFresponses, ...
        photocurrentBasedTTFsComputed, ...
        computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex] = loadAllResponses(...
                theInputConeMosaicTTFResponsesFullFileName, ...
                theTargetRGCindex, theMRGCMosaic, ...
                mRGCsOperateOnBackgroundAdaptedPhotocurrents);


    temporalFrequenciesExamined = TTFparamsStruct.tfSupport;

    % Compute mRGC mosaic responses
    for iTF = 1:numel(temporalFrequenciesExamined)

        if (photocurrentBasedTTFsComputed)

            [theMRGCmosaicResponsesForThisTF, ...
             theMRGCmosaicResponseTemporalSupportSecondsForThisTF, ...
             theLinearMRGCmosaicResponsesForThisTF] = computeMRGCMosaicResponsesForInputConeMosaicSignal(...
                    theMRGCMosaic, ...
                    theTargetRGCindex, ...
                    temporalFrequenciesExamined(iTF), ...
                    squeeze(theInputConeMosaicPhotocurrentTemporalSupportSeconds(iTF,:)), ...
                    squeeze(theInputConeMosaicPhotocurrentTTFresponses(iTF,:,:)), ...
                    nonLinearitiesList);


            if (iTF == 1)
                % Allocate memory
                theMRGCMosaicTTFresponsesAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(theMRGCmosaicResponseTemporalSupportSecondsForThisTF), ...
                    theMRGCMosaic.rgcsNum, ...
                    'single');

                theMRGCMosaicLinearTTFresponsesAllConditions = theMRGCMosaicTTFresponsesAllConditions;

                theMRGCMosaicTemporalSupportSecondsAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(theMRGCmosaicResponseTemporalSupportSecondsForThisTF), ...
                    'single');
            end % iTF == 1


            idx = 1:numel(theMRGCmosaicResponseTemporalSupportSecondsForThisTF);
            theMRGCMosaicTTFresponsesAllConditions(iTF, idx, :) = single(theMRGCmosaicResponsesForThisTF);
            theMRGCMosaicLinearTTFresponsesAllConditions(iTF, idx, :) = single(theLinearMRGCmosaicResponsesForThisTF);
            theMRGCMosaicTemporalSupportSecondsAllConditions(iTF, idx) = single(theMRGCmosaicResponseTemporalSupportSecondsForThisTF);

        end % if (photocurrentBasedTTFsComputed)

    end % iTF


    % Save computed MRGC mosaic responses here
    save(theMRGCMosaicTTFResponsesFullFileName, ...
        'theMRGCMosaic', 'stimParams', 'TTFparamsStruct', ...
        'computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex', ...
        'theMRGCMosaicLinearTTFresponsesAllConditions', ...
        'theMRGCMosaicTTFresponsesAllConditions', ...
        'theMRGCMosaicTemporalSupportSecondsAllConditions', ...
        '-v7.3');
  
end



function computeInputConeMosaicTTF(theMRGCMosaic, theOI, TTFparamsStruct, ...
    theInputConeMosaicTTFResponsesFullFileName, ...
    pCurrentTemporalResolutionSeconds, photocurrentModelWarmUpTimeSeconds, osTimeStep, ...
    visualizeResponse, visualizeStimulusSequence, visualizeStimulusOnMosaic, ...
    debugInputConeMosaicPcurrentResponse, inspectInputConeMosaicResponses, ...
    computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
    validateScenes, visualizeCustomConeFundamentals, theSignal)

    % Compute the cone excitations
    if (strcmp(theSignal,'cone excitations'))
        fprintf('Input cone mosaic TTF responses will be saved in: \n%s\n', theInputConeMosaicTTFResponsesFullFileName);

        temporalFrequenciesExamined = TTFparamsStruct.tfSupport;

        % Compute cone contrasts for desired chromaticity
        coneContrasts = ...
            visualStimulusGenerator.coneContrastsFromChromaticity(TTFparamsStruct.chromaticity);

        totalContrast = TTFparamsStruct.contrast;

        stimParams = struct(...
            'displayType', TTFparamsStruct.displayType, ...
            'backgroundChromaticity', TTFparamsStruct.backgroundChromaticity, ...
            'backgroundLuminanceCdM2', TTFparamsStruct.backgroundLuminanceCdM2, ...
            'contrast', totalContrast, ...
            'coneContrasts', coneContrasts, ...
            'sizeDegs', TTFparamsStruct.sizeDegs, ...
            'positionDegs', TTFparamsStruct.positionDegs, ...
            'resolutionDegs', TTFparamsStruct.stimulusResolutionDegs, ...
            'stimulusPositionDegs', TTFparamsStruct.stimulusPositionDegs, ...
            'stimulusSizeDegs', TTFparamsStruct.stimulusSizeDegs, ...
            'stimulusShape', TTFparamsStruct.stimulusShape, ...
            'temporalPhaseIncrementDegs', TTFparamsStruct.temporalPhaseIncrementDegs, ...
            'coneMosaicModulationBasedResponse',  true ...
            );

        
        if (TTFparamsStruct.coneFundamentalsOptimizedForStimPosition)
            % Compute custom cone fundamentals for the mosaic's eccentricity
            maxConesNumForAveraging = 3;
            customConeFundamentals = visualStimulusGenerator.coneFundamentalsForPositionWithinConeMosaic(...
                theMRGCMosaic.inputConeMosaic, theOI, stimParams.positionDegs, stimParams.sizeDegs, maxConesNumForAveraging);
        else
            customConeFundamentals = [];
        end


        % Generate presentation display, 20% luminance headroom
        viewingDistanceMeters = 4;

        [thePresentationDisplay, ...
         stimParams.backgroundChromaticity, ...
         stimParams.backgroundLuminanceCdM2] = visualStimulusGenerator.presentationDisplay(...
            theMRGCMosaic.inputConeMosaic.wave, ...
            TTFparamsStruct.stimulusResolutionDegs, ...
            viewingDistanceMeters, ...
            'displayType', TTFparamsStruct.displayType, ...
            'bitDepth', 20, ...
            'meanLuminanceCdPerM2', TTFparamsStruct.backgroundLuminanceCdM2, ...
            'luminanceHeadroom', TTFparamsStruct.displayLuminanceHeadroomPercentage, ...
            'adjustBackgroundChromaticityToEqualizeLandMconeExcitations', TTFparamsStruct.adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
            'backgroundChromaticity', stimParams.backgroundChromaticity, ...
            'backgroundLuminanceCdM2', stimParams.backgroundLuminanceCdM2, ...
            'coneFundamentalsToEmploy',customConeFundamentals);
       
        for iTF = 1:numel(temporalFrequenciesExamined)

            % Get stim params
            stimParams.temporalFrequencyHz = temporalFrequenciesExamined(iTF);
            stimParams.durationSeconds =  1.0/stimParams.temporalFrequencyHz;

            % Feedback
            fprintf('Computing input cone mosaic TTF (cone excitations-based) for TF = %2.3f Hz\n', ...
                stimParams.temporalFrequencyHz);

            % Generate the spatial modulation patterns for all spatial phases of the drifting grating
            [theFlickeringGratingSpatialModulationPatterns, spatialSupportDegs, theCurrentTemporalPhasesDegs, ...
                theCurrentTemporalSupportSeconds, theCurrentTemporalRamp] = visualStimulusGenerator.flickeringGratingModulationPatterns(stimParams);


            if (TTFparamsStruct.coneFundamentalsOptimizedForStimPosition)
                if (iTF == 1)
                    % Generate scenes for the different frames of the flickring grating and for the null stimulus
                    [theFlickeringGratingFrameScenes, theNullStimulusScene, ~, theConeFundamentalsStruct] = visualStimulusGenerator.stimulusFramesScenes(...
                        thePresentationDisplay, stimParams, theFlickeringGratingSpatialModulationPatterns, ...
                        'frameIndexToCompute', [], ... % [] field indicates that all stimulus frame scenes must be computed
                        'customConeFundamentals', customConeFundamentals, ...
                        'announceEmployedConeFundamentals', true, ...
                        'validateScenes', validateScenes, ...
                        'visualizeCustomConeFundamentals', visualizeCustomConeFundamentals);
                else
                    [theFlickeringGratingFrameScenes, theNullStimulusScene] = visualStimulusGenerator.stimulusFramesScenes(...
                        thePresentationDisplay, stimParams, theFlickeringGratingSpatialModulationPatterns, ...
                        'frameIndexToCompute', [], ... % [] field indicates that all stimulus frame scenes must be computed
                        'withPreviouslyComputedConeFundamentalsStruct', theConeFundamentalsStruct, ...
                        'announceEmployedConeFundamentals', true, ...
                        'validateScenes', ~true);
                end

            else
                % Generate scenes for the different frames of the drifting grating and for the null stimulus
                [theFlickeringGratingFrameScenes, theNullStimulusScene] = visualStimulusGenerator.stimulusFramesScenes(...
                    thePresentationDisplay, stimParams, theFlickeringGratingSpatialModulationPatterns, ...
                    'frameIndexToCompute', [], ... % [] field indicates that all stimulus frame scenes must be computed
                    'validateScenes', ~true);
            end

            % Compute input cone mosaic response to this temporal frequency

            % Place the stimulus at desired position
            if (isempty(stimParams.stimulusPositionDegs))
                stimulusPosition = 'mosaic-centered';
            elseif (numel(stimParams.stimulusPositionDegs) == 2)
                stimulusPosition = stimParams.stimulusPositionDegs;
            else
                stimParams.stimulusPositionDegs
                error('stimulusPositionDegs must be either empty of a 2 element vector')
            end

            % Set the mosaic integration time equal to the duration of one stimulus frame
            theMRGCMosaic.inputConeMosaic.integrationTime = theCurrentTemporalSupportSeconds(2) - theCurrentTemporalSupportSeconds(1);

            % Compute cone mosaic responses to each stimulus frame
            [theCurrentInputConeMosaicTTFresponse, theConeMosaicNullResponse] = ...
                RGCMosaicConstructor.helper.simulateExperiment.inputConeMosaicResponseToStimulusFrameSequence(...
                theMRGCMosaic, theOI, theNullStimulusScene, theFlickeringGratingFrameScenes, ...
                stimulusPosition, stimParams.coneMosaicModulationBasedResponse, ...
                'visualizeResponse', visualizeResponse, ...
                'visualizeStimulusSequence', visualizeStimulusSequence, ...
                'visualizeStimulusOnMosaic', visualizeStimulusOnMosaic, ...
                'thePresentationDisplayForVisualizingOpticalSceneOrImage', thePresentationDisplay, ...
                'stimulusInfoString', sprintf('TF:%2.2f Hz', stimParams.temporalFrequencyHz));

            if (iTF == 1)
                theInputConeMosaicTTFresponsesAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(theCurrentTemporalPhasesDegs), ...
                    theMRGCMosaic.inputConeMosaic.conesNum, ...
                    'single');

                temporalSupportSecondsAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(theCurrentTemporalSupportSeconds), ...
                    'single');

                temporalPhasesDegsAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(theCurrentTemporalPhasesDegs), ...
                    'single');
        
                temporalRampAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(theCurrentTemporalRamp), ...
                    'single');
            end % iTF == 1

            theInputConeMosaicTTFresponsesAllConditions(iTF, 1:size(theCurrentInputConeMosaicTTFresponse,1), 1:size(theCurrentInputConeMosaicTTFresponse,2)) = ...
                theCurrentInputConeMosaicTTFresponse;
            temporalSupportSecondsAllConditions(iTF, 1:numel(theCurrentTemporalSupportSeconds)) = single(theCurrentTemporalSupportSeconds);
            temporalPhasesDegsAllConditions(iTF, 1:numel(theCurrentTemporalPhasesDegs)) = single(theCurrentTemporalPhasesDegs);
            temporalRampAllConditions(iTF, 1:numel(theCurrentTemporalRamp)) = single(theCurrentTemporalRamp);
        end % iTF

        theInputConeMosaicTTFresponses = theInputConeMosaicTTFresponsesAllConditions;
        stimParams.temporalSupportSeconds = temporalSupportSecondsAllConditions;
        stimParams.temporalPhasesDegs = temporalPhasesDegsAllConditions;
        stimParams.temporalRamp = temporalRampAllConditions;

        % Save results
        fprintf('Saving computed input cone mosaic TTF cone excitation responses to %s.\n', theInputConeMosaicTTFResponsesFullFileName);
        stimParams.temporalFrequencyHz = temporalFrequenciesExamined;

        save(theInputConeMosaicTTFResponsesFullFileName, ...
            'theMRGCMosaic', ...
            'TTFparamsStruct', ...
            'stimParams', ...
            'theInputConeMosaicTTFresponses', ...
            'theConeMosaicNullResponse', ...
            '-v7.3');
    end % if (strcmp(theSignal,'cone excitations'))

    % Compute the photocurrents
    if (strcmp(theSignal, 'photocurrents'))
        load(theInputConeMosaicTTFResponsesFullFileName, ...
            'theMRGCMosaic', ...
            'TTFparamsStruct', ...
            'stimParams', ...
            'theInputConeMosaicTTFresponses', ...
            'theConeMosaicNullResponse');

        % If we loaded cone modulation responses, we will need to transform then to cone excitations.
        % Here we are reshaping the null response to allow for this transform
        if (stimParams.coneMosaicModulationBasedResponse)
            theConeMosaicNullResponse = squeeze(theConeMosaicNullResponse);
            theConeMosaicNullResponse = reshape(theConeMosaicNullResponse, [1 numel(theConeMosaicNullResponse)]);
        end

        % Read in the non-NaN cone-excitation data for each frequency
        % and compute the corresponding photocurrent response
        temporalFrequenciesExamined = stimParams.temporalFrequencyHz;

        % Photocurrent computation takes a long time.
        % Here we have the option to compute photocurrents only for the cones providing inputs to a single mRGC
        computePhotocurrentResponsesOnlyForSelectConeIndices = [];
        if (~isempty(computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex))

            % Compute photocurrents for cone indices that provide input to a single mRGC
            theTargetMRGCindex = computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex(1);

            surroundConnectivityVector = full(squeeze(theMRGCMosaic.rgcRFsurroundConeConnectivityMatrix(:, theTargetMRGCindex)));
            surroundConeIndices = find(surroundConnectivityVector > mRGCMosaic.minSurroundWeightForInclusionInComputing);
            computePhotocurrentResponsesOnlyForSelectConeIndices = surroundConeIndices;
            fprintf('\n---> Will compute photocurrents for %d cones (inputs to mRGC with index: %d) instead of the total %d cones\n', ...
                numel(computePhotocurrentResponsesOnlyForSelectConeIndices), theTargetMRGCindex, theMRGCMosaic.inputConeMosaic.conesNum);
            %surroundConeWeights = reshape(surroundConnectivityVector(surroundConeIndices), [1 1 numel(surroundConeIndices)]);
            % Spatially pool the weighted cone responses to the RF surround
            % surroundSpatiallyIntegratedActivations = sum(bsxfun(@times, theInputConeMosaicResponse(1:nTrials,1:inputTimePoints, surroundConeIndices), surroundConeWeights),3);
        end

        % Allocate memory for each cone mosaic OS biophys model
        nCones = theMRGCMosaic.inputConeMosaic.conesNum;
        theConeOSbiophysModels = cell(1,nCones);

        for iTF = 1:numel(temporalFrequenciesExamined)

            % Retrieve the response data for this TF
            theTemporalSupportSecondsForThisTF = squeeze(stimParams.temporalSupportSeconds(iTF,:));
            theInputConeMosaicExcitationResponsesForThisTF = squeeze(theInputConeMosaicTTFresponses(iTF,:,:));
            nanIndices = find(isnan(theTemporalSupportSecondsForThisTF));
            if (isempty(nanIndices))
                theTimeBins = 1:numel(theTemporalSupportSecondsForThisTF);
            else
                theTimeBins = 1:(nanIndices-1);
            end
            theTemporalSupportSecondsForThisTF = theTemporalSupportSecondsForThisTF(theTimeBins);
            theInputConeMosaicExcitationResponsesForThisTF = theInputConeMosaicExcitationResponsesForThisTF(theTimeBins,:);

            % If we loaded cone modulation responses, transform then to cone excitations.
            if (stimParams.coneMosaicModulationBasedResponse)
                % Transform from modulations to excitations
                %Rmod = (Recx-Ro)/Ro -> (Rmod+1)*Ro = RExc
                theInputConeMosaicExcitationResponsesForThisTF = theInputConeMosaicExcitationResponsesForThisTF  + 1;
                theInputConeMosaicExcitationResponsesForThisTF = ...
                    bsxfun(@times, theInputConeMosaicExcitationResponsesForThisTF, theConeMosaicNullResponse);
            end

            % Compute the photocurrent response
            plotTitle = sprintf('tf: %2.3f Hz', stimParams.temporalFrequencyHz(iTF));

            fprintf('Computing input cone mosaic TTF (photocurrent-based) for TF = %2.3f Hz\n', ...
                stimParams.temporalFrequencyHz(iTF));

            stimulusPeriodDuration = 1/stimParams.temporalFrequencyHz(iTF); 
            nWarmUpPeriods = max([1 ceil(photocurrentModelWarmUpTimeSeconds/stimulusPeriodDuration)]);
            

            % Compute photocurrents here
            [theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
             theInputConeMosaicPhotocurrentResponsesForThisTF, ...
             theInputConeMosaicBackgroundPhotocurrentsForThisTF, ...
             ~, ~, theConeOSbiophysModels] = RGCMosaicAnalyzer.compute.photocurrentsForOneStimulusPeriod(...
                    theMRGCMosaic.eccentricityDegs, ...
                    theTemporalSupportSecondsForThisTF(1:end-1), ...   % Get rid of last point which is a repeat of the first point
                    theInputConeMosaicExcitationResponsesForThisTF(1:end-1,:), ...       % Get rid of last point which is a repeat of the first point
                    nWarmUpPeriods, ...
                    pCurrentTemporalResolutionSeconds, ...
                    osTimeStep, ...
                    theMRGCMosaic.inputConeMosaic.coneTypes, ...
                    theConeOSbiophysModels, ...
                    debugInputConeMosaicPcurrentResponse, ...
                    plotTitle, ...
                    'onlyKeepResponseDuringLastTwoStimulusPeriods', false, ...
                    'onlyKeepResponseDuringLastStimulusPeriod', true, ...
                    'computePhotocurrentResponsesOnlyForSelectConeIndices', computePhotocurrentResponsesOnlyForSelectConeIndices);

            timeBinIndices = 1:size(theInputConeMosaicPhotocurrentResponsesForThisTF,1);
            assert(numel(timeBinIndices) == numel(theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF), 'mismatch in time dimension');
            assert(size(theInputConeMosaicPhotocurrentResponsesForThisTF,2) == theMRGCMosaic.inputConeMosaic.conesNum, 'error in cone index dimension');

            if (iTF == 1)
                theInputConeMosaicPhotocurrentTTFresponsesAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(timeBinIndices), ...
                    theMRGCMosaic.inputConeMosaic.conesNum, ...
                    'single');

                temporalSupportSecondsPhotocurrentAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    numel(timeBinIndices), ...
                    'single');

                theInputConeMosaicBackgroundPhotocurrentsAllConditions = nan(...
                    numel(temporalFrequenciesExamined), ...
                    theMRGCMosaic.inputConeMosaic.conesNum, ...
                    'single');
            end % iTF == 1

            % Get the data for this TF into the all conditions array at the appropriate time bins

            theInputConeMosaicPhotocurrentTTFresponsesAllConditions(iTF, timeBinIndices, :) = theInputConeMosaicPhotocurrentResponsesForThisTF;
            temporalSupportSecondsPhotocurrentAllConditions(iTF, timeBinIndices) = theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF;
            theInputConeMosaicBackgroundPhotocurrentsAllConditions(iTF,:) = theInputConeMosaicBackgroundPhotocurrentsForThisTF;

            if (inspectInputConeMosaicResponses)
                % Plot cone excitation + photocurrents
                hFig = figure(1000); clf;
                set(hFig, 'Position', [10 10 1000 1000]);
                set(hFig, 'Name', sprintf('mosaic cone excitations and photocurrents for TF = %2.3f Hz', temporalFrequenciesExamined(iTF)));

                ax = subplot(2,1,1);
                p1 = plot(ax, theTemporalSupportSecondsForThisTF*1e3, theInputConeMosaicExcitationResponsesForThisTF, 'r-');
                if (iTF == 1)
                    XLims = [theTemporalSupportSecondsForThisTF(1) theTemporalSupportSecondsForThisTF(end)]*1e3;
                end
                title(ax, 'cone excitations')
                xlabel(ax, 'time (msec)');
                ylabel(ax, 'cone excitation response');
                set(ax, 'XLim', XLims);

                ax = subplot(2,1,2);
                p2 = plot(ax, squeeze(temporalSupportSecondsPhotocurrentAllConditions(iTF, timeBinIndices))*1e3, ...
                              squeeze(theInputConeMosaicPhotocurrentTTFresponsesAllConditions(iTF, timeBinIndices, :)), 'b-');
                title(ax, 'photocurrents')
                set(ax, 'XLim', XLims);
                xlabel(ax, 'time (msec)');
                ylabel(ax, 'cone photocurrent response (pAmps)');

                drawnow
            end

        end % iTF

        % Append photocurrent data to theInputConeMosaicTTFResponsesFullFileName
        theInputConeMosaicPhotocurrentTemporalSupportSeconds = temporalSupportSecondsPhotocurrentAllConditions;
        theInputConeMosaicPhotocurrentTTFresponses = theInputConeMosaicPhotocurrentTTFresponsesAllConditions;
        theInputConeMosaicBackgroundPhotocurrents = theInputConeMosaicBackgroundPhotocurrentsAllConditions;

        save(theInputConeMosaicTTFResponsesFullFileName, ...
            'computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex', ...
            'computePhotocurrentResponsesOnlyForSelectConeIndices', ...
            'theInputConeMosaicPhotocurrentTemporalSupportSeconds', ...
            'theInputConeMosaicPhotocurrentTTFresponses', ...
            'theInputConeMosaicBackgroundPhotocurrents', ...
            '-append');

        fprintf('Photocurrent TTF responses were appeded to %s\n', theInputConeMosaicTTFResponsesFullFileName);

    end %if (strcmp(theSignal, 'photocurrents'))
end


function [theMRGCmosaicResponsesForThisTF, ...
         theMRGCmosaicResponseTemporalSupportSecondsForThisTF, ...
         theLinearMRGCmosaicResponsesForThisTF] = computeMRGCMosaicResponsesForInputConeMosaicSignal(...
            theMRGCMosaic, ...
            computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
            theTemporalFrequency, ...
            theTemporalSupportSecondsForThisTF, ...
            theInputConeMosaicPhotocurrentResponsesForThisTF, ...
            nonLinearitiesList)

            fprintf('Computing photocurrents-based mRGC mosaic response for TF = %2.2f Hz', theTemporalFrequency);

            nanIndices = find(isnan(theTemporalSupportSecondsForThisTF));
            if (isempty(nanIndices))
                theTimeBins = 1:numel(theTemporalSupportSecondsForThisTF);
            else
                theTimeBins = 1:(nanIndices-1);
            end

            theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF = theTemporalSupportSecondsForThisTF(theTimeBins);
            theInputConeMosaicPhotocurrentResponsesForThisTF = theInputConeMosaicPhotocurrentResponsesForThisTF(theTimeBins,:);

            
            % Compute the mRGC mosaic response for this TF
            [theMRGCmosaicResponsesForThisTF, ~, ...
             theMRGCmosaicResponseTemporalSupportSecondsForThisTF, ...
             theLinearMRGCmosaicResponsesForThisTF] = theMRGCMosaic.compute(...
                    reshape(theInputConeMosaicPhotocurrentResponsesForThisTF, [1 numel(theTimeBins) theMRGCMosaic.inputConeMosaic.conesNum]), ...
                    theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
                    'nonLinearitiesList', nonLinearitiesList);

end


function contrastInputConeMosaicResponses(theMRGCMosaic, ...
            theInputConeMosaicTTFResponsesFullFileName, ...
            theTargetRGCindex, ...
            mRGCsOperateOnBackgroundAdaptedPhotocurrents)


     % Load all the responses
    [TTFparamsStruct, stimParams, ...
        theInputConeMosaicTTFresponses, ...
        theInputConeMosaicPhotocurrentTemporalSupportSeconds, ...
        theInputConeMosaicPhotocurrentTTFresponses, ...
        photocurrentBasedTTFsComputed] = loadAllResponses(theInputConeMosaicTTFResponsesFullFileName, theTargetRGCindex, theMRGCMosaic, mRGCsOperateOnBackgroundAdaptedPhotocurrents);


    if (~photocurrentBasedTTFsComputed)
        return;
    end

    temporalFrequenciesExamined = TTFparamsStruct.tfSupport;


    hFig = figure(40); clf;
    set(hFig, 'Position', [10 10 500 1150], 'Color', [1 1 1]);

    for iTF = 1:numel(temporalFrequenciesExamined)

        % Retrieve the cone excitation response data for this TF

        theTemporalSupportSecondsForThisTF = squeeze(stimParams.temporalSupportSeconds(iTF,:));
        theInputConeMosaicExcitationResponsesForThisTF = squeeze(theInputConeMosaicTTFresponses(iTF,:,:));
        nanIndices = find(isnan(theTemporalSupportSecondsForThisTF));
        if (isempty(nanIndices))
            theTimeBins = 1:numel(theTemporalSupportSecondsForThisTF);
        else
            theTimeBins = 1:(nanIndices-1);
        end
        theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF = theTemporalSupportSecondsForThisTF(theTimeBins);
        theInputConeMosaicExcitationResponsesForThisTF = theInputConeMosaicExcitationResponsesForThisTF(theTimeBins,:);

        % Retrieve the photocurrent response data for this TF
        theTemporalSupportSecondsForThisTF = squeeze(theInputConeMosaicPhotocurrentTemporalSupportSeconds(iTF,:));
        theInputConeMosaicPhotocurrentResponsesForThisTF = squeeze(theInputConeMosaicPhotocurrentTTFresponses(iTF,:,:));
        nanIndices = find(isnan(theTemporalSupportSecondsForThisTF));
        if (isempty(nanIndices))
            theTimeBins = 1:numel(theTemporalSupportSecondsForThisTF);
        else
            theTimeBins = 1:(nanIndices-1);
        end
        theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF = theTemporalSupportSecondsForThisTF(theTimeBins);
        theInputConeMosaicPhotocurrentResponsesForThisTF = theInputConeMosaicPhotocurrentResponsesForThisTF(theTimeBins,:);

        coneExcitationsTransformedIntoResponseModulations = true;
        for idx = 1:numel( theTargetRGCindex)
            theConeIndex =  theTargetRGCindex(idx);
            plotTitle = sprintf('TF: %2.2fHz, cone index: %d', temporalFrequenciesExamined(iTF), theConeIndex);

            RGCMosaicAnalyzer.visualize.coneExcitationsVsPhotocurrentResponse(hFig, plotTitle, ...
                theMRGCMosaic.inputConeMosaic.coneTypes(theConeIndex), ...
                theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF , ...
                squeeze(theInputConeMosaicExcitationResponsesForThisTF(:,theConeIndex)), ...
                coneExcitationsTransformedIntoResponseModulations, ...
                theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF , ...
                squeeze(theInputConeMosaicPhotocurrentResponsesForThisTF(:, theConeIndex)), ...
                theInputConeMosaicBackgroundPhotocurrents(iTF, theConeIndex), ...
                [], [], ...
                [], [], []);
        end % idx

    end % iTF


end


function visualizeInputConeMosaicResponses(theMRGCMosaic, theOI, ...
            theInputConeMosaicTTFResponsesFullFileName, ...
            theTargetRGCindex, ...
            mRGCsOperateOnBackgroundAdaptedPhotocurrents, ...
            targetTemporalFrequencyHz)


    % Load all the responses
    [TTFparamsStruct, stimParams, ...
        theInputConeMosaicTTFresponses, ...
        theInputConeMosaicPhotocurrentTemporalSupportSeconds, ...
        theInputConeMosaicPhotocurrentTTFresponses, ...
        photocurrentBasedTTFsComputed, ...
        computePhotocurrentResponsesOnlyForSelectConeIndices] = loadAllResponses(theInputConeMosaicTTFResponsesFullFileName, theTargetRGCindex, theMRGCMosaic, mRGCsOperateOnBackgroundAdaptedPhotocurrents);


    if (~photocurrentBasedTTFsComputed)
        return;
    end


    % Find the TF nearest the targetTemporalFrequencyHz
    [~,idx] = min(abs(TTFparamsStruct.tfSupport-targetTemporalFrequencyHz));
    temporalFrequenciesExamined = TTFparamsStruct.tfSupport(idx);

    visualizedHeightDegs = 0.45;
    narrowDomainVisualizationLimits(1:2) = theMRGCMosaic.rgcRFpositionsDegs(theTargetRGCindex, 1) + (2000/1200)*[-0.5 0.5]*visualizedHeightDegs;
    narrowDomainVisualizationLimits(3:4) = theMRGCMosaic.rgcRFpositionsDegs(theTargetRGCindex, 2) + [-0.5 0.5]*visualizedHeightDegs;
    narrowDomainVisualizationTicks = struct(...
        'x', -30:0.2:0, ...
        'y', -10:0.2:10);

    narrowDomainVisualizationTicksNoYticks = narrowDomainVisualizationTicks;
    narrowDomainVisualizationTicksNoYticks.y = [];

    % Generate the PSF data for co-visualization with the cMosaic
    domainUnits = 'degrees';
    theVisualizedWavelength = 550;
    thePSFandMTFdataStruct = RGCMosaicAnalyzer.compute.psfDataStructForCoVisualizationWithConeMosaic(...
        theOI, domainUnits, theVisualizedWavelength);

   
    % OR Replace the PSF.data with the slice at the visualized wavelength
    thePSFandMTFdataStruct.data = thePSFandMTFdataStruct.psfSliceAtTargetWavelength;

    % OR Replace the PSF.data with the v_lambda weighted PSF
    thePSFandMTFdataStruct.data = thePSFandMTFdataStruct.psfVlambdaWeighted;
    

     % Annulus-1
    targetConePositions = [...
        -6.09 -0.043; ...  % L-center
        -6.15 -0.008; ...  % L-surround
        -6.06 -0.042; ...
        -6.05  -0.02];

    % Annulus-2
    targetConePositions = [...
        -6.09 -0.043; ...  % L-center
        -6.15 -0.01; ...  % L-surround
        -6.06 -0.042; ... % M-center
        -6.17  -0.04];    % M-sueeounr

   


    outlinedConeIndices = zeros(1, size(targetConePositions,1));
    outlinedConeColors = zeros(size(targetConePositions,1),3);

    for iCone = 1:size(targetConePositions,1)
        [~,outlinedConeIndices(iCone)] = min(sum(bsxfun(@minus, theMRGCMosaic.inputConeMosaic.coneRFpositionsDegs, targetConePositions(iCone,:)).^2,2));
        switch(theMRGCMosaic.inputConeMosaic.coneTypes(outlinedConeIndices(iCone)))
            case cMosaic.LCONE_ID
                outlinedConeColors(iCone,:) = RGCMosaicConstructor.constants.LcenterColor;
            case cMosaic.MCONE_ID
                outlinedConeColors(iCone,:) = RGCMosaicConstructor.constants.McenterColor;
            case cMosaic.SCONE_ID
                outlinedConeColors(iCone,:) = RGCMosaicConstructor.constants.ScenterColor;
        end
    end


    figureDir = pwd;
    videoOBJ = VideoWriter(fullfile(figureDir,'InputConeMosaicSpatioTemporalActivation'), 'MPEG-4');
    videoOBJ.FrameRate = 30;
    videoOBJ.Quality = 100;
    videoOBJ.open();

    theBackgroundColor = [33 40 42]/255;
    theLighterBackgroundColor = [43 50 52]/255;
    theLabelColor = [0.9 0.9 0.9];

    for iTF = 1:numel(temporalFrequenciesExamined)

        % Retrieve the cone excitation response data for this TF
        theTemporalSupportSecondsForThisTF = squeeze(stimParams.temporalSupportSeconds(iTF,:));
        theInputConeMosaicExcitationResponsesForThisTF = squeeze(theInputConeMosaicTTFresponses(iTF,:,:));
        nanIndices = find(isnan(theTemporalSupportSecondsForThisTF));
        if (isempty(nanIndices))
            theTimeBins = 1:numel(theTemporalSupportSecondsForThisTF);
        else
            theTimeBins = 1:(nanIndices-1);
        end
        theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF = theTemporalSupportSecondsForThisTF(theTimeBins);
        theInputConeMosaicExcitationResponsesForThisTF = theInputConeMosaicExcitationResponsesForThisTF(theTimeBins,:);

        % Retrieve the photocurrent response data for this TF
        theTemporalSupportSecondsForThisTF = squeeze(theInputConeMosaicPhotocurrentTemporalSupportSeconds(iTF,:));
        theInputConeMosaicPhotocurrentResponsesForThisTF = squeeze(theInputConeMosaicPhotocurrentTTFresponses(iTF,:,:));
        nanIndices = find(isnan(theTemporalSupportSecondsForThisTF));
        if (isempty(nanIndices))
            theTimeBins = 1:numel(theTemporalSupportSecondsForThisTF);
        else
            theTimeBins = 1:(nanIndices-1);
        end
        theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF = theTemporalSupportSecondsForThisTF(theTimeBins);
        theInputConeMosaicPhotocurrentResponsesForThisTF = theInputConeMosaicPhotocurrentResponsesForThisTF(theTimeBins,:);


       
        modulationsRange = 0.5*[-1 1];
        photocurrentsRange = 4*[-1 1];

        for iTimeBin = 1:10:numel(theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF)
            
            
            [~,photocurrentsTimeBin] = min(abs(theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF-theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(iTimeBin)));
            thePhotocurrentsActivation = reshape(squeeze(theInputConeMosaicPhotocurrentResponsesForThisTF(photocurrentsTimeBin, :)), [1 1 theMRGCMosaic.inputConeMosaic.conesNum]);
            
            theCurrentTimeMsec = 1e3 * theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF(photocurrentsTimeBin);

            thePlotTitle = sprintf('TF: %2.2f Hz, time: %2.0f msec (pAmps)', ...
                temporalFrequenciesExamined(iTF),  theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(iTimeBin)*1e3);

           

            hFig = figure(2002); clf;
            set(hFig, 'Position', [10 10 2176 1200], 'Color', theBackgroundColor );
        
            subplotHeight = 0.4;
            subplotWidth = subplotHeight;

            axRFpooling = axes('Position', [0.01 0.56 subplotWidth  subplotHeight]);
            axMosaicActivation = axes('Position', [0.01 0.07 subplotWidth  subplotHeight]);
        
            axExemplarCone1 = axes('Position', [0.455 0.56 0.24 0.4]);
            axExemplarCone2 = axes('Position', [0.745 0.56 0.24 0.4]);
            axExemplarCone3 = axes('Position', [0.455 0.07 0.24 0.4]);
            axExemplarCone4 = axes('Position', [0.745 0.07 0.24 0.4]);
        
            set(axExemplarCone1 , 'Color', theLighterBackgroundColor)
            set(axExemplarCone2 , 'Color', theLighterBackgroundColor)
            set(axExemplarCone3 , 'Color', theLighterBackgroundColor)
            set(axExemplarCone4 , 'Color', theLighterBackgroundColor)


            [~, ~, centerLineWeightingFunctions, surroundLineWeightingFunctions] = ...
                theMRGCMosaic.visualizeCenterSurroundConePoolingMap(theTargetRGCindex, ...
                'axesToRenderIn', axRFpooling, ...
                'backgroundColor', theBackgroundColor ,...
                'identifiedConeAperture', 'lightCollectingArea5sigma', ...
                'identifyPooledCones', false, ...
                'identifyInputCones', true, ...
                'doNotLabelScaleBar', true, ...
                'scaleBarDegs', 0, ...
                'plottedRFoutlineLineWidth', 4.0, ...
                'plottedRFoutlineEdgeColor', [1 1 1], ...
                'plottedRFoutlineFaceColor', [0 0 0], ...
                'plottedRFoutlineFaceAlpha', 0.0, ...
                'spatialSupportSamplesNumForLineWeightingFunctions', 2400, ...
                'inputConesAlpha', 0.5, ...
                'noXLabel', true, ...
                'noXLabel', true, ...
                'domainVisualizationLimits', narrowDomainVisualizationLimits, ...
                'domainVisualizationTicks', narrowDomainVisualizationTicksNoYticks);
                
            set(axRFpooling, 'TickDir', 'both', 'fontSize', 24);

            xlabel(axRFpooling, '')
            ylabel(axRFpooling, '')
            set(hFig, 'Color', theBackgroundColor);
            

            centerLineWeightingProfile = centerLineWeightingFunctions.xProfile;
		    surroundLineWeightingProfile = surroundLineWeightingFunctions.xProfile;

            hold(axRFpooling, 'on')
            set(axRFpooling, 'Color', theBackgroundColor );
            theCenterProfile = centerLineWeightingProfile.amplitude;
            maxCenterResponse = max(abs(theCenterProfile));

            baselineValue = -0.18;
            theCenterProfile = baselineValue+ 0.35 * theCenterProfile/maxCenterResponse;
            theSurroundProfile = surroundLineWeightingProfile.amplitude;
            theSurroundProfile = baselineValue -0.35 * theSurroundProfile/maxCenterResponse;


            a1 = area(axRFpooling, ...
                centerLineWeightingProfile.spatialSupportDegs, theCenterProfile, baselineValue);
            a1.FaceColor = [1 .2 .4];
            a1.FaceAlpha = 0.5;
            a1.EdgeColor = [1 1 1];
            a1.LineWidth = 2.0;


            a2 = area(axRFpooling, ...
                surroundLineWeightingProfile.spatialSupportDegs, theSurroundProfile, baselineValue);
            a2.FaceColor = [.2 .4 1];
            a2.FaceAlpha = 0.5;
            a2.EdgeColor = [1 1 1];
            a2.LineWidth = 2.0;

            set(axRFpooling, 'XColor', theLabelColor , 'YColor', theLabelColor );
            title(axRFpooling, 'input cone mosaic pooling', 'Color', theLabelColor , 'FontSize', 24, 'FontAngle', 'italic')
            box(axRFpooling, 'on')


            theActivationlUT = brewermap(256, '*greys') .^ 1.4;

            theMRGCMosaic.inputConeMosaic.visualize(...
                'figureHandle', hFig, ...
                'axesHandle', axMosaicActivation, ...
                'activation', thePhotocurrentsActivation, ...
                'activationRange', photocurrentsRange*0.7, ...
                'withSuperimposedPsf', thePSFandMTFdataStruct, ...
                'withSuperimposedPSFcontourLineColor', [1 1 0], ...
                'withSuperimposedPSFcolorMap', brewermap(1024, '*oranges'), ...
                'activationColorMap', theActivationlUT , ...
                'visualizedConeAperture', 'lightcollectingarea5sigma', ...
                'visualizedConeApertureThetaSamples', 32, ...
                'labelConesInActivationMap', true, ...
                'labelConesWithIndices', outlinedConeIndices, ...
                'conesLineWidth', 2, ...
                'domain', domainUnits, ...
                'domainVisualizationLimits', narrowDomainVisualizationLimits, ...
                'domainVisualizationTicks', narrowDomainVisualizationTicksNoYticks, ...
                'noYLabel', true, ...
                'noXlabel', ~true, ...
                'backgroundColor', theLighterBackgroundColor, ...
                'clearAxesBeforeDrawing', true, ...
                'figureBackgroundColor', theBackgroundColor , ...
                'plotTitleColor', theLabelColor, ...
                'fontSize', 24, ...
                'fontAngle', 'italic', ...
                'verbose', false, ...
                'plotTitle', sprintf('input cone mosaic photocurrent activation (@%2.0f msec)', theCurrentTimeMsec), ...
                'plotTitleFontSize', 24, ...
                'plotTitleFontWeight', 'normal');
   
            box(axMosaicActivation, 'on');
            set(axMosaicActivation, 'XColor', theLabelColor , 'YColor', theLabelColor ,  'TickDir', 'both');

        
            noXLabel = true;
            noYLabel = ~true;

            iCone = 1;
            plotComboExcitationsPhotocurrentResponseTimeSeries(axExemplarCone1, ...
                theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicExcitationResponsesForThisTF(:,outlinedConeIndices(iCone))), ...
                theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicPhotocurrentResponsesForThisTF(:, outlinedConeIndices(iCone))), ...
                iTimeBin, photocurrentsTimeBin, ...
                outlinedConeColors(iCone,:), ...
                theLabelColor, ...
                [theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(1) theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(end)], ...
                modulationsRange, ...
                photocurrentsRange, ...
                noXLabel, noYLabel ...
                );

            noXLabel = true;
            noYLabel = true;

            iCone = 2;
            plotComboExcitationsPhotocurrentResponseTimeSeries(axExemplarCone2, ...
                theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicExcitationResponsesForThisTF(:,outlinedConeIndices(iCone))), ...
                theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicPhotocurrentResponsesForThisTF(:, outlinedConeIndices(iCone))), ...
                iTimeBin, photocurrentsTimeBin, ...
                outlinedConeColors(iCone,:), ...
                theLabelColor, ...
                [theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(1) theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(end)], ...
                modulationsRange, ...
                photocurrentsRange, ...
                noXLabel, noYLabel ...
                );
           

            noXLabel = ~true;
            noYLabel = ~true;
            iCone = 3;
            plotComboExcitationsPhotocurrentResponseTimeSeries(axExemplarCone3, ...
                theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicExcitationResponsesForThisTF(:,outlinedConeIndices(iCone))), ...
                theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicPhotocurrentResponsesForThisTF(:, outlinedConeIndices(iCone))), ...
                iTimeBin, photocurrentsTimeBin, ...
                outlinedConeColors(iCone,:), ...
                theLabelColor, ...
                [theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(1) theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(end)], ...
                modulationsRange, ...
                photocurrentsRange, ...
                noXLabel, noYLabel ...
                );

            noXLabel = ~true;
            noYLabel = true;
            iCone = 4;
            plotComboExcitationsPhotocurrentResponseTimeSeries(axExemplarCone4, ...
                theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicExcitationResponsesForThisTF(:,outlinedConeIndices(iCone))), ...
                theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
                squeeze(theInputConeMosaicPhotocurrentResponsesForThisTF(:, outlinedConeIndices(iCone))), ...
                iTimeBin, photocurrentsTimeBin, ...
                outlinedConeColors(iCone,:), ...
                theLabelColor, ...
                [theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(1) theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(end)], ...
                modulationsRange, ...
                photocurrentsRange, ...
                noXLabel, noYLabel ...
                );
            

            drawnow;
            videoOBJ.writeVideo(getframe(hFig));

        end % for iTimeBin
    end % iTF

    videoOBJ.close();
end


function plotComboExcitationsPhotocurrentResponseTimeSeries(ax, ...
                theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF, ...
                theInputConeMosaicExcitationResponsesForThisTF, ...
                theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF, ...
                theInputConeMosaicPhotocurrentResponsesForThisTF, ...
                coneExcitationTimeBin, photocurrentsTimeBin, ...
                theConeColor, ...
                theLabelColor, ...
                theTimeLimits, ...
                modulationsRange, ...
                photocurrentsRange, ...
                noXLabel, noYLabel)
            
    yyaxis(ax, 'left')

    plot(ax, ...
        theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF*1e3, ...
        theInputConeMosaicPhotocurrentResponsesForThisTF*0, '-',...
        'Color', [1 1 1], 'LineWidth', 1.5);

    hold(ax, 'on')
    p1  = scatter(ax, ...
        theInputConeMosaicExcitationsTemporalSupportSecondsForThisTF(1:coneExcitationTimeBin)*1e3,  ...
        theInputConeMosaicExcitationResponsesForThisTF(1:coneExcitationTimeBin), 144,...
        'MarkerFaceColor', [0 0 0], 'MarkerFaceAlpha', 0.5, ...
        'MarkerEdgeColor', theConeColor, 'LineWidth', 1.5);

   

    set(ax, 'XLim', theTimeLimits*1e3);
    set(ax, 'XTick', 0:500:2000);
    set(ax, 'YLim', modulationsRange, 'YTick', -1:0.1:1, 'YTickLabel', sprintf('%+1.1f\n', -1:0.1:1));
    grid(ax, 'on');
    box(ax, 'off');

    if (~noYLabel)
        ylabel(ax, 'cone modulation');
    else
        set(ax, 'YTickLabel', {});
    end

    if (~noXLabel)
        xlabel(ax, 'time (msec)');
    end

    set(ax, 'YColor', theConeColor, 'LineWidth', 1.0);

    yyaxis(ax, 'right')

    

    hold(ax, 'on');
    p2 = scatter(ax, ...
        theInputConeMosaicPhotocurrentTemporalSupportSecondsForThisTF(1:photocurrentsTimeBin)*1e3,  ...
        theInputConeMosaicPhotocurrentResponsesForThisTF(1:photocurrentsTimeBin), 144, ...
        'MarkerEdgeColor', [1 0.5 0], 'MarkerFaceAlpha', 0.5, ...
        'MarkerFaceColor', [0 0 0], 'LineWidth', 1.5);
    
    

    set(ax, 'YLim', photocurrentsRange, 'YTick', -10:1:10, 'YTickLabel', sprintf('%+1.1f\n', -10:1:10));
    set(ax, 'FontSize', 20, 'FontAngle', 'italic');
    set(ax, 'YColor', theLabelColor );
    grid(ax, 'on');
    set(ax, 'XColor', theLabelColor , 'LineWidth', 1.0);

    if (~noYLabel)
        ylabel(ax, 'photocurrent (pAmps)');
    else
        set(ax, 'YTickLabel', {});
    end

    legend(ax, [p1 p2], {'cone excitations', 'photocurrents'}, 'Location', 'SouthWest', 'NumColumns', 1, 'TextColor', theLabelColor ); 

    hold(ax, 'off');
end

function [TTFparamsStruct, stimParams, ...
        theInputConeMosaicTTFresponses, ...
        theInputConeMosaicPhotocurrentTemporalSupportSeconds, ...
        theInputConeMosaicPhotocurrentTTFresponses, ...
        photocurrentBasedTTFsComputed, ...
        computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex, ...
        computePhotocurrentResponsesOnlyForSelectConeIndices] = loadAllResponses(theInputConeMosaicTTFResponsesFullFileName, theTargetRGCindex, theTargetMRGCMosaic, mRGCsOperateOnBackgroundAdaptedPhotocurrents)

    % See if there are photocurrent responses in the input file
    computedTTFs = who('-file', theInputConeMosaicTTFResponsesFullFileName);
    photocurrentBasedTTFsComputed = ismember('theInputConeMosaicPhotocurrentTTFresponses', computedTTFs);

    if (photocurrentBasedTTFsComputed)
        fprintf('Loading computed input cone mosaic PHOTOCURRENT TTF responses from %s.\n', theInputConeMosaicTTFResponsesFullFileName);

        % Load cone excitation + photocurrent responses
        load(theInputConeMosaicTTFResponsesFullFileName, ...
            'theMRGCMosaic', 'stimParams', 'TTFparamsStruct', ...
            'computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex', ...
            'computePhotocurrentResponsesOnlyForSelectConeIndices', ...
            'theInputConeMosaicPhotocurrentTemporalSupportSeconds', ...
            'theInputConeMosaicPhotocurrentTTFresponses', ...
            'theInputConeMosaicBackgroundPhotocurrents', ...
            'theInputConeMosaicTTFresponses');


        % Ensure RGC indices match
        assert(...
            (...
                (~isempty(computePhotocurrentResponsesOnlyForSelectConeIndices)) && ...
                (theTargetRGCindex == computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex) ...
            ), ...
            sprintf('The RGC index passed (%d) is not the same as the one (%d) that was used to compute the loaded input cone mosaic responses', ...
                    theTargetRGCindex, computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex));


        if (~mRGCsOperateOnBackgroundAdaptedPhotocurrents)
            fprintf('Adding background photocurrents');
            for iOri = 1:size(theInputConeMosaicPhotocurrentTTFresponses,1)
                for iSF = 1:size(theInputConeMosaicPhotocurrentTTFresponses,2)
                    theInputConeMosaicPhotocurrentTTFresponses(iOri,iSF,:,:) = bsxfun(@plus, ...
                        theInputConeMosaicPhotocurrentTTFresponses(iOri,iSF,:,:), ...
                        reshape(theInputConeMosaicBackgroundPhotocurrents(iOri, iSF, :), [1 1 1 size(theInputConeMosaicBackgroundPhotocurrents,3)]));
                end % iSF
            end % iOri
        end


        % Check that all photocurrent response dimensions agree with the cone excitation responses
        assert(size(theInputConeMosaicTTFresponses,1) == size(theInputConeMosaicTTFresponses,1), ...
            'Mismatch in # of temporal frequencies');

        assert(size(theInputConeMosaicTTFresponses,2) == size(theInputConeMosaicTTFresponses,2), ...
            'Mismatch in # of time bins');
        assert(size(theInputConeMosaicTTFresponses,3) == size(theInputConeMosaicTTFresponses,3), ...
            'Mismatch in # of cones');

    else
        fprintf('Loading computed input cone mosaic TTF responses from %s.\n', theInputConeMosaicTTFResponsesFullFileName);

        load(theInputConeMosaicTTFResponsesFullFileName, ...
            'theMRGCMosaic', 'stimParams', 'TTFparamsStruct', ...
            'theInputConeMosaicTTFresponses');

        theInputConeMosaicPhotocurrentTemporalSupportSeconds = [];
        theInputConeMosaicPhotocurrentTTFresponses = [];
        theInputConeMosaicBackgroundPhotocurrents = [];
    end


    % Assert that the input cone mosaic in the stored mRGC mosaic is the same as the input cone mosaic of the passed mRGC Mosaic
    assert(theTargetMRGCMosaic.inputConeMosaic.conesNum == theMRGCMosaic.inputConeMosaic.conesNum, ...
        'Number of cones in the loaded input cone mosaic TTF responses file is not identicial to the that of input cone mosaic of the passed mRGC mosaic');
    assert(all(theTargetMRGCMosaic.inputConeMosaic.coneTypes == theMRGCMosaic.inputConeMosaic.coneTypes), ...
        'Cone types in the loaded input cone mosaic TTF responses file are not identicial to those of the input cone mosaic of the passed mRGC mosaic');

end



