function [mRGCMosaicAchromaticResponsesFileName, ...
          mRGCMosaicLconeIsolatingResponsesFileName, ...
          mRGCMosaicMconeIsolatingResponsesFileName, ...
          opticsParams, opticsToEmploy] = generateFileNamesForContrastedResponses(mosaicParams, measuredResponseType, userPrompt)

    fprintf('\n---> %s \n', userPrompt);
    [opticsParams,opticsToEmploy] = MosaicPoolingOptimizer.chooseOpticsForInputConeMosaicSTFresponses(mosaicParams);

    % Generate filename for the computed mRGCMosaicSTF responses
    [mRGCMosaicResponsesFileName, resourcesDirectory] = ...
        MosaicPoolingOptimizer.resourceFileNameAndPath(sprintf('mRGCMosaic%s',measuredResponseType), ...
            'mosaicParams', mosaicParams, ...
            'opticsParams', opticsParams);

    % Achromatic responses filename
    coneFundamentalsOptimizedForStimPosition = false;
    [~, ~, mRGCMosaicAchromaticResponsesFileName] = ...
        MosaicPoolingOptimizer.chooseStimulusChromaticityForMosaicResponsesAndUpdateFileName(...
        mRGCMosaicResponsesFileName, measuredResponseType, ...
        'doNotQueryUserButUseThisStimulusChromaticityAndConeFundamentals', struct(...
                    'stimulusChromaticity', 'achromatic',...
                    'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition));

    % L-cone isolating responses filename
    [~, ~, mRGCMosaicLconeIsolatingResponsesFileName] = ...
        MosaicPoolingOptimizer.chooseStimulusChromaticityForMosaicResponsesAndUpdateFileName(...
        mRGCMosaicResponsesFileName, measuredResponseType, ...
        'doNotQueryUserButUseThisStimulusChromaticityAndConeFundamentals', struct(...
                    'stimulusChromaticity', 'Lcone isolating',...
                    'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition));

    % M-cone isolating responses filename
    [~, ~, mRGCMosaicMconeIsolatingResponsesFileName] = ...
        MosaicPoolingOptimizer.chooseStimulusChromaticityForMosaicResponsesAndUpdateFileName(...
        mRGCMosaicResponsesFileName, measuredResponseType, ...
        'doNotQueryUserButUseThisStimulusChromaticityAndConeFundamentals', struct(...
                    'stimulusChromaticity', 'Mcone isolating',...
                    'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition));

    mRGCMosaicAchromaticResponsesFileName = fullfile(resourcesDirectory, mRGCMosaicAchromaticResponsesFileName);
    mRGCMosaicLconeIsolatingResponsesFileName = fullfile(resourcesDirectory, mRGCMosaicLconeIsolatingResponsesFileName);
    mRGCMosaicMconeIsolatingResponsesFileName = fullfile(resourcesDirectory, mRGCMosaicMconeIsolatingResponsesFileName);
end

