function performContrastMSequenceRFsAcrossDifferentChromaticities(...
            mosaicParams, ...
            stimPositionDegs, ternaryInsteadOfBinaryMsequence, ...
            mSequenceBitLength, rfPixelsAcross,...
            rawFiguresRoot, scaledFiguresRoot, varargin)


    % Parse input
    p = inputParser;
    p.addParameter('performSurroundAnalysisForConesExclusiveToTheSurround', true, @islogical);
    p.addParameter('targetRangeForSurroundConeMix', [0.4 0.5], @(x)(isnumeric(x)&&(numel(x)==2)));
    p.addParameter('targetRangeForCenterMix', [1 1], @(x)(isnumeric(x)&&(numel(x)==2)));
    p.addParameter('exportScaledFigureVersionForManuscript', true, @islogical);
    p.parse(varargin{:});
    performSurroundAnalysisForConesExclusiveToTheSurround = p.Results.performSurroundAnalysisForConesExclusiveToTheSurround;
    targetRangeForSurroundConeMix = p.Results.targetRangeForSurroundConeMix;
    targetRangeForCenterMix = p.Results.targetRangeForCenterMix;
    exportScaledFigureVersionForManuscript = p.Results.exportScaledFigureVersionForManuscript;

    % Get PDF directory
    [~,~,pdfDirectory] = MosaicPoolingOptimizer.resourceFileNameAndPath('pdfsDirectory', ...
        'mosaicParams', mosaicParams);

    % Load the compute-ready mRGCMosaic
    theComputeReadyMRGCmosaic = MosaicPoolingOptimizer.queryUserAndLoadComputeReadyMRGCMosaic(mosaicParams);
    
    % Find the indices of mRGCs whose surround cone mix is within the target range
    mRGCindicesToVisualizeMSequenceRFmapsAcrossChromaticities = MosaicPoolingOptimizer.findMRGCindicesWithDesiredSurroundConeMix(...
            theComputeReadyMRGCmosaic, ...
            targetRangeForSurroundConeMix, targetRangeForCenterMix, ...
            performSurroundAnalysisForConesExclusiveToTheSurround, ...
            rawFiguresRoot, scaledFiguresRoot, exportScaledFigureVersionForManuscript);


    userPrompt = 'Select the optics that were used to compute the mRGC mosaic mSequence RF maps';
    measuredResponseType = 'MSequenceResponses';
    
    % Start building up the achromatic mRGCMosaicMSequenceResponsesFileName
    [mRGCMosaicMSequenceResponsesFileName, ~, ~, opticsParamsForMSeqRFmapping] = MosaicPoolingOptimizer.generateFileNamesForContrastedResponses(...
            mosaicParams, measuredResponseType, userPrompt);


    % Ask the user whether to use custom cone fundamentals and update theAchromaticMSequenceResponsesFileName
    stimulusChromaticityAndConeFundamentals = struct(...
        'stimulusChromaticity', 'achromatic', ...
        'coneFundamentalsOptimizedForStimPosition', []);

    [~, coneFundamentalsOptimizedForStimPosition, theAchromaticMSequenceResponsesFileName] = ...
        MosaicPoolingOptimizer.chooseStimulusChromaticityForMosaicResponsesAndUpdateFileName(...
        mRGCMosaicMSequenceResponsesFileName, 'mRGCMosaicMSequenceResponses', ...
        'doNotQueryUserButUseThisStimulusChromaticityAndConeFundamentals', stimulusChromaticityAndConeFundamentals);


    % Generate theLconeIsolatingMSequenceResponsesFileName
    stimulusChromaticityAndConeFundamentals = struct(...
        'stimulusChromaticity', 'Lcone isolating', ...
        'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition);

    [~, ~, theLconeIsolatingMSequenceResponsesFileName] = ...
        MosaicPoolingOptimizer.chooseStimulusChromaticityForMosaicResponsesAndUpdateFileName(...
        mRGCMosaicMSequenceResponsesFileName, 'mRGCMosaicMSequenceResponses', ...
        'doNotQueryUserButUseThisStimulusChromaticityAndConeFundamentals', stimulusChromaticityAndConeFundamentals);


    % Generate theMconeIsolatingMSequenceResponsesFileName
    stimulusChromaticityAndConeFundamentals = struct(...
        'stimulusChromaticity', 'Mcone isolating', ...
        'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition);

    [~, ~, theMconeIsolatingMSequenceResponsesFileName] = ...
        MosaicPoolingOptimizer.chooseStimulusChromaticityForMosaicResponsesAndUpdateFileName(...
        mRGCMosaicMSequenceResponsesFileName, 'mRGCMosaicMSequenceResponses', ...
        'doNotQueryUserButUseThisStimulusChromaticityAndConeFundamentals', stimulusChromaticityAndConeFundamentals);



    % Encode m-sequence specific info
    theAchromaticMSequenceResponsesFileName = MosaicPoolingOptimizer.encodeMSequenceSpecificInfoToFilename(...
        theAchromaticMSequenceResponsesFileName, ...
        ternaryInsteadOfBinaryMsequence, ...
        mSequenceBitLength, ...
        rfPixelsAcross);

    theLconeIsolatingMSequenceResponsesFileName = MosaicPoolingOptimizer.encodeMSequenceSpecificInfoToFilename(...
        theLconeIsolatingMSequenceResponsesFileName, ...
        ternaryInsteadOfBinaryMsequence, ...
        mSequenceBitLength, ...
        rfPixelsAcross);

    theMconeIsolatingMSequenceResponsesFileName = MosaicPoolingOptimizer.encodeMSequenceSpecificInfoToFilename(...
        theMconeIsolatingMSequenceResponsesFileName, ...
        ternaryInsteadOfBinaryMsequence, ...
        mSequenceBitLength, ...
        rfPixelsAcross);

    % Optimally generated RF maps filename
    theOptimallyMappedAchromaticMSequenceRFmapsFileName = strrep(theAchromaticMSequenceResponsesFileName, '.mat', '_optimallyMappedRFs.mat');
    theOptimallyMappedLconeIsolatingMSequenceRFmapsFileName = strrep(theLconeIsolatingMSequenceResponsesFileName, '.mat', '_optimallyMappedRFs.mat');
    theOptimallyMappedMconeIsolatingMSequenceRFmapsFileName = strrep(theMconeIsolatingMSequenceResponsesFileName, '.mat', '_optimallyMappedRFs.mat');


    % Encode stimulus position info to the mRGCMosaicMSequenceResponsesFileName
    positionPostFix = sprintf('_atPosition_%2.2f_%2.2f.mat', stimPositionDegs(1), stimPositionDegs(2));
    theOptimallyMappedAchromaticMSequenceRFmapsFileName = strrep(theOptimallyMappedAchromaticMSequenceRFmapsFileName, '.mat', positionPostFix);
    theOptimallyMappedLconeIsolatingMSequenceRFmapsFileName = strrep(theOptimallyMappedLconeIsolatingMSequenceRFmapsFileName, '.mat', positionPostFix);
    theOptimallyMappedMconeIsolatingMSequenceRFmapsFileName = strrep(theOptimallyMappedMconeIsolatingMSequenceRFmapsFileName, '.mat', positionPostFix);


    % Prompt user for examined RGC location
    exampleLconeCenterRGCposition = input('Enter visualized RGC position (e.g. [0.7 0.7], or empty to visualize all RGCs) :');
    exampleMconeCenterRGCposition = exampleLconeCenterRGCposition;

    MosaicPoolingOptimizer.contrastMSequenceRFsAcrossDifferentChromaticities(...
        exampleLconeCenterRGCposition, exampleMconeCenterRGCposition, ...
        theComputeReadyMRGCmosaic, ...
        theOptimallyMappedAchromaticMSequenceRFmapsFileName, ...
        theOptimallyMappedLconeIsolatingMSequenceRFmapsFileName, ...
        theOptimallyMappedMconeIsolatingMSequenceRFmapsFileName, ...
        coneFundamentalsOptimizedForStimPosition, ...
        rfPixelsAcross, opticsParamsForMSeqRFmapping, rawFiguresRoot, scaledFiguresRoot,...
        exportScaledFigureVersionForManuscript,  ...
        'examinedRGCindices', mRGCindicesToVisualizeMSequenceRFmapsAcrossChromaticities, ...
        'performSurroundAnalysisForConesExclusiveToTheSurround', performSurroundAnalysisForConesExclusiveToTheSurround, ...
        'tickSeparationArcMin', 2.0, ...
        'generateVideoWithAllExaminedRGCs', false);

end