function [RGCRFinputs, RGCRFweights] = wireInputConeMosaicToRGCRFs(...
        theInputConeMosaic, RGCRFposMicrons, ...
        localConeToRGCDensityRatioStruct, ...
        wiringParams,visualizationParams)
% Wire the input cone mosaic to the RF centers of a set of RGCs
%
% Syntax:
%   [RGCRFinputs, RGCRFweights] = RGCRFconnector.wireInputConeMosaicToRGCRFs(...
%        theInputConeMosaic, RGCRFposMicrons, ...
%        chromaticSpatialVarianceTradeoff, ...
%        localConeToRGCDensityRatioStruct, ...
%        wiringParams, ...
%        generateProgressionVideo)
%
% Description:
%   Wire the input cone mosaic to the RF centers of a set of RGCs
%
% Inputs:
%    theInputConeMosaic                 - the input cone mosaic
%    RGCRFposMicrons                    - [M x 2] matrix of (x,y) positions (in microns) of M target RGC RF centers
%    localConeToRGCDensityRatioStruct   - Struct with info to compute the cone/RGC density ratio at any (x,y) position
%    wiringParams                       - Struct with the following wiring params
%       chromaticSpatialVarianceTradeoff   - Chromatic-SpatialVariance tradefoff
%       sequentialConeTypeWiring           - Logical. Whether to wire cone types sequentially or not
%       maxNearbyRGCsNum                   - Scalar. Max number of nearby RGCs to look for assignment, if a cone cannot
%                                         be assigned to its closest RGC because that RGC already has one input cone
%    visualizationParams                 - Struct with the following visualization params
%       generateProgressionVideo           - Boolean. Whether to generate a video showning the different wiring steps
%       exportStagesAsPDF                  - Boolean. Whether to generate a PDF at the end of each wiring stage
%
% Outputs:
%    RGCRFinputs                - Cell array with indices of the input cones, one cell per each target RGC RF center
%    RGCRFweights               - Cell array with weights of the input cones, one cell per each target RGC RF center   
%
% Optional key/value pairs
%   none
%   
% History:
%   5/11/2022       NPC     Wrote it
%

    
    % Step1. Connect cones to the nearestRGC minimizing the cost of
    % ownership of the input cones
    [RGCRFinputs, RGCRFweights, availableZeroInputRGCsNum] = ...
        RGCRFconnector.connectEachConeToItsNearestRGC(...
            theInputConeMosaic, RGCRFposMicrons, ...
            localConeToRGCDensityRatioStruct, ...
            wiringParams, visualizationParams);

    hFig = figure(2001); clf;
    set(hFig, 'Color', [1 1 1], 'Position', [10 10 900 1100]);
    axMosaic = subplot('Position', [0.15 0.35 0.8 0.62]);
    axStats{1} = subplot('Position', [0.07 0.05 0.42 0.2]);
    axStats{2} = subplot('Position', [0.57 0.05 0.42 0.2]);
    RGCRFconnector.visualizeWiringOfInputConeMosaicToRFcenters(...
            RGCRFinputs, RGCRFweights, ...
            theInputConeMosaic, ...
            'titleString', 'before', ...
            'superimposeConeInputWiring', true, ...
            'pauseAfterEachRGCisRendered', ~true, ...
            'figureHandle', hFig, ...
            'axesHandle', axMosaic);

    RGCRFconnector.reportConeInputStatistics(...
            wiringParams.chromaticSpatialVarianceTradeoff, ...
            RGCRFinputs, RGCRFweights, theInputConeMosaic, ...
            localConeToRGCDensityRatio, ...
            'figureHandle', hFig, ...
            'axesHandles', axStats);
    
    
    % Step2. Re-assign cones from RGCs to nearby RGCs minimizing the
    % combined cost of cone ownership for the 2 RGCs
    mode = 'lower combined cost';
    mode = 'less inputs';

    [RGCRFinputs, RGCRFweights] = ...
        RGCRFconnector.reassignConesToNearbyRGCs(...
            mode, ...
            theInputConeMosaic, RGCRFinputs, RGCRFweights, ...
            localConeToRGCDensityRatio, ...
            wiringParams, visualizationParams);
    

    hFig = figure(2002); clf;
    set(hFig, 'Color', [1 1 1], 'Position', [10 10 900 1100]);
    axMosaic = subplot('Position', [0.15 0.35 0.8 0.62]);
    axStats{1} = subplot('Position', [0.07 0.05 0.42 0.2]);
    axStats{2} = subplot('Position', [0.57 0.05 0.42 0.2]);
    RGCRFconnector.visualizeWiringOfInputConeMosaicToRFcenters(...
            RGCRFinputs, RGCRFweights, ...
            theInputConeMosaic, ...
            'titleString', 'after', ...
            'superimposeConeInputWiring', true, ...
            'pauseAfterEachRGCisRendered', ~true, ...
            'figureHandle', hFig, ...
            'axesHandle', axMosaic);

    RGCRFconnector.reportConeInputStatistics(...
            wiringParams.chromaticSpatialVarianceTradeoff, ...
            RGCRFinputs, RGCRFweights, theInputConeMosaic, ...
            localConeToRGCDensityRatio, ...
            'figureHandle', hFig, ...
            'axesHandles', axStats);
end