% Compare eccentricity-varying and spatially uniform cone efficacy
%
% Description:
%   Cone inner-segment aperture and outer-segment length vary with retinal
%   eccentricity. This example compares the response of one cone mosaic
%   with those variations enabled against the same mosaic with spatially
%   uniform aperture and outer-segment length.
%
%   Related examples cover aperture shape and macular pigment separately:
%     s_cmModifyApertureProperties
%     s_cmEccVaryingMacularPigment
%
% History:
%   03/01/21  NPC  Wrote it.
%   06/21/26  BW   Focus on one comparison and remove repeated mosaics.

%% Initialize
ieInit;

%% Generate a harmonic stimulus and its retinal image
% The scene resolution is high enough for the 20 cycles/degree stimulus
% without using the former 2048-by-2048 image.
pixelsNum = 1024;
fovDegs = 3.0;
stimFreqCyclesPerDeg = 20;

sceneParams.freq = stimFreqCyclesPerDeg*fovDegs;
sceneParams.contrast = 1;
sceneParams.ph = 0;
sceneParams.ang = 0;
sceneParams.row = pixelsNum;
sceneParams.col = pixelsNum;
sceneParams.GaborFlag = 0;

scene = sceneCreate('harmonic', sceneParams);
scene = sceneSet(scene, 'fov', fovDegs);

oi = oiCreate('human');
oi = oiCompute(oi, scene, 'pad value', 'mean');

%% Construct one mosaic
% Both conditions below use this same geometry and cone identities. Only
% the two efficacy flags change, which makes the comparison easier to read
% and avoids loading or cropping another large source lattice.
cm = cMosaic(...
    'sizeDegs', [1 1], ...
    'eccentricityDegs', [1 0], ...
    'randomSeed', 1);

%% Condition 1: eccentricity-varying efficacy
cm.eccVaryingConeAperture = true;
cm.eccVaryingOuterSegmentLength = true;
varyingResponse = cm.compute(oi);

%% Condition 2: spatially uniform efficacy
cm.eccVaryingConeAperture = false;
cm.eccVaryingOuterSegmentLength = false;
uniformResponse = cm.compute(oi);

%% Compare responses
% Plot the two responses with a shared range, followed by their percentage
% difference. Cone positions and types are identical in all three panels.
subplotPositions = NicePlot.getSubPlotPosVectors(...
    'rowsNum', 1, ...
    'colsNum', 3, ...
    'heightMargin', 0.01, ...
    'widthMargin', 0.05, ...
    'leftMargin', 0.05, ...
    'rightMargin', 0.03, ...
    'bottomMargin', 0.06, ...
    'topMargin', 0.03);

hFig = figure(1); clf;
originalFigureUnits = hFig.Units;
hFig.Units = 'pixels';
set(hFig, ...
    'Position', [10 10 1400 550], ...
    'Color', [1 1 1], ...
    'Name', 'Eccentricity-dependent cone efficacy');
hFig.Units = originalFigureUnits;

responseRange = [min([varyingResponse(:); uniformResponse(:)]) ...
    max([varyingResponse(:); uniformResponse(:)])];
responseColorMap = brewermap(1024, 'reds');

ax = axes('Parent', hFig, 'Position', subplotPositions(1,1).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', varyingResponse(:), ...
    'activationRange', responseRange, ...
    'activationColorMap', responseColorMap, ...
    'horizontalActivationColorBar', true, ...
    'colorBarTickLabelPostFix', 'R*', ...
    'crossHairsOnOpticalImageCenter', true, ...
    'plotTitle', 'eccentricity-varying efficacy');

ax = axes('Parent', hFig, 'Position', subplotPositions(1,2).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', uniformResponse(:), ...
    'activationRange', responseRange, ...
    'activationColorMap', responseColorMap, ...
    'horizontalActivationColorBar', true, ...
    'colorBarTickLabelPostFix', 'R*', ...
    'crossHairsOnOpticalImageCenter', true, ...
    'plotTitle', 'spatially uniform efficacy');

responseDenominator = max(abs(varyingResponse), eps);
percentDifference = 100*(varyingResponse-uniformResponse)./responseDenominator;
differenceRange = max(abs(percentDifference(:)))*[-1 1];

ax = axes('Parent', hFig, 'Position', subplotPositions(1,3).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', percentDifference(:), ...
    'activationRange', differenceRange, ...
    'activationColorMap', brewermap(1024, '*RdBu'), ...
    'horizontalActivationColorBar', true, ...
    'colorBarTickLabelPostFix', '%', ...
    'crossHairsOnOpticalImageCenter', true, ...
    'backgroundColor', [0 0 0], ...
    'plotTitle', '100*(varying-uniform)/varying');

fprintf('Median absolute response difference: %0.3f%%\n', ...
    median(abs(percentDifference(:)), 'omitnan'));
