% Compare rod intrusion near the fovea and in the peripheral retina
%
% Description:
%   Rod density increases outside the fovea, reducing the retinal area
%   available to cone apertures. This compact example compares equal-sized
%   foveal and peripheral cMosaic patches using rod-intrusion-adjusted cone
%   apertures.
%
% See also:
%   s_cmRodIntrusion
%
% History:
%   06/21/26  BW  Replace nine separate mosaics with one focused pair.

%% Initialize
ieInit;

%% Shared cone-aperture model
coneApertureModifiers = struct(...
    'smoothLocalVariations', true, ...
    'sigma', 0.204, ...  % McMahon et al. (2000)
    'shape', 'Gaussian');

commonParameters = {...
    'sourceLatticeSizeDegs', 60, ...
    'sizeDegs', [1 1], ...
    'whichEye', 'right eye', ...
    'eccVaryingConeBlur', true, ...
    'rodIntrusionAdjustedConeAperture', true, ...
    'coneApertureModifiers', coneApertureModifiers, ...
    'randomSeed', 1234};

%% Generate one foveal and one peripheral mosaic
% The full source lattice is loaded for the first constructor and reused
% from the in-memory lattice cache for the second constructor.
fovealMosaic = cMosaic(commonParameters{:}, ...
    'eccentricityDegs', [0 0]);
peripheralMosaic = cMosaic(commonParameters{:}, ...
    'eccentricityDegs', [8 8]);

%% Compare the light-collecting apertures
hFig = figure(1); clf;
originalFigureUnits = hFig.Units;
hFig.Units = 'pixels';
set(hFig, ...
    'Position', [100 200 1200 520], ...
    'Color', [1 1 1], ...
    'Name', 'Rod intrusion comparison');
hFig.Units = originalFigureUnits;

ax = subplot(1,2,1);
fovealMosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'visualizedConeAperture', 'lightCollectingArea', ...
    'plotTitle', 'fovea: [0 0] deg');

ax = subplot(1,2,2);
peripheralMosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'visualizedConeAperture', 'lightCollectingArea', ...
    'plotTitle', 'periphery: [8 8] deg');

fprintf('Foveal cones: %d; peripheral cones: %d.\n', ...
    fovealMosaic.conesNum, peripheralMosaic.conesNum);
