function surroundConnectivitySimulationParamsStruct = generateSurroundConnectivitySimulationParamsStruct(...
	whichZernikeDataBase, whichSubjectID, employRFCenterOverlappingMosaic, ...
	optimizationPositionsAndSizesGrids, surroundRetinalConePoolingModelParamsStruct, ...
	targetVisualSTFmodifiersFromMeanValuesParamsStruct)

% Compose struct with params that control the optimization of cone connections to the RGC RF surrounds
surroundConnectivitySimulationParamsStruct = struct(...
	'fixedOptimalOrientation', [], ...  % [] for automatic detection of max axcursion, or specify an orientation
	'optimizationPositionsGrid', optimizationPositionsAndSizesGrids(:,1:2), ...
	'optimizationSizeGrid', optimizationPositionsAndSizesGrids(:,3:4), ...
	'opticsParamsStruct', struct(...
		'ZernikeDataBase', whichZernikeDataBase, ...
		'subjectID', whichSubjectID, ...
		'pupilDiameterMM', 3.0, ...
		'noLCA', false, ...
		'refractiveErrorDiopters', 0.0, ...
		'zeroCenterPSF', true, ...
		'modification', 'maxStrehlRatio' ... % choose from {'none', 'subtractedCentralRefraction', 'maxStrehlRatio', etc}
		), ...  % opticsParams
	'STFparamsStruct', struct(...
			'backgroundChromaticity', [0.301 0.301], ...
			'backgroundLuminanceCdM2', 50.0, ...
			'chromaticity', 'Achromatic', ...
			'coneFundamentalsOptimizedForStimPosition', false, ...
			'resolutionDegs', [], ...                       % to be determined separately for each optimization position
			'sfSupport', logspace(log10(0.01), log10(100), 20), ...
			'orientationDeltaDegs', 30, ...
			'spatialPhaseIncrementDegs', 30, ...
			'positionDegs', [], ...                         % to be detemined based on each optimization position
			'sizeDegs', [] ...                              % to be detemined separately for each optimization position;
			), ... % STFparamsStruct
	'targetVisualSTFmodifiersFromMeanValuesStruct', targetVisualSTFmodifiersFromMeanValuesParamsStruct, ...
	'fitParams', struct(...
		'weightsOptimization', struct(...					% params controlling the optimization of the surround cone pooling weights		
			'multiStartsNum', 32, ...
			'maxIterations', 128, ...
			'useParallel', true, ...
			'displayProgress', 'off' ... 					% choose between {'iter' and 'final-detailed'}
		), ...
		'GaussianToSTF', struct(...                         % params controlling the fit of a Gaussian to the center STF (used to estimate the RcDegs)
			'multiStartsNum', 32, ...
			'deltaThresholdToDeclareLocalMinInSTF', 0.01 ...
		), ...
		'DifferenceOfGaussiansToCompositeSTF', struct(...  %  params controlling the fit of a DoG to the composite STF (used to estimate Rc/Rs andintS/C ratios, which have to be optimized relative to the C&K macaque values at the corresponding eccentricity, by optimizing the surround cone pooling weights)
			'multiStartsNum', 128, ...
			'deltaThresholdToDeclareLocalMinInSTF', 0.01, ...
			'targetVisualSTFparamFractionalTolerances', surroundRetinalConePoolingModelParamsStruct.targetVisualSTFparamFractionalTolerances) ...
		), ... 
	'poolingOptimizationParamsStruct', struct(...
		'employRFCenterOverlappingMosaic', employRFCenterOverlappingMosaic, ...
		'coneTypesToBePooled', [cMosaic.LCONE_ID cMosaic.MCONE_ID], ...
		'maxSurroundSupportFactor', mRGCMosaic.maxSurroundSupportFactor, ...		    % max surround radius: this factor x C&K surroundCharacteristicRadius at the fitted cell's temporal equivalent eccentricity, ...
		'poolingModel', surroundRetinalConePoolingModelParamsStruct ...
	) ... % poolingOptimizationParamsStruct
); % surroundConnectivitySimulationParamsStruct