function surroundRetinalConePoolingModel = generateSurroundRetinalConePoolingStruct(surroundOptimizationStrategy)
	% Ranges of (VnarrowToVwideRatio, RnarrowToRwideRatio) of Packer&Dacey H1 cells
	RnarrowToRwideRatioRange = ...
	    max(RGCMosaicConstructor.constants.PackerDaceyParamsForH1CellIndices.RnarrowToRwideRatios)- ...
	    min(RGCMosaicConstructor.constants.PackerDaceyParamsForH1CellIndices.RnarrowToRwideRatios);
	VnarrowToVwideRatioRange = ...
	    max(RGCMosaicConstructor.constants.PackerDaceyParamsForH1CellIndices.VnarrowToVwideRatios)- ...
	    min(RGCMosaicConstructor.constants.PackerDaceyParamsForH1CellIndices.VnarrowToVwideRatios);

	switch (surroundOptimizationStrategy)
		case 'TargetH1paramsMediumVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1FixedCellIndex', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'fixedH1CellIndex', [], ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio', RnarrowToRwideRatioRange*0.25, ...
					'VnarrowToVwideRatio', VnarrowToVwideRatioRange*0.25), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...
	                'surroundToCenterRcRatio', 0.15, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.15) ...
				);

		case 'TargetH1paramsLooseVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1FixedCellIndex', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'fixedH1CellIndex', [], ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio', RnarrowToRwideRatioRange*0.2, ...
					'VnarrowToVwideRatio', VnarrowToVwideRatioRange*0.1), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...
	                'surroundToCenterRcRatio', 0.5, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.5) ...
				);

		case 'MiddleQH1paramsMediumVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio', [0.09 0.26]+0.05, ...
					'VnarrowToVwideRatio', [0.01 0.6]+0.31), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...
	                'surroundToCenterRcRatio', 0.15, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.15) ...
				);

	    case 'LowerLeftQH1paramsMediumVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio', [0.09 0.26], ...
					'VnarrowToVwideRatio', [0.01 0.6]), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...
	                'surroundToCenterRcRatio', 0.15, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.15) ...
				);

		case 'LowerLeftQH1paramsNarrowVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio', [0.09 0.26], ...
					'VnarrowToVwideRatio', [0.01 0.6]), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...
	                'surroundToCenterRcRatio', 0.05, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.05) ...
				);

		case 'UpperH1paramsNarrowVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio',[0.07 0.35], ...
					'VnarrowToVwideRatio', [0.6 1.3] ...
					), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...   % (0.5 to 2.0) x the one derived by fitting the center STF
	                'surroundToCenterRcRatio', 0.05, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.05) ...
				);

		case 'MidH1paramsNarrowVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio',[0.07 0.35], ...
					'VnarrowToVwideRatio', [0.3 0.9] ...
					), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...   % (0.5 to 2.0) x the one derived by fitting the center STF
	                'surroundToCenterRcRatio', 0.05, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.05) ...
				);

		case 'LowH1paramsNarrowVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio',[0.07 0.35], ...
					'VnarrowToVwideRatio', [0.01 0.6] ...
					), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...   % (0.5 to 2.0) x the one derived by fitting the center STF
	                'surroundToCenterRcRatio', 0.05, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.05) ...
				);
			
		case 'UpperRightQH1paramsMediumVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio', 0.1+[0.09 0.26], ...
					'VnarrowToVwideRatio', 0.6+[0.01 0.6]), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...
	                'surroundToCenterRcRatio', 0.15, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.15) ...
				);

	    case 'FullH1paramsVeryTightVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio',[0.08 0.34], ...
					'VnarrowToVwideRatio', [0.01 1.2] ...
					), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...   % (0.5 to 2.0) x the one derived by fitting the center STF
	                'surroundToCenterRcRatio', 0.01, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.01) ...
				);

        case 'FullH1paramsNarrowVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio',[0.08 0.34], ...
					'VnarrowToVwideRatio', [0.01 1.2] ...
					), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...   % (0.5 to 2.0) x the one derived by fitting the center STF
	                'surroundToCenterRcRatio', 0.05, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.05) ...
				);

		case 'FullH1paramsMediumVisualSTFparamTolerance'
			surroundRetinalConePoolingModel = struct(...
				'name', 'PackerDacey2002H1free', ...
				'weightsComputeHandle', @RGCMosaicConstructor.compute.surroundConePoolingWeightsUsingComputeFunctionFor.PackerDaceyDoubleExponentModel, ...
				'identifierString', surroundOptimizationStrategy, ...
				'H1parameterTolerances', struct(...
					'RnarrowToRwideRatio',[0.08 0.33], ...
					'VnarrowToVwideRatio', [0.01 1.1] ...
					), ...
				'targetVisualSTFparamFractionalTolerances', struct(...
	                'visualRcDegs', 0.5, ...   % (0.5 to 2.0) x the one derived by fitting the center STF
	                'surroundToCenterRcRatio', 0.15, ...
	                'surroundToCenterIntegratedSensitivityRatio', 0.15) ...
				);
		otherwise
			error('Unknown surround optimization strategy: ''%s''.', surroundOptimizationStrategy);
	end % switch (surroundOptimizationStrategy)



end
