function [visualRcDegs, theOptimalOrientation, anatomicalRcDegs] = visualRcAtOptimalOrientation(...
  theMRGCMosaic, theTargetRGCindex, ...
  inputConeMosaicSTFresponses, stimParams, multiStartsNum, deltaThresholdToDeclareLocalMinInSTF, ...
  visualizeFullAndMaximalExcursionSTF, visualizeGaussianFitToCenterSTF, varargin)

  % Parse input
  p = inputParser;
  p.addParameter('fixedOptimalOrientation', [], @(x)(isempty(x)||isscalar(x)));
  p.parse(varargin{:});
  fixedOptimalOrientation = p.Results.fixedOptimalOrientation;

  % 1. Find the center cone indices
  % Get all center cones, not just those with >= exp(-1) weight
  minConeWeightIncluded = 0.001;
	inputConeIndices = theMRGCMosaic.singleCellConnectivityStats(...
		theTargetRGCindex, 'center', ...
        'minConeWeightIncluded', minConeWeightIncluded, ...
		'inputConeIndicesOnly', true);
	inputConeWeights = full(theMRGCMosaic.rgcRFcenterConeConnectivityMatrix(inputConeIndices, theTargetRGCindex));

  % Compute  the visual STF responses of the RF center for all SFs/Oris
  % Integrate across all center cones
	theRFcenterSTFresponses =  sum(bsxfun(@times, ...
			inputConeMosaicSTFresponses(:,:,:, inputConeIndices), ...
			reshape(inputConeWeights, [1 1 1 numel(inputConeWeights)]) ...
			), 4);


	% Find the orientation that results in the maximalExcursionSTF
	[theMaximalExcursionSTF, theOptimalOrientation] = RGCMosaicConstructor.helper.simulateExperiment.maximalExcursionSTFfrom2DSTF( ...
        stimParams.orientationDegs, stimParams.spatialFrequencyCPD, ...
        stimParams.spatialPhasesDegs, stimParams.temporalSupportSeconds, ...
        theRFcenterSTFresponses, ...
        'visualizeFullAndMaximalExcursionSTF', visualizeFullAndMaximalExcursionSTF, ...
        'fixedOptimalOrientation', fixedOptimalOrientation);

  % By setting the minPeakProminance to [], we search to find the global peak of the STF
  % If we set to some value, like 1e-2, we are looking for the first peaks in which there is a drop by at least that factor on either side
  minPeakProminance = [];

   [spatialFrequencySupportCPDtoFit, theSTFportionToFit] = ...
      RGCMosaicConstructor.helper.simulateExperiment.stfPortionToAnalyze(...
        stimParams.spatialFrequencyCPD, theMaximalExcursionSTF, ...
        deltaThresholdToDeclareLocalMinInSTF, minPeakProminance);

    % Some initial estimate of the visual Rc (this does not account the effect of optics), 
    % but it is better than nothing. The Gaussian STF model is only a 2-parameter model (gain,
    % Rc), so it should be able to find the Rc without getting stuct to a local minimum
    anatomicalRcDegs = sqrt(...
      numel(inputConeWeights)) * ...
      theMRGCMosaic.inputConeMosaic.coneApertureToConeCharacteristicRadiusConversionFactor * ...
      mean(theMRGCMosaic.inputConeMosaic.coneApertureDiametersDegs(inputConeIndices) );
    initialRcDegs = anatomicalRcDegs;

    % Fit theMaximalExcursionSTF with a Gaussian
    rangeForRc = [];
    [fittedParamsStruct, theFittedVRFcenterVisualSTF] = RGCMosaicConstructor.helper.fit.GaussianToSubregionSTF(...
      spatialFrequencySupportCPDtoFit, ...
      theSTFportionToFit, ...
      initialRcDegs, ...
      rangeForRc, ...
      multiStartsNum);

    visualRcDegs = fittedParamsStruct.finalValues(2);

    if (visualizeGaussianFitToCenterSTF)
      hFig = figure();
      ax = subplot(1,1,1);
      plot(ax,stimParams.spatialFrequencyCPD, theMaximalExcursionSTF, 'ko', 'MarkerSize', 16, 'LineWidth', 1.5);
      hold(ax, 'on')
      plot(ax,theFittedVRFcenterVisualSTF.sfHiRes, theFittedVRFcenterVisualSTF.subregionSTFHiRes, 'r-', 'LineWidth', 1.5);
      axis(ax, 'xy')
      set(ax, 'YLim', [1e-2 1e0], 'YScale', 'log');
      title(sprintf('Characteristic radius (Rc) of %d-cone RF center:  %2.2f arc min', numel(inputConeWeights), visualRcDegs*60));
      xtickangle(ax, 0);
      set(ax, 'FontSize', 16)
      xlabel('spatial frequency (c/deg)');
      ylabel('amplitude');
     % RGCMosaicConstructor.helper.queryUserFor.unpausingExecution();
    end
end
