function t_examplesVSS2024talk(options)
% Examples used to generate material for the VSS2024 talk

% History:
%    08/28/25  NPC  Wrote it.

% Examples:
%{

% UTTBSkip

% Skip running these examples during autovalidation because they require material
% not included in the ISETBio repository.

%
% SYNTHESIS
%
% --- mosaic: VSS2024TalkTemporal9DegsMosaic, optics: VSS2024 First Subject ---

    % Compute input cone mosaic STF responses (stage 3A)
    t_mRGCMosaicSynthesizeAtStage3(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'regenerateMosaicAtStage3A', true);


    % Derive optimized surround pooling functions for L-cone dominated mRGCs (stage 3B)
    t_mRGCMosaicSynthesizeAtStage3(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'regenerateMosaicAtStage3B', true, ...
        'positionSetToCompute', '1/3', ...
        'centerConeDominanceToOptimize', cMosaic.LCONE_ID);

    % Derive optimized surround pooling functions for M-cone dominated mRGCs (stage 3B)
    t_mRGCMosaicSynthesizeAtStage3(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'regenerateMosaicAtStage3B', true, ...
        'initialSurroundOptimizationValuesSource', 'skip if previous file exists', ...
        'positionSetToCompute', '2/3', ...
        'centerConeDominanceToOptimize', cMosaic.LCONE_ID);

    % Synthesize the compute-ready mosaic by interpolating the derived
    % surround cone poolings and deriving surround weights for all cells in
    % the synthesized mRGCMosaic
    t_mRGCMosaicSynthesizeAtStage3(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'regenerateMosaicAtStage3C', true);

    t_mRGCMosaicSynthesizeAtStage3(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'inspectMosaicAtStage3B', true, ...
        'centerConeNumerosityToInspect', 4, ...
        'centerConeDominanceToInspect', cMosaic.LCONE_ID);

%
% COMPUTING STFs
%

   % Tiny mosaic for algorithm testing
    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'PLOSpaperNasal7DegsMosaic', ... %'PLOSpaperNasal2DegsTinyMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [7 0], ...
            'sizeDegs', [0.5 0.5] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.0 ...
        ), ...
        'STForientationDeltaDegs', 45, ...
        'STFtemporalFrequencyHz', 2.5, ...                   % Matching Lee&Shapley 2012
        'STFsfSupport', [0.5 1 2 4 8 16], ...
        'STFmeanLuminanceCdM2', 31.34, ...                   % Matching Lee&Shapley 2012
        'STFbackgroundXYchromaticity', [0.436, 0.476], ...   % Matching Lee&Shapley 2012
        'STFchromaticity', 'Achromatic', ...
        'STFcontrast', 0.60, ...                             % Trying to match Lee&Shapley, who claim 35% and 37% L/M cone contrasts, 60 for achromatic)
        'coneFundamentalsOptimizedForStimPosition', true, ...
        'displayLuminanceHeadroomPercentage', 200/100, ...   % Very large luminance headroom to generate these high cone contrasts
        'computeInputConeMosaicResponses', true, ...
        'mRGCNonLinearityParamsStruct', ...                  % photocurrent nonlinearity (full OS-biophysical model)
            struct(...
                'type', 'photocurrent', ...
                'osBiophysicalModelWarmUpTimeSeconds', 2.0, ...
                'osBiophysicalModelTemporalResolutionSeconds', 1e-5, ...
                'pCurrentTemporalResolutionSeconds', 5/1000 ...
            ), ...
        'spatialPhaseIncrementDegs', 12, ...                  % To achieve a temporal sampling for pCurrent, so compute very short stimulus frames by setting the spatial phase increment step to a low value
        'visualizeStimulusSequence', true, ...
        'visualizeInputConeMosaicResponses', true ...
        );


    % Macaque mosaic
    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [-7 0], ...
            'sizeDegs', [2 2] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.0 ...
        ), ...
        'STFmeanLuminanceCdM2', 31.34, ...                   % Matching Lee&Shapley 2012
        'STFbackgroundXYchromaticity', [0.436, 0.476], ...   % Matching Lee&Shapley 2012
        'STFtemporalFrequencyHz', 2.5, ...                   % Matching Lee&Shapley 2012
        'mRGCNonLinearityParamsStruct', ...
            struct('type', 'photocurrent'), ...
        'computeInputConeMosaicResponses', false);
    );

%}
