function t_mRGCMosaicSTFcomputation(options)

% History:
%    10/26/25  NPC  Wrote it.

% Examples:
%{
    % --- mosaic: VSS2024TalkTemporal9DegsMosaic, optics: VSS2024 First Subject --- 

    % Tiny mosaic for algorithm testing
    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'PLOSpaperNasal7DegsMosaic', ... %'PLOSpaperNasal2DegsTinyMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [7 0], ...
            'sizeDegs', [0.5 0.5] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.0 ...
        ), ...
        'STForientationDeltaDegs', 45, ...
        'STFtemporalFrequencyHz', 2.5, ...                   % Matching Lee&Shapley 2012 
        'STFsfSupport', [0.5 1 2 4 8 16], ...
        'STFmeanLuminanceCdM2', 31.34, ...                   % Matching Lee&Shapley 2012
        'STFbackgroundXYchromaticity', [0.436, 0.476], ...   % Matching Lee&Shapley 2012
        'STFchromaticity', 'Achromatic', ...
        'STFcontrast', 0.60, ...                             % Trying to match Lee&Shapley, who claim 35% and 37% L/M cone contrasts, 60 for achromatic)
        'coneFundamentalsOptimizedForStimPosition', true, ...
        'displayLuminanceHeadroomPercentage', 200/100, ...   % Very large luminance headroom to generate these high cone contrasts
        'computeInputConeMosaicResponses', true, ...
        'mRGCNonLinearityParamsStruct', ...                  % photocurrent nonlinearity (full OS-biophysical model)
            struct(...
                'type', 'photocurrent', ...
                'osBiophysicalModelWarmUpTimeSeconds', 2.0, ...
                'osBiophysicalModelTemporalResolutionSeconds', 1e-5, ...
                'pCurrentTemporalResolutionSeconds', 5/1000 ...
            ), ...
        'spatialPhaseIncrementDegs', 12, ...                  % To achieve a temporal sampling for pCurrent, so compute very short stimulus frames by setting the spatial phase increment step to a low value
        'visualizeStimulusSequence', true, ...
        'visualizeInputConeMosaicResponses', true ...
        );


t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'PLOSpaperNasal7DegsMosaic', ... %'PLOSpaperNasal2DegsTinyMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [7 0], ...
            'sizeDegs', [0.5 0.5] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.0 ...
        ), ...
        'STForientationDeltaDegs', 45, ...
        'STFtemporalFrequencyHz', 2.5, ...                   % Matching Lee&Shapley 2012 
        'STFsfSupport', [0.5 1 2 4 8 16], ...
        'STFmeanLuminanceCdM2', 31.34, ...                   % Matching Lee&Shapley 2012
        'STFbackgroundXYchromaticity', [0.436, 0.476], ...   % Matching Lee&Shapley 2012
        'STFchromaticity', 'Achromatic', ...
        'STFcontrast', 0.60, ...                             % Trying to match Lee&Shapley, who claim 35% and 37% L/M cone contrasts, 60 for achromatic)
        'coneFundamentalsOptimizedForStimPosition', true, ...
        'displayLuminanceHeadroomPercentage', 200/100, ...   % Very large luminance headroom to generate these high cone contrasts
        'computeInputConeMosaicResponses', true);

    % Macaque mosaic
    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'VSS2024TalkTemporal9DegsMosaic', ...
        'opticsSubjectName', 'VSS2024TalkFirstSubject', ...
        'coneMosaicSpecies', 'macaque', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [-7 0], ...
            'sizeDegs', [2 2] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.0 ...
        ), ...
        'STFmeanLuminanceCdM2', 31.34, ...                   % Matching Lee&Shapley 2012
        'STFbackgroundXYchromaticity', [0.436, 0.476], ...   % Matching Lee&Shapley 2012
        'STFtemporalFrequencyHz', 2.5, ...                   % Matching Lee&Shapley 2012
        'mRGCNonLinearityParamsStruct', ...
            struct('type', 'photocurrent'), ...
        'computeInputConeMosaicResponses', false);
    );

%}

arguments

    % ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ------
    
    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'PLOSpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';


    % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'PLOSpaperDefaultSubject' ...
            'PLOSpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'PLOSpaperStrehlRatio_0.87' ...
            'PLOSpaperStrehlRatio_0.72' ...
            'PLOSpaperStrehlRatio_0.59' ...
            'PLOSpaperStrehlRatio_0.60' ...
            'PLOSpaperStrehlRatio_0.27' ...
            'PLOSpaperStrehlRatio_0.23' ...
            'PLOSpaperStrehlRatio_0.21' ...
            'PLOSpaperStrehlRatio_0.19' ...
            'PLOSpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'PLOSpaperSecondSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';

    % Submosaic to map
    options.cropParams = [];

    % Different options for the optics
    options.opticsForSTFresponses = [];

    % STF params
    options.STFmeanLuminanceCdM2 (1,1) double = 100;
    options.STFbackgroundXYchromaticity (1,2) double = [0.31, 0.31];
    options.STFchromaticity (1,:) char{mustBeMember(options.STFchromaticity, {'LconeIsolating' 'MconeIsolating' 'Achromatic'})} = 'Achromatic';
    options.STFsfSupport (1,:) double = logspace(log10(0.05), log10(50), 15);
    options.STFtemporalFrequencyHz (1,1) double = 10;
    options.STFcontrast (1,1) double = 0.5;
    options.STForientationDeltaDegs (1,1) double = 30;

    options.displayLuminanceHeadroomPercentage (1,1) double = 5/100;
    options.coneFundamentalsOptimizedForStimPosition (1,1) logical = false;

    % Nonlinearities
    options.mRGCNonLinearityParamsStruct = [];
    options.spatialPhaseIncrementDegs (1,1) double = 30;

    % Visualizations
    options.visualizeStimulusSequence (1,1) logical = false;
    options.visualizeInputConeMosaicResponses (1,1) logical = false;

    % ---- Choices of actions to perform ----
    % Whether to compute the input cone mosaic STF responses
    options.computeInputConeMosaicResponses (1,1) logical = false;

    
    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;

end % arguments



% Set flags from key/value pairs

% Mosaic specifiers for selecting a previously synthesized center-connected mRGC mosaic 
rgcMosaicName = options.rgcMosaicName;
coneMosaicSpecies = options.coneMosaicSpecies;
opticsSubjectName = options.opticsSubjectName;
targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;

% Optics to employ for the computations
opticsForSTFresponses = options.opticsForSTFresponses;

% STF params
STFmeanLuminanceCdM2 = options.STFmeanLuminanceCdM2;
STFbackgroundXYchromaticity = options.STFbackgroundXYchromaticity;
STFchromaticity = options.STFchromaticity; 
STFcontrast = options.STFcontrast;
STFtemporalFrequencyHz = options.STFtemporalFrequencyHz;
STFsfSupport = options.STFsfSupport;
STForientationDeltaDegs = options.STForientationDeltaDegs;

displayLuminanceHeadroomPercentage = options.displayLuminanceHeadroomPercentage;
coneFundamentalsOptimizedForStimPosition = options.coneFundamentalsOptimizedForStimPosition;


% Nonlinearities
mRGCNonLinearityParamsStruct = options.mRGCNonLinearityParamsStruct;
spatialPhaseIncrementDegs = options.spatialPhaseIncrementDegs;

% Mosaic cropping
cropParams = options.cropParams;

% Visualizations
visualizeStimulusSequence = options.visualizeStimulusSequence;
visualizeInputConeMosaicResponses = options.visualizeInputConeMosaicResponses;


% Actions to perform
computeInputConeMosaicResponses = options.computeInputConeMosaicResponses;
computeMRGCMosaicResponses = ~true;




% Load the mRGCmosaic specified by the passed parameters:
%   coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
% and generate the optics that were used to synthesize the mosaic
[theMRGCmosaic, theOptics, thePSFatTheMosaicEccentricity, ...
    prebakedMRGCMosaicDir, prebakedMRGCMosaicFilename] = mRGCMosaic.loadPrebakedMosaic(...
        coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
        'computeTheMosaicOptics', true, ...
        'opticsToEmploy', opticsForSTFresponses, ...
        'cropParams', cropParams);

disp('Done loading mosaic and optics')


% Filenames for intermediate responses
intermediateDataDir = RGCMosaicConstructor.filepathFor.intermediateDataDir();

% ENcode chromaticity, eccentricity and size of the mosaic
postFix = sprintf('%s_%s_Ecc_%2.1f_%2.1f_Size_%2.1f_%2.1f', ...
    STFchromaticity, ...
    strrep(prebakedMRGCMosaicFilename, '.mat', ''), ...
    theMRGCmosaic.eccentricityDegs(1), ...
    theMRGCmosaic.eccentricityDegs(2), ...
    theMRGCmosaic.sizeDegs(1), ...
    theMRGCmosaic.sizeDegs(2));
   
theInputConeMosaicSTFResponsesFileName = fullfile('scratchspace', sprintf('LeeShapleyInputConeMosaicSTFresponses%s.mat', postFix));
theInputConeMosaicSTFResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theInputConeMosaicSTFResponsesFileName, ...
        'generateMissingSubDirs', true);

theMRGCMosaicSTFResponsesFileName = fullfile('scratchspace', sprintf('LeeShapleymRGCMosaicSTFresponses%s.mat', postFix));
theMRGCMosaicSTFResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theMRGCMosaicSTFResponsesFileName, ...
        'generateMissingSubDirs', true);

%theLeeShapleyAnalysisFileName = fullfile('scratchspace', sprintf('LeeShapleyAnalysis_%s.mat', postFix));
%theLeeShapleyAnalysisFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
%        intermediateDataDir, theLeeShapleyAnalysisFileName, ...
%        'generateMissingSubDirs', true);

if (~isempty(mRGCNonLinearityParamsStruct))
    theInputConeMosaicSTFResponsesFullFileName = ...
        strrep(theInputConeMosaicSTFResponsesFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
    theMRGCMosaicSTFResponsesFullFileName = ...
        strrep(theMRGCMosaicSTFResponsesFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
    %theLeeShapleyAnalysisFullFileName = ...
    %    strrep(theLeeShapleyAnalysisFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
end

theInputConeMosaicSTFResponsesFullFileName
theMRGCMosaicSTFResponsesFullFileName 
%theLeeShapleyAnalysisFullFileName
pause
if (computeInputConeMosaicResponses)

    % Temporal frequency (only has an effect if mRGCNonLinearityParams.type = 'photocurrent');
    customTemporalFrequencyAndContrast = struct(...
        'temporalFrequencyHz', STFtemporalFrequencyHz, ...
        'totalContrast', STFcontrast, ...
        'backgroundLuminanceMultiplier', 1.0);

    % Determine the stimulus pixel resolution to be a fraction of the minimum cone aperture or cone spacing in the mosaic
    % here, half of the cone spacing
    theMetric = 'cone aperture';  % choose from {'cone aperture' or cone spacing'}
    if ((strcmp(opticsForSTFresponses, 'adaptiveOptics6MM')) || (strcmp(opticsForSTFresponses, 'adaptiveOptics6MMwithLCA')))
        theFraction = 0.1;
    else
        theFraction = 0.25;
    end
    targetRGCindices =  1:theMRGCmosaic.rgcsNum;
    STFstimulusResolutionDegs = RGCMosaicConstructor.helper.simulateExperiment.stimulusResolutionFromConeApertureOrConeSpacing(...
                theMRGCmosaic, targetRGCindices, theFraction, theMetric);


    RGCMosaicAnalyzer.compute.inputConeMosaicSTFsForStimulusChromaticityAndOptics(...
        theMRGCmosaic, theOptics, ...
        STFmeanLuminanceCdM2, ...
        STFbackgroundXYchromaticity, ...
        STFchromaticity, ...
        STFsfSupport, ...
        STFstimulusResolutionDegs, ...
        coneFundamentalsOptimizedForStimPosition, ...
        theInputConeMosaicSTFResponsesFullFileName, ...
        theMRGCMosaicSTFResponsesFullFileName, ...
        visualizeInputConeMosaicResponses, ...
        'displayLuminanceHeadroomPercentage', displayLuminanceHeadroomPercentage, ...
        'customTemporalFrequencyAndContrast', customTemporalFrequencyAndContrast, ...
        'mRGCNonLinearityParams', mRGCNonLinearityParamsStruct, ...
        'debugInputConeMosaicPcurrentResponse', ~true, ...
        'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs, ...
        'orientationDeltaDegs', STForientationDeltaDegs, ...
        'visualizeStimulusSequence', visualizeStimulusSequence);


end % if (computeInputConeMosaicResponses)