function t_mRGCMosaicSTFcomputation(options)

% History:
%    10/26/25  NPC  Wrote it.

% Examples:
%{

%
% NOTE: To run any RGC-related ISETBio code, such as this tutorial, users must follow
% the directions discribed in:
%    https://github.com/isetbio/isetbio/wiki/Retinal-ganglion-cell-(RGC)-mosaics
% under section "Configuring ISETBio to access RGC resources and run RGC simulations"
%

    % Compute an achromatic STF

    t_mRGCMosaicSTFcomputation(...
        'computeInputConeMosaicResponses', true, ...
        'computeMRGCMosaicResponses', true);

    % Compute an L-cone isolating STF with 10% L-cone isolating gratings
    % presented on a background with a mean luminance of 50 cd/m2
    % and a mean (xy) chromaticity of (0.31,0.31), simulating an error in
    % refraction of 0.5 diopters

    % STEP 1: compute the input cone mosaic STF
    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'PLOSpaperNasal2DegsTinyMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [2.0 0], ...
            'sizeDegs', [0.5 0.5] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.5 ...
        ), ...
        'STForientationDeltaDegs', 45, ...
        'STFtemporalFrequencyHz', 5, ...
        'STFsfSupport', [0.5 1 2 4 8 16], ...
        'STFmeanLuminanceCdM2', 50, ...
        'STFbackgroundXYchromaticity', [0.31, 0.31], ...
        'STFchromaticity', 'LconeIsolating', ...
        'STFcontrast', 0.10, ...
        'computeInputConeMosaicResponses', true);

    % STEP 2: compute the mRGC mosaic STF
    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'PLOSpaperNasal2DegsTinyMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [2.0 0], ...
            'sizeDegs', [0.5 0.5] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.5 ...
        ), ...
        'STForientationDeltaDegs', 45, ...
        'STFtemporalFrequencyHz', 5, ...
        'STFsfSupport', [0.5 1 2 4 8 16], ...
        'STFmeanLuminanceCdM2', 50, ...
        'STFbackgroundXYchromaticity', [0.31, 0.31], ...
        'STFchromaticity', 'LconeIsolating', ...
        'STFcontrast', 0.10, ...
        'computeMRGCMosaicResponses', true);
%}

arguments

    % ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ------
    
    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'PLOSpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';


    % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'PLOSpaperDefaultSubject' ...
            'PLOSpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'PLOSpaperStrehlRatio_0.87' ...
            'PLOSpaperStrehlRatio_0.72' ...
            'PLOSpaperStrehlRatio_0.59' ...
            'PLOSpaperStrehlRatio_0.60' ...
            'PLOSpaperStrehlRatio_0.27' ...
            'PLOSpaperStrehlRatio_0.23' ...
            'PLOSpaperStrehlRatio_0.21' ...
            'PLOSpaperStrehlRatio_0.19' ...
            'PLOSpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'PLOSpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';

    % Submosaic to map
    options.cropParams = [];

    % Different options for the optics
    options.opticsForSTFresponses = [];

    % STF params
    options.STFmeanLuminanceCdM2 (1,1) double = 100;
    options.STFbackgroundXYchromaticity (1,2) double = [0.31, 0.31];
    options.STFchromaticity (1,:) char{mustBeMember(options.STFchromaticity, {'LconeIsolating' 'MconeIsolating' 'Achromatic'})} = 'Achromatic';
    options.STFsfSupport (1,:) double = logspace(log10(0.05), log10(50), 15);
    options.STFtemporalFrequencyHz (1,1) double = 10;
    options.STFcontrast (1,1) double = 0.5;
    options.STForientationDeltaDegs (1,1) double = 30;

    options.displayType (1,:) char = '';
    options.displayLuminanceHeadroomPercentage (1,1) double = 5/100;
    options.coneFundamentalsOptimizedForStimPosition (1,1) logical = false;

    % Nonlinearities
    options.mRGCNonLinearityParamsStruct = [];

    % Decreasing the spatial phase increment results in higher temporal resolution, and vice versa
    options.spatialPhaseIncrementDegs (1,1) double = 30;

    % Visualizations
    options.visualizeStimulusSequence (1,1) logical = false;
    options.visualizeMosaicResponses (1,1) logical = false;
    options.visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses (1,1) logical = false;
    options.visualizeConeExcitationVsPhotocurrentSTFs (1,1) logical = false;

    % ---- Choices of actions to perform ----
    % Whether to compute the input cone mosaic STF responses
    options.computeInputConeMosaicResponses (1,1) logical = false;
    options.computeInputConeMosaicResponsesBasedOnConeExcitations (1,1) logical = true;
    options.computeInputConeMosaicResponsesBasedOnPhotocurrents (1,1) logical = true;


    % Whether to inspect the input cone mosaic STF responses
    options.inspectInputConeMosaicResponses (1,1) logical = false;

    % Whether to compute the input cone mosaic STF responses
    options.computeMRGCMosaicResponses (1,1) logical = false;
    
    % Whether to analyze the STF responses for select target mRGCs
    options.analyzeSTFresponsesForTargetCells(1,1) logical = false;

    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;

end % arguments



% Set flags from key/value pairs

% Mosaic specifiers for selecting a previously synthesized center-connected mRGC mosaic 
rgcMosaicName = options.rgcMosaicName;
coneMosaicSpecies = options.coneMosaicSpecies;
opticsSubjectName = options.opticsSubjectName;
targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;

% Optics to employ for the computations
opticsForSTFresponses = options.opticsForSTFresponses;

% STF params
STFmeanLuminanceCdM2 = options.STFmeanLuminanceCdM2;
STFbackgroundXYchromaticity = options.STFbackgroundXYchromaticity;
STFchromaticity = options.STFchromaticity; 
STFcontrast = options.STFcontrast;
STFtemporalFrequencyHz = options.STFtemporalFrequencyHz;
STFsfSupport = options.STFsfSupport;
STForientationDeltaDegs = options.STForientationDeltaDegs;

displayType = options.displayType;
displayLuminanceHeadroomPercentage = options.displayLuminanceHeadroomPercentage;
coneFundamentalsOptimizedForStimPosition = options.coneFundamentalsOptimizedForStimPosition;


% Nonlinearities
mRGCNonLinearityParamsStruct = options.mRGCNonLinearityParamsStruct;
spatialPhaseIncrementDegs = options.spatialPhaseIncrementDegs;

% Mosaic cropping
cropParams = options.cropParams;

% Visualizations
visualizeStimulusSequence = options.visualizeStimulusSequence;
visualizeMosaicResponses = options.visualizeMosaicResponses;

visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses = options.visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses;
visualizeConeExcitationVsPhotocurrentSTFs = options.visualizeConeExcitationVsPhotocurrentSTFs;

% Actions to perform
computeInputConeMosaicResponses = options.computeInputConeMosaicResponses;
computeInputConeMosaicResponsesBasedOnConeExcitations = options.computeInputConeMosaicResponsesBasedOnConeExcitations;
computeInputConeMosaicResponsesBasedOnPhotocurrents = options.computeInputConeMosaicResponsesBasedOnPhotocurrents;
inspectInputConeMosaicResponses = options.inspectInputConeMosaicResponses;
computeMRGCMosaicResponses = options.computeMRGCMosaicResponses;
analyzeSTFresponsesForTargetCells = options.analyzeSTFresponsesForTargetCells;



% Load the mRGCmosaic specified by the passed parameters:
%   coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
% and generate the optics that were used to synthesize the mosaic
[theMRGCmosaic, theOptics, thePSFatTheMosaicEccentricity, ...
    prebakedMRGCMosaicDir, prebakedMRGCMosaicFilename] = mRGCMosaic.loadPrebakedMosaic(...
        coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
        'computeTheMosaicOptics', true, ...
        'opticsToEmploy', opticsForSTFresponses, ...
        'cropParams', cropParams);

disp('Done loading mosaic and optics')


% Filenames for intermediate responses
intermediateDataDir = RGCMosaicConstructor.filepathFor.intermediateDataDir();

% ENcode chromaticity, eccentricity and size of the mosaic
postFix = sprintf('%s_%s_Ecc_%2.1f_%2.1f_Size_%2.1f_%2.1f', ...
    STFchromaticity, ...
    strrep(prebakedMRGCMosaicFilename, '.mat', ''), ...
    theMRGCmosaic.eccentricityDegs(1), ...
    theMRGCmosaic.eccentricityDegs(2), ...
    theMRGCmosaic.sizeDegs(1), ...
    theMRGCmosaic.sizeDegs(2));
   
% Directory where all STF data will go
STFsubDir = 'LeeShapley';

theInputConeMosaicSTFResponsesFileName = fullfile(STFsubDir, sprintf('cMosaicSTF_%s.mat', postFix));
theInputConeMosaicSTFResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theInputConeMosaicSTFResponsesFileName, ...
        'generateMissingSubDirs', true);

theMRGCMosaicSTFResponsesFileName = fullfile(STFsubDir, sprintf('mRGCMosaicSTF_%s.mat', postFix));
theMRGCMosaicSTFResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theMRGCMosaicSTFResponsesFileName, ...
        'generateMissingSubDirs', true);

theAnalyzedSTFsFileName = fullfile(STFsubDir, sprintf('targetCellsSTF_%s.mat', postFix));
theAnalyzedSTFsFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theAnalyzedSTFsFileName, ...
        'generateMissingSubDirs', true);

if (~isempty(mRGCNonLinearityParamsStruct))
    theInputConeMosaicSTFResponsesFullFileName = ...
        strrep(theInputConeMosaicSTFResponsesFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
    theMRGCMosaicSTFResponsesFullFileName = ...
        strrep(theMRGCMosaicSTFResponsesFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
    theAnalyzedSTFsFullFileName = ...
        strrep(theAnalyzedSTFsFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
end


% Temporal frequency (only has an effect if mRGCNonLinearityParams.type = 'photocurrent');
customTemporalFrequencyAndContrast = struct(...
    'temporalFrequencyHz', STFtemporalFrequencyHz, ...
    'totalContrast', STFcontrast);

% Determine the stimulus pixel resolution to be a fraction of the minimum cone aperture or cone spacing in the mosaic
% here, half of the cone spacing
theMetric = 'cone aperture';  % choose from {'cone aperture' or cone spacing'}
if ((strcmp(opticsForSTFresponses, 'adaptiveOptics6MM')) || (strcmp(opticsForSTFresponses, 'adaptiveOptics6MMwithLCA')))
    theFraction = 0.1;
else
    theFraction = 0.25;
end
targetRGCindices =  1:theMRGCmosaic.rgcsNum;
STFstimulusResolutionDegs = RGCMosaicConstructor.helper.simulateExperiment.stimulusResolutionFromConeApertureOrConeSpacing(...
            theMRGCmosaic, targetRGCindices, theFraction, theMetric);


if (computeInputConeMosaicResponses || inspectInputConeMosaicResponses || computeMRGCMosaicResponses)

    % Do one at a time
    if (computeInputConeMosaicResponses)
        debugInputConeMosaicPcurrentResponse = inspectInputConeMosaicResponses;
        inspectInputConeMosaicResponses = false;
        computeMRGCMosaicResponses = false;

    elseif (inspectInputConeMosaicResponses)
        debugInputConeMosaicPcurrentResponse = false;
        computeInputConeMosaicResponses = false;
        computeMRGCMosaicResponses = false;

    elseif (computeMRGCMosaicResponses)
        debugInputConeMosaicPcurrentResponse = false;
        computeInputConeMosaicResponses = false;
        inspectInputConeMosaicResponses = false;
    end

    RGCMosaicAnalyzer.compute.mosaicSTFsForStimulusChromaticityAndOptics(...
        theMRGCmosaic, theOptics, ...
        STFmeanLuminanceCdM2, ...
        STFbackgroundXYchromaticity, ...
        STFchromaticity, ...
        STFsfSupport, ...
        STFstimulusResolutionDegs, ...
        coneFundamentalsOptimizedForStimPosition, ...
        theInputConeMosaicSTFResponsesFullFileName, ...
        theMRGCMosaicSTFResponsesFullFileName, ...
        visualizeMosaicResponses, ...
        'displayType', displayType, ...
        'displayLuminanceHeadroomPercentage', displayLuminanceHeadroomPercentage, ...
        'customTemporalFrequencyAndContrast', customTemporalFrequencyAndContrast, ...
        'mRGCNonLinearityParams', mRGCNonLinearityParamsStruct, ...
        'debugInputConeMosaicPcurrentResponse', debugInputConeMosaicPcurrentResponse, ...
        'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs, ...
        'orientationDeltaDegs', STForientationDeltaDegs, ...
        'visualizeStimulusSequence', visualizeStimulusSequence, ...
        'computeInputConeMosaicResponses', computeInputConeMosaicResponses, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations', computeInputConeMosaicResponsesBasedOnConeExcitations, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
        'inspectInputConeMosaicResponses', inspectInputConeMosaicResponses, ...
        'computeMRGCMosaicResponses', computeMRGCMosaicResponses);
end


if (analyzeSTFresponsesForTargetCells)

    % We will analyze cells with a center purity range of 1.0, i.e., all center cones are of the same type
    targetedCenterPurityRange = [1 1];      % e.g., [0.5 1.0]. If this is set to [], we will target RGCs with any center specificity

    % Any center cone numerosity
    targetedCenterConeNumerosityRange = []; % e.g., [1 2]. If set to [], we will target RGCs with any center numerosity

    % Surround purity range
    targetedSurroundPurityRange = [];       % e.g., [0.4 0.6] to checks cells with around 50/50 L/M cone net weight in their surrounds)

    % Radial eccentricity range
    targetedRadialEccentricityRange = [];   % e.g., [4.9 5.5]; If set to empty we will examine all cells


    RGCMosaicAnalyzer.compute.mosaicSTFanalysisForTargetedCellPopulation(...
        theMRGCMosaicSTFResponsesFullFileName, ...
        theAnalyzedSTFsFullFileName, ...
        targetedCenterPurityRange, ...
        targetedCenterConeNumerosityRange, ...
        targetedSurroundPurityRange, ...
        targetedRadialEccentricityRange, ...
        visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses, ...
        visualizeConeExcitationVsPhotocurrentSTFs);

end
