function t_mRGCMosaicSynthesizeTemporalFilters(options)
% Generate center and surround temporal filters for cells in an mRGC mosaic
%
% Syntax:
%   t_mRGCMosaicSynthesizeTemporalFilters()
%
% Description:
%   Demonstrates how to generate temporal filters for the center and surround mechanisms of cells in a synthesized mRGC mosaic
%
%  This is set up with key/value pairs that demonstate how to select different
%  options. Different choices are illustrated in the examples
%  in the source code.
%
% Optional key/value pairs
%    See source code arguments block for a list of key/value pairs.

% History:
%    12/02/25  NPC  Wrote it.

% Examples:
%{

    examinedTemporalFrequencies = [1.4 2 3 4 6 8 12 16 24 32];
    

    % TTF with a support from 0.5 Hz to 100 Hz
    tfMinHz = 0.5;
    tfDeltaHz = 0.5;
    tfMaxHz = 200;
    examinedTemporalFrequencies = tfMinHz : tfDeltaHz : tfMaxHz;

    % Specify phase increment and a minFrameDurationMsec
    % if the frameDurationMsec computed based on TF and
    % temporalPhaseIncrementDegs is > maxFrameDurationMsec (and the maxFrameDurationMsec is not empty)
    % we adjust temporalPhaseIncrementDegs so that we achieve a frameDuration that is < maxFrameDurationMsec

    temporalPhaseIncrementDegs = struct('val', 10, 'maxFrameDurationMsec', 5);


    % Stimulus position (centered on a single mRGC given the current PSF)
    stimulusPositionDegs = [-6.075 -0.050];


    % Stimuluc chromaticity: 50% achromatic
    stimulusContrast = 0.5;
    stimulusChromaticity = 'Achromatic';

    % Stimulus spatial support (degs)
    stimulusMaxSupportDegs = 0.5;

    % Stimulus pixel size as a fraction of local cone aperture
    stimulusPixelSizeAsFractionOfConeAperture = 0.4;

    % Diameter of spot stimulus (degs)
    spotStimulusDiameterDegs = 0.05;

    % Inner and outer diameters of annulus stimulus (degs)
    annulusStimulusInnerOuterDiametersDegs = [0.06 0.35];
    
    
    % Specify a smaller # of wavefront samples (usually we employ 501). B
    % This is neccessary here because we have large number of temporal frames to compute.
    % The stimulus is not too fine, so this is probably not too bad
    opticsWavefrontSpatialSamples = 201;


    % Only use a small patch of the mRGC mosaic
    cropParams = struct( ...
        'sizeDegs', [0.25 0.25], ...
        'eccentricityDegs', [-6 0]);

    % Photocurrent non-linearity
    mRGCNonLinearityParamsStruct = struct(...
        'type', 'photocurrent', ...
        'osBiophysicalModelWarmUpTimeSeconds', 2.0, ...
        'osBiophysicalModelTemporalResolutionSeconds', 1e-5, ...
        'pCurrentTemporalResolutionSeconds', 2.0/1000 ...
    );


	% ----- Compute input cone mosaic EXCITATION responses (SPOT stimulus) ------
	t_mRGCMosaicSynthesizeTemporalFilters(...
       'rgcMosaicName', 'PLOSpaperTemporal7DegsMosaic', ...
       'opticsWavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
       'stimulusPixelSizeAsFractionOfConeAperture', stimulusPixelSizeAsFractionOfConeAperture, ...
       'stimulusMaxSupportDegs', stimulusMaxSupportDegs, ...
       'stimulusPositionDegs',  stimulusPositionDegs, ...
       'stimulusSizeDegs', spotStimulusDiameterDegs, ... 
       'stimulusShape', 'spot', ...
       'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs, ...
       'frequencySupport', examinedTemporalFrequencies, ...
       'chromaticity', stimulusChromaticity, ...
       'contrast', stimulusContrast, ...
       'cropParams', cropParams, ...
       'visualizeMosaicResponses', ~true, ...
       'computeInputConeMosaicResponses', true, ...
       'computeInputConeMosaicResponsesBasedOnConeExcitations', true, ...
       'visualizeConePoolingMapForRGCindex', 30, ...
       'visualizeMRGCmosaic', true, ...
       'exportVisualizationPDF', true, ...
       'exportVisualizationPNG', true);


    % -----  Compute input cone mosaic EXCITATION responses (ANNULUS stimulus)  ----
	t_mRGCMosaicSynthesizeTemporalFilters(...
       'rgcMosaicName', 'PLOSpaperTemporal7DegsMosaic', ...
       'opticsWavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
       'stimulusPixelSizeAsFractionOfConeAperture', stimulusPixelSizeAsFractionOfConeAperture, ...
       'stimulusMaxSupportDegs', stimulusMaxSupportDegs, ...
       'stimulusPositionDegs',  stimulusPositionDegs, ...
       'stimulusSizeDegs', annulusStimulusInnerOuterDiametersDegs, ...
       'stimulusShape', 'annulus', ...
       'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs, ...
       'frequencySupport', examinedTemporalFrequencies, ...
       'chromaticity', stimulusChromaticity, ...
       'contrast', stimulusContrast, ...
       'cropParams', cropParams, ...
       'visualizeMosaicResponses', ~true, ...
       'computeInputConeMosaicResponses', true, ...
       'computeInputConeMosaicResponsesBasedOnConeExcitations', true ...
    );




    % -----  Compute input cone mosaic PHOTOCURRENT responses (SPOT stimulus)  ----
	t_mRGCMosaicSynthesizeTemporalFilters(...
       'rgcMosaicName', 'PLOSpaperTemporal7DegsMosaic', ...
       'opticsWavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
       'stimulusPixelSizeAsFractionOfConeAperture', stimulusPixelSizeAsFractionOfConeAperture, ...
       'stimulusMaxSupportDegs', stimulusMaxSupportDegs, ...
       'stimulusPositionDegs',  stimulusPositionDegs, ...
       'stimulusSizeDegs', spotStimulusDiameterDegs, ...    
       'stimulusShape', 'spot', ...
       'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs, ...
       'frequencySupport', examinedTemporalFrequencies, ...
       'chromaticity', stimulusChromaticity, ...
       'contrast', stimulusContrast, ...
       'cropParams', cropParams, ...
       'mRGCNonLinearityParamsStruct', mRGCNonLinearityParamsStruct, ...
       'computeInputConeMosaicResponses', true, ...
       'computeInputConeMosaicResponsesBasedOnConeExcitations', false, ...
       'computeInputConeMosaicResponsesBasedOnPhotocurrents', true ...
    );


    % -----  Compute input cone mosaic PHOTOCURRENT responses (ANNULUS stimulus) ----
	t_mRGCMosaicSynthesizeTemporalFilters(...
       'rgcMosaicName', 'PLOSpaperTemporal7DegsMosaic', ...
       'opticsWavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
       'stimulusPixelSizeAsFractionOfConeAperture', stimulusPixelSizeAsFractionOfConeAperture, ...
       'stimulusMaxSupportDegs', stimulusMaxSupportDegs, ...
       'stimulusPositionDegs',  stimulusPositionDegs, ...
       'stimulusSizeDegs', annulusStimulusDiameterDegs, ...    
       'stimulusShape', 'annulus', ...
       'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs, ...
       'frequencySupport', examinedTemporalFrequencies, ...
       'chromaticity', stimulusChromaticity, ...
       'contrast', stimulusContrast, ...
       'cropParams', cropParams, ...
       'mRGCNonLinearityParamsStruct', mRGCNonLinearityParamsStruct, ...
       'computeInputConeMosaicResponses', true, ...
       'inspectInputConeMosaicResponses', true, ...
       'computeInputConeMosaicResponsesBasedOnConeExcitations', false, ...
       'computeInputConeMosaicResponsesBasedOnPhotocurrents', true ...
    );




    % -----  Synthesize the mRGC temporal filters
    t_mRGCMosaicSynthesizeTemporalFilters(...
        'rgcMosaicName', 'PLOSpaperTemporal7DegsMosaic', ...
        'opticsWavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
        'stimulusPixelSizeAsFractionOfConeAperture', stimulusPixelSizeAsFractionOfConeAperture, ...
        'stimulusMaxSupportDegs', stimulusMaxSupportDegs, ...
        'stimulusPositionDegs',  stimulusPositionDegs, ...
        'stimulusSizeDegs', spotStimulusDiameterDegs, ...     
        'stimulusShape', 'spot', ...
        'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs, ...
        'frequencySupport', examinedTemporalFrequencies, ...
        'chromaticity', stimulusChromaticity, ...
        'contrast', stimulusContrast, ...
        'cropParams', cropParams, ...
        'mRGCNonLinearityParamsStruct', mRGCNonLinearityParamsStruct, ...
        'synthesizeMRGCtemporalFilters', true);
%}


arguments
	% ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ------

    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'PLOSpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';


    % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'PLOSpaperDefaultSubject' ...
            'PLOSpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'PLOSpaperStrehlRatio_0.87' ...
            'PLOSpaperStrehlRatio_0.72' ...
            'PLOSpaperStrehlRatio_0.59' ...
            'PLOSpaperStrehlRatio_0.60' ...
            'PLOSpaperStrehlRatio_0.27' ...
            'PLOSpaperStrehlRatio_0.23' ...
            'PLOSpaperStrehlRatio_0.21' ...
            'PLOSpaperStrehlRatio_0.19' ...
            'PLOSpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'PLOSpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';

    % Submosaic to map
    options.cropParams = [];

    % Different options for the optics
    options.opticsForTTFresponses = [];

    % Wavefront spatial samples
    options.opticsWavefrontSpatialSamples = [];

    % TTF params
    options.meanLuminanceCdM2 (1,1) double = 60;
    options.backgroundXYchromaticity (1,2) double = [0.31, 0.31];
    options.frequencySupport (1,:) double = logspace(log10(0.1), log10(100), 16);
    options.chromaticity (1,:) char{mustBeMember(options.chromaticity, {'LconeIsolating' 'MconeIsolating' 'Achromatic'})} = 'Achromatic';
    options.contrast (1,1) double = 0.5;

    options.displayType (1,:) char = '';
    options.displayLuminanceHeadroomPercentage (1,1) double = 5/100;
    options.coneFundamentalsOptimizedForStimPosition (1,1) logical = false;

	% Decreasing the temporal phase increment results in higher temporal resolution, and vice versa
    options.temporalPhaseIncrementDegs (1,1) struct = struct('val', 12, 'maxFrameDurationMsec', []);

    % Spatial position params
    options.stimulusPixelSizeAsFractionOfConeAperture (1,1) double = 0.5;
    options.stimulusMaxSupportDegs (1,1) double = [];
    options.stimulusPositionDegs (1,:) double = [];
    options.stimulusSizeDegs (1,:) double = [];
    options.stimulusShape (1,:) char{mustBeMember(options.stimulusShape, {'spot' 'annulus'})} = 'spot';

    % Nonlinearities
    options.mRGCNonLinearityParamsStruct = [];



    % Visualizations
    options.visualizeMRGCmosaic (1,1) logical = false;
    options.visualizeConePoolingMapForRGCindex (1,:) double = [];
    options.visualizeStimulusOnMosaic (1,1) logical = false;
    options.visualizeStimulusSequence (1,1) logical = false;
    options.visualizeMosaicResponses (1,1) logical = false;
    options.visualizeConeExcitationVsPhotocurrentTTFs (1,1) logical = false;


    % ---- Choices of actions to perform ----
    % Whether to compute the input cone mosaic TTF responses
    options.computeInputConeMosaicResponses (1,1) logical = false;
    options.computeInputConeMosaicResponsesBasedOnConeExcitations (1,1) logical = true;
    options.computeInputConeMosaicResponsesBasedOnPhotocurrents (1,1) logical = true;


    % Whether to inspect the input cone mosaic TTF responses
    options.inspectInputConeMosaicResponses (1,1) logical = false;

    % Whether to synthesize the mRGC temporal filters.
    % This assumes we have previously computed the input cone mosaic TTF responses
    options.synthesizeMRGCtemporalFilters (1,1) logical = false;

    % Whether to analyze the TTF responses for select target mRGCs
    options.analyzeTTFresponsesForTargetCells(1,1) logical = false;


    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;

    options.exportVisualizationPDF (1,1) logical = false;
    options.exportVisualizationPNG (1,1) logical = false;
end

% Set flags from key/value pairs

% Mosaic specifiers for selecting a prebaked mRGC mosaic
rgcMosaicName = options.rgcMosaicName;
coneMosaicSpecies = options.coneMosaicSpecies;
opticsSubjectName = options.opticsSubjectName;
targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;

% Mosaic cropping
cropParams = options.cropParams;

% Optics to employ for the computations
opticsForTTFresponses = options.opticsForTTFresponses;
opticsWavefrontSpatialSamples = options.opticsWavefrontSpatialSamples;

% TTF params
meanLuminanceCdM2 = options.meanLuminanceCdM2;
backgroundXYchromaticity = options.backgroundXYchromaticity;
chromaticity = options.chromaticity;
contrast = options.contrast;
frequencySupport = options.frequencySupport;

if (min(frequencySupport) <= 0)
	frequencySupport
	error('frequencySupport must be all positive, and non-zero.')
end

% Spatial params
stimulusPixelSizeAsFractionOfConeAperture = options.stimulusPixelSizeAsFractionOfConeAperture;
stimulusMaxSupportDegs = options.stimulusMaxSupportDegs;
stimulusPositionDegs = options.stimulusPositionDegs;
stimulusSizeDegs =  options.stimulusSizeDegs;
stimulusShape = options.stimulusShape;


displayType = options.displayType;
displayLuminanceHeadroomPercentage = options.displayLuminanceHeadroomPercentage;
coneFundamentalsOptimizedForStimPosition = options.coneFundamentalsOptimizedForStimPosition;

% Nonlinearities
mRGCNonLinearityParamsStruct = options.mRGCNonLinearityParamsStruct;
temporalPhaseIncrementDegs = options.temporalPhaseIncrementDegs;

% Visualizations
visualizeMRGCmosaic = options.visualizeMRGCmosaic;
visualizeConePoolingMapForRGCindex = options.visualizeConePoolingMapForRGCindex;
visualizeStimulusSequence = options.visualizeStimulusSequence;
visualizeStimulusOnMosaic = options.visualizeStimulusOnMosaic;
visualizeMosaicResponses = options.visualizeMosaicResponses;
exportVisualizationPDF = options.exportVisualizationPDF;
exportVisualizationPNG = options.exportVisualizationPNG;

% Actions to perform
computeInputConeMosaicResponses = options.computeInputConeMosaicResponses;
computeInputConeMosaicResponsesBasedOnConeExcitations = options.computeInputConeMosaicResponsesBasedOnConeExcitations;
computeInputConeMosaicResponsesBasedOnPhotocurrents = options.computeInputConeMosaicResponsesBasedOnPhotocurrents;
inspectInputConeMosaicResponses = options.inspectInputConeMosaicResponses;

synthesizeMRGCtemporalFilters  = options.synthesizeMRGCtemporalFilters;
analyzeTTFresponsesForTargetCells = options.analyzeTTFresponsesForTargetCells;


% Close previously open figures
closePreviouslyOpenFigures = options.closePreviouslyOpenFigures;



if (closePreviouslyOpenFigures)
    % Close any stray figs
    close all;
end


% Load the mRGCmosaic specified by the passed parameters:
%   coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
% and generate the optics that were used to synthesize the mosaic
[theMRGCmosaic, theOptics, thePSFatTheMosaicEccentricity, ...
  prebakedMRGCMosaicDir, prebakedMRGCMosaicFilename] = mRGCMosaic.loadPrebakedMosaic(...
        coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
        'computeTheMosaicOptics', true, ...
        'opticsToEmploy', opticsForTTFresponses, ...
        'wavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
        'cropParams', cropParams);



% Plot a smaller region of the mRGC mosaic with the PSF superimposed
visualizedWidthDegs = 0.5;
narrowDomainVisualizationLimits(1:2) = theMRGCmosaic.eccentricityDegs(1) + [-0.5 0.5]*visualizedWidthDegs;
narrowDomainVisualizationLimits(3:4) = theMRGCmosaic.eccentricityDegs(2) + [-0.5 0.5]*visualizedWidthDegs;
narrowDomainVisualizationTicks = struct(...
    'x', -30:0.2:0, ...
    'y', -10:0.2:10);

% Generate a PSF visualization data struct (containing the vLambda-weighted PSF) for
% visualization purposes
PSFvisualizationOffset = theMRGCmosaic.eccentricityDegs - [mean(narrowDomainVisualizationLimits(1:2)) mean(narrowDomainVisualizationLimits(3:4))];
vLambdaWeightedPSF.data = RGCMosaicAnalyzer.compute.vLambdaWeightedPSF(thePSFatTheMosaicEccentricity);
vLambdaWeightedPSF.supportXdegs = thePSFatTheMosaicEccentricity.supportX/60 - PSFvisualizationOffset(1);
vLambdaWeightedPSF.supportYdegs = thePSFatTheMosaicEccentricity.supportY/60 - PSFvisualizationOffset(2);


% Visualize the full mosaic of RF centers using a representation
% like the representation used in visualizing
% mosaics of RGCs in typical in-vitro experiments (e.g. by the Chichilnisky lab)
minCenterConeWeight = mRGCMosaic.sensitivityAtPointOfOverlap;

exportVisualizationPDFdirectory = 'temporalResponseGenerationPDFs';

if (visualizeMRGCmosaic)
    % Get ready for publication-quality visualization
    ff = PublicationReadyPlotLib.figureComponents('1x1 giant square mosaic');


    % Subdirectory for exporting the generated PDFs

    comboMosaicPSFvisualizationFileName = sprintf('mRGCmosaicWithPSF');
    % Visualize the cropped mRGC mosaic and the PSF
    hFig = figure(3); clf;
    theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
    ff.backgroundColor = [0 0 0];
    ax = theAxes{1,1};


    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', true, ...
        'identifyPooledCones', true, ...
        'inputConesAlpha', 0.35, ...
        'identifiedConeAperture', 'lightCollectingArea4sigma', ...
        'identifiedConeApertureThetaSamples', 16, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'plottedRFoutlineEdgeColor',  [1 1 1], ...
        'plottedRFoutlineLineWidth', 1.5, ...
        'centerSubregionContourSamples', 32, ...
        'domainVisualizationLimits', narrowDomainVisualizationLimits, ...
        'domainVisualizationTicks', narrowDomainVisualizationTicks, ...
        'withSuperimposedPSF', vLambdaWeightedPSF, ...
        'plotTitle', ' ', ...
        'withFigureFormat', ff, ...
        'visualizationPDFfileName', comboMosaicPSFvisualizationFileName , ...
        'exportVisualizationPDF', exportVisualizationPDF, ...
        'exportVisualizationPNG', exportVisualizationPNG, ...
        'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);
end



if (~isempty(visualizeConePoolingMapForRGCindex))

    targetRGCindexForVisualizingConePoolingMaps = visualizeConePoolingMapForRGCindex;

    hFig = figure(4); clf;
    theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
    ff.backgroundColor = [0 0 0];
    ax = theAxes{1,1};

    exemplarMRGCvisualizationFileName = sprintf('labeledRGC-#%d', targetRGCindexForVisualizingConePoolingMaps);

    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', true, ...
        'identifyPooledCones', true, ...
        'inputConesAlpha', 0.35, ...
        'identifiedConeAperture', 'lightCollectingArea4sigma', ...
        'identifiedConeApertureThetaSamples', 16, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'plottedRFoutlineEdgeColor',  [1 1 1], ...
        'plottedRFoutlineLineWidth', 1.5, ...
        'centerSubregionContourSamples', 32, ...
        'labelRGCsWithIndices', targetRGCindexForVisualizingConePoolingMaps, ...
        'labeledRGCsLineWidth', 2, ...
        'domainVisualizationLimits', narrowDomainVisualizationLimits, ...
        'domainVisualizationTicks', narrowDomainVisualizationTicks, ...
        'plotTitle', exemplarMRGCvisualizationFileName, ...
        'withFigureFormat', ff, ...
        'visualizationPDFfileName', exemplarMRGCvisualizationFileName, ...
        'exportVisualizationPDF', exportVisualizationPDF, ...
        'exportVisualizationPNG', exportVisualizationPNG, ...
        'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);


    % Plot the cone pooling RF map of the exemplar mRGC
    figNo = 5;
    figPos = [1000 500];

    % Add a scale bar, 0.15 degs in size
    scaleBarDegs = 0.15;

    % Include surround cones whose pooling weights are >= 0.001
    minSurroundConeWeight = 0.001;

    theMRGCmosaic.visualizeCenterSurroundConePoolingMap(targetRGCindexForVisualizingConePoolingMaps, ...
        'minConeWeightForVisualizingRFcenterPooling', minCenterConeWeight, ...
        'minConeWeightForVisualizingRFsurroundPooling', minSurroundConeWeight, ...
        'minSurroundConeWeightRelativity', 'center', ...
        'withLineWeightingFunctions', false, ...
        'scaleBarDegs', scaleBarDegs, ...
        'doNotLabelScaleBar', true, ...
        'plotTitle', sprintf('scale bar: %2.2f degs', scaleBarDegs), ...
        'figNo', figNo, ...
        'figPos', figPos, ...
        'exportVisualizationPDF', true, ...
        'exportVisualizationPNG', true, ...
        'exportToFigurePDFsDirWithPDFFileName', sprintf('RFmap%d.pdf', targetRGCindexForVisualizingConePoolingMaps), ...
        'pdfExportSubDir', exportVisualizationPDFdirectory);

    % Plot the cone pooling RF map of the exemplar mRGC along with
    % line weighting functions of the center and of the surround cone pooling weights
    % along the horizontal and vertical axes
    theMRGCmosaic.visualizeCenterSurroundConePoolingMap(targetRGCindexForVisualizingConePoolingMaps, ...
        'minConeWeightForVisualizingRFcenterPooling', minCenterConeWeight, ...
        'minConeWeightForVisualizingRFsurroundPooling', minSurroundConeWeight, ...
        'minSurroundConeWeightRelativity', 'center', ...
        'withLineWeightingFunctions', true, ...
        'scaleBarDegs', scaleBarDegs, ...
        'doNotLabelScaleBar', true, ...
        'plotTitle', sprintf('scale bar: %2.2f degs', scaleBarDegs), ...
        'figNo', figNo+1, ...
        'figPos', figPos, ...
        'exportVisualizationPDF', true, ...
        'exportVisualizationPNG', true, ...
        'exportToFigurePDFsDirWithPDFFileName', sprintf('RFmap%dWithLineWeightingFunctions.pdf', targetRGCindexForVisualizingConePoolingMaps), ...
        'pdfExportSubDir', exportVisualizationPDFdirectory);

end




% Directory where all STF data will go
TTFsubDir = 'TTFresponses';

% Filenames for intermediate responses
intermediateDataDir = RGCMosaicConstructor.filepathFor.intermediateDataDir();

% Encode chromaticity, eccentricity and size of the mosaic
postFix = sprintf('%s_%s@%2.1fC_%2.0fCdM2_%s_Ecc_%2.1f_%2.1f_Size_%2.1f_%2.1f', ...
	stimulusShape, ...
    chromaticity, ...
    contrast, ...
    meanLuminanceCdM2, ...
    strrep(prebakedMRGCMosaicFilename, '.mat', ''), ...
    theMRGCmosaic.eccentricityDegs(1), ...
    theMRGCmosaic.eccentricityDegs(2), ...
    theMRGCmosaic.sizeDegs(1), ...
    theMRGCmosaic.sizeDegs(2));

theInputConeMosaicTTFResponsesFileName = fullfile(TTFsubDir, sprintf('cMosaicTTF_%s.mat', postFix));
theInputConeMosaicTTFResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theInputConeMosaicTTFResponsesFileName, ...
        'generateMissingSubDirs', true);

theMRGCMosaicTTFResponsesFileName = fullfile(TTFsubDir, sprintf('mRGCMosaicTTF_%s.mat', postFix));
theMRGCMosaicTTFResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theMRGCMosaicTTFResponsesFileName, ...
        'generateMissingSubDirs', true);

theAnalyzedTTFsFileName = fullfile(TTFsubDir, sprintf('targetCellsTTF_%s.mat', postFix));
theAnalyzedTTFsFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
        intermediateDataDir, theAnalyzedTTFsFileName, ...
        'generateMissingSubDirs', true);

if (~isempty(mRGCNonLinearityParamsStruct))
    theMRGCMosaicTTFResponsesFullFileName = ...
        strrep(theMRGCMosaicTTFResponsesFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
    theAnalyzedTTFsFullFileName = ...
        strrep(theAnalyzedTTFsFullFileName, '.mat', sprintf('%s.mat', mRGCNonLinearityParamsStruct.type));
end


% Determine the stimulus pixel resolution to be a fraction of the minimum cone aperture or cone spacing in the mosaic
% here, half of the cone spacing
theMetric = 'cone aperture';  % choose from {'cone aperture' or cone spacing'}
if (~isempty(opticsForTTFresponses)) && (isstruct(opticsForTTFresponses) && (isfield(opticsForTTFresponses, 'type'))) && ...
   ((strcmp(opticsForTTFresponses.type, 'adaptiveOptics6MM')) || (strcmp(opticsForTTFresponses.type, 'adaptiveOptics6MMwithLCA')))
    theFraction = 0.1;
else
    % This is typically 0.25, but since we have uniform stimuli it can be
    % larger to save RAM
    theFraction = stimulusPixelSizeAsFractionOfConeAperture;
end

targetRGCindices =  1:theMRGCmosaic.rgcsNum;
stimulusResolutionDegs = RGCMosaicConstructor.helper.simulateExperiment.stimulusResolutionFromConeApertureOrConeSpacing(...
            theMRGCmosaic, targetRGCindices, theFraction, theMetric);

if (isempty(stimulusMaxSupportDegs))
    stimulusMaxSupportDegs  = 1.1 * max(theMRGCmosaic.inputConeMosaic.sizeDegs);
end

% Compute responses
if (computeInputConeMosaicResponses || inspectInputConeMosaicResponses)

    if (computeInputConeMosaicResponsesBasedOnConeExcitations)
        ASPPManager = AppleSiliconParPoolManager('conservative');
    else
        ASPPManager = AppleSiliconParPoolManager('extreme');
    end

    % Do one at a time
    if (computeInputConeMosaicResponses)
        debugInputConeMosaicPcurrentResponse = inspectInputConeMosaicResponses;
        inspectInputConeMosaicResponses = false;
        computeMRGCMosaicResponses = false;

    elseif (inspectInputConeMosaicResponses)
        debugInputConeMosaicPcurrentResponse = false;
        computeInputConeMosaicResponses = false;
        computeMRGCMosaicResponses = false;
    end

	RGCMosaicAnalyzer.compute.mosaicTTFsForStimulusChromaticityAndOptics(...
        theMRGCmosaic, theOptics, ...
        meanLuminanceCdM2, ...
        backgroundXYchromaticity, ...
        chromaticity, ...
        contrast, ...
        frequencySupport, ...
        stimulusMaxSupportDegs, ...
        stimulusResolutionDegs, ...
        stimulusPositionDegs, stimulusSizeDegs, stimulusShape, ...
        coneFundamentalsOptimizedForStimPosition, ...
        theInputConeMosaicTTFResponsesFullFileName, ...
        theMRGCMosaicTTFResponsesFullFileName, ...
        'displayType', displayType, ...
        'displayLuminanceHeadroomPercentage', displayLuminanceHeadroomPercentage, ...
        'mRGCNonLinearityParams', mRGCNonLinearityParamsStruct, ...
        'debugInputConeMosaicPcurrentResponse', debugInputConeMosaicPcurrentResponse, ...
        'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs, ...
        'visualizeMosaicResponse', visualizeMosaicResponses, ...
        'visualizeStimulusSequence', visualizeStimulusSequence, ...
        'visualizeStimulusOnMosaic', visualizeStimulusOnMosaic, ...
        'computeInputConeMosaicResponses', computeInputConeMosaicResponses, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations', computeInputConeMosaicResponsesBasedOnConeExcitations, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
        'inspectInputConeMosaicResponses', inspectInputConeMosaicResponses, ...
        'computeMRGCMosaicResponses', false);

end % if (computeInputConeMosaicResponses || inspectInputConeMosaicResponses)



% HERE - Start by loading the photocurrent TTF responses and visualize them

if (synthesizeMRGCtemporalFilters)
end

%
end
