function t_mRGCMosaicEnableSurroundSconeInputs(options)
% Enable S-cone input to mRGC surrounds which are built with L/M-only input
%
% Description:
%   Demonstrates how to enable S-cone pooling to the surrounds of a set of 
%   user-specified mRGCs, mimicking H2 horizontal cells. The mRGC mosaic is
%   built based on H1 RF properties (with Packer&Dacey spatial RF dynamics
%   and pooling only from L&M cones). This modification does not introduce 
%   spatial RF properties of H2 cells, it only enables the indiscriminate 
%   (L/M/S-cone) pooling characteristic of H2 cells. 
%
%  This is set up with key/value pairs that demonstate how to select different
%  options. Different choices are illustrated in the examples
%  in the source code.
%
% Optional key/value pairs
%    See source code arguments block for a list of key/value pairs.

% History:
%    07/28/25  NPC  Wrote it.

% Examples:
%{

    t_mRGCMosaicEnableSurroundSconeInputs(...
        'rgcMosaicName', 'PLOSpaperTemporal2DegsMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'SconeSurroundEnabledRGCindices', [33 20 50 80 180 200 220]);

%}

arguments

    % ---- Name encoding properties of the rgcMosaic, such as its eccentricity ---
    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) ...
        char ...
        {...
        mustBeMember(options.rgcMosaicName, ...
            { ...
            'PLOSpaperNasal25DegsMosaic' ...
            'PLOSpaperNasal19DegsMosaic' ...
            'PLOSpaperNasal14DegsMosaic' ...
            'PLOSpaperNasal10DegsMosaic' ...
            'PLOSpaperNasal7DegsMosaic' ...
            'PLOSpaperNasal2DegsTinyMosaic' ...
            'PLOSpaperFovealMosaic' ...
            'PLOSpaperTemporal2DegsMosaic' ...
            'PLOSpaperTemporal4DegsMosaic' ...
            'PLOSpaperTemporal7DegsMosaic' ...
            'PLOSpaperTemporal10DegsMosaic' ...
            'PLOSpaperTemporal14DegsMosaic' ...
            'PLOSpaperTemporal19DegsMosaic' ...
            'PLOSpaperTemporal25DegsMosaic' ...
            'PLOSpaperTemporal32DegsMosaic' ...
            } ...
            ) ...
        } ...
        = 'PLOSpaperTemporal2DegsMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';

     % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'PLOSpaperDefaultSubject' ...
            'PLOSpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'PLOSpaperStrehlRatio_0.87' ...
            'PLOSpaperStrehlRatio_0.72' ...
            'PLOSpaperStrehlRatio_0.59' ...
            'PLOSpaperStrehlRatio_0.60' ...
            'PLOSpaperStrehlRatio_0.27' ...
            'PLOSpaperStrehlRatio_0.23' ...
            'PLOSpaperStrehlRatio_0.21' ...
            'PLOSpaperStrehlRatio_0.19' ...
            'PLOSpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'PLOSpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';


    % Indices of mRGCs for which indiscriminate L/M/S cone surround pooling will be enabled
    options.indicesOfSconeSurroundPoolingEnabledRGCs = [];

    % Or alternatively, if no RGC indices are specified, the (xy) eccentricity of 
    % mRGCs for which indiscriminate L/M/S cone surround pooling will be enabled
    options.eccOfSconeSurroundPoolingEnabledRGCs (:,2) double = [-2.5 0.0; -2.5 -0.5; -2.5 0.5; -3.0 0.0; -3.0 0.5; -3.0 -0.5];
    
    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;
end


% Set flags from key/value pairs

% Mosaic specifiers for selecting a prebaked mRGC mosaic 
rgcMosaicName = options.rgcMosaicName;
coneMosaicSpecies = options.coneMosaicSpecies;
opticsSubjectName = options.opticsSubjectName;
targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;

% Target RGCs
indicesOfSconeSurroundPoolingEnabledRGCs = options.indicesOfSconeSurroundPoolingEnabledRGCs;
eccOfSconeSurroundPoolingEnabledRGCs = options.eccOfSconeSurroundPoolingEnabledRGCs;

% Old figures
closePreviouslyOpenFigures = options.closePreviouslyOpenFigures;
if (closePreviouslyOpenFigures)
    % Close any stray figs
    close all;
end


% Load the mRGCmosaic specified by the passed parameters:
%   coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
% and generate the optics that were used to synthesize the mosaic
theMRGCmosaic = mRGCMosaic.loadPrebakedMosaic(...
        coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
        'computeTheMosaicOptics', false);

if (isempty(indicesOfSconeSurroundPoolingEnabledRGCs))
    [~,indicesOfSconeSurroundPoolingEnabledRGCs] = pdist2(theMRGCmosaic.rgcRFpositionsDegs, eccOfSconeSurroundPoolingEnabledRGCs,'euclidean','Smallest',1);
end

% Subdirectory for exporting the generated PDFs
exportVisualizationPDFdirectory = 'mosaicSconeSurroundEnabling';


% Get ready for publication-quality visualization
ff = PublicationReadyPlotLib.figureComponents('1x1 giant square mosaic');

hFig = figure(1); clf;
theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
ax = theAxes{1,1};

% Visualize the mosaic we will work on outlining the RGCs which will be
% modified to have surrounds with indiscriminate pooling from L/M/S-cones 
theMRGCmosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'identifyInputCones', ~true, ...
    'identifyPooledCones', ~true, ...
    'inputConesAlpha', 0.5, ...
    'identifiedConeAperture', 'lightCollectingArea4sigma', ...
    'identifiedConeApertureThetaSamples', 16, ...
    'centerSubregionContourSamples', 32, ...
    'labelRGCsWithIndices', indicesOfSconeSurroundPoolingEnabledRGCs, ...
    'labeledRGCsLineWidth', 2, ...
    'plotTitle', '', ...
    'withFigureFormat', ff, ...
    'visualizationPDFfileName', 'mRGCmosaic', ...
    'exportVisualizationPDF', true, ...
    'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);


theMRGCmosaic.enableSconeSurroundPoolingInSelectCells(...
    indicesOfSconeSurroundPoolingEnabledRGCs, ...
    'visualizeBeforeAndAfterConePoolingMaps', true, ...
    'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);

 
end



