function t_mRGCMosaicBasic(options)
% Introduction to the midget RGC mosaic (mRGCMosaic) object.
%
% Requires locally configured precomputed mRGC resources.
% SkipFile
% Description:
%    Demonstrates
%        - how to select one of the pre-computed midget RGC mosaics,
%        - how to select noise source (cone-only or intrinscic mRGC noise only)
%        - how to compute responses to a static (single-frame) stimulus
%        - how to visualize different aspects of the mRGCMosaic
%        - how to visualize its response
%
% History:
%    10/25/23  NPC  Wrote it.
%    7/26/2026 NPC  Modernized it

% Examples:
%{

    t_mRGCMosaicBasic();

    t_mRGCMosaicBasic(...
        'rgcMosaicName', 'JCNpaperTemporal7DegsMosaic', ...
        'opticsSubjectName', 'JCNpaperDefaultSubject');

%}

arguments

    % ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ---

    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'JCNpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';

     % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'JCNpaperDefaultSubject' ...
            'JCNpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'JCNpaperStrehlRatio_0.87' ...
            'JCNpaperStrehlRatio_0.72' ...
            'JCNpaperStrehlRatio_0.59' ...
            'JCNpaperStrehlRatio_0.60' ...
            'JCNpaperStrehlRatio_0.27' ...
            'JCNpaperStrehlRatio_0.23' ...
            'JCNpaperStrehlRatio_0.21' ...
            'JCNpaperStrehlRatio_0.19' ...
            'JCNpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'JCNpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';


    % ------ Visualization options ----
    % Visualize cone pooling maps for a target RGC
    options.targetRGCindexForVisualizingConePoolingMaps (1,:) double = [];

    % Whether to generate a video of RFpooling maps along the horizontal meridian
    options.generateVideoOfRFpoolingMapsAlongHorizontalMeridian (1,1) logical = false;

    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;
end


    % Set flags from key/value pairs
    
    % Mosaic specifiers for selecting a prebaked mRGC mosaic
    rgcMosaicName = options.rgcMosaicName;
    coneMosaicSpecies = options.coneMosaicSpecies;
    opticsSubjectName = options.opticsSubjectName;
    targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;


    %% Close all figures
    close all;

    % Configure a conservative parpool manager. This gives at least 8 GB RAM/core
    % You might need to set this to true if you are hitting a strange
    % parpool crash.  Setting it to true, however, invokes a new parpool
    % open and restore which slows things down in most cases.
    fancyParpoolControl = false;
    if (fancyParpoolControl)
        ASPPManager = AppleSiliconParPoolManager('conservative');
    end

    % Control saving of figures.  We don't want tutorials
    % saving things into the isetbio source tree.
    saveFigures = true;
    figureDir = figExporter.figureDir(mfilename, saveFigures);

    %% Load the mRGCMosaic and the optics that were used to optimize it
    % 'wavefrontSpatialSamples' is set below the default (501) to keep this
    % tutorial fast. The optics are generated by searching for the defocus
    % that maximizes the Strehl ratio, and that search dominates the run
    % time. At 301 samples the search returns the same optimal defocus.
    [theMRGCMosaic, theOI] = mRGCMosaic.loadPrebakedMosaic(...
            coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
            'computeTheMosaicOptics', true, ...
            'wavefrontSpatialSamples', 301);
    

    %% Set the presentation display on which the stimulus must be realized
    presentationDisplay = generateCRTDisplay();


    %% Set stimulus parameters
    sinusoidalStimulusParams = struct(...
        'sizeDegs', max(theMRGCMosaic.sizeDegs), ...
        'positionDegs', theMRGCMosaic.eccentricityDegs, ...
        'spatialFrequencyCyclesPerDeg', 10.0, ...
        'orientationDegs', 0, ...               
        'phaseDegs', 0, ...  
        'contrast', 0.9, ...
        'meanLuminanceCdPerM2', 40, ...
        'isWindowed', false, ...
        'pixelsAlongWidthDim', 1024, ...       
        'pixelsAlongHeightDim', 1024);

    %% Generate a sinusoidal stimulus scene and the background scene
    [theStimulusScene, theBackgroundScene] = generateSinusoidalStimulusAndBackgroundScene(...
        presentationDisplay, sinusoidalStimulusParams);


    %% Compute the retinal image of the stimulus and background scenes
    theStimulusRetinalImage = oiCompute(theOI, theStimulusScene);
    theBackgroundRetinalImage = oiCompute(theOI, theBackgroundScene);

    %% Set the integration time of the input cone mosaic to 100 msec
    theMRGCMosaic.inputConeMosaic.integrationTime = 100/1000;

    %% Set the input cone mosaic noise flag to none
    theMRGCMosaic.inputConeMosaic.noiseFlag = 'none';
    
    %% Compute the noise-free background activation of the input cone mosaic
    %
    % Setting 'lowOpticalImageResolutionWarning' to false supresses a
    % warning that the oi spatial resolution is too low to model cone
    % aperture blur. This would go away if the oi is set to have a higher 
    % spatial resolution, but we use a lower resolution here to speed this
    % tutorial up.
    theConeMosaicBackgroundNoiseFreeActivation = theMRGCMosaic.inputConeMosaic.compute(...
            theBackgroundRetinalImage, ...
            'opticalImagePositionDegs', sinusoidalStimulusParams.positionDegs, ...
            'lowOpticalImageResolutionWarning',false);

    %% Set the input cone mosaic noise flag to random to generate noisy response instances
    theMRGCMosaic.inputConeMosaic.noiseFlag = 'random';

    %% Number of noisy response instances to compute
    noisyInstancesNum = 128;

    %% Compute the noise-free response and noisyInstancesNum of noisy response instances of the input cone mosaic
    [theConeMosaicNoiseFreeResponse,  ...
     theConeMosaicNoisyResponseInstances, ~, ~, ...
     theConeMosaicResponseTemporalSupportSeconds] = theMRGCMosaic.inputConeMosaic.compute(...
            theStimulusRetinalImage, ...
            'opticalImagePositionDegs', sinusoidalStimulusParams.positionDegs, ...
            'nTrials', noisyInstancesNum, ...
            'lowOpticalImageResolutionWarning',false);

    %% Visualize the spatial relationship between stimulus and MRGCMmosaic
    % This function must be called after the cMosaic.compute() method in
    % order to display the OI at the correct location within the mosaic
    coVisualizeRetinalStimulusConeAndMRGCmosaic(1, theMRGCMosaic, theStimulusRetinalImage);

    %% Define a function handle to convert excitations to modulations
    excitationsToModulations = @(e) (bsxfun(@times, (bsxfun(@minus, e, theConeMosaicBackgroundNoiseFreeActivation)), 1./theConeMosaicBackgroundNoiseFreeActivation));

    %% Set the mRGCMosaic noise flag to none
    theMRGCMosaic.noiseFlag = 'none';

    %% Compute the noise-free response of the mRGC mosaic. No cone noise, no mRGC noise
    noiseFreeResponse = theMRGCMosaic.compute( ...
              excitationsToModulations(theConeMosaicNoiseFreeResponse), ...
              theConeMosaicResponseTemporalSupportSeconds);

    %% Set the mRGCMosaic noise flag to random
    theMRGCMosaic.noiseFlag = 'random';
 
    %% Set the intrinsic noise of the mRGCMosaic to 0
    theMRGCMosaic.vMembraneGaussianNoiseSigma = 0.0;

    %% Compute noisyInstancesNum of mRGC mosaic responses with the cone mosaic noise being the only noise source
    % To do so, we compute using the input cone mosaic noisy modulation response instances
    [~, noisyResponseInstancesConeNoiseOnly] = theMRGCMosaic.compute( ...
             excitationsToModulations(theConeMosaicNoisyResponseInstances), ...
             theConeMosaicResponseTemporalSupportSeconds, ...
             'nTrials', noisyInstancesNum);

    %% Set the intrinsic noise of the mRGCMosaic to the examined level
    theMRGCMosaic.vMembraneGaussianNoiseSigma = 0.05;

    %% Compute noisyInstancesNum of mRGC mosaic responses with the mRGCMosaic intrinsic noise being the only noise source
    % To do so, we compute using the input cone mosaic noise-free modulation response 
    [~, noisyResponseInstancesIntrinsicMRGCnoiseOnly] = theMRGCMosaic.compute( ...
             excitationsToModulations(theConeMosaicNoiseFreeResponse), ...
             theConeMosaicResponseTemporalSupportSeconds, ...
             'nTrials', noisyInstancesNum);

    %% Find indices of RGCs along the y = y-stimulus position
    targetYdegs = sinusoidalStimulusParams.positionDegs(2);
    minConeSeparation = 0;
    minRGCSeparation = 0;
    [~, mRGCIndices] = coneAndMRGCindicesAlongDesiredYposition(...
        theMRGCMosaic, targetYdegs, ...
        minConeSeparation, minRGCSeparation);

    %% Visualize response components
    figHandlesAndFileNames = visualizeMRGMosaicResponseComponents(theMRGCMosaic, mRGCIndices, ...
        noiseFreeResponse, ...
        noisyResponseInstancesConeNoiseOnly, ...
        noisyResponseInstancesIntrinsicMRGCnoiseOnly);

    if (saveFigures)
        for iFig = 1:numel(figHandlesAndFileNames)
            s = figHandlesAndFileNames{iFig};
            NicePlot.exportFigToPDF(fullfile(figureDir,s.pdfFileName), s.hFig,300);
        end
    end

     % Restore previous parpool config
    if (fancyParpoolControl)
        ASPPManager.restoreLastParpoolSize();
    end

end
