function eccDegs = rhoMMsToDegs(eccMMs)
% Convert retinal distance in mm to retinal distance in degs
% (Equation A6)
    absEccMMs = abs(eccMMs);
    eccDegs = sign(eccMMs) .* (...
            3.556     * absEccMMs ...
          + 0.05993   * absEccMMs .^2 ...
          - 0.007358  * absEccMMs .^3 ...
          + 0.0003027 * absEccMMs .^4);
end
