function opticsParams = getOpticsParams(mosaicParams)
    opticsParams = MosaicPoolingOptimizer.chooseOpticsForInputConeMosaicSTFresponses(...
        mosaicParams, ...
        'opticsChoice', 'n', ...
        'refractiveErrorDiopters', 0.0, ...
        'queryUserWhetherToUseSpecializedOpticsCases', false);
end
