function testComputeRetinalConePoolingRF()

    % Struct with the various optics params
    opticsParams = struct(...
            'rfPositionEccDegs', [0.1 -0.2], ...  % (x,y) eccentricity for the cone pooling RF, in degrees
            'ZernikeDataBase', 'Artal2012', ...
            'examinedSubjectRankOrder', 1 , ...
            'analyzedEye', 'right eye', ...
            'subjectRankingEye', 'right eye', ...
            'pupilDiameterMM', 3.0, ...
            'wavefrontSpatialSamples', 801 ...
            );

    % The cone mosaic whose cones are to be pooled by the retinal RGC RF
    % Use a Gaussian cone aperture with 
    % sigma equal to 0.204 x inner segment diameter (cone diameter)
    sigmaGaussian = 0.204;  % From McMahon et al, 2000

    % Set cone aperture modifiers
    coneApertureModifiers = struct(...
        'smoothLocalVariations', true, ...
        'sigma',  sigmaGaussian, ...
        'shape', 'Gaussian');

    theConeMosaic = cMosaic(...
        'sourceLatticeSizeDegs', 60, ...
        'whichEye', opticsParams.analyzedEye, ...
        'eccentricityDegs', opticsParams.rfPositionEccDegs, ...
        'sizeDegs', [1 1], ...
        'rodIntrusionAdjustedConeAperture', true, ...
        'coneApertureModifiers', coneApertureModifiers, ...
        'customDegsToMMsConversionFunction', @RGCmodels.Watson.convert.rhoDegsToMMs, ...
        'customMMsToDegsConversionFunction', @RGCmodels.Watson.convert.rhoMMsToDegs);

    
    % From Croner & Kaplan '95 (Figure 4c and text)
    % "P surrounds were on average 6.7 times wider than the centers of 
    % the same cells, or about 45 times larger in area".

    % Also from Croner & Kaplan '95 (Figure 10b)
    % "These mean ratios for P and M cells are not significantly different 
    % (Student's t-test: P = 0.482). The overall mean ratio is 0.55. In 
    % general, then, the surround of a cell is less sensitive to contrast 
    % than is the center, and the ratio of sensitivities is such that the 
    % surround can reduce the center's response by about 55%.

    targetVisualRFDoGparams = struct(...
        'conesNumPooledByTheRFcenter', 4, ...
        'surroundToCenterRcRatio', 6.7, ...
        'surroundToCenterIntegratedSensitivityRatio', 0.55 ...
        );

    % Instantiate the RetinaToVisualFieldTransformer
    tic
    xFormer = RetinaToVisualFieldTransformer(theConeMosaic, opticsParams, targetVisualRFDoGparams);
    toc

end
