function  plotlabOBJ  = setUpPlotLab()

    % Instantiate the WatsonRGCModel
    obj = WatsonRGCModel();
    meridianNames = obj.enumeratedMeridianNames;
    for k = 1:numel(meridianNames)
        meridianColors(k,:) = str2num(obj.meridianColors(meridianNames{k}));
    end
    
    % Instantiate a plotlab object
    plotlabOBJ = plotlab();
    
    plotlabOBJ.applyRecipe(...
            'colorOrder', meridianColors, ...
            'lineWidth', obj.figurePrefs.lineWidth, ...
            'axesFontAngle', obj.figurePrefs.fontAngle, ...
            'axesFontSize', obj.figurePrefs.fontSize, ...
            'axesXGrid', obj.figurePrefs.grid, ...
            'axesYGrid', obj.figurePrefs.grid, ...
            'legendLocation', 'SouthWest', ...
            'figureWidthInches', 6, ...
            'figureHeightInches', 4);
        
end



