function [stimTemporalParams, stimSpatialParams] = generateSpatioTemporalStimulationParams(stimulusType)
    
    switch (stimulusType)
        case 'subspace rev corr'
            
        case 'drifting gratings'
            minSF = 0.1;
            maxSF = 100;
            sfsNum = 15;
            spatialFrequenciesCPD = logspace(log10(minSF), log10(maxSF),sfsNum);

            stimulusFOVdegs = 2.0;
            minPixelsPerCycle = 8;
            stimulusPixelsNum = stimulusFOVdegs*minPixelsPerCycle;
            temporalFrequency = 4.0;
            stimDurationSeconds = 0.5;

            stimTemporalParams = struct(...
                'temporalFrequencyHz', temporalFrequency, ...
                'stimDurationSeconds', stimDurationSeconds);

            stimSpatialParams = struct(...
                'type', 'driftingGrating', ...
                'fovDegs', stimulusFOVdegs,...
                'pixelsNumPerSF', stimulusPixelsNum, ...
                'minPixelsNum', 1024, ...
                'gaborPosDegs', [0 0], ...
                'gaborSpatialFrequencyCPD', 0, ...
                'testedSpatialFrequenciesCPD', spatialFrequenciesCPD, ...
                'gaborSigmaDegs', Inf, ... %stimulusFOVdegs/(2*4), ...%Inf, ...
                'gaborOrientationDegs', 0, ...
                'deltaPhaseDegs', []);
        
        otherwise
            error('Dont know stimulus: ''%s''.', stimulusType);
    end
end

