function renderRGCanalysesFigures(patchDogParams, spatialFrequenciesCPDHR, responseAmplitudeHR, spatialFrequenciesCPD, responseAmplitude, ...
        responseTimeAxis, integratedResponsesMean, responseTimeAxisHR, fittedResponsesHR, ...
        maxSpikeRateModulation, theConeMosaic, runParams, theMidgetRGCmosaic, ...
        visualizePatchStatistics, visualizeRGCTemporalResponsesAtRGCPositions, visualizeRGCSFTuningsAtRGCPositions, ...
        targetRGCsForWhichToVisualizeSpatialFrequencyTuningCurves, coVisualizedRetinalStimulus, ...
        LMScontrast,  opticsPostFix, PolansSubjectID, exportFig, figExportsDir)
    
    if (visualizePatchStatistics)
        % Visualize data to contrast with Cronner and Kaplan data
        RGCpositionsMicrons = determineRGCPositionsFromCenterInputs(theConeMosaic, runParams.rgcMosaicPatchEccMicrons, theMidgetRGCmosaic.centerWeights);
        RGCeccentricityDegs = WatsonRGCModel.rhoMMsToDegs(sqrt(sum(RGCpositionsMicrons.^2,2))/1000.0);
        visualizePatchStatsDerivedFromSFcurves(patchDogParams, theMidgetRGCmosaic.synthesizedRFParams, RGCeccentricityDegs, ...
            LMScontrast, opticsPostFix, PolansSubjectID, exportFig, figExportsDir);
    end
    
    labelCells = true;
    %   Visualize the temporal response of each RGC at the RGC's location
    if (visualizeRGCTemporalResponsesAtRGCPositions)
        for sfIndex = 1:numel(spatialFrequenciesCPD)
            superimposedRetinalStimulus = [];
            plotXaxisScaling = 'linear';
            plotType = 'TimeResponse';
            figureName = sprintf('%2.1fcpdResponse', spatialFrequenciesCPD(sfIndex));
            visualizeRGCmosaicWithResponses(100+sfIndex, theConeMosaic, plotXaxisScaling, plotType, ...
               responseTimeAxis, squeeze(integratedResponsesMean(sfIndex,:,:)), ...
               responseTimeAxisHR, squeeze(fittedResponsesHR(sfIndex,:,:)), ...
               runParams.rgcMosaicPatchEccMicrons, runParams.rgcMosaicPatchSizeMicrons, ...
               theMidgetRGCmosaic, 'centers', maxSpikeRateModulation, ...
               superimposedRetinalStimulus, ....
               figureName, LMScontrast, opticsPostFix, PolansSubjectID, ...
               [], labelCells, ...
               exportFig, figExportsDir);
        end
    end
    
    if (visualizeRGCSFTuningsAtRGCPositions)
        % Visualize the response tuning of each RGC at the RGC's location
        exportFig = true;
        superimposedRetinalStimulus = [];
        plotXaxisScaling = 'log';
        plotType = 'SFtuning';
        figureName = 'SFtuningAll';

        visualizeRGCmosaicWithResponses(1000, theConeMosaic, plotXaxisScaling, plotType, ...
                    spatialFrequenciesCPD, responseAmplitude, ...
                    spatialFrequenciesCPDHR, responseAmplitudeHR, ...
                    runParams.rgcMosaicPatchEccMicrons, runParams.rgcMosaicPatchSizeMicrons, ...
                    theMidgetRGCmosaic, 'centers', maxSpikeRateModulation, ...
                    superimposedRetinalStimulus, ....
                    figureName, LMScontrast, opticsPostFix, PolansSubjectID, ...
                    [], labelCells, ...
                    exportFig, figExportsDir);
    end
    
    if (~isempty(targetRGCsForWhichToVisualizeSpatialFrequencyTuningCurves))
        for iTargetRGC = 1:numel(targetRGCsForWhichToVisualizeSpatialFrequencyTuningCurves)
            figureName = sprintf('SFtuning%d', targetRGCsForWhichToVisualizeSpatialFrequencyTuningCurves(iTargetRGC));

            visualizeRGCmosaicWithResponses(1000+targetRGCsForWhichToVisualizeSpatialFrequencyTuningCurves(iTargetRGC), theConeMosaic, plotXaxisScaling, plotType, ...
                    spatialFrequenciesCPD, responseAmplitude, ...
                    spatialFrequenciesCPDHR, responseAmplitudeHR, ...
                    runParams.rgcMosaicPatchEccMicrons, runParams.rgcMosaicPatchSizeMicrons, ...
                    theMidgetRGCmosaic,  'centers', maxSpikeRateModulation, ...
                    coVisualizedRetinalStimulus, ...
                    figureName, LMScontrast, opticsPostFix, PolansSubjectID, ...
                    targetRGCsForWhichToVisualizeSpatialFrequencyTuningCurves(iTargetRGC), false, ...
                    exportFig, figExportsDir);
        end
    end
end