function  visualizeDeconvolutionModelForConnectedPatch(synthesizedRFParams, figExportsDir)
    
    plotlabOBJ = setupPlotLab(0, 14, 14);
    visualizeCenterSurroundProperties(300, synthesizedRFParams, 'visual', plotlabOBJ, 'PatchDeconvolutionModel_VisualParams', figExportsDir);
    visualizeCenterSurroundProperties(301, synthesizedRFParams, 'retinal', plotlabOBJ, 'PatchDeconvolutionModel_RetinalParams', figExportsDir);
   
end

function plotlabOBJ = setupPlotLab(mode, figWidthInches, figHeightInches)
    if (mode == 0)
        plotlabOBJ = plotlab();
        plotlabOBJ.applyRecipe(...
                'colorOrder', [1 0 0; 0 0 1], ...
                'axesBox', 'off', ...
                'axesTickDir', 'in', ...
                'renderer', 'painters', ...
                'lineMarkerSize', 12, ...
                'axesTickLength', [0.01 0.01], ...
                'legendLocation', 'SouthWest', ...
                'figureWidthInches', figWidthInches, ...
                'figureHeightInches', figHeightInches);
    else
        pause(2.0);
        plotlab.resetAllDefaults();
    end
    
end 
