function eliminateRGCsWithThisManyCenterConesNum(obj, targetCenterConesNum)

   if (isempty(obj.rgcRFcenterConePoolingMatrix))
       indicesOfRGCsToEliminate = obj.indicesOfRGCsWithThisManyCenterCones(targetCenterConesNum);
       fprintf('Will eliminate %d RGCs which all have %d cones in their RF center', numel(indicesOfRGCsToEliminate), targetCenterConesNum)
   else
       error('RGC elimination can only be done before cones are connected to surrounds\n');
   end
   

   % Visualize mosaic before RGC elimination
   identifyPooledCones = true;
   identifyInputCones = true;
   plotRFoutlines = true;
   indicesOfRGCsIdentified = indicesOfRGCsToEliminate;

   hFig = figure(10); clf;
   set(hFig, 'Position', [10 10 1800 1000], 'Color', [1 1 1], ...
        'Name', sprintf('Before elimination of RGCs with %d center cones', targetCenterConesNum));
   obj.visualize(...
            'figureHandle', hFig, ...
            'identifiedConeApertureThetaSamples', 32, ...
            'identifiedConeAperture', 'lightCollectingAreaCharacteristicDiameter', ...
            'identifyPooledCones', identifyPooledCones, ...
            'identifyInputCones',identifyInputCones, ...
            'labelRGCsWithIndices', indicesOfRGCsIdentified , ...
            'plotRFoutlines', plotRFoutlines, ...
            'domainVisualizationLimits', [], ...
            'domainVisualizationTicks', [], ...
            'backgroundColor', [0 0 0], ...
            'plotTitle', sprintf('Before elimination of RGCs with %d center cones', targetCenterConesNum));


    % --------- Do the RGC elimination -------
    indicesOfRGCsToKeep = setdiff(1:obj.rgcsNum, indicesOfRGCsToEliminate);
    obj.rgcRFcenterConeConnectivityMatrix = obj.rgcRFcenterConeConnectivityMatrix(:,indicesOfRGCsToKeep);
    obj.rgcRFpositionsMicrons = obj.rgcRFpositionsMicrons(indicesOfRGCsToKeep,:);
    obj.rgcRFpositionsDegs = obj.rgcRFpositionsDegs(indicesOfRGCsToKeep,:);
    obj.rgcRFspacingsMicrons = obj.rgcRFspacingsMicrons(indicesOfRGCsToKeep);
    obj.rgcRFspacingsDegs = obj.rgcRFspacingsDegs(indicesOfRGCsToKeep);
    % Reset the visualization cache
    obj.visualizationCache = [];
    % ------------------------------------------

    % Visualize mosaic after RGC elimination
    indicesOfRGCsIdentified = obj.indicesOfRGCsWithThisManyCenterCones(targetCenterConesNum);
    hFig = figure(20); clf;
    set(hFig, 'Position', [10 10 1800 1000], 'Color', [1 1 1], ...
       'Name', sprintf('After elimination of RGCs with %d center cones', targetCenterConesNum));
    obj.visualize(...
            'figureHandle', hFig, ...
            'identifiedConeApertureThetaSamples', 32, ...
            'identifiedConeAperture', 'lightCollectingAreaCharacteristicDiameter', ...
            'identifyPooledCones', identifyPooledCones, ...
            'identifyInputCones',identifyInputCones, ...
            'labelRGCsWithIndices', indicesOfRGCsIdentified, ...
            'plotRFoutlines', plotRFoutlines, ...
            'domainVisualizationLimits', [], ...
            'domainVisualizationTicks', [], ...
            'backgroundColor', [0 0 0], ...
            'plotTitle', sprintf('After elimination of RGCs with %d center cones', targetCenterConesNum));

    % Report stats of the updated mosaic
    obj.centerConePoolingStats();
end
