function theRGCIndices = indicesOfRGCsWithinROI(obj, roiCenterDegs, roiSizeDegs)

	% Define theROI based on the passed eccentricity and size
    theROI = regionOfInterest(...
        'geometryStruct', struct(...
            'units', 'degs', ...
            'shape', 'rect', ...
            'center', roiCenterDegs, ...
            'width', roiSizeDegs(1), ...
            'height', roiSizeDegs(2), ...
            'rotation', 0.0...
        ));

    % Find the indices of the RGCs whose position is within theROI
    theRGCIndices = theROI.indicesOfPointsInside(obj.rgcRFpositionsDegs);

    % Sort them according to their distance from the center of the ROI
    d2 = sum((bsxfun(@minus, obj.rgcRFpositionsDegs(theRGCIndices,:),roiCenterDegs)) .^ 2, 2);
    [~,idx] = sort(d2, 'ascend');
    theRGCIndices = theRGCIndices(idx);

end