function visualizeSpatialRFofRGCwithIndex(obj,theRGCindex, pdfFileName)
    % Generate the visualization cache
    xSupport = [];
    ySupport = []; 
    obj.generateVisualizationCache(xSupport, ySupport);
    theContourData = obj.visualizationCache.rfCenterContourData{theRGCindex};

    % The cell position
    theCurrentRGCposition = obj.rgcRFpositionsDegs(theRGCindex,:);

    % Retrieve this cell's  center cone indices and weights
    connectivityVector = full(squeeze(obj.rgcRFcenterConePoolingMatrix(:, theRGCindex)));
    centerConeIndicesForCurrentRGC = find(connectivityVector > 0.0001);
    centerConeWeightsForCurrentRGC = connectivityVector(centerConeIndicesForCurrentRGC);

    % Retrieve this cell's surround cone indices and weights
    connectivityVector = full(squeeze(obj.rgcRFsurroundConePoolingMatrix(:, theRGCindex)));
    surroundConeIndicesForCurrentRGC = find(connectivityVector > 0.0001);
    surroundConeWeightsForCurrentRGC = connectivityVector(surroundConeIndicesForCurrentRGC);

    inputConeMosaic = obj.inputConeMosaic;

    hFig = figure(1); clf;
    ff = MSreadyPlot.figureFormat('1x3 RF poster');
    theAxes = MSreadyPlot.generateAxes(hFig,ff);

    tickSeparationArcMin = 3;
    spatialSupportRangeArcMin = tickSeparationArcMin*6;


    centerLineWeightingFunctions = MSreadyPlot.renderConePoolingPlot(theAxes{1,1}, ...
            inputConeMosaic, ...
            theCurrentRGCposition, ...
            centerConeIndicesForCurrentRGC, ...
            centerConeWeightsForCurrentRGC, ...
            ff, ...
            'spatialSupportRangeArcMin', spatialSupportRangeArcMin, ...
            'tickSeparationArcMin', tickSeparationArcMin, ...
            'plotTitle', '', ...
            'noXLabel', true, ...
            'noYLabel', true, ...
            'noYTicks', true, ...
            'xAxisTickAngleRotationDegs', 0);

    cla(theAxes{1,1}, 'reset');

    % Plot the RFs
    surroundLineWeightingFunctions = MSreadyPlot.renderConePoolingPlot(theAxes{1,1}, ...
            inputConeMosaic, ...
            theCurrentRGCposition, ...
            surroundConeIndicesForCurrentRGC, ...
            surroundConeWeightsForCurrentRGC, ...
            ff, ...
            'spatialSupportRangeArcMin', spatialSupportRangeArcMin, ...
            'tickSeparationArcMin', tickSeparationArcMin, ...
            'plotTitle', '', ...
            'noXLabel', false, ...
            'noYLabel', false, ...
            'noYTicks', false, ...
            'xAxisTickAngleRotationDegs', 0);

    S.Vertices = theContourData{1}.vertices;
    S.Faces = theContourData{1}.faces;
    S.FaceVertexCData = [0.5 0.5 0.5];

    S.FaceColor = 'flat';
    S.EdgeColor = [0 0 0];
    S.FaceAlpha = 0.0;
    S.LineWidth = 1.0;
    patch(S, 'Parent', theAxes{1,1})


    % Add the line weighting functions
    sensitivityRange(2) =  1.0*max([max(centerLineWeightingFunctions.x.amplitude(:)) max(centerLineWeightingFunctions.y.amplitude(:))]);
    sensitivityRange(1) = -0.8*sensitivityRange(2);
    
    centerLineWeightingFunctions.x.amplitude = centerLineWeightingFunctions.x.amplitude / max(sensitivityRange);
    centerLineWeightingFunctions.y.amplitude = centerLineWeightingFunctions.y.amplitude / max(sensitivityRange);
    surroundLineWeightingFunctions.x.amplitude = surroundLineWeightingFunctions.x.amplitude / max(sensitivityRange);
    surroundLineWeightingFunctions.y.amplitude = surroundLineWeightingFunctions.y.amplitude / max(sensitivityRange);
    sensitivityRange = sensitivityRange / max(sensitivityRange);

    MSreadyPlot.renderConePoolingLineWeightingFunctions(theAxes{1,2}, ...
            centerLineWeightingFunctions.x, surroundLineWeightingFunctions.x, ...
            sensitivityRange, 'x', ff, ...
            'spatialSupportRangeArcMin', spatialSupportRangeArcMin, ...
            'tickSeparationArcMin', tickSeparationArcMin, ...
            'plotTitle', '', ...
            'noYTicks', true, ...
            'xAxisTickAngleRotationDegs', 0);

    MSreadyPlot.renderConePoolingLineWeightingFunctions(theAxes{1,3}, ...
            centerLineWeightingFunctions.y, surroundLineWeightingFunctions.y, ...
            sensitivityRange, 'y', ff, ...
            'spatialSupportRangeArcMin', spatialSupportRangeArcMin, ...
            'tickSeparationArcMin', tickSeparationArcMin, ...
            'plotTitle', '', ...
            'noYLabel', true, ...
            'noYTicks', true, ...
            'xAxisTickAngleRotationDegs', 0);

    if (~isempty(pdfFileName))
        NicePlot.exportFigToPDF(pdfFileName, hFig, 300);
    end

end