function coneMosaic(app)

    % Generate cone mosaic with new params
    fprintf('Generating new cone mosaic (eye: ''%s'') (%2.1f x %2.1f) degs located at (%2.1f, %2.1f)\n', ...
        app.coneMosaicParams.whichEye, ...
        app.coneMosaicParams.sizeDegs(1), app.coneMosaicParams.sizeDegs(2), ...
        app.coneMosaicParams.eccentricityDegs(1), app.coneMosaicParams.eccentricityDegs(2));
    
    app.components.coneMosaic = cMosaic(...
        'whichEye', app.coneMosaicParams.whichEye, ...
        'sizeDegs', app.coneMosaicParams.sizeDegs, ...
        'eccentricityDegs', app.coneMosaicParams.eccentricityDegs);
    
    
%     , ...
%         'coneDensities', app.mosaicConeDensities, ...
%         'tritanopicRadiusDegs', app.mosaicTritanopicRadiusDegs, ...
%         'wave', app.wavelengthMinValue : app.wavelengthStepSize: app.wavelengthMaxValue, ...
%         'integrationTime', app.mosaicIntegrationTimeMseconds/1000, ...
%         'eccVaryingConeAperture', app.mosaicEccVaryingConeAperture, ...
%         'eccVaryingOuterSegmentLength', app.mosaicEccVaryingOuterSegmentLength, ...
%         'eccVaryingConeBlur', app.mosaicEccVaryingConeBlur, ...
%         'eccVaryingMacularPigmentDensity', app.mosaicEccVaryingMacularPigmentDensity, ...
%         'eccVaryingMacularPigmentDensityDynamic', false ...


    domain = 'degrees';
    domainVisualizationLimits = [];
    mosaicVisualizationView = 'retinal view';
    
%   Visualize the cone mosaic
    app.components.coneMosaic.visualize(...
        'figureHandle', app.mainView, ...
        'axesHandle', app.coneMosaicView, ...
        'visualizationView', mosaicVisualizationView, ...
        'labelCones', true, ...
        'crossHairsOnFovea', true, ...
        'visualizedConeAperture', 'geometricArea', ...
        'domain', domain, ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'noYLabel', ~true, ...
        'fontSize', 14, ...
        'plotTitle',  ' ');
                
                
%   Set the microns-per-deg field
    app.visualFieldMagnificationFactorEditField.Value = app.components.coneMosaic.micronsPerDegree;
    
end

