function optics(app)

    switch (app.opticsParams.subjectDataset)
        case 'Polans2015'
            zernikeDataBase = 'Polans2015';
        case 'Artal'
            zernikeDataBase = 'Artal';
        otherwise
            error('Unknown optics dataset: ''%s''.', app.opticsParams.subjectDataset);
    end
    
    % Generate optics appropriate for the mosaic's eccentricity
    [oiEnsemble, psfEnsemble] = ...
            app.components.coneMosaic.oiEnsembleGenerate(app.coneMosaicParams.eccentricityDegs, ...
            'zernikeDataBase', zernikeDataBase, ...
            'subjectID', app.opticsParams.subjectID, ...
            'pupilDiameterMM', app.opticsParams.pupilDiameterMM, ...
            'subtractCentralRefraction', app.opticsParams.subtractCentralRefraction);
           
     % Exported data
%             app.exportedOpticsParams = struct(...
%                 'eccentricityDegs', app.mosaicEccentricityDegs, ...
%                 'zernikeDataBase', 'Polans2015', ...
%                 'subjectID', app.opticsParams.PolansSubjectID, ...
%                 'pupilDiameterMM', app.opticsParams.pupilDiameterMM, ...
%                 'subtractCentralRefraction', app.opticsParams.subtractCentralRefraction ...
%                 );
            
     % Update all components with new optics
     app.components.psf = psfEnsemble{1};
     app.components.optics = oiEnsemble{1};
            
     CSFGeneratorApp.render.opticsView(app, 'update');
end
