function [sParams, coneMosaicIsTooSmall] = stimParamsStructForGratingSceneEngine(app, currentSpatialFrequency)
    % Form sParams struct
    sParams = struct(...
                'contrast', 1.0, ...
                'chromaDir', [app.stimParams.LconeContrast app.stimParams.MconeContrast app.stimParams.SconeContrast]/100, ...
                'meanLuminanceCdPerM2', app.stimParams.meanLuminanceCdM2, ...
                'sf', currentSpatialFrequency, ...
                'fovDegs', app.stimParams.sizeDegs, ...
                'orientation', app.stimParams.orientationDegs, ...
                'spatialEnvelope', app.stimParams.spatialEnvelope, ...
                'spatialPhase', app.stimParams.spatialPhaseDegs, ...
                'pixelsNum', app.stimParams.resolutionPixels, ...
                'minPixelsNumPerCycle', app.stimParams.minPixelsNumPerCycle, ...
                'spectralSupport', (app.stimParams.wavelengthSupportMin : app.stimParams.wavelengthSupportStepSize: app.stimParams.wavelengthSupportMax), ...
                'presentationMode', app.stimParams.presentationMode, ...
                'duration', app.stimParams.durationSec, ...
                'warningInsteadOfErrorOnOutOfGamut', true ...
     );
 
    
     if (strcmp(app.csfParams.constantParameter, 'constant cycles'))
        spatialPeriodDegs = 1.0/currentSpatialFrequency;
        stimSizeDegs = app.csfParams.numberOfConstantCycles * spatialPeriodDegs;
     else
        stimSizeDegs = app.stimParams.sizeDegs;
     end
        
     switch (app.stimParams.spatialEnvelope)
            case 'disk'
                sParams.spatialEnvelopeRadiusDegs = stimSizeDegs/2;
            case 'rect'
                sParams.spatialEnvelopeRadiusDegs = stimSizeDegs/(2*sqrt(2.0));
            case 'soft'
                sParams.spatialEnvelopeRadiusDegs = stimSizeDegs/6;  
            otherwise
                error('Unknown spatial envelope: ''%s''.', app.stimParams.spatialEnvelope);
     end
     
     % Check whether the cone mosaic is large enough for the stimulus
     coneMosaicIsTooSmall = false;
     maxStimSize = CSFGeneratorApp.compute.stimulusSizeAtLowestSpatialFrequency(app);
     if (min(app.coneMosaicParams.sizeDegs) < maxStimSize)
        coneMosaicIsTooSmall = true;
     end
            
end

