function sParams = stimParamsStructForGratingSceneEngine(stimParams)
    % Form sParams struct
    sParams = struct(...
                'contrast', 1.0, ...
                'chromaDir', [stimParams.LconeContrast stimParams.MconeContrast stimParams.SconeContrast]/100, ...
                'meanLuminanceCdPerM2', stimParams.meanLuminanceCdM2, ...
                'sf', stimParams.spatialFrequencyCPD, ...
                'fovDegs', stimParams.sizeDegs, ...
                'orientation', stimParams.orientationDegs, ...
                'spatialEnvelope', stimParams.spatialEnvelope, ...
                'spatialPhase', stimParams.spatialPhaseDegs, ...
                'pixelsNum', stimParams.resolutionPixels, ...
                'minPixelsNumPerCycle', stimParams.minPixelsNumPerCycle, ...
                'spectralSupport', (stimParams.wavelengthSupportMin : stimParams.wavelengthSupportStepSize: stimParams.wavelengthSupportMax), ...
                'presentationMode', stimParams.presentationMode, ...
                'duration', stimParams.durationSec, ...
                'warningInsteadOfErrorOnOutOfGamut', true ...
     );
 
     switch (stimParams.spatialEnvelope)
            case 'disk'
                sParams.spatialEnvelopeRadiusDegs = stimParams.sizeDegs/2;
            case 'rect'
                sParams.spatialEnvelopeRadiusDegs = stimParams.sizeDegs/(2*sqrt(2.0));
            case 'soft'
                sParams.spatialEnvelopeRadiusDegs = stimParams.sizeDegs/6;  
            otherwise
                error('Unknown spatial envelope: ''%s''.', stimParams.spatialEnvelope);
     end
    
end

