function theSurroundOptimizationString = surroundOptimizationString(surroundOptimizationPpoolingModel)
  switch (surroundOptimizationPpoolingModel.name)
      case 'PackerDacey2002H1FixedCellIndex'
          theSurroundOptimizationString = sprintf('srndModel_%s%d_%s', ...
            surroundOptimizationPpoolingModel.name, ...
            surroundOptimizationPpoolingModel.fixedH1CellIndex, ...
            surroundOptimizationPpoolingModel.identifierString);
      otherwise
          theSurroundOptimizationString = sprintf('srndModel_%s%s', ...
            surroundOptimizationPpoolingModel.name, ...
            surroundOptimizationPpoolingModel.identifierString);
  end
end