function hFig = visualizeCurrentConnectivity(obj, figNo, varargin)
    % Parse input
    p = inputParser;
    p.addParameter('titleString', '', @ischar);
    p.addParameter('visualizedDestinationRFindices', [], @isnumeric);
    p.addParameter('onlyVisualizeConnectivity', false, @islogical);
    p.parse(varargin{:});
    titleString = p.Results.titleString;
    visualizedDestinationRFindices = p.Results.visualizedDestinationRFindices;
    onlyVisualizeConnectivity = p.Results.onlyVisualizeConnectivity;


    hFig = figure(figNo); clf;
    if (onlyVisualizeConnectivity)
        subplotPosVectors = NicePlot.getSubPlotPosVectors(...
           'rowsNum', 1, ...
           'colsNum', 1, ...
           'heightMargin',  0.07, ...
           'widthMargin',    0.04, ...
           'leftMargin',     0.04, ...
           'rightMargin',    0.00, ...
           'bottomMargin',   0.05, ...
           'topMargin',      0.03);
    else
        subplotPosVectors = NicePlot.getSubPlotPosVectors(...
           'rowsNum', 2, ...
           'colsNum', 2, ...
           'heightMargin',  0.07, ...
           'widthMargin',    0.04, ...
           'leftMargin',     0.04, ...
           'rightMargin',    0.00, ...
           'bottomMargin',   0.05, ...
           'topMargin',      0.03);
    set(hFig, 'Units', 'pixels');
    set(hFig, 'Color', [1 1 1], 'Position', [10 10 1650 990]);

    if (onlyVisualizeConnectivity)
        minXYdest = min(obj.destinationLattice.RFpositionsMicrons,[],1);
        maxXYdest = max(obj.destinationLattice.RFpositionsMicrons,[],1);
        maxDestSpacing = max(obj.destinationLattice.RFspacingsMicrons);
        XLims = [minXYdest(1) maxXYdest(1)] + maxDestSpacing*[-1 1];
        YLims = [minXYdest(2) maxXYdest(2)] + maxDestSpacing*[-1 1];
    else
        % The input lattices on the rop-right plot
        ax = subplot('Position', subplotPosVectors(1,1).v);
        [~,~,XLims, YLims] = obj.visualizeInputLattices(...
            'figureHandle', hFig, ...
            'axesHandle', ax, ...
            'thetaSamples', 30);
        set(ax, 'FontSize', 16);
    end

    if (isempty(titleString))
        titleString = 'lattice wiring (stars: destination RFs with 0 inputs)';
    end

    % The connectivity (pooling of destination lattice RFs) in the bottom-right plot
    if (~onlyVisualizeConnectivity)
        ax = subplot('Position', subplotPosVectors(1,2).v);
    else
        ax = subplot('Position', subplotPosVectors(1,1).v);
    end
    visualizeDestinationLatticePooling(obj, ...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'titleString', titleString, ...
        'titleWithPoolingStats', true, ...
        'visualizedDestinationRFindices', visualizedDestinationRFindices, ...
        'thetaSamples', 10, ...
        'XLims', XLims, ...
        'YLims', YLims);

    % Report statistics of spatial/chromatic cost
    if (~onlyVisualizeConnectivity)
        if (~isempty(obj.connectivityMatrix))
            if (~isempty(obj.destinationRFspacingsFromCentroids))

                % Compute costs across entire destinationRF mosaic
                theTotalPoolingCosts = obj.totalPoolingCosts();

                ax1 = subplot('Position', subplotPosVectors(2,1).v);
                ax2 = subplot('Position', subplotPosVectors(2,2).v);
                obj.visualizeCostComponentStatistics(ax1, ax2, theTotalPoolingCosts);
            end
        end
    end
    drawnow;
end
