function coneMosaicView(app)

    domain = 'degrees';
    domainVisualizationLimits = [];
    mosaicVisualizationView = 'retinal view';
    
    if (~isempty(app.components.coneMosaic.coneRFpositionsDegs))
        app.components.coneMosaic.visualize(...
            'figureHandle', app.mainView, ...
            'axesHandle', app.coneMosaicView, ...
            'visualizationView', mosaicVisualizationView, ...
            'labelCones', true, ...
            'crossHairsOnFovea', true, ...
            'visualizedConeAperture', 'geometricArea', ...
            'domain', domain, ...
            'domainVisualizationLimits', domainVisualizationLimits, ...
            'noYLabel', ~true, ...
            'fontSize', 14, ...
            'backgroundColor', 0.94*[1 1 1], ...
            'plotTitle',  ' ');
    else
        cla(app.coneMosaicView)
    end
    set(app.coneMosaicView, 'LineWidth', 0.01);
    box(app.coneMosaicView, 'off');
end
