function [centerLineWeightingFunctions, surroundLineWeightingFunctions] = ...
	conePoolingWeightsMap(pdfExportSubDir, figNo, figPos, theMRGCMosaic, theTargetRGCindex, ...
		spatialSupportCenterDegs, spatialSupportTickSeparationArcMin,  ...
		theOptimizedPooledConeIndicesAndWeights, ...
		minConeWeightForVisualizingRFcenterPooling, ...
        minConeWeightForVisualizingRFsurroundPooling, ...
        minSurroundConeWeightRelativity, ...
        visualizedConeWeights, ...
        varargin)
	
    
    % Parse input
    p = inputParser;
    p.addParameter('domainVisualizationLimits', [], @(x)(isempty(x)||(numel(x)==4)));
    p.addParameter('domainVisualizationTicks', [], @(x)(isempty(x)||(isstruct(x))));
    p.addParameter('scaleBarDegs', [], @(x)(isempty(x)||(isscalar(x))));
    p.addParameter('doNotLabelScaleBar', false, @islogical);
    p.addParameter('contourGenerationMethod', 'ellipseFitToPooledConePositions', @(x)(ismember(x, mRGCMosaic.validRFsubregionContourGenerationMethods)));
    p.addParameter('maxNumberOfConesOutsideContour', 1, @isscalar);
    p.addParameter('gridless', false, @islogical);
    p.addParameter('noXLabel', false, @islogical);
    p.addParameter('noYLabel', false, @islogical);
    p.addParameter('plotTitle', '', @ischar);
    p.addParameter('axesToRenderIn', [], @(x)(isempty(x)||(isa(x, 'handle'))));
    p.addParameter('exportToFigurePDFsDirWithPDFFileName', '', @(x)(isempty(x)||(ischar(x))));
    p.parse(varargin{:});

    domainVisualizationLimits = p.Results.domainVisualizationLimits;
    domainVisualizationTicks = p.Results.domainVisualizationTicks;
    scaleBarDegs = p.Results.scaleBarDegs;
    doNotLabelScaleBar = p.Results.doNotLabelScaleBar;

    gridless = p.Results.gridless;
    noXLabel = p.Results.noXLabel;
    noYLabel = p.Results.noYLabel;
    plotTitle = p.Results.plotTitle;
    axesToRenderIn = p.Results.axesToRenderIn;
    contourGenerationMethod = p.Results.contourGenerationMethod;
    maxNumberOfConesOutsideContour = p.Results.maxNumberOfConesOutsideContour;
    exportToFigurePDFsDirWithPDFFileName = p.Results.exportToFigurePDFsDirWithPDFFileName;


    % Call mRGC.visualizeCenterSurroundConePoolingMap routine for plotting
    % and returning the center/surround line weighting functions
    [~, ~, centerLineWeightingFunctions, surroundLineWeightingFunctions] = ...
            theMRGCMosaic.visualizeCenterSurroundConePoolingMap(theTargetRGCindex, ...
            'pooledConeIndicesAndWeights', theOptimizedPooledConeIndicesAndWeights, ...
            'visualizedConeWeights', visualizedConeWeights, ...
            'minConeWeightForVisualizingRFcenterPooling', minConeWeightForVisualizingRFcenterPooling, ...
            'minConeWeightForVisualizingRFsurroundPooling', minConeWeightForVisualizingRFsurroundPooling, ...
            'minSurroundConeWeightRelativity', minSurroundConeWeightRelativity, ...
            'spatialSupportCenterDegs', spatialSupportCenterDegs, ...
            'spatialSupportTickSeparationArcMin', spatialSupportTickSeparationArcMin, ...
            'domainVisualizationLimits', domainVisualizationLimits, ...
            'domainVisualizationTicks', domainVisualizationTicks, ...
            'scaleBarDegs', scaleBarDegs, ...
            'doNotLabelScaleBar', doNotLabelScaleBar, ...
            'contourGenerationMethod', contourGenerationMethod, ...
            'maxNumberOfConesOutsideContour', maxNumberOfConesOutsideContour, ...
            'gridless', gridless, ...
            'noXLabel', noXLabel, ...
            'noYLabel', noYLabel, ...
            'plotTitle', plotTitle, ...
            'axesToRenderIn', axesToRenderIn, ...
            'figNo', figNo, ...
            'figPos', figPos, ...
            'exportToFigurePDFsDirWithPDFFileName', exportToFigurePDFsDirWithPDFFileName, ...
            'pdfExportSubDir', pdfExportSubDir);
end

