 % Phase 4: Connect cones to the mRGC RF centers
function runPhase4(runParams)

    % Load data
    load(fullfile(runParams.outputDir, sprintf('%s.mat',runParams.inputFile)), ...
            'conePositionsMicrons', 'coneSpacingsMicrons', 'coneTypes', ...
            'RGCRFPositionsMicrons', 'RGCRFSpacingsMicrons', ...
            'desiredConesToRGCratios');
        
    visualizeConnectionProcess = false;
    [midgetRGCconnectionMatrix, RGCRFPositionsMicrons, RGCRFSpacingsMicrons] = computeConnectionMatrix(...
                RGCRFPositionsMicrons, conePositionsMicrons, RGCRFSpacingsMicrons, coneSpacingsMicrons, ...
                coneTypes, desiredConesToRGCratios, runParams.orphanRGCpolicy, runParams.maximizeConeSpecificity, ...
                visualizeConnectionProcess);
            
    % Save RGC center connection data
    save(fullfile(runParams.outputDir, sprintf('%s.mat',runParams.outputFile)), ...
            'conePositionsMicrons', 'coneSpacingsMicrons', 'coneTypes', ...
            'RGCRFPositionsMicrons', 'RGCRFSpacingsMicrons', ...
            'desiredConesToRGCratios', 'midgetRGCconnectionMatrix');
end

function [midgetRGCconnectionMatrix, RGCRFPositionsMicrons, RGCRFSpacingsMicrons] = ...
    computeConnectionMatrix(RGCRFPositionsMicrons, conePositionsMicrons, ...
    RGCRFSpacingsMicrons, coneSpacingsMicrons, ...
    coneTypes, desiredConesToRGCratios,  orphanRGCpolicy, maximizeConeSpecificity, visualizeProcess)
        
    % Step1. Align each RGC with its nearest cone. This ensure all RGC's
    % are connected to at least one cone. Since cones are more numerous
    % than RGCs some cones will not connect to an RGC at this step. This 
    % step occurs only for RGCs for which the cone-to-RGC ratio is [1..2]
    
    RGCRFPositionsMicrons = alignRGCmosaicToConeMosaic(...
        conePositionsMicrons, coneSpacingsMicrons, ...
        RGCRFPositionsMicrons, RGCRFSpacingsMicrons, ...
        coneTypes, desiredConesToRGCratios, visualizeProcess);
    
    % Step 2. Connect L and M cones to midget RGC centers.
    [midgetRGCconnectionMatrix, RGCRFPositionsMicrons, RGCRFSpacingsMicrons] = connectConesToMidgetRGCRFcenters(...
        conePositionsMicrons, coneSpacingsMicrons, ...
        RGCRFPositionsMicrons, RGCRFSpacingsMicrons, ...
        orphanRGCpolicy, maximizeConeSpecificity, ...
        coneTypes, desiredConesToRGCratios, visualizeProcess);
end