% Phase 5: Visualize connection of cones to the mRGC RF centers in a
% selected patch
function runPhase5(runParams)
    
     
    fprintf('Running %s()\n', mfilename());
    % Load data
    load(fullfile(runParams.outputDir, sprintf('%s.mat',runParams.inputFile)), ...
            'conePositionsMicrons', 'coneSpacingsMicrons', 'coneTypes', ...
            'RGCRFPositionsMicrons', 'RGCRFSpacingsMicrons', ...
            'desiredConesToRGCratios', 'midgetRGCconnectionMatrix');
    
  
    for sizeIndex = 1:size(runParams.patchEccMicrons,1)
        figHeightInches = 15;
        % Subregion center and size in microns
        patchEccDegs = WatsonRGCModel.rhoMMsToDegs(runParams.patchEccMicrons(sizeIndex,:)*1e-3);
        subregion.center = runParams.patchEccMicrons(sizeIndex,:);
        subregion.size = runParams.patchSizeMicrons(sizeIndex,:);

        plotlabOBJ = plotlab();
        plotlabOBJ.applyRecipe(...
                'renderer', 'painters', ... %'opengl', ...
                'axesBox', 'on', ...
                'colorOrder', [0 0 0; 1 0 0.5], ...
                'axesTickLength', [0.015 0.01]/4,...
                'axesFontSize', 22, ...
                'figureWidthInches', figHeightInches/(subregion.size(2))*(subregion.size(1)), ...
                'figureHeightInches', figHeightInches);

         xPos = RGCRFPositionsMicrons(:,1);
         yPos = RGCRFPositionsMicrons(:,2);
         subregionRGCidx = find( (xPos> subregion.center(1) - subregion.size(1)/2) & ...
                                 (xPos< subregion.center(1) + subregion.size(1)/2) & ...
                                 (yPos> subregion.center(2) - subregion.size(2)/2) & ...
                                 (yPos< subregion.center(2) + subregion.size(2)/2));

         subregionMidgetRGCconnectionMatrix = midgetRGCconnectionMatrix(:,subregionRGCidx);
         subregionRGCRFPositionsMicrons = RGCRFPositionsMicrons(subregionRGCidx,:);
        
         visualizeRFs(patchEccDegs, runParams.zLevels, runParams.whichLevelsToContour, ...
             subregionMidgetRGCconnectionMatrix, subregionRGCRFPositionsMicrons,...
             conePositionsMicrons, coneSpacingsMicrons, coneTypes, subregion, ...
             runParams.displayEllipseInsteadOfContour, runParams.showConnectedConePolygon, ...
             plotlabOBJ, runParams.outputFile,runParams.exportsDir);
    end
end
