% Phase 7: Visualize weights of cone inputs to mRGC  RF centers and surrounds
function runPhase7(runParams)
    % Weights datafile
    weightsFile = fullfile(runParams.outputDir, sprintf('%s_inPatchAt_%2.1f_%2.1fdegs_WithSize_%2.2f_%2.2f.mat', ...
        runParams.inputFile, runParams.patchEccDegs(1), runParams.patchEccDegs(2), runParams.patchSizeDegs(1), runParams.patchSizeDegs(2)));
    
    load(weightsFile, ...
        'conePositionsMicrons', 'coneSpacingsMicrons', 'coneTypes', ...
        'RGCRFPositionsMicrons', 'RGCRFSpacingsMicrons', ...
        'desiredConesToRGCratios', 'midgetRGCconnectionMatrix', ...
        'synthesizedRFParamsForRetinalPatch', 'patchEccDegs', 'patchSizeDegs');
    
    % Set up plotlab
    plotlabOBJ = setupPlotLab();
    outputFile = sprintf('%s_Summary',runParams.outputFile);
    % Visualize summary of visual rf properties
   %visualizeCenterSurroundProperties(1, synthesizedRFParamsForRetinalPatch, 'visual', plotlabOBJ, outputFile,runParams.exportsDir);
    
    % Visualize summary of retinal rf properties
    %visualizeCenterSurroundProperties(2, synthesizedRFParamsForRetinalPatch, 'retinal', plotlabOBJ, outputFile,runParams.exportsDir);
    
    % Visualize examples of retinal 2D RFs
    outputFile = sprintf('%s_RFexamples',runParams.outputFile);
    computeWeightedConeInputsToRGCCenterSurroundSubregions(synthesizedRFParamsForRetinalPatch, 'retinal', ...
        conePositionsMicrons, coneSpacingsMicrons, coneTypes, ...
        midgetRGCconnectionMatrix, ...
        plotlabOBJ, outputFile,runParams.exportsDir);
end

function plotlabOBJ = setupPlotLab()
    plotlabOBJ = plotlab();
    plotlabOBJ.applyRecipe(...
            'colorOrder', [1 0 0; 0 0 1], ...
            'axesBox', 'off', ...
            'axesTickDir', 'in', ...
            'renderer', 'painters', ...
            'lineMarkerSize', 6, ...
            'axesTickLength', [0.01 0.01], ...
            'legendLocation', 'SouthWest', ...
            'figureWidthInches', 14, ...
            'figureHeightInches', 14);
end 

