%% s_eyemovementsMosaic
%
% Illustrating the differential effect of eye movements on the fovea and
% periphery, as cone apertures change size. The same complete eye-movement
% path is shown on both mosaics in a static comparison. Earlier versions
% redrew both mosaics for every time point and trial.
% 

%% Initialize
ieInit;

%% Generate two @cMosaic objects.  Fovea and periphery.

cmFovea = cMosaic(...
    'sizeDegs', [0.3 0.3], ...    
    'eccentricityDegs', [0 0], ...
    'rodIntrusionAdjustedConeAperture', true, ...
    'integrationTime', 5/1000);

cmPeriphery = cMosaic(...
    'sizeDegs', [0.3 0.3], ...      
    'eccentricityDegs', [5 0], ...
    'rodIntrusionAdjustedConeAperture', true, ...
    'integrationTime', 5/1000);


%% Generate one short fixational eye-movement path

eyeMovementDurationSeconds = 50/1000;
nTrials = 1;

% These are the same because they have the same seed.
cmFovea.emGenSequence(eyeMovementDurationSeconds, ...
    'microsaccadeType', 'none', ...
    'nTrials', nTrials, ...
    'randomSeed', 1);

cmPeriphery.emGenSequence(eyeMovementDurationSeconds, ...
    'microsaccadeType', 'none', ...
    'nTrials', nTrials, ...
    'randomSeed', 1);

%% Select the full eye-movement path

emPathsDegs = cmFovea.fixEMobj.emPosArcMin/60;
nTimePoints = size(emPathsDegs,2);
displayedEyeMovementData = struct(...
    'trial', 1, ...
    'timePoints', 1:nTimePoints);

%% Compare the same path on the two mosaics
hFig = ieFigure([], 'wide');
axFovea = subplot(1,2,1);
axPeriphery = subplot(1,2,2);

cmFovea.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', axFovea, ...
    'conesAlpha', 0.4, ...
    'visualizedConeAperture', 'lightCollectingArea', ...
    'displayedEyeMovementData', displayedEyeMovementData, ...
    'backgroundColor', [0 0 0], ...
    'plotTitle', sprintf('fovea: complete %2.0f msec path', ...
        cmFovea.fixEMobj.timeAxis(end)*1000));

cmPeriphery.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', axPeriphery, ...
    'conesAlpha', 0.4, ...
    'visualizedConeAperture', 'lightCollectingArea', ...
    'displayedEyeMovementData', displayedEyeMovementData, ...
    'backgroundColor', [0 0 0], ...
    'plotTitle', sprintf('periphery: complete %2.0f msec path', ...
        cmPeriphery.fixEMobj.timeAxis(end)*1000));

fprintf('Median cone aperture diameter: fovea %0.3f arcmin, periphery %0.3f arcmin.\n', ...
    60*median(cmFovea.coneApertureDiametersDegs), ...
    60*median(cmPeriphery.coneApertureDiametersDegs));

%% END
