function dataFileName = computeObjectDataFileName(obj)
    s1 = sprintf('%s_Rank_%d_Pupil_%1.1f', ...
                    obj.opticsParams.ZernikeDataBase, obj.opticsParams.examinedSubjectRankOrder, obj.opticsParams.pupilDiameterMM);
    s2 = sprintf('RFecc_%2.4f_%2.4f', ...
                    obj.opticsParams.positionDegs(1), obj.opticsParams.positionDegs(2));
    s3 = sprintf('RFcenterCones_%d_RsRcRatio_%1.2f_SCratio_%1.2f', ...
                    numel(obj.targetVisualRFDoGparams.indicesOfConesPooledByTheRFcenter), ...
                    obj.targetVisualRFDoGparams.surroundToCenterRcRatio, ...
                    obj.targetVisualRFDoGparams.surroundToCenterIntegratedSensitivityRatio);
    s4 = sprintf('RetinalPoolingModel_%s', strrep(strrep(obj.targetVisualRFDoGparams.retinalConePoolingModel, ' ', ''),',', '_'));
    dataFileName = sprintf('RTVF_%s_%s_%s_%s.mat', s1,s2,s3,s4);
end