function hFig = visualizeCurrentConnectivityState(obj, figNo)
% Visualize current connectivity state.
    hFig = figure(figNo); clf;
    if (~isempty(obj.coneConnectivityMatrix))
        subplotPosVectors = NicePlot.getSubPlotPosVectors(...
           'rowsNum', 2, ...
           'colsNum', 2, ...
           'heightMargin',  0.08, ...
           'widthMargin',    0.06, ...
           'leftMargin',     0.05, ...
           'rightMargin',    0.00, ...
           'bottomMargin',   0.05, ...
           'topMargin',      0.01);
        set(hFig, 'Color', [1 1 1], 'Position', [10 10 1650 1000]);
    else
        subplotPosVectors = NicePlot.getSubPlotPosVectors(...
           'rowsNum', 2, ...
           'colsNum', 1, ...
           'heightMargin',  0.08, ...
           'widthMargin',    0.06, ...
           'leftMargin',     0.05, ...
           'rightMargin',    0.00, ...
           'bottomMargin',   0.05, ...
           'topMargin',      0.01);
        set(hFig, 'Color', [1 1 1], 'Position', [10 10 950 1000]);
    end


    ax = subplot('Position', subplotPosVectors(1,1).v);
    [~,~,XLims, YLims] = obj.visualizeInputMosaics(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'thetaSamples', 30, ...
        'titleString', 'starting positions');
    set(ax, 'FontSize', 16)

    ax = subplot('Position', subplotPosVectors(2,1).v);
    obj.visualizeConnectivity(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'XLims', XLims, ...
        'YLims', YLims);

    % Report statistics of spatial/chromatic cost
    if (~isempty(obj.coneConnectivityMatrix))
        if (~isempty(obj.localRGCRFspacingsMicrons))
            % Compute costs across entire RGC mosaic
            [totalCost, spatialCost, chromaticCost] = obj.computeInputMaintenanceCostAcrossEntireMosaic();
    
            ax = subplot('Position', subplotPosVectors(1,2).v);
            obj.visualizeSpatialVarianceCostStatistics(ax, spatialCost);
            ax = subplot('Position', subplotPosVectors(2,2).v);
            obj.visualizeChromaticVarianceCostStatistics(ax, chromaticCost);
        end
    end
    drawnow;
end