function hFig = visualizeCurrentConnectivityState(obj, figNo)
    subplotPosVectors = NicePlot.getSubPlotPosVectors(...
       'rowsNum', 2, ...
       'colsNum', 1, ...
       'heightMargin',  0.03, ...
       'widthMargin',    0.05, ...
       'leftMargin',     0.05, ...
       'rightMargin',    0.00, ...
       'bottomMargin',   0.05, ...
       'topMargin',      0.0);

    % Visualize current connectivity state.
    hFig = figure(figNo); clf;
    set(hFig, 'Color', [1 1 1], 'Position', [10 10 1650 1000]);

    ax = subplot('Position', subplotPosVectors(1,1).v);
    [~,~,XLims, YLims] = obj.visualizeInputMosaics(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'thetaSamples', 30, ...
        'titleString', 'starting positions');
    set(ax, 'FontSize', 16)

    ax = subplot('Position', subplotPosVectors(2,1).v);
    obj.visualizeConnectivity(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'XLims', XLims, ...
        'YLims', YLims);
end