function [theOptimalStrehlRatioOI, theOptimalStrehlRatioPSF, theOptimalStrehlRatioDefocusDiopters, theOptimalStrehlRatio] = optimizedStrehlRatioPSF(examinedRefractionErrorDiopters, ...
	theConeMosaic, oiPositionDegs, opticsParams, wavefrontSpatialSamples, psfUpsampleFactor, ...
	visualizeStrehlRatioOptimization, contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection)

	% Generate diffraction-limited PSF so that we can compute the Strehl ratio later
	[oiEnsemble, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
			oiPositionDegs, ...
	       'zernikeDataBase', opticsParams.ZernikeDataBase, ...
	       'subjectID', 0, ...
	       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
	       'refractiveErrorDiopters', 0.0, ...
	       'noLCA', false, ...
	       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
	       'subtractCentralRefraction', false, ...
	       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
	       'upsampleFactor', psfUpsampleFactor, ...
	       'warningInsteadOfErrorForBadZernikeCoeffs', false);

	% Find the wavelength at thich the diffraction-limited PSF achieves it peak.
	% Since we have LCA enabled, this should be 550.
	theDiffractionLimitedPSF = psfEnsemble{1,1};
	[peakDiffractionLimitedPSFAmplitude, ...
	 wavelengthIndexOfPeakDiffractionLimitedPSFamplitude, ...
	 wavelengthOfPeakDiffractionLimitedPSFamplitude] = RGCMosaicConstructor.helper.optics.analyzePSF(theDiffractionLimitedPSF, []);
	 assert(wavelengthOfPeakDiffractionLimitedPSFamplitude == 550, 'Diffraction-limited PSF does not peak at 550');

	targetInFocusWavelengthIndex = wavelengthIndexOfPeakDiffractionLimitedPSFamplitude;
	targetInFocusWavelength = wavelengthOfPeakDiffractionLimitedPSFamplitude;
	fprintf('Diffraction-limited PSF peaks at %d nm (which is our in-focus wavelength)\n', targetInFocusWavelength);

	if (visualizeStrehlRatioOptimization) || (contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection)
		% Generate central-diffraction corrected PSF (just for reference to the optimal Strehl ratio PSF)
		[oiEnsemble, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
        			oiPositionDegs, ...
			       'zernikeDataBase', opticsParams.ZernikeDataBase, ...
			       'subjectID', opticsParams.subjectID, ...
			       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
			       'refractiveErrorDiopters', 0.0, ...
			       'noLCA', opticsParams.noLCA, ...
			       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
			       'subtractCentralRefraction', true, ...
			       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
			       'upsampleFactor', psfUpsampleFactor, ...
			       'warningInsteadOfErrorForBadZernikeCoeffs', false);

		theCentralCorrectionPSF = psfEnsemble{1,1};
		[peakCentralCorrectionPSFAmplitude, ...
	 	wavelengthIndexOfPeakCentralCorrectionPSFamplitude, ...
	 	wavelengthOfPeakCentralCorrectionPSFamplitude] = RGCMosaicConstructor.helper.optics.analyzePSF(theCentralCorrectionPSF, []);
	end

	StrehlRatio = examinedRefractionErrorDiopters * 0;

	% Search through the defocus values in examinedRefractionErrorDiopters to determine the defocus value
	% for which the ratio of peak PSF amplitude for the current subject to peakDiffractionLimitedPSFAmplitude 
	% (at the wavelengthOfPeakDiffractionLimitedPSFamplitude) is maximal
	for iRefractiveError = 1:numel(examinedRefractionErrorDiopters)
		defocusValue = examinedRefractionErrorDiopters(iRefractiveError);
		% Generate optics with the examined defocus value
		[oiEnsemble, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
        			oiPositionDegs, ...
			       'zernikeDataBase', opticsParams.ZernikeDataBase, ...
			       'subjectID', opticsParams.subjectID, ...
			       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
			       'refractiveErrorDiopters', defocusValue, ...
			       'noLCA', opticsParams.noLCA, ...
			       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
			       'subtractCentralRefraction', false, ...
			       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
			       'upsampleFactor', psfUpsampleFactor, ...
			       'warningInsteadOfErrorForBadZernikeCoeffs', false);
		theCurrentPSF = psfEnsemble{1,1};
		peakCurrentPSFAmplitude = RGCMosaicConstructor.helper.optics.analyzePSF(theCurrentPSF, targetInFocusWavelengthIndex);
		StrehlRatio(iRefractiveError) = peakCurrentPSFAmplitude/peakDiffractionLimitedPSFAmplitude;

		if (visualizeStrehlRatioOptimization)
			hFig = figure(1000);
			set(hFig, 'Position', [10 10 1200 1200]);
			ax = subplot(2,2,1);
			RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, theDiffractionLimitedPSF, wavelengthIndexOfPeakDiffractionLimitedPSFamplitude, ...
				peakDiffractionLimitedPSFAmplitude, ...
						sprintf('diffraction-limited PSF\npeak: %f at %d nm (in-focus wavelength)', peakDiffractionLimitedPSFAmplitude, targetInFocusWavelength));

			ax = subplot(2,2,2);
			RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, theCentralCorrectionPSF, wavelengthIndexOfPeakCentralCorrectionPSFamplitude, ...
				peakCentralCorrectionPSFAmplitude, ...
				sprintf('central refraction corrected PSF\npeak: %f at %d nm (peak wavelength)', peakCentralCorrectionPSFAmplitude, wavelengthOfPeakCentralCorrectionPSFamplitude));

			ax = subplot(2,2,3);
			RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, theCurrentPSF, targetInFocusWavelengthIndex, ...
				peakCurrentPSFAmplitude, ...
				sprintf('current defocus: (%2.2fD) PSF \npeak: %f at %d nm (in-focus wavelength)', examinedRefractionErrorDiopters(iRefractiveError), peakCurrentPSFAmplitude, targetInFocusWavelength));
					
			ax = subplot(2,2,4);
			plot(ax,examinedRefractionErrorDiopters, StrehlRatio, 'ro-', 'MarkerSize', 12, 'MarkerFaceColor', [1 0.5 0.5]);
			xlabel('defocus (D)');
            ylabel(sprintf('Strehl ratio at %d nm (in-focus wavelength)', targetInFocusWavelength));
            axis 'square'
			colormap(brewermap(1024, '*greys'));
			drawnow;
		end % if (visualizeStrehlRatioOptimization)
	end % for iRefractiveError

	% Find the refraction that maximized the Strehl ratio at the wavelength where the diffraction-limited PSF reaches its peak (550)
	[theOptimalStrehlRatio, iRefractiveError] = max(StrehlRatio);
	theOptimalStrehlRatioDefocusDiopters = examinedRefractionErrorDiopters(iRefractiveError);


	% Generate the optimal Strehl ratio optics
	[oiEnsemble, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
		oiPositionDegs, ...
       'zernikeDataBase', opticsParams.ZernikeDataBase, ...
       'subjectID', opticsParams.subjectID, ...
       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
       'refractiveErrorDiopters', theOptimalStrehlRatioDefocusDiopters, ...
       'noLCA', opticsParams.noLCA, ...
       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
       'subtractCentralRefraction', false, ...
       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
       'upsampleFactor', psfUpsampleFactor, ...
       'warningInsteadOfErrorForBadZernikeCoeffs', false);

	% This is it.
	theOptimalStrehlRatioOI = oiEnsemble{1,1}; 
	theOptimalStrehlRatioPSF = psfEnsemble{1,1};
	
	if (contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection)
		[oiEnsemble, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
        			oiPositionDegs, ...
			       'zernikeDataBase', opticsParams.ZernikeDataBase, ...
			       'subjectID', opticsParams.subjectID, ...
			       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
			       'refractiveErrorDiopters', 0.0, ...
			       'noLCA', opticsParams.noLCA, ...
			       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
			       'subtractCentralRefraction', false, ...
			       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
			       'upsampleFactor', psfUpsampleFactor, ...
			       'warningInsteadOfErrorForBadZernikeCoeffs', false);
		theOIasMeasured = oiEnsemble{1,1}; 
		thePSFasMeasured = psfEnsemble{1,1};
		

		hFig = figure(2000);
		clf;
		set(hFig, 'Position', [10 10 1970 500]);

		XLimsArcMin = 5*[-1 1];
		YLimsArcMin = 5*[-1 1];
		XTicksArcMin = [-5:1:5];
		YTicksArcMin = [-5:1:5];
		
		colormap(brewermap(1024, '*greys'));

		% The diffraction-limited PSF at the target in-focus wavelength
		ax = subplot(1,4,1);
		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, theDiffractionLimitedPSF, targetInFocusWavelengthIndex, ...
			peakDiffractionLimitedPSFAmplitude, ...
			sprintf('diffraction limited PSF\npeak: %d at \n%d nm (in-focus wavelength)', peakDiffractionLimitedPSFAmplitude, targetInFocusWavelength), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax, brewermap(1024, '*greys'));
		
		% The optimal Strehl ratio PSF at the target in-focus wavelength
		ax = subplot(1,4,2);
		peakOptimalStrehlRatioPSFAmplitude = RGCMosaicConstructor.helper.optics.analyzePSF(theOptimalStrehlRatioPSF, targetInFocusWavelengthIndex);
		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, theOptimalStrehlRatioPSF, targetInFocusWavelengthIndex, ...
			peakOptimalStrehlRatioPSFAmplitude,  ...
			sprintf('(%2.1f,%2.1f) degs PSF \n with optimal Strehl ratio (%2.3f)\npeak: %f at \n%d nm (in-focus wavelength))', ...
				oiPositionDegs(1), oiPositionDegs(2), peakOptimalStrehlRatioPSFAmplitude/ peakDiffractionLimitedPSFAmplitude, peakOptimalStrehlRatioPSFAmplitude, targetInFocusWavelength), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax, brewermap(1024, '*greys'));

		% The PSF as measured
		[peakPSFasMeasuredAmplitude, wavelengthIndexOfPeakPSFasMeasuredAmplitude, ...
	    wavelengthOfPeakPSFasMeasuredAmplitude] = RGCMosaicConstructor.helper.optics.analyzePSF(thePSFasMeasured, []);
		ax = subplot(1,4,3);
		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, thePSFasMeasured, wavelengthIndexOfPeakPSFasMeasuredAmplitude, ...
			peakPSFasMeasuredAmplitude, ...
			sprintf('(%2.1f,%2.1f) PSF as measured\npeak: %f \nat %d nm', oiPositionDegs(1), oiPositionDegs(2), peakPSFasMeasuredAmplitude, wavelengthOfPeakPSFasMeasuredAmplitude), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax, brewermap(1024, '*greys'));

		ax = subplot(1,4,4);
		peakCentralCorrectionPSFAmplitude = RGCMosaicConstructor.helper.optics.analyzePSF(theCentralCorrectionPSF, targetInFocusWavelengthIndex);
		StrehlRatioForCentralCorrection = peakCentralCorrectionPSFAmplitude/peakDiffractionLimitedPSFAmplitude;

		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax, theCentralCorrectionPSF, targetInFocusWavelengthIndex, ...
			peakCentralCorrectionPSFAmplitude, ...
			sprintf('(%2.1f,%2.1f) PSF \n(with central refraction (0,0) correction)\nStrehl ratio: %2.3f\npeak %f \nat %d nm',  oiPositionDegs(1), oiPositionDegs(2), StrehlRatioForCentralCorrection, peakCentralCorrectionPSFAmplitude, targetInFocusWavelength), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax, brewermap(1024, '*greys'));
		drawnow;	
		pause
	end

end
