function eccMMs = rhoDegsToMMs(eccDegs)
% Convert retinal distance in degs to retinal distance in mm 
% (Equation A5)
    absEccDegs = abs(eccDegs);
    eccMMs = sign(eccDegs) .* ...
        (...
                0.268         * absEccDegs ...
              + 0.0003427     * absEccDegs .^2 ...
              - 8.3309 * 1e-6 * absEccDegs .^3 ...
        );
end
