function testMidgetRGCmosaic

    computeMosaics = ~true;

    if (~computeMosaics)
        load('midgetRGCs.mat', 'm60_neg25degs', 'm60_pos25degs', 'm58_neg25degs', 'm58_pos25degs');

        m60_neg25degs.inputConeMosaic.horizontalRetinalMeridian
        neg25degsConesNum = numel(m60_neg25degs.inputConeMosaic.coneTypes)
        neg25degsRGCsnum = numel(m60_neg25degs.rgcRFspacingsMicrons)
        
        m60_pos25degs.inputConeMosaic.horizontalRetinalMeridian
        pos25degsConesNum = numel(m60_pos25degs.inputConeMosaic.coneTypes)
        pos25degsRGCsnum = numel(m60_pos25degs.rgcRFspacingsMicrons)

        return;
    end

    m58_pos25degs = midgetRGCMosaic(...
        'sourceLatticeSizeDegs', 58, ...
        'eccentricityDegs', [25 0], ...
        'sizeDegs', [2 2] ...
        );

    m58_neg25degs = midgetRGCMosaic(...
        'sourceLatticeSizeDegs', 58, ...
        'eccentricityDegs', [-25 0], ...
        'sizeDegs', [2 2] ...
        );

    m60_pos25degs = midgetRGCMosaic(...
        'sourceLatticeSizeDegs', 60, ...
        'eccentricityDegs', [25 0], ...
        'sizeDegs', [2 2] ...
        );

    m60_neg25degs = midgetRGCMosaic(...
        'sourceLatticeSizeDegs', 60, ...
        'eccentricityDegs', [-25 0], ...
        'sizeDegs', [2 2] ...
        );

    save('midgetRGCs.mat', 'm60_neg25degs', 'm60_pos25degs', 'm58_neg25degs', 'm58_pos25degs', '-v7.3');
end
