function [mosaicsFilename, opticsFilename, opticsPostFix] = mosaicsAndOpticsFileName(runParams)
    mosaicsFilename = sprintf('MosaicsForEccentricity_%2.0f_%2.0f_%2.0f_%2.0f_microns_coneSpecificity_%2.0f_orphanPolicy_%s.mat', ...
        runParams.rgcMosaicPatchEccMicrons(1), runParams.rgcMosaicPatchEccMicrons(2), ...
        runParams.rgcMosaicPatchSizeMicrons(1), runParams.rgcMosaicPatchSizeMicrons(2), ...
        runParams.maximizeConeSpecificity, runParams.orphanRGCpolicy);
    
    if ((runParams.noLCA == false) && (runParams.noOptics == false))
        opticsPostFix = 'normalOptics';
    elseif ((runParams.noLCA == true) && (runParams.noOptics == false))
        opticsPostFix = 'noLCAOptics';
    else
        opticsPostFix = 'noBlurOptics';
    end
    
    opticsFilename = sprintf('OpticsForEccentricity_%2.0f_%2.0f_%2.0f_%2.0f_microns_PolansSID_%d_%s.mat', ...
        runParams.rgcMosaicPatchEccMicrons(1), runParams.rgcMosaicPatchEccMicrons(2), ...
        runParams.rgcMosaicPatchSizeMicrons(1), runParams.rgcMosaicPatchSizeMicrons(2), ...
        runParams.PolansSubjectID, opticsPostFix);
end
