function fname = nullResponseFilename(runParams, opticsPostFix)
    fname = sprintf('NullResponses_%2.0f_%2.0f_%2.0f_%2.0f_%s.mat', ...
            runParams.rgcMosaicPatchEccMicrons(1), runParams.rgcMosaicPatchEccMicrons(2), ...
            runParams.rgcMosaicPatchSizeMicrons(1), runParams.rgcMosaicPatchSizeMicrons(2), ...
            opticsPostFix);
end

