 function fname = testResponseFilename(runParams, testLMScontrast, opticsPostFix)
    fname = sprintf('L_%2.2f_M_%2.2f_S_%2.2fResponses_%2.0f_%2.0f_%2.0f_%2.0f_%s.mat', ...
            testLMScontrast(1), testLMScontrast(2), testLMScontrast(3), ...
            runParams.rgcMosaicPatchEccMicrons(1), runParams.rgcMosaicPatchEccMicrons(2), ...
            runParams.rgcMosaicPatchSizeMicrons(1), runParams.rgcMosaicPatchSizeMicrons(2), ...
            opticsPostFix);
end