function [midgetRGCconnectionMatrix, RGCRFPositionsMicrons, RGCRFSpacingsMicrons] = ...
    computeConnectionMatrix(RGCRFPositionsMicrons, conePositionsMicrons, ...
    RGCRFSpacingsMicrons, coneSpacingsMicrons, ...
    coneTypes, desiredConesToRGCratios,  orphanRGCpolicy, visualizeProcess)
        
    % Step1. Align each RGC with its nearest cone. This ensure all RGC's
    % are connected to at least one cone. Since cones are more numerous
    % than RGCs some cones will not connect to an RGC at this step. This 
    % step occurs only for RGCs for which the cone-to-RGC ratio is [1..2]
    
    RGCRFPositionsMicrons = alignRGCmosaicToConeMosaic(...
        conePositionsMicrons, coneSpacingsMicrons, ...
        RGCRFPositionsMicrons, RGCRFSpacingsMicrons, ...
        coneTypes, desiredConesToRGCratios, visualizeProcess);
    

    % Step 2. Connect L and M cones to midget RGC centers.
    [midgetRGCconnectionMatrix, RGCRFPositionsMicrons, RGCRFSpacingsMicrons] = connectConesToMidgetRGCRFcenters(conePositionsMicrons, coneSpacingsMicrons, ...
        RGCRFPositionsMicrons, RGCRFSpacingsMicrons, ...
        orphanRGCpolicy, coneTypes, desiredConesToRGCratios, visualizeProcess);
end