function [connectionMatrix, conePositionsMicrons, RGCRFPositionsMicrons] = ...
    computeConnectionMatrix(RGCRFPositionsMicrons, conePositionsMicrons, ...
    RGCRFSpacingsMicrons, coneSpacingsMicrons, ...
    desiredConesToRGCratios, orphanRGCpolicy, visualizeProcess)

    
    % Step1. Align each RGC with its nearest cone. This ensure all RGC's
    % are connected to at least one cone. Since cones are more numerous
    % than RGCs some cones will not connect to an RGC at this step. This 
    % step occurs only for RGCs for which the cone-to-RGC ratio is [1..2]
    
    RGCRFPositionsMicrons = alignRGCmosaicToConeMosaic(...
        conePositionsMicrons, coneSpacingsMicrons, ...
        RGCRFPositionsMicrons, RGCRFSpacingsMicrons, ...
        desiredConesToRGCratios, visualizeProcess);
    
    % Step 2. Connect cones to RGCs.
    [connectionMatrix, RGCRFPositionsMicrons] = connectConesToRGC(conePositionsMicrons, coneSpacingsMicrons, ...
        RGCRFPositionsMicrons, RGCRFSpacingsMicrons, ...
        orphanRGCpolicy, desiredConesToRGCratios, visualizeProcess);
end