function paramsForBatchProcessing(app, exportFileName, exportedDataSelection)
    params = struct(...
        'roiParams', app.roiParams, ...
        'coneMosaicParams', app.coneMosaicParams, ...
        'opticsParams', app.opticsParams, ...
        'stimParams', app.stimParams, ...
        'psychometricFunctionParams', app.psychometricFunctionParams, ...
        'csfParams', app.csfParams);
    
    save( exportFileName, 'params');
end
