function visualizeHexLatticeQuality(histogramData, minQualityValue)
    plotlabOBJ = plotlab();
    plotlabOBJ.applyRecipe(...
            'colorOrder', [0.1 0.1 0.1; 1 0 0; 0 0 1], ...
            'axesBox', 'off', ...
            'axesTickLength', [0.01 0.01], ...
            'legendLocation', 'SouthWest', ...
            'figureWidthInches', 9, ...
            'figureHeightInches', 9);
        
    hFig = figure(2);
    bar(histogramData.x, histogramData.y, 'r'); hold on;
    plot(minQualityValue*[1 1], [0 max(histogramData.y)]);
    
end

