function paramsStruct = paramsVectorToParamsStruct(paramsVector, retinalConePoolingModel)

    switch (retinalConePoolingModel)
        case 'GaussianCenterGaussianSurroundBased'
            paramsStruct = struct(...
                'Kc', paramsVector(1), ...
                'RcDegs', paramsVector(2), ...
                'surroundToCenterRcRatio', paramsVector(3), ...
                'surroundToCenterIntegratedRatio', paramsVector(4));
            
        case 'GaussianCenterDoubleExponentSurroundBased'
            paramsStruct = struct(...
                'Kc', paramsVector(1), ...
                'RcDegs', paramsVector(2), ...
                'KsToKcPeakRatio', paramsVector(3), ...
                'narrowToWideVolumeRatio', paramsVector(4), ...
                'RwideDegs', paramsVector(5), ...
                'RnarrowToRwideRatio', paramsVector(6));

        otherwise
            error('Unknown retinalConePoolingModel: ''%s''.', retinalConePoolingModel);
    end

end
