function dataFileName = computedObjectDataFileName(opticsParams, targetVisualDoGparams)
    s1 = sprintf('%s_Rank_%d_Pupil_%1.1f', ...
                    opticsParams.ZernikeDataBase, opticsParams.examinedSubjectRankOrder, opticsParams.pupilDiameterMM);
    s2 = sprintf('RFecc_%2.1f_%2.1f', ...
                    opticsParams.positionDegs(1), opticsParams.positionDegs(2));
    s3 = sprintf('RFcenterCones_%d_RsRcRatio_%1.2f_SCratio_%1.2f', ...
                    targetVisualDoGparams.conesNumPooledByTheRFcenter, ...
                    targetVisualDoGparams.surroundToCenterRcRatio, ...
                    targetVisualDoGparams.surroundToCenterIntegratedSensitivityRatio);
    s4 = sprintf('VisualRFmodel_%s', strrep(strrep(targetVisualDoGparams.visualRFmodel, ' ', ''),',', '_'));
    s5 = sprintf('RetinalPoolingModel_%s', strrep(strrep(targetVisualDoGparams.retinalConePoolingModel, ' ', ''),',', '_'));
    dataFileName = sprintf('RVT_%s_%s_%s_%s_%s.mat', s1,s2,s3,s4,s5);
end