function [DoGparams, theFittedSTF] = fitDoGmodelToMeasuredSTF(...
    sfCPD, theMeasuredSTF, RcDegsInitialEstimate, multiStartsNum, varargin)

    p = inputParser;
    p.addParameter('rangeForRc', [], @(x)(isempty(x)||(numel(x)==3)));
    p.parse(varargin{:});
    rangeForRc = p.Results.rangeForRc;

    % DoG param initial values and limits: center gain, kc
    Kc = struct(...    
        'low', 1, ...
        'high', 1e6, ...
        'initial', 1);

    % DoG param initial values and limits: Ks/Kc ratio
    KsToKc = struct(...
        'low', 1e-6, ...
        'high', 1.0, ...
        'initial', 0.1);

    % DoG param initial values and limits: RsToRc ratio
    RsToRc = struct(...
        'low', 1.5, ...
        'high', 30, ...
        'initial', 5);

    % DoG param initial values and limits: RcDegs
    if (~isempty(rangeForRc))
            RcDegs = struct(...
                'low', rangeForRc(1), ...
                'high', rangeForRc(3), ...
            'initial', rangeForRc(2));
    else
            RcDegs = struct(...
                'low', RcDegsInitialEstimate/sqrt(2.0), ...
                'high', RcDegsInitialEstimate*200, ...
            'initial', RcDegsInitialEstimate*5);
    end

     %                          Kc           kS/kC             RsToRc            RcDegs    
     DoGparams.initialValues = [Kc.initial   KsToKc.initial    RsToRc.initial    RcDegs.initial];
     DoGparams.lowerBounds   = [Kc.low       KsToKc.low        RsToRc.low        RcDegs.low];
     DoGparams.upperBounds   = [Kc.high      KsToKc.high       RsToRc.high       RcDegs.high];
     DoGparams.names         = {'Kc',        'kS/kC',         'RsToRc',         'RcDegs'};
     DoGparams.scaling       = {'log',       'log',           'linear',         'linear'};
     
     % The DoG model in the frequency domain
     DoGSTF = @(params,sfCPD)(...
                    abs(params(1)       * ( pi * params(4)^2             * exp(-(pi*params(4)*sfCPD).^2) ) - ...
                    params(1)*params(2) * ( pi * (params(4)*params(3))^2 * exp(-(pi*params(4)*params(3)*sfCPD).^2) )));
        
     % The optimization objective
     objective = @(p) sum((DoGSTF(p, sfCPD) - theMeasuredSTF).^2);

     % Ready to fit
     options = optimset(...
            'Display', 'off', ...
            'Algorithm', 'interior-point',... % 'sqp', ... % 'interior-point',...
            'GradObj', 'off', ...
            'DerivativeCheck', 'off', ...
            'MaxFunEvals', 10^5, ...
            'MaxIter', 10^3);
        
     % Multi-start
     problem = createOptimProblem('fmincon',...
          'objective', objective, ...
          'x0', DoGparams.initialValues, ...
          'lb', DoGparams.lowerBounds, ...
          'ub', DoGparams.upperBounds, ...
          'options', options...
          );
      
     ms = MultiStart(...
          'Display', 'off', ...
          'StartPointsToRun','bounds-ineqs', ...  % run only initial points that are feasible with respect to bounds and inequality constraints.
          'UseParallel', true);
      
     % Run the multi-start
     DoGparams.finalValues = run(ms, problem, multiStartsNum);

     theFittedSTF.compositeSTF = DoGSTF(DoGparams.finalValues, sfCPD);
     theFittedSTF.centerSTF = DoGparams.finalValues(1) * ( pi * DoGparams.finalValues(4)^2 * exp(-(pi*DoGparams.finalValues(4)*sfCPD).^2) );
     theFittedSTF.surroundSTF = DoGparams.finalValues(1)*DoGparams.finalValues(2) * ( pi * (DoGparams.finalValues(4)*DoGparams.finalValues(3))^2 * exp(-(pi*DoGparams.finalValues(4)*DoGparams.finalValues(3)*sfCPD).^2) );
     
     sfHiRes = logspace(log10(0.1), log10(100), 64);
     theFittedSTF.sfHiRes = sfHiRes;
     theFittedSTF.compositeSTFHiRes = DoGSTF(DoGparams.finalValues, sfHiRes);
     theFittedSTF.centerSTFHiRes = DoGparams.finalValues(1) * ( pi * DoGparams.finalValues(4)^2 * exp(-(pi*DoGparams.finalValues(4)*sfHiRes).^2) );
     theFittedSTF.surroundSTFHiRes = DoGparams.finalValues(1)*DoGparams.finalValues(2) * ( pi * (DoGparams.finalValues(4)*DoGparams.finalValues(3))^2 * exp(-(pi*DoGparams.finalValues(4)*DoGparams.finalValues(3)*sfHiRes).^2) );
end