function paramsVector = paramsStructToParamsVector(paramsStruct, retinalConePoolingModel)

    switch (retinalConePoolingModel)
        case 'GaussianCenterGaussianSurroundBased'
            if (isfield(paramsStruct, 'flatTopGaussianExponent'))
                if (isfield(paramsStruct, 'rotationDegs'))
                    paramsVector = [...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.surroundToCenterRcRatio ...
                        paramsStruct.surroundToCenterIntegratedRatio  ...
                        paramsStruct.flatTopGaussianExponent ...
                        paramsStruct.rotationDegs];
                else
                    paramsVector = [...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.surroundToCenterRcRatio ...
                        paramsStruct.surroundToCenterIntegratedRatio ...
                        paramsStruct.flatTopGaussianExponent];
                end
            else
                if (isfield(paramsStruct, 'rotationDegs'))
                    paramsVector = [...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.surroundToCenterRcRatio ...
                        paramsStruct.surroundToCenterIntegratedRatio  ...
                        paramsStruct.rotationDegs];
                else
                    paramsVector = [...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.surroundToCenterRcRatio ...
                        paramsStruct.surroundToCenterIntegratedRatio];
                end
            end


        case 'GaussianCenterDoubleExponentSurroundBased'
            if (isfield(paramsStruct, 'flatTopGaussianExponent'))
                if (isfield(paramsStruct, 'rotationDegs'))
                    paramsVector = [ ...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.KsToKcPeakRatio ...
                        paramsStruct.narrowToWideVolumeRatio ...
                        paramsStruct.RwideDegs ...
                        paramsStruct.RnarrowToRwideRatio ...
                        paramsStruct.flatTopGaussianExponent ...
                        paramsStruct.rotationDegs];
                else
                    paramsVector = [ ...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.KsToKcPeakRatio ...
                        paramsStruct.narrowToWideVolumeRatio ...
                        paramsStruct.RwideDegs ...
                        paramsStruct.RnarrowToRwideRatio ...
                        paramsStruct.flatTopGaussianExponent];
                end
            else
                if (isfield(paramsStruct, 'rotationDegs'))
                    paramsVector = [ ...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.KsToKcPeakRatio ...
                        paramsStruct.narrowToWideVolumeRatio ...
                        paramsStruct.RwideDegs ...
                        paramsStruct.RnarrowToRwideRatio ...
                        paramsStruct.rotationDegs];
                else
                    paramsVector = [ ...
                        paramsStruct.Kc ...
                        paramsStruct.RcDegs ...
                        paramsStruct.KsToKcPeakRatio ...
                        paramsStruct.narrowToWideVolumeRatio ...
                        paramsStruct.RwideDegs ...
                        paramsStruct.RnarrowToRwideRatio];
                end
            end


        otherwise
            error('Unknown retinalConePoolingModel: ''%s''.', retinalConePoolingModel);
    end

end
