function paramsStruct = paramsVectorToParamsStruct(paramsVector, retinalConePoolingModel)

    switch (retinalConePoolingModel)
        case 'GaussianCenterGaussianSurroundBased'

            switch (numel(paramsVector))
                case 4
                     paramsStruct = struct(...
                        'Kc', paramsVector(1), ...
                        'RcDegs', paramsVector(2), ...
                        'surroundToCenterRcRatio', paramsVector(3), ...
                        'surroundToCenterIntegratedRatio', paramsVector(4));
                case 5 
                    paramsStruct = struct(...
                        'Kc', paramsVector(1), ...
                        'RcDegs', paramsVector(2), ...
                        'surroundToCenterRcRatio', paramsVector(3), ...
                        'surroundToCenterIntegratedRatio', paramsVector(4), ...
                        'flatTopGaussianExponent', paramsVector(5));
                case 6
                    paramsStruct = struct(...
                        'Kc', paramsVector(1), ...
                        'RcDegs', paramsVector(2), ...
                        'surroundToCenterRcRatio', paramsVector(3), ...
                        'surroundToCenterIntegratedRatio', paramsVector(4), ...
                        'flatTopGaussianExponent', paramsVector(5), ...
                        'rotationDegs', paramsVector(6));
                otherwise
                    error('paramsVector must have 4, 5, or 6 entries');
            end
            
        case 'GaussianCenterDoubleExponentSurroundBased'

            switch (numel(paramsVector))
                case 6
                    paramsStruct = struct(...
                        'Kc', paramsVector(1), ...
                        'RcDegs', paramsVector(2), ...
                        'KsToKcPeakRatio', paramsVector(3), ...
                        'narrowToWideVolumeRatio', paramsVector(4), ...
                        'RwideDegs', paramsVector(5), ...
                        'RnarrowToRwideRatio', paramsVector(6));

                case 7 
                    paramsStruct = struct(...
                        'Kc', paramsVector(1), ...
                        'RcDegs', paramsVector(2), ...
                        'KsToKcPeakRatio', paramsVector(3), ...
                        'narrowToWideVolumeRatio', paramsVector(4), ...
                        'RwideDegs', paramsVector(5), ...
                        'RnarrowToRwideRatio', paramsVector(6), ...
                        'flatTopGaussianExponent', paramsVector(7));
                case 8
                    paramsStruct = struct(...
                        'Kc', paramsVector(1), ...
                        'RcDegs', paramsVector(2), ...
                        'KsToKcPeakRatio', paramsVector(3), ...
                        'narrowToWideVolumeRatio', paramsVector(4), ...
                        'RwideDegs', paramsVector(5), ...
                        'RnarrowToRwideRatio', paramsVector(6), ...
                        'flatTopGaussianExponent', params(7), ...
                        'rotationDegs', paramsVector(8));
                otherwise
                    error('paramsVector must have 6, 7, or 8 entries');
            end

            

        otherwise
            error('Unknown retinalConePoolingModel: ''%s''.', retinalConePoolingModel);
    end

end
