function paramsVector = paramsStructToParamsVector(paramsStruct, retinalConePoolingModel)

    switch (retinalConePoolingModel)
        case 'GaussianCenterGaussianSurroundBased'
            paramsVector = [...
                paramsStruct.Kc ...
                paramsStruct.RcDegs ...
                paramsStruct.surroundToCenterRcRatio ...
                paramsStruct.surroundToCenterIntegratedRatio ...
                ];
        case 'GaussianCenterDoubleExponentSurroundBased'
            paramsVector = [ ...
                paramsStruct.Kc ...
                paramsStruct.RcDegs ...
                paramsStruct.KsToKcPeakRatio ...
                paramsStruct.narrowToWideVolumeRatio ...
                paramsStruct.RwideDegs ...
                paramsStruct.RnarrowToRwideRatio ...
                ];

        otherwise
            error('Unknown retinalConePoolingModel: ''%s''.', retinalConePoolingModel);
    end

end
