function vLambdaWeightedPSFandOTF(obj)

    [obj.thePSFData, ...
     obj.testSubjectID, ...
     obj.subtractCentralRefraction ...
     ] = RetinaToVisualFieldTransformer.computeVlambdaWeightedPSF(obj.opticsParams, obj.theConeMosaic, obj.psfWavelengthSupport);
end


