function vLambdaWeightedPSFandOTF(obj)

    [obj.thePSFData, ...
     obj.testSubjectID, ...
     obj.subtractCentralRefraction, ...
     obj.theOI] = RetinaToVisualFieldTransformer.computeVlambdaWeightedPSF(...
            obj.opticsParams, ...
            obj.theConeMosaic, ...
            obj.psfWavelengthSupport);
end


