function vLambdaWeightedPSFandOTF(obj)

    [obj.theVlambdaWeightedPSFData, ...
     obj.testSubjectID, ...
     obj.subtractCentralRefraction, ...
     obj.opticsParams] = RetinaToVisualFieldTransformer.computeVlambdaWeightedPSF(...
            obj.opticsParams, ...
            obj.theConeMosaic, ...
            obj.psfWavelengthSupport);
end


