function generateRFpositionsAndWireTheirCenters(obj, pResults)

    % Generate sourceLatticeStruct for the @coneToMidgetRGCConnector
    metaDataStruct.coneTypes = obj.inputConeMosaic.coneTypes;
    metaDataStruct.coneTypeIDs = [obj.inputConeMosaic.LCONE_ID    obj.inputConeMosaic.MCONE_ID    obj.inputConeMosaic.SCONE_ID];
    metaDataStruct.coneColors  = [obj.inputConeMosaic.lConeColor; obj.inputConeMosaic.mConeColor; obj.inputConeMosaic.sConeColor];
    metaDataStruct.midgetRGCSurroundRadiusMicronsAtMaxEccentricityGivenOptics = ...
        1e3 * obj.inputConeMosaic.customDegsToMMsConversionFunction(obj.extraDegsForInputConeMosaic/2);


    % Source lattice (i.e. cone mosaic lattice) struct
    sourceLatticeStruct = struct(...
        'name', 'cone RFs', ...
        'DegsToMMsConversionFunction', obj.inputConeMosaic.customDegsToMMsConversionFunction, ...
        'MMsToDegsConversionFunction', obj.inputConeMosaic.customMMsToDegsConversionFunction, ...
        'RFpositionsMicrons', obj.inputConeMosaic.coneRFpositionsMicrons, ...
        'metaData', metaDataStruct ...
    );


    % Import mRGC RF positions (destination) 
    mRGCRFposMicrons = retinalattice.import.finalMRGCPositions(...
         obj.sourceLatticeSizeDegs, ...
         mean(sourceLatticeStruct.RFpositionsMicrons,1), ... 
         max(max(sourceLatticeStruct.RFpositionsMicrons,[], 1)-min(sourceLatticeStruct.RFpositionsMicrons,[], 1)), ...
         obj.whichEye, ...
         obj.inputConeMosaic.customDegsToMMsConversionFunction);

    % Generate the destination lattice struct
    destinationLatticeStruct = struct(...
        'name', 'mRGC RFs', ...
        'DegsToMMsConversionFunction', obj.inputConeMosaic.customDegsToMMsConversionFunction, ...
        'MMsToDegsConversionFunction', obj.inputConeMosaic.customMMsToDegsConversionFunction, ...
        'RFpositionsMicrons', mRGCRFposMicrons ...
        );


    % Cone indices to be connected
    coneIndicesToBeConnected = [...
        obj.inputConeMosaic.lConeIndices(:); ...
        obj.inputConeMosaic.mConeIndices(:)];

    % Connect the source and destination lattices
    obj.theMosaicConnectorOBJ = coneToMidgetRGCConnector(...
        sourceLatticeStruct, destinationLatticeStruct, ...
        'optimizationCenter', 'origin', ...
        'maxMeanConeInputsPerRGCToConsiderSwappingWithNearbyRGCs', pResults.maxMeanConeInputsPerRGCToConsiderSwappingWithNearbyRGCs, ...
        'maxConeInputsPerRGCToConsiderTransferToNearbyRGCs', pResults.maxConeInputsPerRGCToConsiderTransferToNearbyRGCs, ...
        'chromaticSpatialVarianceTradeoff', obj.chromaticSpatialVarianceTradeoff, ...
        'coneIndicesToBeConnected', coneIndicesToBeConnected, ...
        'saveIntermediateConnectivityStagesMetaData', pResults.saveIntermediateStagesOfCenterConnectivityOptimization, ...
        'visualizeConnectivityAtIntermediateStages', pResults.visualizeIntermediateStagesOfCenterConnectivityOptimization, ...
        'generateProgressVideo', ~true);

    % Save the intermediate metaData structs
    obj.intermediateMetaDataStructs = obj.theMosaicConnectorOBJ.intermediateMetaDataStructs;

    % Save the intermediate figure handles
    obj.mosaicConnectorIntermediateFigureHandles = obj.theMosaicConnectorOBJ.intermediateFigureHandles;

    % Set the rf center connectivity matrix
    obj.rgcRFcenterConeConnectivityMatrix = obj.theMosaicConnectorOBJ.connectivityMatrix;
                
    % Set the rf positions, in microns
    obj.rgcRFpositionsMicrons = obj.theMosaicConnectorOBJ.destinationRFcentroidsFromInputs;

    % Set the rf spacings, in microns
    obj.rgcRFspacingsMicrons = obj.theMosaicConnectorOBJ.destinationRFspacingsFromCentroids;
   
    % Set the rf positions in degrees
    obj.rgcRFpositionsDegs = obj.inputConeMosaic.customMMsToDegsConversionFunction(obj.rgcRFpositionsMicrons/1000);
    
    % Set the rf spacings in degrees
    RFeccentricityMicrons = sqrt(sum((obj.rgcRFpositionsMicrons).^2,2));
    obj.rgcRFspacingsDegs = obj.inputConeMosaic.sizeMicronsToSizeDegreesForCmosaic(obj.rgcRFspacingsMicrons, RFeccentricityMicrons');

end