function  [mosaicCenterParams, ...
     mosaicSurroundParams, ...
     opticsParams] = generateMosaicAndOpticsParamStructs()

    
    mosaicCenterParams = struct(...
        'positionDegs',[0 0], ...
        'sizeDegs',  [3 3], ...        
        'whichEye', 'right eye');

    H1cellIndex = 1;
    mosaicSurroundParams = struct(...
                'eccentricitySamplingGridHalfSamplesNum', 1, ...                         % generate R2VFTobjects at 2*gridHalfSamplesNum + 1 spatial positions
                'centerConnectableConeTypes', [cMosaic.LCONE_ID cMosaic.MCONE_ID], ...   % cone types that can connect to the RF center
                'surroundConnectableConeTypes', [cMosaic.LCONE_ID cMosaic.MCONE_ID], ... % cone types that can connect to the RF surround
                'coneWeightsCompensateForVariationsInConeEfficiency', true, ...          % cone weight compensationfor eccentricity-dependent variations in cone efficiency
                'visualRFmodel', 'gaussian center, gaussian surround', ...
                'retinalConePoolingModel', sprintf('arbitrary center cone weights, double exponential surround from H1 cell with index %d', H1cellIndex),...
                'H1cellIndex', H1cellIndex, ...
                'targetSTFmatchMode', 'STFDoGparams' ...
            );
        
    opticsParams = struct(...
                'ZernikeDataBase', 'Polans2015', ...
                'subjectRankOrder', 6, ...
                'pupilDiameterMM', 3.0 ...
            );
end
