function peekIntoRTVFobj(theRTVFTobj, iRTVobjIndex, ...
    theSamplingPositionGrid, theConesNumPooledByTheRFcenterGrid, figNo)

    iRTVobjIndexDoesNotCorrespondToFullList = false;
    if (iRTVobjIndex < 0)
        iRTVobjIndex = -iRTVobjIndex;
        iRTVobjIndexDoesNotCorrespondToFullList = true;
    end

    % Target and achieved ratios
    targetRsRcRatio = theRTVFTobj.targetVisualRFDoGparams.surroundToCenterRcRatio;
    targetSCintSensRatio = theRTVFTobj.targetVisualRFDoGparams.surroundToCenterIntegratedSensitivityRatio;
    theRTVFTobj.rfComputeStruct.theSTF
    fittedRsRcRatio = theRTVFTobj.rfComputeStruct.theSTF.fittedRsRcRatio;
    fittedSCintSensRatio = theRTVFTobj.rfComputeStruct.theSTF.fittedSCIntSensRatio;
    targetKsKcRatio = targetSCintSensRatio / (targetRsRcRatio^2);
    fittedKsKcRatio = fittedSCintSensRatio / (fittedRsRcRatio^2);
    

    fprintf('RTVFobj at position (degs): %2.2f %2.2f with %d center cones\n', ...
        theSamplingPositionGrid(iRTVobjIndex,1), theSamplingPositionGrid(iRTVobjIndex,2), theConesNumPooledByTheRFcenterGrid(iRTVobjIndex));
    fprintf('Target Rs/Rc ratio: %2.2f, achieved: %2.2f\n', targetRsRcRatio, fittedRsRcRatio);
    fprintf('Target S/C int. sens. ratio: %2.3f, achieved: %2.3f\n', targetSCintSensRatio, fittedSCintSensRatio);


    figureName = sprintf('RTVF obj %d located at position (degs): %2.2f, %2.2f with %d center cones', ...
                         iRTVobjIndex, ...
                         theSamplingPositionGrid(iRTVobjIndex,1), ...
                         theSamplingPositionGrid(iRTVobjIndex,2), ...
                         theConesNumPooledByTheRFcenterGrid(iRTVobjIndex));

    RetinaToVisualFieldTransformer.performCronerKaplanSimulation(...
                theRTVFTobj.rfComputeStruct.theFittedVisualRFMap, ...
                theRTVFTobj.rfComputeStruct.theRetinalRFcenterConeMap, ...
                theRTVFTobj.rfComputeStruct.theRetinalRFsurroundConeMap, ...
                theRTVFTobj.rfComputeStruct.retinalConePoolingParams.finalValues, ...
                theRTVFTobj.rfComputeStruct.retinalConePoolingParams, ...
                theRTVFTobj.rfComputeStruct.theRotationOfTheFittedVisualRF, ...
                theRTVFTobj.rfComputeStruct.modelConstants.spatialSupportDegs(:,1), ...
                theRTVFTobj.rfComputeStruct.modelConstants.targetSTFmatchMode, ...
                theRTVFTobj.rfComputeStruct.theSTF.target, ...
                theRTVFTobj.targetVisualRFDoGparams.surroundToCenterRcRatio, ...
                theRTVFTobj.targetVisualRFDoGparams.surroundToCenterIntegratedSensitivityRatio, ...
                theRTVFTobj.rfComputeStruct.modelConstants.visualRFcenterCharacteristicRadiusDegs, ...
                theRTVFTobj.multiStartsNumDoGFit, ...
                figNo, figureName);

    hFig = figure(figNo);
    ax = subplot(2,4,[7 8]);
    title(ax, sprintf('retinal pooling params for RFs with %d center cone(s) around (%2.2f,%2.2f) degs', ...
        theConesNumPooledByTheRFcenterGrid(iRTVobjIndex), theSamplingPositionGrid(iRTVobjIndex,1), theSamplingPositionGrid(iRTVobjIndex,2)));

    % Plot correspondence between target and achieved ratios
    ax = subplot(2,4,4);
    bar(ax, 1, 100*((fittedRsRcRatio/targetRsRcRatio)-1), 'BaseValue', 0.0);
    hold(ax, 'on');
    bar(ax, 2, 100*((fittedSCintSensRatio/targetSCintSensRatio)-1), 'BaseValue', 0.0);


    bar(ax, 3, 100*((fittedKsKcRatio/targetKsKcRatio)-1), 'BaseValue', 0.0);
    axis(ax, 'square');
    grid(ax, 'on');
    set(ax, 'XLim', [0 4],  'XTick', [1 2 3], 'XTickLabel', {'Rs/Rc','S/C sens', 'Ks/Kc'}, ...
        'YLim', [-100 100], 'FontSize', 16, 'YTick', -100:20:100);
    ylabel(ax,'(fitted-target)/target');
    
    drawnow;
    
    if (iRTVobjIndexDoesNotCorrespondToFullList)
        pdfFileName = sprintf('RTVFobj_X_at_%2.2f_%2.2fdegs_with%d_centerCones.pdf', ...
                         theSamplingPositionGrid(iRTVobjIndex,1), ...
                         theSamplingPositionGrid(iRTVobjIndex,2), ...
                         theConesNumPooledByTheRFcenterGrid(iRTVobjIndex));
    else
        pdfFileName = sprintf('RTVFobj_%d_at_%2.2f_%2.2fdegs_with_%d_centerCones.pdf', ...
                         iRTVobjIndex, ...
                         theSamplingPositionGrid(iRTVobjIndex,1), ...
                         theSamplingPositionGrid(iRTVobjIndex,2), ...
                         theConesNumPooledByTheRFcenterGrid(iRTVobjIndex));
    end
    
    NicePlot.exportFigToPDF(pdfFileName, hFig, 300);

end