function quicklyInspectSingleRTVFobjectFile()

    dropboxDir = midgetRGCMosaicInspector.localDropboxPath();
    [file,path] = uigetfile(fullfile(dropboxDir, '*.mat'), ...
                        'Select an RTVF file');

    if (file == 0)
        return;
    end

    fName = fullfile(path,file);
    load(fName, 'obj', 'iMultifocalRTVFobjIndex', ...
        'theConesNumPooledByTheRFcenterGrid', ...
        'theOpticsPositionGrid');

    RTVFmultifocal.peekIntoSingleRTVFobj(...
        obj, ...
        -iMultifocalRTVFobjIndex, ... % negative sign to indicate that this is not the index to the full list
        theOpticsPositionGrid, ...
        theConesNumPooledByTheRFcenterGrid, ...
        990);

end