function optimizationResultsFileName = exportOptimizationResults(theSurroundConnectedMRGCMosaicFullFileName, ...
	theMRGCMosaic, theTargetRGCindex, targetVisualSTFparams, optimizationResults)

	% Retrieve target cell connectivity stats
	theTargetRGCRFcenterConnectivityStats = theMRGCMosaic.singleCellConnectivityStats(theTargetRGCindex, 'center');

	% Assemble optimizationResultsFilename based on employed MRGC mosaic + target input cones num + target input cone dominance
    optimizationResultsFileName = RGCMosaicConstructor.filepathFor.optimizationResults(...
    	theSurroundConnectedMRGCMosaicFullFileName, ...
    	theTargetRGCRFcenterConnectivityStats.inputConesNum, ...
    	theTargetRGCRFcenterConnectivityStats.dominantConeType, ...
        'generateMissingSubDirs', true);


   	% Export optimizedValuesForSurroundPoolingModel as well as info relevant to the
    % optimization position and targetRGC
    save(optimizationResultsFileName, ...
    	'theMRGCMosaic', ...
        'targetVisualSTFparams', ...
        'theTargetRGCindex', ...
        'theTargetRGCRFcenterConnectivityStats', ...
        'optimizationResults');

    fprintf('Saved optimization results to %s\n', optimizationResultsFileName);
end