function setupPlotLab(obj, mode, figWidthInches, figHeightInches)
    if (mode == 0)
        obj.plotlabOBJ = plotlab();
        obj.plotlabOBJ.applyRecipe(...
                'colorOrder', [1 0 0; 0 0 1], ...
                'axesBox', 'off', ...
                'axesTickDir', 'in', ...
                'renderer', 'painters', ...
                'axesTickLength', [0.01 0.01], ...
                'legendLocation', 'SouthWest', ...
                'figureWidthInches', figWidthInches, ...
                'figureHeightInches', figHeightInches);
    else
        pause(2.0);
        obj.plotlabOBJ.resetAllDefaults();
    end
end