function visualizeFitsForDeconvolution(inputConeCombinationIndex, thePSFsupportDegs, thePSF, ...
                conePosDegs, retinalConeImage, visualConeImage, ...
                retinalConeActivations, visualConeActivations, ...
                hiResPSFsupportDegs, hiResRetinalConeActivationMap, hiResVisualConeActivationMap, ...
                rfSigmasRetinal, rfGainRetinal, rfSigmasVisual, rfGainVisual, visualizedSpatialSupportRange)

    hFig = figure(inputConeCombinationIndex); clf;
    set(hFig, 'Position', [100 100 20 18], ...
        'Name', sprintf('Deconvolution fits for input layout #%d', inputConeCombinationIndex));

    theAxesGrid = plotlab.axesGrid(hFig, ...
            'leftMargin', 0.04, ...
            'bottomMargin', 0.04, ...
            'rightMargin', 0.01, ...
            'widthMargin', 0.05, ...
            'heightMargin', 0.08, ...
            'topMargin', 0.03, ...
            'rowsNum', 2, ...
            'colsNum', 2);

        
    ax = theAxesGrid{1,1};
    renderConeImage(ax,thePSFsupportDegs, retinalConeImage, thePSF, visualizedSpatialSupportRange, 'retinal cone image');

    ax = theAxesGrid{2,1};
    renderConeActivationImageAndFitAsSurfacePlot(ax,retinalConeActivations, conePosDegs, ...
        hiResPSFsupportDegs, hiResRetinalConeActivationMap, ...
        visualizedSpatialSupportRange, ...
        sprintf('gain: %2.2f, sigmas: (%2.2f'',%2.2f'')', rfGainRetinal, rfSigmasRetinal(1)*60, rfSigmasRetinal(2)*60));
    
    
    ax = theAxesGrid{1,2};
    renderConeImage(ax,thePSFsupportDegs, visualConeImage, [], visualizedSpatialSupportRange, 'visual cone image');

    ax = theAxesGrid{2,2};
    renderConeActivationImageAndFitAsSurfacePlot(ax,visualConeActivations, conePosDegs, ...
        hiResPSFsupportDegs, hiResVisualConeActivationMap, ...
        visualizedSpatialSupportRange, ...
        sprintf('gain: %2.2f, sigmas: (%2.2f'',%2.2f'')', rfGainVisual, rfSigmasVisual(1)*60, rfSigmasVisual(2)*60));
    
    drawnow;
    pause(0.5);
end

function renderConeImage(ax,thePSFsupportDegs, coneImage, thePSF, visualizedSpatialSupportRange, figTitle)
    imagesc(ax,thePSFsupportDegs, thePSFsupportDegs, coneImage);
    hold(ax, 'on');
    if (~isempty(thePSF))
        contour(ax,thePSFsupportDegs, thePSFsupportDegs, thePSF/max(thePSF(:)), 0.2:0.2:1);
    end
    plot(ax,[-1 1], [0 0], 'r-');
    plot(ax,[0 0],[-1 1], 'r-');
    set(ax, 'XLim', visualizedSpatialSupportRange, 'YLim', visualizedSpatialSupportRange,...
        'XTick', (-0.3:0.1:0.3), 'YTick', (-0.3:0.1:0.3));
    axis(ax, 'square'); axis(ax, 'xy');
    title(ax,figTitle);
end

function renderConeActivationImageAndFitAsSurfacePlot(ax,retinalConeActivations, conePosDegs, ...
        hiResPSFsupportDegs, hiResRetinalConeActivationMap, visualizedSpatialSupportRange, figTitle)
    
    surf(ax,hiResPSFsupportDegs, hiResPSFsupportDegs, hiResRetinalConeActivationMap);
    hold(ax, 'on');
    stem3(ax,conePosDegs(:,1), conePosDegs(:,2),retinalConeActivations, 'filled');
    set(ax, 'XLim', visualizedSpatialSupportRange, 'YLim', visualizedSpatialSupportRange,...
        'XTick', (-0.3:0.1:0.3), 'YTick', (-0.3:0.1:0.3), 'CLim', [0 1], 'ZLim', [0 1]);
    axis(ax,'square');  axis(ax, 'xy');
    title(ax, figTitle);
end