function f = figureFormat(panelLayout)

    % figure sizes
    switch panelLayout
        case '1x4'
            f.figureSize = [1500 450];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 1, ...
                'colsNum', 4, ...
                'heightMargin',  0.01, ...
                'widthMargin',    0.06, ...
                'leftMargin',     0.04, ...
                'rightMargin',    0.01, ...
                'bottomMargin',   0.15, ...
                'topMargin',      0.05);
        case '2x4'
            f.figureSize = [1500 950];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 2, ...
                'colsNum', 4, ...
                'heightMargin',  0.10, ...
                'widthMargin',    0.06, ...
                'leftMargin',     0.05, ...
                'rightMargin',    0.00, ...
                'bottomMargin',   0.06, ...
                'topMargin',      0.02);
            
        case '4x4'
            f.figureSize = [1200 1150];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 4, ...
                'colsNum', 4, ...
                'heightMargin',  0.10, ...
                'widthMargin',    0.06, ...
                'leftMargin',     0.05, ...
                'rightMargin',    0.00, ...
                'bottomMargin',   0.06, ...
                'topMargin',      0.02);

       case '4x8'
            f.figureSize = [2050 1150];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 4, ...
                'colsNum', 8, ...
                'heightMargin',  0.04, ...
                'widthMargin',    0.03, ...
                'leftMargin',     0.04, ...
                'rightMargin',    0.00, ...
                'bottomMargin',   0.05, ...
                'topMargin',      0.03);

        case '2x2'
            f.figureSize = [800 800];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 2, ...
                'colsNum', 2, ...
                'heightMargin',  0.12, ...
                'widthMargin',    0.08, ...
                'leftMargin',     0.08, ...
                'rightMargin',    0.01, ...
                'bottomMargin',   0.07, ...
                'topMargin',      0.02);

        case '1x1 large'
            f.figureSize = [800 800];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 1, ...
                'colsNum', 1, ...
                'heightMargin',  0.00, ...
                'widthMargin',    0.00, ...
                'leftMargin',     0.08, ...
                'rightMargin',    0.00, ...
                'bottomMargin',   0.07, ...
                'topMargin',      0.02);

        case '1x2 large'
            f.figureSize = [1700 800];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 1, ...
                'colsNum', 2, ...
                'heightMargin',  0.00, ...
                'widthMargin',    0.04, ...
                'leftMargin',     0.03, ...
                'rightMargin',    0.00, ...
                'bottomMargin',   0.07, ...
                'topMargin',      0.02);

        otherwise
            error('unknown panelLayout: ''%s''.', panelLayout);
    end

    f.fontSize = 18;
    f.markerSize = 12;
    f.lineWidth = 1.5;
    f.LconeColor = [1 0.2 0.6];
    f.MconeColor = [0.2 1 0.4];
    f.SconeColor = [0.6 0.2 0.9];
    f.axisLineWidth = 1.0;

    f.axisColor = [0.3 0.3 0.3];
    f.axisFontAngle = 'italic';

    f.titleFontSize = 16;
    f.titleColor = [0.2 0.2 0.2];
    f.titleFontWeight = 'normal';

    f.legendFontSize = 13;

    f.axisOffsetFactor = -0.03;
end