function f = figureFormat(panelLayout)

    % figure sizes
    switch panelLayout
        case '1x4'
            f.figureSize = [1320 350];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 1, ...
                'colsNum', 4, ...
                'heightMargin',  0.01, ...
                'widthMargin',    0.05, ...
                'leftMargin',     0.06, ...
                'rightMargin',    0.01, ...
                'bottomMargin',   0.06, ...
                'topMargin',      0.01);
        case '2x2'
            f.figureSize = [800 800];
            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                'rowsNum', 2, ...
                'colsNum', 2, ...
                'heightMargin',  0.12, ...
                'widthMargin',    0.08, ...
                'leftMargin',     0.08, ...
                'rightMargin',    0.01, ...
                'bottomMargin',   0.07, ...
                'topMargin',      0.02);

        otherwise
            error('unknown panelLayout: ''%s''.', panelLayout);
    end

    f.fontSize = 18;
    f.markerSize = 12;
    f.lineWidth = 1.5;
    f.LconeColor = [1 0.2 0.6];
    f.MconeColor = [0.2 1 0.4];
    f.SconeColor = [0.6 0.2 0.9];
    f.axisLineWidth = 1.0;

    f.axisColor = [0.3 0.3 0.3];
    f.axisFontAngle = 'italic';

    f.titleFontSize = 16;
    f.titleColor = [0.2 0.2 0.2];
    f.titleFontWeight = 'normal';

end