function renderIdentifiedMRGClocations(hFigLcenter, hFigMcenter, axLcenter, axMcenter, theMRGCMosaic, ...
    identifiedLcenterMRGCindices, identifiedMcenterMRGCindices, plotTitleLcenter, plotTitleMcenter, ff,varargin)
    p = inputParser;
    p.addParameter('noXLabel', false, @islogical);
    p.addParameter('noYLabel', false, @islogical);
    p.addParameter('noXTickLabel', false, @islogical);
    p.addParameter('noYTickLabel', false, @islogical);

    p.parse(varargin{:});
    
    noXLabel = p.Results.noXLabel;
    noYLabel = p.Results.noYLabel;
    noXTickLabel = p.Results.noXTickLabel;
    noYTickLabel = p.Results.noYTickLabel;

    theMRGCMosaic.visualize(...
        'figureHandle', hFigLcenter, ...
        'axesHandle', axLcenter, ...
        'identifyPooledCones', false, ...
        'identifyInputCones', false, ...
        'labelRGCsWithIndices', identifiedLcenterMRGCindices, ...
        'labeledRGCsColor', [1 0 0], ...
        'labeledRGCsLineWidth', 1.0, ...
        'domainVisualizationTicks', struct('x', -1:1:1, 'y', -1:1:1), ...
        'fontSize', ff.fontSize, ...
        'fontAngle', ff.axisFontAngle, ...
        'backgroundColor', [1 1 1], ...
        'plotTitle', plotTitleLcenter);

    theMRGCMosaic.visualize(...
        'figureHandle', hFigMcenter, ...
        'axesHandle', axMcenter, ...
        'identifyPooledCones', false, ...
        'identifyInputCones', false, ...
        'labelRGCsWithIndices', identifiedMcenterMRGCindices, ...
        'labeledRGCsColor', [0 0.8 0], ...
        'labeledRGCsLineWidth', 1.0, ...
        'domainVisualizationTicks', struct('x', -1:1:1, 'y', -1:1:1), ...
        'fontSize', ff.fontSize, ...
        'fontAngle', ff.axisFontAngle, ...
        'backgroundColor', [1 1 1], ...
        'plotTitle', plotTitleMcenter);


end
