% Script to examine the properties of compute-ready mosaics 
% This script is also used to generate materials for the validation
% figures for the VSS2024 presentation
%
% Usage:
%{
    t_testRGCMosaicValidationVSS2024     
%}

% Initialize session
close all; clear all;

% Configure a conservative parpool manager. This gives at least 8 GB RAM/core
%ASPPManager = AppleSiliconParPoolManager(12);
%
ASPPManager = AppleSiliconParPoolManager('half max');
%ASPPManager = AppleSiliconParPoolManager('conservative');

computeInputConeMosaicResponses = ~true;
computeMRGCMosaicResponses = ~true;
visualizeInputConeMosaicResponses = false;
visualizePSFonTopOfConeMosaic = ~true;

reAnalyzeSingleTargetVisualSTFdata = ~true;
performCronerKaplanAnalysis = ~true;
performLeeShapleyAnalysis = ~true;


aggregatePreviouslyAnalyzedRunsFromMultipleTargetVisualSTFs = true;

% Specify targetVisualSTFdescriptors to be aggregated
targetVisualSTFdescriptorsToBeAggregated = { ...
   'default' ...
   'lower intSCratio' ...
   'higher intSCratio' ...
   'very high intSCratio' ...
   'ultra high intSCratio'
};


% Or just the reference (for generating figures)
% targetVisualSTFdescriptor used for the exemplar STFs in the VSS2024 talk
%targetVisualSTFdescriptorsToBeAggregated = { ...
%   'default' ...
%   'higher intSCratio' ...
%   'very high intSCratio' ...
%};

% Examine effect of residual error in refraction. 
% This is selected by desiredResidualErrorInRefractionIndex below
analyzeAggregatedBPIsAtDesiredAchromaticRefractionError = ~true;
%desiredResidualErrorInRefractionIndex = 3;  % refraction was off by 0.75D
%desiredResidualErrorInRefractionIndex = 2;  % refraction was off by 0.5D
%desiredResidualErrorInRefractionIndex = 1; % refraction was off by 0.25D
%desiredResidualErrorInRefractionIndex = 0;  % refraction was spot on
%desiredResidualErrorInRefractionIndex = -1;  % refraction was off by -0.25D

analyzeAggregatedBPIsAtRandomAchromaticRefractionError = ~true;

%if (analyzeAggregatedBPIsAtDesiredAchromaticRefractionError||analyzeAggregatedBPIsAtRandomAchromaticRefractionError)
%    aggregatePreviouslyAnalyzedRunsFromMultipleTargetVisualSTFs = false;
%end

if (performCronerKaplanAnalysis)
    STFchromaticity = 'Achromatic';  
    opticsModification = 'nativeOptics';
    targetVisualSTFdescriptor = 'default';               % mean of Croner & Kaplan
    targetVisualSTFdescriptor = 'higher intSCratio';
    targetVisualSTFdescriptor = 'very high intSCratio';
    %targetVisualSTFdescriptor = 'ultra high intSCratio';
end


if (performLeeShapleyAnalysis)
    % Choose degree of bandpassiness
    targetVisualSTFdescriptor = 'default';               % mean of Croner & Kaplan with default Rc/Rs
    targetVisualSTFdescriptor = 'higher intSCratio';     % Higher than mean of Croner & Kaplan with default Rc/Rs
    %targetVisualSTFdescriptor = 'very high intSCratio';   % Much higher than mean Croner & Kaplan with higher Rc/Rs
    %targetVisualSTFdescriptor = 'lower intSCratio';      % Lower than mean of Croner & Kaplan with default Rc/Rs
    %targetVisualSTFdescriptor = 'ultra high intSCratio';  % Twice the mean Croner & Kaplan with default Rc/Rs

    % Control optics (always adaptiveOptics6MM)
    LeeShapleyAnalysisControlOptics = 'adaptiveOptics6MM';

    % Below is the optics conditions to be analyzed
    % Native optics (optimized Strehl ratio)
    LeeShapleyAnalysisTestOptics{1} = 'nativeOptics';
    LeeShapleyAnalysisTestOpticsParam{1} = [];

    LeeShapleyAnalysisTestOptics{numel(LeeShapleyAnalysisTestOptics)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParam{numel(LeeShapleyAnalysisTestOpticsParam)+1} = -0.25;
    
    LeeShapleyAnalysisTestOptics{numel(LeeShapleyAnalysisTestOptics)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParam{numel(LeeShapleyAnalysisTestOpticsParam)+1} = 0.25;
    
    LeeShapleyAnalysisTestOptics{numel(LeeShapleyAnalysisTestOptics)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParam{numel(LeeShapleyAnalysisTestOpticsParam)+1} = 0.50;
   
    LeeShapleyAnalysisTestOptics{numel(LeeShapleyAnalysisTestOptics)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParam{numel(LeeShapleyAnalysisTestOpticsParam)+1} = 0.75;
end



% If fixedRGCindices is not empty, we use these indices.
% If fixedRGCindices is empty, we find the indices of RGCs whose (achromaticBPIs,centerIsolatingBPIs) 
% are closest to the specified exemplarRGCs.achromaticBPIs, exemplarRGCs.centerIsolatingBPIs

% Indices of exemplar cells visualized
%McenterExemplars = [4204 4257 4054 ]
%LcenterExemplars = [5051 4271 5020 4591]
exemplarRGCs.fixedRGCindices = [5051 4271 5020 4591 4204 4257 4054 ] ; %[4271 4054];
exemplarRGCs.fixedRGCindices = [4204];
% The above cells were selected for the folling BPI targets 
% for the max Strehl ratio responses (0.00 defocus)
exemplarRGCs.achromaticBPIs      = [0.48  0.48];
exemplarRGCs.centerIsolatingBPIs = [0.9  0.95 1.0];

if (performLeeShapleyAnalysis) || (performCronerKaplanAnalysis)
    % Target RGCs with surround specificity around 0.5 (i.e., 50/50 L/M cone net weight in the surround)
    targetedSurroundPurityRange = [0 1];    % [0.4 0.6];
    targetedRadialEccentricityRange = [];       % Empty means full range
    targetedCenterConeNumerosityRange = [1 1];  % single cone centers only
   
    % Or, target RGCs with surround specificity < 0.25 (i.e., similar surround and center cone dominances)
    %targetedSurroundSpecificifyRange = [0.0 0.15];
    % Or, target RGCs with surround specificity > 0.75 (i.e., opposite surround and center cone dominances)
    %targetedSurroundSpecificifyRange = [0.85 1.0];
end


if (computeInputConeMosaicResponses || computeMRGCMosaicResponses)
    % Choose chromaticity to run
    chromaticityForSTFresponses = 'Achromatic';   % Choose between 'LconeIsolating', 'MconeIsolating', 'Achromatic'
    
    % Choose degree of bandpassiness
    targetVisualSTFdescriptor = 'default';               % mean of Croner & Kaplan with default Rc/Rs
    targetVisualSTFdescriptor = 'higher intSCratio';     % Higher than mean of Croner & Kaplan with default Rc/Rs
    %targetVisualSTFdescriptor = 'very high intSCratio';  % Much higher than mean Croner & Kaplan with higher Rc/Rs
    %targetVisualSTFdescriptor = 'lower intSCratio';      % Lower than mean of Croner & Kaplan with default Rc/Rs
    targetVisualSTFdescriptor = 'ultra high intSCratio';  % Twice the mean Croner & Kaplan with default Rc/Rs

    % Choose optics to run
    % Option 1. Native optics (what was used to optimize the surround)
    %opticsForSTFresponses = 'nativeOptics';
    %residualWithRespectToNativeOpticsDefocusDiopters = [];

    % Option 2. residual defocus with respect to native optics
    opticsForSTFresponses = 'refractionResidualWithRespectToNativeOptics';
    %residualWithRespectToNativeOpticsDefocusDiopters = 0.75;
    residualWithRespectToNativeOpticsDefocusDiopters = 0.50;
    %residualWithRespectToNativeOpticsDefocusDiopters = 0.25;
    %residualWithRespectToNativeOpticsDefocusDiopters =-0.25;

    % Option 3. adaptive optics, 6 mm pupil, no LCA
    %opticsForSTFresponses = 'adaptiveOptics6MM';

    % Option 4.  adaptive optics with LCA
    % opticsForSTFresponses = 'adaptiveOptics6MMwithLCA';
 
    % Option 5. a custom refraction
    % opticsForSTFresponses = 'customRefraction';
    % customRefractionDiopters = -4;
end


% orientation for STF analysis: optimal for achromatic grating (What Lee et al may have done)
%orientationSelection = 'achromaticSTFbased' ;   

% orientation for STF analysis: random (What Lee et al may have done)
orientationSelection = 'random'; 

% orientation for STF analysis: optimal for center-cone isolating grating 
% orientationSelection = 'centerConeTypeSTFbased'; 


% Which mRGC/cone mosaic lattice to use
sourceLatticeSizeDegs = 64; 
whichEye = 'right eye';


% Human retina
customLMSconeDensities = [];

% Macaque retina
customLMSconeDensities = [0.45 0.45 0.1];

% Examined spatialChromaticUniformityTradeoff [0: minimize chromatic variance 1: minimize spatial variance]
spatialChromaticUniformityTradeoff = 1.0;

% Which optics to use
whichZernikeDataBase = 'Polans2015';

% First compute-ready mosaic was generated foPolans subject #3
mosaicEccDegs = [0 0]; mosaicSizeDegs = [0.5 0.5];
whichSubjectID = 3;

% Second compute-ready mosaic (What was used for the VSS2024 talk)
mosaicEccDegs = [-3 0]; mosaicSizeDegs = 1*[1 1];
whichSubjectID = 3;

% Third compute-ready mosaic (Second subject used for the VSS2024 talk)
mosaicEccDegs = [-3 0]; mosaicSizeDegs = 1*[1 1];
whichSubjectID = 8;

% Extra size (margin)
extraSizeDegs = 1;
mosaicSizeDegs = mosaicSizeDegs+extraSizeDegs*[1 1];

% Use mosaic with RFcenter overlap
employRFCenterOverlappingMosaic = true;

surroundOptimizationStrategy = 'LowerLeftQH1paramsMediumVisualSTFparamTolerance';


% Generate filenames
if (computeInputConeMosaicResponses || computeMRGCMosaicResponses)
    [theSurroundConnectedMRGCMosaicFullFileName, theInputConeMosaicSTFResponsesFullFileName, ...
    theMRGCMosaicSTFResponsesFullFileName, surroundConnectedParamsStruct, targetVisualSTFmodifierStruct] = ...
        RGCMosaicAnalyzer.filepathFor.testRuns(whichEye, whichZernikeDataBase, whichSubjectID, ...
            mosaicEccDegs, mosaicSizeDegs, employRFCenterOverlappingMosaic, ...
            spatialChromaticUniformityTradeoff, customLMSconeDensities, ...
            targetVisualSTFdescriptor, surroundOptimizationStrategy, ...
            opticsForSTFresponses, residualWithRespectToNativeOpticsDefocusDiopters, ...
            chromaticityForSTFresponses, ...
            'STFresponses');
else
    [theSurroundConnectedMRGCMosaicFullFileName, theInputConeMosaicSTFResponsesFullFileName, ...
    theMRGCMosaicSTFResponsesFullFileName, surroundConnectedParamsStruct, targetVisualSTFmodifierStruct] = ...
        RGCMosaicAnalyzer.filepathFor.testRuns(whichEye, whichZernikeDataBase, whichSubjectID, ...
            mosaicEccDegs, mosaicSizeDegs, employRFCenterOverlappingMosaic, ...
            spatialChromaticUniformityTradeoff, customLMSconeDensities, ...
            targetVisualSTFdescriptor, surroundOptimizationStrategy, ...
            'nativeOptics', [], 'Achromatic', ...
            'STFresponses');
end



% Load theMRGCmosaic
load(theSurroundConnectedMRGCMosaicFullFileName, 'theMRGCMosaic');
% Print info on how the surrounds where optimized
%RGCMosaicConstructor.helper.utils.printStruct(theMRGCMosaic.rfSurroundConnectivityParams, 'rfSurroundConnectivityParams')

probePartOfTheMosaic = false;
if (probePartOfTheMosaic)
     % Study a small patch, so lets crop the full mosaic
    targetPositionDegs = [0 0];
    targetSizeDegs = [1 1];
    % Compute extra support for input cone mosaic at the optimization position
    extraSupportDegsForInputConeMosaic = mRGCMosaic.extraSupportDegsForMidgetRGCSurrounds(targetPositionDegs, targetSizeDegs);
    visualizeSpatialRelationshipToSourceMosaic = true;

    theMRGCMosaic.cropToSizeAtEccentricity(targetSizeDegs, targetPositionDegs, ...
        'extraSupportDegsForInputConeMosaic', extraSupportDegsForInputConeMosaic, ...
        'visualizeSpatialRelationshipToSourceMosaic', visualizeSpatialRelationshipToSourceMosaic);
end


if (computeInputConeMosaicResponses)
    switch (opticsForSTFresponses) 
        case  'refractionResidualWithRespectToNativeOptics'
            computeSTFresponses(theMRGCMosaic, opticsForSTFresponses, residualWithRespectToNativeOpticsDefocusDiopters, ...
                chromaticityForSTFresponses, ...
                theInputConeMosaicSTFResponsesFullFileName, theMRGCMosaicSTFResponsesFullFileName, ...
                visualizeInputConeMosaicResponses, ...
                visualizePSFonTopOfConeMosaic);

        case 'customRefraction'
            computeSTFresponses(theMRGCMosaic, opticsForSTFresponses, customRefractionDiopters, ...
                chromaticityForSTFresponses, ...
                theInputConeMosaicSTFResponsesFullFileName, theMRGCMosaicSTFResponsesFullFileName, ...
                visualizeInputConeMosaicResponses, ...
                visualizePSFonTopOfConeMosaic);

        otherwise
            computeSTFresponses(theMRGCMosaic, opticsForSTFresponses, [],  ...
                chromaticityForSTFresponses,  ...
                theInputConeMosaicSTFResponsesFullFileName, theMRGCMosaicSTFResponsesFullFileName, ...
                visualizeInputConeMosaicResponses, ...
                visualizePSFonTopOfConeMosaic);
    end % switch
end


if (computeMRGCMosaicResponses)
    RGCMosaicConstructor.helper.simulateExperiment.spatialTransferFunction(...
        theMRGCMosaic, [], [],...
        theInputConeMosaicSTFResponsesFullFileName, ...
        theMRGCMosaicSTFResponsesFullFileName, ...
        'computeInputConeMosaicResponses', false, ...
        'computeMRGCMosaicResponses', true, ...
        'visualizeResponse', ~true);
    return;
end % if (computeMRGCMosaicResponses)



if (performCronerKaplanAnalysis)
    % Output file
    theCronerKaplanAnalysisFileName = strrep(theMRGCMosaicSTFResponsesFullFileName, 'STFresponses', 'demos/CronerKaplanAnalyses');

    if (aggregatePreviouslyAnalyzedRunsFromMultipleTargetVisualSTFs)
        % Accumulate data across all aggregated runs
        aggregatedRunParams = generateRunParamsForMultipleTargetVisualSTFs(targetVisualSTFdescriptorsToBeAggregated);

        % Generate filenames for all aggregated runs
        for iRun = 1:size(aggregatedRunParams,1)
            theRunParams = aggregatedRunParams(iRun,:)
            allMRGCMosaicSTFResponsesFullFileNames{iRun} = strrep(theMRGCMosaicSTFResponsesFullFileName, 'vSTF_1.0_1.0', ...
                sprintf('vSTF_%1.1f_%1.1f', theRunParams(1), theRunParams(2)));
            allCronerKaplanAnalysisFileNames{iRun} = strrep(theCronerKaplanAnalysisFileName, 'vSTF_1.0_1.0', ...
                sprintf('vSTF_%1.1f_%1.1f', theRunParams(1), theRunParams(2)));
            fprintf('%s\n', allCronerKaplanAnalysisFileNames{iRun})
        end

        % Do it !
        RGCMosaicAnalyzer.compute.CronerAndKaplanSTFanalysis(...
            allMRGCMosaicSTFResponsesFullFileNames, ...
            allCronerKaplanAnalysisFileNames, ...
            targetedSurroundPurityRange, ...
            targetedRadialEccentricityRange, ...
            targetedCenterConeNumerosityRange, ...
            reAnalyzeSTFData);
    else
        % Run a single run using the theMRGCMosaicSTFResponsesFullFileName and save it in theCronerKaplanAnalysisFileName
        RGCMosaicAnalyzer.compute.CronerAndKaplanSTFanalysis(...
            theMRGCMosaicSTFResponsesFullFileName, ...
            theCronerKaplanAnalysisFileName, ...
            targetedSurroundPurityRange, ...
            targetedRadialEccentricityRange, ...
            targetedCenterConeNumerosityRange, ...
            reAnalyzeSTFData);
    end
    return;
end


if (performLeeShapleyAnalysis)
    % Params for visualized bandpass density map
    bandpassIndexDensityMap = struct(....
        'maxVisualizedValue', 0.9, ...
        'interval', 0.1, ...
        'LeeShapleyDataMarkerSize', 10)

    superimposeLeeShapleyData = true;
    onlyDepictLeeShapleyData = ~true;

    if (aggregatePreviouslyAnalyzedRunsFromMultipleTargetVisualSTFs)
        % Generate aggregatedRunParams data across all aggregated runs
        aggregatedRunParams = generateRunParamsForMultipleTargetVisualSTFs(targetVisualSTFdescriptorsToBeAggregated);

        % Aggregate, visualize and export the BPI data
        aggregateVisualizeAndExportBPIsAcrossMultipleTargetVisualSTFs( ...
            mosaicEccDegs, whichSubjectID, ...
            aggregatedRunParams, ...
            LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, ...
            LeeShapleyAnalysisControlOptics, orientationSelection, ...
            surroundConnectedParamsStruct, ...
            targetedSurroundPurityRange, ...
            exemplarRGCs, ...
            bandpassIndexDensityMap, ...
            superimposeLeeShapleyData, ...
            onlyDepictLeeShapleyData);
        return;
    end % if (aggregatePreviouslyAnalyzedRunsFromMultipleTargetVisualSTFs)


    if (analyzeAggregatedBPIsAtDesiredAchromaticRefractionError) 
        analyzeBPIsForRefractionErrorRelativeToOptimalAchromaticRefraction(...
            mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
            desiredResidualErrorInRefractionIndex, orientationSelection, ...
            bandpassIndexDensityMap, ...
            superimposeLeeShapleyData);
        return;
    end

    if (analyzeAggregatedBPIsAtRandomAchromaticRefractionError) 
        superimposeLeeShapleyData = true;
        analyzeBPIsForRefractionErrorRelativeToOptimalAchromaticRefraction(...
            mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
            [], orientationSelection, ...
            bandpassIndexDensityMap, ...
            superimposeLeeShapleyData);
        return;
    end


    if (reAnalyzeSingleTargetVisualSTFdata)
        superimposeLeeShapleyData = true;
        showExemplarRGCdata = false;
        analyzeMultipleOpticsSingleVisualSTFrun(targetVisualSTFmodifierStruct, ...
            mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
            LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, LeeShapleyAnalysisControlOptics, ...
            targetedSurroundPurityRange, targetedRadialEccentricityRange, targetedCenterConeNumerosityRange, ...
            orientationSelection, exemplarRGCs, ...
            theMRGCMosaicSTFResponsesFullFileName, ...
            showExemplarRGCdata, ...
            superimposeLeeShapleyData, ...
            bandpassIndexDensityMap);
        return;
    end

end % performLeeShapleyAnalysis

%
% SUPPORTING FUNCTIONS
%

function analyzeMultipleOpticsSingleVisualSTFrun(targetVisualSTFmodifierStruct, ...
    mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
    LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, LeeShapleyAnalysisControlOptics, ...
    targetedSurroundPurityRange, targetedRadialEccentricityRange, targetedCenterConeNumerosityRange, ...
    orientationSelection, exemplarRGCs, ...
    theMRGCMosaicSTFResponsesFullFileName, ...
    showExemplarRGCdata, ...
    superimposeLeeShapleyData, ...
    bandpassIndexDensityMap)

    for iOptics = 1:numel(LeeShapleyAnalysisTestOptics)
        analyzeSingleVisualSTFrun(targetVisualSTFmodifierStruct, ...
            mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
            LeeShapleyAnalysisTestOptics{iOptics}, LeeShapleyAnalysisTestOpticsParam{iOptics}, LeeShapleyAnalysisControlOptics, ...
            targetedSurroundPurityRange, targetedRadialEccentricityRange, targetedCenterConeNumerosityRange, ...
            orientationSelection, exemplarRGCs, ...
            theMRGCMosaicSTFResponsesFullFileName, ...
            showExemplarRGCdata, ...
            superimposeLeeShapleyData, ...
            bandpassIndexDensityMap);
    end

end


function analyzeSingleVisualSTFrun(targetVisualSTFmodifierStruct, ...
    mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
    LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, LeeShapleyAnalysisControlOptics, ...
    targetedSurroundPurityRange, targetedRadialEccentricityRange, targetedCenterConeNumerosityRange, ...
    orientationSelection, exemplarRGCs, ...
    theMRGCMosaicSTFResponsesFullFileName, ...
    showExemplarRGCdata, ...
    superimposeLeeShapleyData, ...
    bandpassIndexDensityMap)

    % Re-analyze data
    assert(contains(theMRGCMosaicSTFResponsesFullFileName, 'Achromatic'), ...
        'STF analysis must be set for ''Achromatic'' gratings.');
    assert(contains(theMRGCMosaicSTFResponsesFullFileName, 'nativeOptics'), ...
        'STF analysis must be set for ''nativeOptics'' gratings.');


    if (strcmp(LeeShapleyAnalysisTestOptics, 'refractionResidualWithRespectToNativeOptics'))
        theMRGCMosaicSTFResponsesFullFileName = strrep(theMRGCMosaicSTFResponsesFullFileName, ...
            'nativeOptics', sprintf('nativeOpticsWithDefocus_%2.2fD', LeeShapleyAnalysisTestOpticsParam));
    end

    % Generate file names for L- and M-cone isolating STFs with native optics
    theMRGCMosaicLconeSTFResponsesFileName = strrep(theMRGCMosaicSTFResponsesFullFileName, 'Achromatic', 'LconeIsolating');
    theMRGCMosaicMconeSTFResponsesFileName = strrep(theMRGCMosaicSTFResponsesFullFileName, 'Achromatic', 'MconeIsolating');

    if (strcmp(LeeShapleyAnalysisTestOptics, 'refractionResidualWithRespectToNativeOptics'))
        theMRGCMosaicSTFResponsesControlFullFileName = ...
            strrep(theMRGCMosaicSTFResponsesFullFileName, sprintf('nativeOpticsWithDefocus_%2.2fD', LeeShapleyAnalysisTestOpticsParam), LeeShapleyAnalysisControlOptics);
        theMRGCMosaicLconeSTFResponsesControlFileName = ...
            strrep(theMRGCMosaicLconeSTFResponsesFileName, sprintf('nativeOpticsWithDefocus_%2.2fD', LeeShapleyAnalysisTestOpticsParam), LeeShapleyAnalysisControlOptics);
        theMRGCMosaicMconeSTFResponsesControlFileName = ...
            strrep(theMRGCMosaicMconeSTFResponsesFileName, sprintf('nativeOpticsWithDefocus_%2.2fD', LeeShapleyAnalysisTestOpticsParam), LeeShapleyAnalysisControlOptics);
    else
        theMRGCMosaicSTFResponsesControlFullFileName = ...
            strrep(theMRGCMosaicSTFResponsesFullFileName, LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisControlOptics);
        theMRGCMosaicLconeSTFResponsesControlFileName = ...
            strrep(theMRGCMosaicLconeSTFResponsesFileName, LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisControlOptics);
        theMRGCMosaicMconeSTFResponsesControlFileName = ...
            strrep(theMRGCMosaicMconeSTFResponsesFileName, LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisControlOptics);
    end

    dataOut = RGCMosaicAnalyzer.compute.STFdependenceOnChromaticityAndOptics(...
        targetedSurroundPurityRange, ...
        targetedRadialEccentricityRange, ...
        targetedCenterConeNumerosityRange, ...
        exemplarRGCs, ...
        orientationSelection, ...
        theMRGCMosaicSTFResponsesFullFileName, ...
        theMRGCMosaicLconeSTFResponsesFileName, ...
        theMRGCMosaicMconeSTFResponsesFileName, ...
        theMRGCMosaicSTFResponsesControlFullFileName, ...
        theMRGCMosaicLconeSTFResponsesControlFileName, ...
        theMRGCMosaicMconeSTFResponsesControlFileName);

    if (isempty(LeeShapleyAnalysisTestOpticsParam))
        % Add test and control optics, orientation selection, and target visual STF info
        matFileName = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%s_%s_%1.2f_%1.2f.mat', ...
            mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
            LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisControlOptics, ...
            orientationSelection, ...
            targetVisualSTFmodifierStruct.surroundToCenterRcRatioMultiplier,...
            targetVisualSTFmodifierStruct.surroundToCenterIntegratedSensitivityRatioMultiplier);
    else
        % Add test and control optics, orientation selection, and target visual STF info
        matFileName = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%2.2fD_%s_%s_%1.2f_%1.2f.mat', ...
            mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
            LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, LeeShapleyAnalysisControlOptics, ...
            orientationSelection, ...
            targetVisualSTFmodifierStruct.surroundToCenterRcRatioMultiplier,...
            targetVisualSTFmodifierStruct.surroundToCenterIntegratedSensitivityRatioMultiplier);
    end

    % Add cone mosaic info
    if (~isempty(surroundConnectedParamsStruct.customLMSconeDensities))
        matFileName = strrep(matFileName, 'LeeShapleySimulation', ...
                     sprintf('LeeShapleySimulation_%d_%d_%d',...
                     round(surroundConnectedParamsStruct.customLMSconeDensities(1)*100), ...
                     round(surroundConnectedParamsStruct.customLMSconeDensities(2)*100), ...
                     round(surroundConnectedParamsStruct.customLMSconeDensities(3)*100)));
    end
    
    matFileName = fullfile(RGCMosaicConstructor.filepathFor.intermediateDataDir, ...
                'SLIM', 'demos', 'LeeShapleyAnalyses', matFileName);

    fprintf('Saving STF data to %s\n', matFileName);
    save(matFileName, 'dataOut');


    if (~showExemplarRGCdata)
        return;
    end

    maxSTFamplitude = 0.6;
    for iExemplarRGCindex = 1:numel(dataOut.exemplarRGCdata)
        d = dataOut.exemplarRGCdata{iExemplarRGCindex};

        if (isempty(d))
            fprintf('Exemplar RGC not found. Skip plotting\n');
            continue;
        end
        figNo = 100 + iExemplarRGCindex;
        thePDFFileName = sprintf('diffractionLimitedOpticsSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingSTFs(figNo, ...
            d.rgcIndex, d.rfCenterConeDominance, ...
            d.diffractionLimitedSTF.sfSupport, d.diffractionLimitedSTF.achromaticSTF, ...
            d.diffractionLimitedSTF.lConeIsolatingSTF, d.diffractionLimitedSTF.mConeIsolatingSTF, ...
            d.diffractionLimitedSTF.achromaticSTFBPI, ...
            d.diffractionLimitedSTF.lConeIsolatingSTFBPI , ...
            d.diffractionLimitedSTF.mConeIsolatingSTFBPI , ...
            maxSTFamplitude, ... %d.maxSTF, ...
            thePDFFileName);

        figNo = 200 + iExemplarRGCindex;
        thePDFFileName = sprintf('physiologicalOpticsSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingSTFs(figNo, ...
            d.rgcIndex, d.rfCenterConeDominance, ...
            d.physiologicalSTF.sfSupport, d.physiologicalSTF.achromaticSTF , ...
            d.physiologicalSTF.lConeIsolatingSTF, d.physiologicalSTF.mConeIsolatingSTF, ...
            d.physiologicalSTF.achromaticSTFBPI, ...
            d.physiologicalSTF.lConeIsolatingSTFBPI , ...
            d.physiologicalSTF.mConeIsolatingSTFBPI , ...
            maxSTFamplitude, ... % d.maxSTF, ...
            thePDFFileName);

        figNo = 300 + 10*iExemplarRGCindex;
        thePDFFileName = sprintf('physiologicalOpticsFullSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingFullSTFs(figNo, ...
            d.rgcIndex, ...
            d.rfCenterConeDominance, ...
            d.physiologicalSTF.optimalOrientation, ...
            d.physiologicalSTF.sfSupportFullSTF, d.physiologicalSTF.orientationSupport, ...
            d.physiologicalSTF.achromaticFullSTF, ...
            d.physiologicalSTF.lConeIsolatingFullSTF, ...
            d.physiologicalSTF.mConeIsolatingFullSTF, ...
            thePDFFileName);

        figNo = 400 + 10*iExemplarRGCindex;
        thePDFFileName = sprintf('diffractionLimitedOpticsFullSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingFullSTFs(figNo, ...
            d.rgcIndex, ...
            d.rfCenterConeDominance, ...
            d.diffractionLimitedSTF.optimalOrientation, ...
            d.diffractionLimitedSTF.sfSupportFullSTF, d.diffractionLimitedSTF.orientationSupport, ...
            d.diffractionLimitedSTF.achromaticFullSTF, ...
            d.diffractionLimitedSTF.lConeIsolatingFullSTF, ...
            d.diffractionLimitedSTF.mConeIsolatingFullSTF, ...
            thePDFFileName);

        figNo = 500 + iExemplarRGCindex;
        thePDFfileName = sprintf('conePoolingWeightsMap_exemplarRGC%d.pdf', d.rgcIndex);
        thePlotTitle = sprintf('RGC #%d, surround cone purity: %2.2f', d.rgcIndex, d.surroundConePurity);
        RGCMosaicAnalyzer.visualize.exemplarRGCconePoolingMap(figNo, ...
            dataOut.theMRGCMosaic, d.rgcIndex, thePDFfileName, ...
            'fixedSpatialSupportTickSeparationArcMin', 4.0, ...
            'fixedScalaBarDegs', 0.05, ...
            'plotTitle', thePlotTitle);


        

        % L-cone centers, natural optics
        figNo = 10+iExemplarRGCindex;
        idx = find(dataOut.LconeCenter.rgcIndices == d.rgcIndex);
        if (~isempty(idx))
            RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
                dataOut.LconeCenter.physiologicalOptics.achromaticBPIs(idx), ...
                dataOut.LconeCenter.physiologicalOptics.coneIsolatingBPIs(idx), ...
                dataOut.LconeCenter.surroundConePurities(idx), ...
                cMosaic.LCONE_ID, ...
                sprintf('BPIscatterPlotLconeCenterNaturalOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                sprintf('BPIvsSurroundConePurityLconeCenterNaturalOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                '', ...
                'bpiInterval', bandpassIndexDensityMap.interval, ...
                'markerSize', 16, ...
                'markerFaceAlpha', 1.0, ...
                'markerLineWidth', 1.0, ...
                'markerEdgeAlpha', 1.0, ...
                'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
                'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);
        

            figNo = 30+iExemplarRGCindex;
            RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
                dataOut.LconeCenter.diffractionLimitedOptics.achromaticBPIs(idx), ...
                dataOut.LconeCenter.diffractionLimitedOptics.coneIsolatingBPIs(idx), ...
                dataOut.LconeCenter.surroundConePurities(idx), ...
                cMosaic.LCONE_ID, ...
                sprintf('BPIscatterPlotLconeCenterDiffractionLimitedOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                sprintf('BPIvsSurroundConePurityLconeCenterDiffractionLimitedOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                '', ...
                'bpiInterval', bandpassIndexDensityMap.interval, ...
                'markerSize', 16, ...
                'markerFaceAlpha', 1.0, ...
                'markerLineWidth', 1.0, ...
                'markerEdgeAlpha', 1.0, ...
                'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
                'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);
        end

        % M-cone centers, natural optics
        figNo = 20+iExemplarRGCindex;
        idx = find(dataOut.MconeCenter.rgcIndices == d.rgcIndex);
        if (~isempty(idx))
            RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
                dataOut.MconeCenter.physiologicalOptics.achromaticBPIs(idx), ...
                dataOut.MconeCenter.physiologicalOptics.coneIsolatingBPIs(idx), ...
                dataOut.MconeCenter.surroundConePurities(idx), ...
                cMosaic.MCONE_ID, ...
                sprintf('BPIscatterPlotMconeCenterNaturalOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                sprintf('BPIvsSurroundConePurityMconeCenterNaturalOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                '', ...
                'bpiInterval', bandpassIndexDensityMap.interval, ...
                'markerSize', 16, ...
                'markerFaceAlpha', 1.0, ...
                'markerLineWidth', 1.0, ...
                'markerEdgeAlpha', 1.0, ...
                'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
                'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

            figNo = 40+iExemplarRGCindex;
            RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
                dataOut.MconeCenter.diffractionLimitedOptics.achromaticBPIs(idx), ...
                dataOut.MconeCenter.diffractionLimitedOptics.coneIsolatingBPIs(idx), ...
                dataOut.MconeCenter.surroundConePurities(idx), ...
                cMosaic.MCONE_ID, ...
                sprintf('BPIscatterPlotMconeCenterDiffractionLimitedOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                sprintf('BPIvsSurroundConePurityMconeCenterDiffractionLimitedOptics_exemplarRGC%d.pdf', d.rgcIndex), ...
                '', ...
                '', ...
                'bpiInterval', bandpassIndexDensityMap.interval, ...
                'markerSize', 16, ...
                'markerFaceAlpha', 1.0, ...
                'markerLineWidth', 1.0, ...
                'markerEdgeAlpha', 1.0, ...
                'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
                'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);
        end
    end % iExemplar
end


function aggregatedRunParams = generateRunParamsForMultipleTargetVisualSTFs(targetVisualSTFdescriptorsToBeAggregated)

    aggregatedRunParams = zeros(numel(targetVisualSTFdescriptorsToBeAggregated),2);
    for iRun = 1:numel(targetVisualSTFdescriptorsToBeAggregated)
        pStruct = RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct(targetVisualSTFdescriptorsToBeAggregated{iRun});
        aggregatedRunParams(iRun,:) = ...
            [pStruct.surroundToCenterRcRatioMultiplier pStruct.surroundToCenterIntegratedSensitivityRatioMultiplier];
    end
end


function aggregateVisualizeAndExportBPIsAcrossMultipleTargetVisualSTFs(...
            mosaicEccDegs, whichSubjectID, ...
            aggregatedRunParams, ...
            LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, ...
            LeeShapleyAnalysisControlOptics, orientationSelection, ...
            surroundConnectedParamsStruct, ...
            targetedSurroundPurityRange, ...
            exemplarRGCs, ...
            bandpassIndexDensityMap, ...
            superimposeLeeShapleyData, ...
            onlyDepictLeeShapleyData);

    fprintf('Loading previously analyzed Lee-Shapley data from multiple targetVisualSTFs...')

    % The aggregated data matrices
    physioOpticsLconeCenterPeakSTFextension = [];
    physioOpticsMconeCenterPeakSTFextension = [];

    physioOpticsLconeCenterAchromaticSTFBPIs = [];
    physioOpticsLconeCenterConeIsolatingSTFBPIs = [];

    physioOpticsMconeCenterAchromaticSTFBPIs = [];
    physioOpticsMconeCenterConeIsolatingSTFBPIs = [];

    diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs = [];
    diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs = [];

    diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs = [];
    diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs = [];

    LconeCenterSurroundConePurities = [];
    MconeCenterSurroundConePurities = [];


    for iRun = 1:size(aggregatedRunParams,1)

        if (isempty(LeeShapleyAnalysisTestOpticsParam))
            % Add test and control optics, orientation selection, and target visual STF info
            matFileName = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%s_%s_%1.2f_%1.2f.mat', ...
                mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisControlOptics, ...
                orientationSelection, ...
                aggregatedRunParams(iRun,1),...
                aggregatedRunParams(iRun,2));
        else
            
            % Add test and control optics, orientation selection, and target visual STF info
            matFileName = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%2.2fD_%s_%s_%1.2f_%1.2f.mat', ...
                mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, LeeShapleyAnalysisControlOptics, ...
                orientationSelection, ...
                aggregatedRunParams(iRun,1),...
                aggregatedRunParams(iRun,2));
        end

        if (~isempty(surroundConnectedParamsStruct.customLMSconeDensities))
            matFileName = strrep(matFileName, 'LeeShapleySimulation', ...
                sprintf('LeeShapleySimulation_%d_%d_%d',...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(1)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(2)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(3)*100)));
        end

        matFileName = fullfile(RGCMosaicConstructor.filepathFor.intermediateDataDir, ...
                    'SLIM', 'demos', 'LeeShapleyAnalyses', matFileName);

        fprintf('Agreggating data for multiple condition runs (%d/%d) from %s\n', iRun, size(aggregatedRunParams,1), matFileName);
        load(matFileName, 'dataOut');

        % Aggregate data 
        idx = find(...
            (dataOut.LconeCenter.surroundConePurities >= targetedSurroundPurityRange(1)) & ...
            (dataOut.LconeCenter.surroundConePurities <= targetedSurroundPurityRange(2)));

        newData = dataOut.LconeCenter.physiologicalOptics.peakSTFextension(:,idx);
        physioOpticsLconeCenterPeakSTFextension = cat(1, ...
             physioOpticsLconeCenterPeakSTFextension, ...
             newData');

        newData = dataOut.LconeCenter.physiologicalOptics.achromaticBPIs(idx);
        physioOpticsLconeCenterAchromaticSTFBPIs = cat(1, ...       
            physioOpticsLconeCenterAchromaticSTFBPIs(:), ...
            newData(:));
        newData = dataOut.LconeCenter.diffractionLimitedOptics.achromaticBPIs(idx);
        diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs = cat(1, ...       
            diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs(:), ...
            newData(:));

        newData = dataOut.LconeCenter.physiologicalOptics.coneIsolatingBPIs(idx);
        physioOpticsLconeCenterConeIsolatingSTFBPIs = cat(1, ...
            physioOpticsLconeCenterConeIsolatingSTFBPIs(:), ...
            newData(:));
        newData = dataOut.LconeCenter.diffractionLimitedOptics.coneIsolatingBPIs(idx);
        diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs = cat(1, ...
            diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs(:), ...
            newData(:));

        newData = dataOut.LconeCenter.surroundConePurities(idx);
        LconeCenterSurroundConePurities = cat(1, ...
            LconeCenterSurroundConePurities(:), ...
            newData(:));

        idx = find(...
            (dataOut.MconeCenter.surroundConePurities >= targetedSurroundPurityRange(1)) & ...
            (dataOut.MconeCenter.surroundConePurities <= targetedSurroundPurityRange(2)));

        newData = dataOut.MconeCenter.physiologicalOptics.peakSTFextension(:,idx);
        physioOpticsMconeCenterPeakSTFextension = cat(1, ...
             physioOpticsMconeCenterPeakSTFextension, ...
             newData');

        newData = dataOut.MconeCenter.physiologicalOptics.achromaticBPIs(idx);
        physioOpticsMconeCenterAchromaticSTFBPIs = cat(1, ...
            physioOpticsMconeCenterAchromaticSTFBPIs(:), ...
            newData(:));
        newData = dataOut.MconeCenter.diffractionLimitedOptics.achromaticBPIs(idx);
        diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs = cat(1, ...
            diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs(:), ...
            newData(:));

        newData = dataOut.MconeCenter.physiologicalOptics.coneIsolatingBPIs(idx);
        physioOpticsMconeCenterConeIsolatingSTFBPIs = cat(1, ...
            physioOpticsMconeCenterConeIsolatingSTFBPIs (:), ...
            newData(:));
        newData = dataOut.MconeCenter.diffractionLimitedOptics.coneIsolatingBPIs(idx);
        diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs = cat(1, ...
            diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs (:), ...
            newData(:));

        newData = dataOut.MconeCenter.surroundConePurities(idx);
        MconeCenterSurroundConePurities = cat(1, ...
            MconeCenterSurroundConePurities(:), ...
            newData(:));
    end % for iRun

    if (isempty(LeeShapleyAnalysisTestOpticsParam))
        % Save the aggregated data for the examined (LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam)
        aggregatedRunsMatFile = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%s_%s_aggregatedOverExaminedTargetVisualSTFs.mat', ...
                mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisControlOptics, ...
                orientationSelection);
    else
        % Save the aggregated data for the examined (LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam)
        aggregatedRunsMatFile = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%2.2fD_%s_%s_aggregatedOverExaminedTargetVisualSTFs.mat', ...
                mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam, LeeShapleyAnalysisControlOptics, ...
                orientationSelection);
    end

    if (~isempty(surroundConnectedParamsStruct.customLMSconeDensities))
            aggregatedRunsMatFile = strrep(aggregatedRunsMatFile, 'LeeShapleySimulation', ...
                sprintf('LeeShapleySimulation_%d_%d_%d',...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(1)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(2)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(3)*100)));
    end

    aggregatedRunsMatFile = fullfile(RGCMosaicConstructor.filepathFor.intermediateDataDir, ...
                    'SLIM', 'demos', 'LeeShapleyAnalyses', aggregatedRunsMatFile);

    save(aggregatedRunsMatFile, ...
        'physioOpticsLconeCenterPeakSTFextension', ...
        'physioOpticsMconeCenterPeakSTFextension', ...
        'physioOpticsLconeCenterAchromaticSTFBPIs', ...
        'physioOpticsLconeCenterConeIsolatingSTFBPIs', ...
        'physioOpticsMconeCenterAchromaticSTFBPIs', ...
        'physioOpticsMconeCenterConeIsolatingSTFBPIs', ...
        'diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs', ...
        'diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs', ...
        'diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs', ...
        'diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs', ...
        'LconeCenterSurroundConePurities', ...
        'MconeCenterSurroundConePurities'...
        );
    fprintf('Saved aggregated data to %s\n', aggregatedRunsMatFile);


    % L-center RGCs, physiological optics
    figNo = 3000 + 10;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        physioOpticsLconeCenterAchromaticSTFBPIs, ...
        physioOpticsLconeCenterConeIsolatingSTFBPIs, ...
        LconeCenterSurroundConePurities, ...
        cMosaic.LCONE_ID, ...
        '', ... %'agreggateOverMultipleRunsBPIscatterPlotLconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIhistogramsLconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIvsSurroundConePurityLconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIdensityPlotLconeCenterNaturalOptics.pdf', ...
        'agreggateOverMultipleRunsBPIprctilePlotLconeCenterNaturalOptics.pdf', ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 16, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'onlyDepictLeeShapleyData', onlyDepictLeeShapleyData, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize',  bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

    % M-center RGCs, physiological optics
    figNo = 3000 + 20;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        physioOpticsMconeCenterAchromaticSTFBPIs , ...
        physioOpticsMconeCenterConeIsolatingSTFBPIs, ...
        MconeCenterSurroundConePurities, ...
        cMosaic.MCONE_ID, ...
        '', ... %'agreggateOverMultipleRunsBPIscatterPlotMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIhistogramsMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIvsSurroundConePurityMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIdensityPlotMconeCenterNaturalOptics.pdf', ...
        'agreggateOverMultipleRunsBPIprctilePlotMconeCenterNaturalOptics.pdf', ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 16, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'onlyDepictLeeShapleyData', onlyDepictLeeShapleyData, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

    % L- and M-center RGCs combined, physiological optics
    figNo = 3000 + 25;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        cat(1,physioOpticsLconeCenterAchromaticSTFBPIs(:), physioOpticsMconeCenterAchromaticSTFBPIs(:)) , ...
        cat(1, physioOpticsLconeCenterConeIsolatingSTFBPIs(:), physioOpticsMconeCenterConeIsolatingSTFBPIs(:)), ...
        cat(1, LconeCenterSurroundConePurities(:), MconeCenterSurroundConePurities(:)), ...
        -99, ...
        '', ... %'agreggateOverMultipleRunsBPIscatterPlotMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIhistogramsMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIvsSurroundConePurityMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIdensityPlotMconeCenterNaturalOptics.pdf', ...
        'agreggateOverMultipleRunsBPIprctilePlotLMcombinedNaturalOptics.pdf', ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 16, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'onlyDepictLeeShapleyData', onlyDepictLeeShapleyData, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);


    % L-center RGCs, diffraction-limited optics
    figNo = 3000 + 30;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs , ...
        diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs, ...
        LconeCenterSurroundConePurities, ...
        cMosaic.LCONE_ID, ...
        '', ... %'agreggateOverMultipleRunsBPIscatterPlotLconeCenterDiffractionLimitedOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIhistogramsLconeCenterDiffractionLimitedOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIvsSurroundConePurityLconeCenterDiffractionLimitedOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIdensityPlotLconeCenterDiffractionLimitedOptics.pdf', ...
        'agreggateOverMultipleRunsBPIprctilePlotLconeCenterDiffractionLimitedOptics.pdf', ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 16, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'onlyDepictLeeShapleyData', onlyDepictLeeShapleyData, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);


    % M-center RGCs, diffraction-limited optics
    figNo = 3000 + 40;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs , ...
        diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs, ...
        MconeCenterSurroundConePurities, ...
        cMosaic.MCONE_ID, ...
        '', ... %'agreggateOverMultipleRunsBPIscatterPlotMconeCenterDiffractionLimitedOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIhistogramsMconeCenterDiffractionLimitedOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIvsSurroundConePurityMconeCenterDiffractionLimitedOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIdensityPlotMconeCenterDiffractionLimitedOptics.pdf', ...
        'agreggateOverMultipleRunsBPIprctilePlotMconeCenterDiffractionLimitedOptics.pdf', ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 16, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'onlyDepictLeeShapleyData', onlyDepictLeeShapleyData, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

    % L- and M-center RGCs combined, diffraction-limited optics
    figNo = 3000 + 45;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        cat(1, diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs(:), diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs (:)) , ...
        cat(1, diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs(:), diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs(:)), ...
        cat(1, LconeCenterSurroundConePurities(:), MconeCenterSurroundConePurities(:)), ...
        -99, ...
        '', ... %'agreggateOverMultipleRunsBPIscatterPlotMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIhistogramsMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIvsSurroundConePurityMconeCenterNaturalOptics.pdf', ...
        '', ... %'agreggateOverMultipleRunsBPIdensityPlotMconeCenterNaturalOptics.pdf', ...
        'agreggateOverMultipleRunsBPIprctilePlotLMcombinedDiffractionLimitedOptics.pdf', ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 16, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'onlyDepictLeeShapleyData', onlyDepictLeeShapleyData, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

    maxSTFamplitude = 0.6;

    if (1==1)
    fprintf('Hit enter to visualize exemplar RGCs for the last aggregated run: %f %f\n',  aggregatedRunParams(end,1),  aggregatedRunParams(end,2));
    pause;

    for iExemplarRGCindex = 1:numel(dataOut.exemplarRGCdata)
        d = dataOut.exemplarRGCdata{iExemplarRGCindex};
        if (~ismember(d.rgcIndex, exemplarRGCs.fixedRGCindices))
            continue;
        end



        figNo = 5000 + iExemplarRGCindex*10;
        thePDFFileName = sprintf('diffractionLimitedOpticsSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingSTFs(figNo, ...
            d.rgcIndex, d.rfCenterConeDominance, ...
            d.diffractionLimitedSTF.sfSupport, d.diffractionLimitedSTF.achromaticSTF, ...
            d.diffractionLimitedSTF.lConeIsolatingSTF, d.diffractionLimitedSTF.mConeIsolatingSTF, ...
            d.diffractionLimitedSTF.achromaticSTFBPI, ...
            d.diffractionLimitedSTF.lConeIsolatingSTFBPI , ...
            d.diffractionLimitedSTF.mConeIsolatingSTFBPI , ...
            maxSTFamplitude, ... %d.maxSTF, ...
            thePDFFileName, ...
            'markerSizeBoost', 4, ...
            'lineWidthBoost', 1.5, ...
            'spatialFrequencyLims', [0.1 100], ...
            'squareAxes', true);

        figNo = 5000 + iExemplarRGCindex*20;
        thePDFFileName = sprintf('physiologicalOpticsSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingSTFs(figNo, ...
            d.rgcIndex, d.rfCenterConeDominance, ......
            d.physiologicalSTF.sfSupport, d.physiologicalSTF.achromaticSTF , ...
            d.physiologicalSTF.lConeIsolatingSTF, d.physiologicalSTF.mConeIsolatingSTF, ...
            d.physiologicalSTF.achromaticSTFBPI, ...
            d.physiologicalSTF.lConeIsolatingSTFBPI , ...
            d.physiologicalSTF.mConeIsolatingSTFBPI , ...
            maxSTFamplitude, ... %d.maxSTF, ...
            thePDFFileName, ...
            'markerSizeBoost', 4, ...
            'lineWidthBoost', 1.5, ...
            'spatialFrequencyLims', [0.1 100], ...
            'squareAxes', true);


        figNo = 5000 + iExemplarRGCindex*30;
        thePDFFileName = sprintf('physiologicalOpticsFullSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingFullSTFs(figNo, ...
            d.rgcIndex, ...
            d.rfCenterConeDominance, ...
            d.physiologicalSTF.optimalOrientation, ...
            d.physiologicalSTF.sfSupportFullSTF, d.physiologicalSTF.orientationSupport, ...
            d.physiologicalSTF.achromaticFullSTF, ...
            d.physiologicalSTF.lConeIsolatingFullSTF, ...
            d.physiologicalSTF.mConeIsolatingFullSTF, ...
            thePDFFileName);

        figNo = 5000 + iExemplarRGCindex*40;
        thePDFFileName = sprintf('diffractionLimitedOpticsFullSTF_exemplarRGC%d.pdf', d.rgcIndex);
        RGCMosaicAnalyzer.visualize.achromaticAndConeIsolatingFullSTFs(figNo, ...
            d.rgcIndex, ...
            d.rfCenterConeDominance, ...
            d.diffractionLimitedSTF.optimalOrientation, ...
            d.diffractionLimitedSTF.sfSupportFullSTF, d.diffractionLimitedSTF.orientationSupport, ...
            d.diffractionLimitedSTF.achromaticFullSTF, ...
            d.diffractionLimitedSTF.lConeIsolatingFullSTF, ...
            d.diffractionLimitedSTF.mConeIsolatingFullSTF, ...
            thePDFFileName);

        figNo = 5000 + iExemplarRGCindex*50;
        thePDFfileName = sprintf('conePoolingWeightsMap_exemplarRGC%d.pdf', d.rgcIndex);
        thePlotTitle = sprintf('surround cone purity: %2.2f',d.surroundConePurity);
        RGCMosaicAnalyzer.visualize.exemplarRGCconePoolingMap(figNo, ...
            dataOut.theMRGCMosaic, d.rgcIndex, thePDFfileName, ...
            'fixedSpatialSupportTickSeparationArcMin', 4.0, ...
            'fixedScalaBarDegs', 0.05, ...
            'plotTitle', thePlotTitle);

    end % iExemplar
    end
end

function analyzeBPIsForRefractionErrorRelativeToOptimalAchromaticRefraction(...
    mosaicEccDegs, whichSubjectID, surroundConnectedParamsStruct, ...
    desiredResidualErrorInRefractionIndex, orientationSelection, bandpassIndexDensityMap, ...
    superimposeLeeShapleyData)   

    LeeShapleyAnalysisControlOptics = 'adaptiveOptics6MM';

    LeeShapleyAnalysisTestOpticsList = [];
    LeeShapleyAnalysisTestOpticsParamList = [];

    % Residual defocus: -0.25
    LeeShapleyAnalysisTestOpticsList{numel(LeeShapleyAnalysisTestOpticsList)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParamList{numel(LeeShapleyAnalysisTestOpticsParamList)+1} = -0.25;
   
    % Residual refraction: 0.0D (optimized Strehl ratio)
    LeeShapleyAnalysisTestOpticsList{numel(LeeShapleyAnalysisTestOpticsList)+1} = 'nativeOptics';
    LeeShapleyAnalysisTestOpticsParamList{numel(LeeShapleyAnalysisTestOpticsParamList)+1} = [];

    % Residual defocus:+ 0.25D
    LeeShapleyAnalysisTestOpticsList{numel(LeeShapleyAnalysisTestOpticsList)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParamList{numel(LeeShapleyAnalysisTestOpticsParamList)+1} = 0.25;

    % Residual defocus: + 0.50D 
    LeeShapleyAnalysisTestOpticsList{numel(LeeShapleyAnalysisTestOpticsList)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParamList{numel(LeeShapleyAnalysisTestOpticsParamList)+1} = 0.50;

    % Residual defocus: + 0.75D
    LeeShapleyAnalysisTestOpticsList{numel(LeeShapleyAnalysisTestOpticsList)+1} = 'refractionResidualWithRespectToNativeOptics';
    LeeShapleyAnalysisTestOpticsParamList{numel(LeeShapleyAnalysisTestOpticsParamList)+1} = 0.75;

    for iRefraction = 1:numel(LeeShapleyAnalysisTestOpticsList)
        % Load the aggregated data for the examined (LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam)
        if (isempty(LeeShapleyAnalysisTestOpticsParamList{iRefraction}))
            aggregatedRunsMatFile = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%s_%s_aggregatedOverExaminedTargetVisualSTFs.mat', ...
                    mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                    LeeShapleyAnalysisTestOpticsList{iRefraction}, LeeShapleyAnalysisControlOptics, ...
                    orientationSelection);
        else
            aggregatedRunsMatFile = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%2.2fD_%s_%s_aggregatedOverExaminedTargetVisualSTFs.mat', ...
                    mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                    LeeShapleyAnalysisTestOpticsList{iRefraction}, LeeShapleyAnalysisTestOpticsParamList{iRefraction}, LeeShapleyAnalysisControlOptics, ...
                    orientationSelection);
        end


        if (~isempty(surroundConnectedParamsStruct.customLMSconeDensities))
            aggregatedRunsMatFile = strrep(aggregatedRunsMatFile, 'LeeShapleySimulation', ...
                sprintf('LeeShapleySimulation_%d_%d_%d',...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(1)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(2)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(3)*100)));
        end

        aggregatedRunsMatFile = fullfile(RGCMosaicConstructor.filepathFor.intermediateDataDir, ...
                    'SLIM', 'demos', 'LeeShapleyAnalyses', aggregatedRunsMatFile);

        load(aggregatedRunsMatFile, 'physioOpticsLconeCenterPeakSTFextension', 'physioOpticsMconeCenterPeakSTFextension');
        physioOpticsLconeCenterPeakSTFextensionAllRefractions(iRefraction,:,:) = physioOpticsLconeCenterPeakSTFextension;
        physioOpticsMconeCenterPeakSTFextensionAllRefractions(iRefraction,:,:) = physioOpticsMconeCenterPeakSTFextension;
    end % for iRefraction

    optimalRefractionCriterion = 2;  % choose either 1 (max STF) or 2 (max STF extension)
    [~,optimalRefractionIndexLconeCenterRGCs] = max(squeeze(physioOpticsLconeCenterPeakSTFextensionAllRefractions(:, :, optimalRefractionCriterion)), [], 1);
    [~,optimalRefractionIndexMconeCenterRGCs] = max(squeeze(physioOpticsMconeCenterPeakSTFextensionAllRefractions(:, :, optimalRefractionCriterion)), [], 1);


    if isempty(desiredResidualErrorInRefractionIndex)
        r = randn(size(optimalRefractionIndexLconeCenterRGCs));
        r(r < -1) = -1;
        r(r > 1) = 1;
        r(abs(r)<1) = 0;
        optimalRefractionIndexLconeCenterRGCs = min(max(optimalRefractionIndexLconeCenterRGCs + r, 1),numel(LeeShapleyAnalysisTestOpticsList));

        r = randn(size(optimalRefractionIndexMconeCenterRGCs));
        r(r < -1) = -1;
        r(r > 1) = 1;
        r(abs(r)<1) = 0;
        optimalRefractionIndexMconeCenterRGCs = min(max(optimalRefractionIndexMconeCenterRGCs + r, 1),numel(LeeShapleyAnalysisTestOpticsList));

    else
        optimalRefractionIndexLconeCenterRGCs = min(max(optimalRefractionIndexLconeCenterRGCs + desiredResidualErrorInRefractionIndex, 1),numel(LeeShapleyAnalysisTestOpticsList));
        optimalRefractionIndexMconeCenterRGCs = min(max(optimalRefractionIndexMconeCenterRGCs + desiredResidualErrorInRefractionIndex, 1),numel(LeeShapleyAnalysisTestOpticsList));
    end

    physioOpticsOptimizedRefractionLconeCenterAchromaticSTFBPIs = zeros(1, numel(optimalRefractionIndexLconeCenterRGCs));
    physioOpticsOptimizedRefractionLconeCenterConeIsolatingSTFBPIs = zeros(1, numel(optimalRefractionIndexLconeCenterRGCs));

    physioOpticsOptimizedRefractionMconeCenterAchromaticSTFBPIs = zeros(1, numel(optimalRefractionIndexMconeCenterRGCs));
    physioOpticsOptimizedRefractionMconeCenterConeIsolatingSTFBPIs = zeros(1, numel(optimalRefractionIndexMconeCenterRGCs));

    for iRefraction = 1:numel(LeeShapleyAnalysisTestOpticsList)
        % Load the aggregated data for the examined (LeeShapleyAnalysisTestOptics, LeeShapleyAnalysisTestOpticsParam)
        if (isempty(LeeShapleyAnalysisTestOpticsParamList{iRefraction}))
            aggregatedRunsMatFile = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%s_%s_aggregatedOverExaminedTargetVisualSTFs.mat', ...
                mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                LeeShapleyAnalysisTestOpticsList{iRefraction}, LeeShapleyAnalysisControlOptics, ...
                orientationSelection);
        else
            aggregatedRunsMatFile = sprintf('LeeShapleySimulation_EccDegs_%2.1f_%2.1f_PolansOptics_%d_%s_%2.2fD_%s_%s_aggregatedOverExaminedTargetVisualSTFs.mat', ...
                mosaicEccDegs(1), mosaicEccDegs(2), whichSubjectID, ...
                LeeShapleyAnalysisTestOpticsList{iRefraction}, LeeShapleyAnalysisTestOpticsParamList{iRefraction}, LeeShapleyAnalysisControlOptics, ...
                orientationSelection);
        end

        if (~isempty(surroundConnectedParamsStruct.customLMSconeDensities))
            aggregatedRunsMatFile = strrep(aggregatedRunsMatFile, 'LeeShapleySimulation', ...
                sprintf('LeeShapleySimulation_%d_%d_%d',...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(1)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(2)*100), ...
                 round(surroundConnectedParamsStruct.customLMSconeDensities(3)*100)));
        end

        aggregatedRunsMatFile = fullfile(RGCMosaicConstructor.filepathFor.intermediateDataDir, ...
                    'SLIM', 'demos', 'LeeShapleyAnalyses', aggregatedRunsMatFile);

        load(aggregatedRunsMatFile, ...
            'physioOpticsLconeCenterPeakSTFextension', ...
            'physioOpticsMconeCenterPeakSTFextension', ...
            'physioOpticsLconeCenterAchromaticSTFBPIs', ...
            'physioOpticsLconeCenterConeIsolatingSTFBPIs', ...
            'physioOpticsMconeCenterAchromaticSTFBPIs', ...
            'physioOpticsMconeCenterConeIsolatingSTFBPIs', ...
            'diffractionLimitedOpticsLconeCenterAchromaticSTFBPIs', ...
            'diffractionLimitedOpticsLconeCenterConeIsolatingSTFBPIs', ...
            'diffractionLimitedOpticsMconeCenterAchromaticSTFBPIs', ...
            'diffractionLimitedOpticsMconeCenterConeIsolatingSTFBPIs', ...
            'LconeCenterSurroundConePurities', ...
            'MconeCenterSurroundConePurities'...
            );

            for iRGC = 1:numel(physioOpticsLconeCenterAchromaticSTFBPIs)
                if (optimalRefractionIndexLconeCenterRGCs(iRGC) == iRefraction)
                    if (physioOpticsOptimizedRefractionLconeCenterAchromaticSTFBPIs(iRGC) ~= 0)
                        error('How can this be?')
                    end
                    physioOpticsOptimizedRefractionLconeCenterAchromaticSTFBPIs(iRGC) = physioOpticsLconeCenterAchromaticSTFBPIs(iRGC);
                    physioOpticsOptimizedRefractionLconeCenterConeIsolatingSTFBPIs(iRGC) = physioOpticsLconeCenterConeIsolatingSTFBPIs(iRGC);
                end
            end

            for iRGC = 1:numel(physioOpticsMconeCenterAchromaticSTFBPIs)
                if (optimalRefractionIndexMconeCenterRGCs(iRGC) == iRefraction)
                    if (physioOpticsOptimizedRefractionMconeCenterAchromaticSTFBPIs(iRGC) ~= 0)
                        error('How can this be?')
                    end
                    physioOpticsOptimizedRefractionMconeCenterAchromaticSTFBPIs(iRGC) = physioOpticsMconeCenterAchromaticSTFBPIs(iRGC);
                    physioOpticsOptimizedRefractionMconeCenterConeIsolatingSTFBPIs(iRGC) = physioOpticsMconeCenterConeIsolatingSTFBPIs(iRGC);
                end
            end
    end % for iRefraction

    if (isempty(desiredResidualErrorInRefractionIndex))
        thePDFfile = sprintf('achromaticOptimizedOpticsBPIprctilePlotLconeCenterNaturalOptics_RandomResidualError.pdf');
    else
        thePDFfile = sprintf('achromaticOptimizedOpticsBPIprctilePlotLconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex);
    end


    % L-center RGCs, physiological optics
    figNo = 3333 + 10;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        physioOpticsOptimizedRefractionLconeCenterAchromaticSTFBPIs, ...
        physioOpticsOptimizedRefractionLconeCenterConeIsolatingSTFBPIs, ...
        LconeCenterSurroundConePurities, ...
        cMosaic.LCONE_ID, ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIscatterPlotLconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIhistogramsLconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIvsSurroundConePurityLconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIdensityPlotLconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        thePDFfile, ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 12, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize',  bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

    if (isempty(desiredResidualErrorInRefractionIndex))
        thePDFfile = sprintf('achromaticOptimizedOpticsBPIprctilePlotMconeCenterNaturalOptics_RandomResidualError.pdf');
    else
        thePDFfile = sprintf('achromaticOptimizedOpticsBPIprctilePlotMconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex);
    end

    % M-center RGCs, physiological optics
    figNo = 4444 + 20;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        physioOpticsOptimizedRefractionMconeCenterAchromaticSTFBPIs, ...
        physioOpticsOptimizedRefractionMconeCenterConeIsolatingSTFBPIs, ...
        MconeCenterSurroundConePurities, ...
        cMosaic.MCONE_ID, ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIscatterPlotMconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIhistogramsMconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIvsSurroundConePurityMconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIdensityPlotMconeCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        thePDFfile, ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 12, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);

    if (isempty(desiredResidualErrorInRefractionIndex))
        thePDFfile = sprintf('achromaticOptimizedOpticsBPIprctilePlotCenterNaturalOptics_RandomResidualError.pdf');
    else
        thePDFfile = sprintf('achromaticOptimizedOpticsBPIprctilePlotCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex);
    end

    figNo = 4444 + 30;
    RGCMosaicAnalyzer.visualize.centerConeIsolatingVsAchromaticBPIscatterPlot(figNo, ...
        cat(1, physioOpticsOptimizedRefractionLconeCenterAchromaticSTFBPIs(:), physioOpticsOptimizedRefractionMconeCenterAchromaticSTFBPIs(:)), ...
        cat(1, physioOpticsOptimizedRefractionLconeCenterConeIsolatingSTFBPIs(:), physioOpticsOptimizedRefractionMconeCenterConeIsolatingSTFBPIs(:)), ...
        cat(1, LconeCenterSurroundConePurities(:), MconeCenterSurroundConePurities(:)), ...
        -99, ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIscatterPlotCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIhistogramsCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIvsSurroundConePurityCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        '', ... % sprintf('achromaticOptimizedOpticsBPIdensityPlotCenterNaturalOptics_ResidualError_%d.pdf', desiredResidualErrorInRefractionIndex), ...
        thePDFfile, ...
        'maxVisualizedBPIDensity', bandpassIndexDensityMap.maxVisualizedValue, ...
        'bpiInterval', bandpassIndexDensityMap.interval, ...
        'markerSize', 12, ...
        'markerFaceAlpha', 0.3, ...
        'markerLineWidth', 1.0, ...
        'markerEdgeAlpha', 0.3, ...
        'superimposeLeeShapleyData', superimposeLeeShapleyData, ...
        'superimposeLeeShapleyDataMarkerSize', bandpassIndexDensityMap.LeeShapleyDataMarkerSize);
end

function computeSTFresponses(theMRGCMosaic, opticsForSTFresponses, customRefractionDiopters, ...
    STFchromaticity, ...
    theInputConeMosaicSTFResponsesFullFileName, ...
    theMRGCMosaicSTFResponsesFullFileName, ...
    visualizeInputConeMosaicResponses, ...
    visualizePSFonTopOfConeMosaic)

    % Generate the optics
    [theOI, thePSF] = RGCMosaicAnalyzer.compute.opticsForResponses(...
        theMRGCMosaic, opticsForSTFresponses, customRefractionDiopters, visualizePSFonTopOfConeMosaic);

    % Determine the stimulus pixel resolution to be a fraction of the minimum cone aperture or cone spacing in the mosaic
    % here, half of the cone spacing
    theMetric = 'cone aperture';  % choose from {'cone aperture' or cone spacing'}
    mosaicRadialEcc = sqrt(sum(theMRGCMosaic.eccentricityDegs.^2,2));
    if ((strcmp(opticsForSTFresponses, 'adaptiveOptics6MM')) || (strcmp(opticsForSTFresponses, 'adaptiveOptics6MMwithLCA')))
        theFraction = 0.1;
    else
        theFraction = 0.25;
    end
    targetRGCindices =  1:theMRGCMosaic.rgcsNum;
    stimulusResolutionDegs = RGCMosaicConstructor.helper.simulateExperiment.stimulusResolutionFromConeApertureOrConeSpacing(...
                theMRGCMosaic, targetRGCindices, theFraction, theMetric);

    sfSupport = logspace(log10(0.01), log10(120), 20);
    orientationDeltaDegs = 30;
    spatialPhaseIncrementDegs = 30;

    STFparamsStruct = struct(...
        'backgroundChromaticity', [0.301 0.301], ...
        'backgroundLuminanceCdM2', 50.0, ...
        'chromaticity', STFchromaticity, ...
        'coneFundamentalsOptimizedForStimPosition', false, ...
        'resolutionDegs', stimulusResolutionDegs, ...                       % to be determined separately for each optimization position
        'sfSupport', sfSupport, ...
        'orientationDeltaDegs', orientationDeltaDegs, ...
        'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs, ...
        'positionDegs', theMRGCMosaic.eccentricityDegs, ...  
        'sizeDegs', 1.1*max(theMRGCMosaic.inputConeMosaic.sizeDegs));

    RGCMosaicConstructor.helper.simulateExperiment.spatialTransferFunction(...
        theMRGCMosaic, theOI, ...
        STFparamsStruct, ...
        theInputConeMosaicSTFResponsesFullFileName, ...
        theMRGCMosaicSTFResponsesFullFileName, ...
        'computeInputConeMosaicResponses', true, ...
        'computeMRGCMosaicResponses', false, ...
        'visualizeResponse', visualizeInputConeMosaicResponses);
end


