% Demo ways of modifying the apertures of a @cMosaic object
%
% Description:
%    Shows how one can modify some properties of the cone aperture of a
%    @cMosaic object. 
%
% See Also:
%   t_cMosaicGenerate

% History:
%    09/28/21  NPC  ISETBIO Team, Copyright 2021 Wrote it.


%% Initialize
ieInit;
clear;
close all;

%% Generate the ring rays stimulus
parms.freq = 30;
parms.contrast = 1;
parms.ph = 90;
parms.ang = 0;
parms.row = 512;
parms.col = 512;
parms.GaborFlag = 0;
scene = sceneCreate('harmonic', parms);
scene = sceneSet(scene, 'fov', 0.7);


%% Generate a @cMosaic object by cropping a region from a large (45x45 deg)
%% precomputed lattice. This is the fastest way to generate a @cMosaic at any eccentricity
cm = cMosaic(...
    'sizeDegs', [0.4 0.4], ...     % SIZE: x=0.2 degs, y=0.2 degs
    'eccentricityDegs', [0 0], ...  % ECC:  x=0 deg, y= 1 deg, near the edge of the precomputed 45x45 mosaic
    'integrationTime', 1000/1000 ...
    );
cm.eccVaryingConeBlur = true;
    
    
%% Compute the optical image
theOI = oiCreate;
theOI = oiCompute(scene, theOI);


%% Setup plotting
sv = NicePlot.getSubPlotPosVectors(...
       'rowsNum', 3, ...
       'colsNum', 6, ...
       'heightMargin',  0.12, ...
       'widthMargin',    0.04, ...
       'leftMargin',     0.01, ...
       'rightMargin',    0.01, ...
       'bottomMargin',   0.06, ...
       'topMargin',      0.02);
   
hFig = figure(1);
set(hFig, 'Position', [10 10 2500 1200]);



activationRange = [];
instancesNum = 1;


noiseFreeExcitationResponse1 = cm.compute(theOI, 'nTrials', instancesNum);
activationRange = prctile(noiseFreeExcitationResponse1(:), [1 99]);

% By default the aperture sizes are smoothed locally
ax = subplot('Position', sv(1,1).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'domain', 'degrees', ...
    'visualizedConeAperture', 'geometricArea', ...
    'plotTitle', 'smoothed aperture sizes');

ax = subplot('Position', sv(2,1).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse1, ...
    'activationRange', activationRange, ...
    'visualizedConeAperture', 'geometricArea', ...
    'verticalActivationColorBarInside', true, ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', 'smoothed aperture sizes');

% Do not smooth locally the aperture size variations
newConeApertureModifiers = cm.coneApertureModifiers;
newConeApertureModifiers.smoothLocalVariations = false;
cm.coneApertureModifiers = newConeApertureModifiers;
noiseFreeExcitationResponse2 = cm.compute(theOI, 'nTrials', instancesNum);

ax = subplot('Position', sv(1,2).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'domain', 'degrees', ...
    'visualizedConeAperture', 'geometricArea', ...
    'plotTitle', 'non-smoothed aperture sizes');

ax = subplot('Position', sv(2,2).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse2, ...
    'activationRange', activationRange, ...
    'visualizedConeAperture', 'geometricArea', ...
    'verticalActivationColorBarInside', true, ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', 'non-smoothed aperture sizes');

% Smooth locally the aperture size variations
newConeApertureModifiers = cm.coneApertureModifiers;
newConeApertureModifiers.smoothLocalVariations = true;
cm.coneApertureModifiers = newConeApertureModifiers;

%Set an coneDiameterToSpacingRatio of 0.5
cm.coneDiameterToSpacingRatio = 0.5;

noiseFreeExcitationResponse3 = cm.compute(theOI, 'nTrials', instancesNum);

ax = subplot('Position', sv(1,3).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'domain', 'degrees', ...
    'visualizedConeAperture', 'geometricArea', ...
    'plotTitle', 'coneDiameterToSpacingRatio = 0.5');

ax = subplot('Position', sv(2,3).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse3, ...
    'activationRange', activationRange, ...
    'verticalActivationColorBarInside', true, ...
    'visualizedConeAperture', 'geometricArea', ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', 'coneDiameterToSpacingRatio = 0.5');




% Pillbox matching the integration in coneMosaicHex apertures
newConeApertureModifiers = cm.coneApertureModifiers;
newConeApertureModifiers.smoothLocalVariations = true;
newConeApertureModifiers.shape = 'Pillbox';
newConeApertureModifiers.PillboxApertureIntegrationMatching = 'ConeMosaicHex';
cm.coneApertureModifiers = newConeApertureModifiers;
cm.coneDiameterToSpacingRatio = 1.0;
noiseFreeExcitationResponse4A = cm.compute(theOI, 'nTrials', instancesNum);


ax = subplot('Position', sv(1,4).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'domain', 'degrees', ...
    'visualizedConeAperture', 'geometricArea', ...
    'plotTitle', sprintf('Pillbox aperture'));

ax = subplot('Position', sv(2,4).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse4A, ...
    'activationRange', activationRange, ...
    'verticalActivationColorBarInside', true, ...
    'visualizedConeAperture', 'geometricArea', ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', sprintf('Pillbox aperture - matching coneMosaicHex'));


% Pillbox matching the integration of Gaussian apertures
newConeApertureModifiers = cm.coneApertureModifiers;
newConeApertureModifiers.smoothLocalVariations = true;
newConeApertureModifiers.shape = 'Pillbox';
newConeApertureModifiers.PillboxApertureIntegrationMatching = 'ChenMakousWilliams1993';
cm.coneApertureModifiers = newConeApertureModifiers;
cm.coneDiameterToSpacingRatio = 1.0;
noiseFreeExcitationResponse4B = cm.compute(theOI, 'nTrials', instancesNum);


ax = subplot('Position', sv(1,5).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'domain', 'degrees', ...
    'visualizedConeAperture', 'geometricArea', ...
    'plotTitle', sprintf('Pillbox aperture'));

ax = subplot('Position', sv(2,5).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse4B, ...
    'activationRange', activationRange, ...
    'verticalActivationColorBarInside', true, ...
    'visualizedConeAperture', 'geometricArea', ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', sprintf('Pillbox aperture - matching coneMosaicHex'));


% Gaussian aperture
newConeApertureModifiers = cm.coneApertureModifiers;
newConeApertureModifiers.smoothLocalVariations = true;
newConeApertureModifiers.shape = 'Gaussian';
newConeApertureModifiers.sigma = 0.204;
cm.coneApertureModifiers = newConeApertureModifiers;
noiseFreeExcitationResponse5 = cm.compute(theOI, 'nTrials', instancesNum);

ax = subplot('Position', sv(1,6).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'domain', 'degrees', ...
    'visualizedConeAperture', 'geometricArea', ...
    'plotTitle', sprintf('Gaussian aperture'));

ax = subplot('Position', sv(2,6).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse5, ...
    'activationRange', activationRange, ...
    'visualizedConeAperture', 'geometricArea', ...
    'verticalActivationColorBarInside', true, ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', sprintf('Gaussian aperture'));


ax = subplot('Position', sv(3,4).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse5-noiseFreeExcitationResponse4A, ...
    'visualizedConeAperture', 'geometricArea', ...
    'verticalActivationColorBarInside', true, ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', sprintf('differential response\n(Gaussian-Pillbox matching coneMosaicHex)'));

ax = subplot('Position', sv(3,5).v);
cm.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'activation', noiseFreeExcitationResponse5-noiseFreeExcitationResponse4B, ...
    'visualizedConeAperture', 'geometricArea', ...
    'verticalActivationColorBarInside', true, ...
    'domain', 'degrees', ...
    'backgroundColor', [0 0 0], ...
    'colorbarTickLabelColor', [0 1 0], ...
    'plotTitle', sprintf('differential response\n(Gaussian-Pillbox matching ChenMakoutWilliams1993)'));

