function [RGCRFinputs, RGCRFweights] = wireInputConeMosaicToRGCRFs(...
        theInputConeMosaic, RGCRFposMicrons, ...
        chromaticSpatialVarianceTradeoff, ...
        sequentialConeTypeWiring, ...
        maxNearbyRGCsNum, ...
        visualizeProgression)
% Wire the input cone mosaic to the RF centers of a set of RGCs
%
% Syntax:
%   [RGCRFinputs, RGCRFweights] = RGCRFconnector.wireInputConeMosaicToRGCRFs(...
%        theInputConeMosaic, RGCRFposMicrons, ...
%        chromaticSpatialVarianceTradeoff, ...
%        sequentialConeTypeWiring, ...
%        maxNearbyRGCsNum, ...
%        visualizeProgression)
%
% Description:
%   Wire the input cone mosaic to the RF centers of a set of RGCs
%
% Inputs:
%    theInputConeMosaic                 - the input cone mosaic
%    RGCRFposMicrons                    - [M x 2] matrix of (x,y) positions (in microns) of M target RGC RF centers
%    chromaticSpatialVarianceTradeoff   - Chromatic-SpatialVariance tradefoff
%    sequentialConeTypeWiring           - Logical. Whether to wire cone types sequentially or not
%    maxNearbyRGCsNum                   - Scalar. Max number of nearby RGCs to look for assignment, if a cone cannot
%                                         be assigned to its closest RGC because that RGC already has one input cone
%    visualizeProgression               - Boolean. Whether to visualize the different stages of the wiring
%
% Outputs:
%    RGCRFinputs                - Cell array with indices of the input cones, one cell per each target RGC RF center
%    RGCRFweights               - Cell array with weights of the input cones, one cell per each target RGC RF center   
%
% Optional key/value pairs
%   none
%   
% History:
%   5/11/2022       NPC     Wrote it
%

    allConeRFpositions = theInputConeMosaic.coneRFpositionsMicrons;
    allConeRFspacings = theInputConeMosaic.coneRFspacingsMicrons;
    allConeTypes = theInputConeMosaic.coneTypes;

    % Step1. Connect cones to the nearestRGC that minimizes the cost
    % according to the passed chromaticSpatialVarianceTradeoff
    [RGCRFinputs, RGCRFweights, availableZeroInputRGCsNum] = ...
        RGCRFconnector.connectEachConeToItsNearestRGC(...
            allConeRFpositions, ...
            allConeRFspacings, ...
            allConeTypes, ...
            RGCRFposMicrons, ...
            chromaticSpatialVarianceTradeoff, ...
            sequentialConeTypeWiring, ...
            maxNearbyRGCsNum, ...
            visualizeProgression);


    RGCRFconnector.reportConeInputStatistics(...
            chromaticSpatialVarianceTradeoff, ...
            RGCRFinputs, RGCRFweights, ...
            allConeRFpositions, ...
            allConeRFspacings, ...
            allConeTypes);
    


    availableZeroInputRGCsNum
    sConesNum = numel(find(theInputConeMosaic.coneTypes == cMosaic.SCONE_ID));
    

%     RGCRFconnector.costToMaintainInputCones(...
%         chromaticSpatialVarianceTradeoff, ...
%         inputConePositions, inputConeSpacings, ...
%         inputConeTypes, inputConeWeights);

end