% t_cMosaicReassignCones
%
% Demo basic usage of how to reassign the identity of cones in a @cMosaic.
%
% Description:
%    Shows how to reassign the identity of cones in a @cMosaic.
%

% History:
%    08/24/22  NPC  ISETBIO Team, Copyright 2022 Wrote it.


% Generate a small mosaic
c = cMosaic(...
    'sizeDegs', 2*[0.02 0.01], ...
    'noiseFlag', 'frozen', ...
    'randomSeed', 3, ...
    'useParfor', false);

% Visualize the mosaic, outlining the first 6 cones.
hFig = figure(1); clf;
beforeAxes = subplot(1, 2, 1);
c.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', beforeAxes, ...
    'domain', 'microns', ...
    'domainVisualizationLimits', 2*[-3.5 3.5 -2.5 2.5], ...
    'outlinedConesWithIndices', 1:6, ...
    'labelConesWithIndices', 1:6, ...
    'backgroundColor', [0 0 0], ...
    'plotTitle', 'before reassignment');


% Let cones [2 and 4] be S-cones
c.reassignTypeOfCones([2 4], cMosaic.SCONE_ID);

% Let cone 1 be an M-cone
c.reassignTypeOfCones(1, cMosaic.MCONE_ID);

% Let cones [3 and 5] be L-cones
c.reassignTypeOfCones([3 5], cMosaic.LCONE_ID);

% Visualize the result.
afterAxes = subplot(1, 2, 2);
c.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', afterAxes, ...
    'domain', 'microns', ...
    'domainVisualizationLimits', 2*[-3.5 3.5 -2.5 2.5], ...
    'outlinedConesWithIndices', 1:6, ...
    'labelConesWithIndices', 1:6, ...
    'backgroundColor', [0 0 0], ...
    'plotTitle', 'after reassignment');
