function  [mosaicCenterParams, rfModelParams, opticsParams] = generateDefaultMosaicAndOpticsParamStructs()

    % Position, size and eye of the mosaic
    mosaicCenterParams = struct(...
        'positionDegs',[0 0], ...
        'sizeDegs',  [3 3], ...        
        'whichEye', 'right eye');

    % index of the one of 4 H1 cells in Packer & Dacey (valid numbers: 1, 2, 3, or 4)
    H1cellIndex = 1;

    retinalConePoolingModel = sprintf('arbitraryCenterConeWeights_doubleExpH1cellIndex1SurroundWeights', H1cellIndex);

    % Params controlling the optimization of retinal cone pooling weights
    rfModelParams = struct(...
        'retinalConePoolingModel', retinalConePoolingModel, ...
        'H1cellIndex', H1cellIndex, ...                                          
        'centerConnectableConeTypes', [cMosaic.LCONE_ID cMosaic.MCONE_ID], ...   % cone types that can connect to the RF center
        'surroundConnectableConeTypes', [cMosaic.LCONE_ID cMosaic.MCONE_ID], ... % cone types that can connect to the RF surround
        'eccentricitySamplingGridHalfSamplesNum', 1 ...                          % generate R2VFTobjects at 2*gridHalfSamplesNum + 1 spatial positions        
    );
        
    % Optics for which the cone pooling weights are optimized
    opticsParams = struct(...
        'ZernikeDataBase', 'Polans2015', ...
        'subjectRankOrder', 6, ...
        'pupilDiameterMM', 3.0 ...
    );
end
