function adaptedData = riekeAdapt(sensor,params)
%Convert photon absorption rates at the sensor into cone photocurrent
%
%  adaptedData = riekeAdapt(sensor,params)
%
% The returned adapted data are in units of current (pico amps).  The size
% of adapted data is equal to the size of the time series of input photons.
% These are stored as a (x,y,t) array in the sensor.
% 
% In this case, the physiological differential equations for cones
% are implemented. The differential equations are (from Rieke's PPT)
%
%    1) d opsin(t) / dt = -sigma * opsin(t) + R*(t)          [3.1]
%    2) d PDE(t) / dt   = opsin(t) - phi * PDE(t) + eta      [3.8]
%    3) d cGMP(t) / dt  = S(t) - PDE(t) * cGMP(t)            [3.10, 3.13]
%    4) d Ca(t) / dt    = q * I(t) - beta * Ca(t)            [3.9]
%    5) d Ca_slow(t) / dt = - beta_slow * (Ca_slow(t)-Ca(t)) 
%    6) S(t) = smax / (1 + (Ca(t)/kGc)^n)                    [3.12]
%    7) I(t) = k * cGMP(t)^h / (1 + Ca_slow/Ca_dark)         [2.5, 2.6 ?]
%
% Here, S(t) corresponds to V_GC(Ca) in reference [1].
%
% This model gives a cone-by-cone time series for the current. To calculate
% the response requires a time-series of photon absorptions in the sensor
% structure.
%
% The default value of all the parameters are generated by function
% riekeInit
% 
%
% Comments:
%
% This is a very nonlinear set of equations that cannot be reduced to an
% auto-regressive (AR) formulation.  The difference between the
% steady-state responses with this adaptation model and the simpler ones
% (e.g., from Dunn et al.) is modest.  Though we should really check how
% much of an effect there is by running specific calculations that include
% noise.
%
% The advantage of this calculation is that it does a better job at
% capturing the rapid temporal fluctuations (ms timescale) than simpler
% models.  So, perhaps this should be used for cases where the rapid
% onset/offset voltage swings matter.  It may be less useful and not worth
% the extra computation for steady-state judgments.
%
% Problem ... the different equations always solve to a positive value.
% But the measured current reports are sometimes negative (HJ). It's
% possible to map this in / out current to some depolarization voltage
% values. I guess that mapping should be linear (HJ).
%
% Example:
%
%
% Reference:
% [1] Juan I. Korenbrot, Speed, adaptation, and stability of the response
%     to light in cone photoreceptors: The functional role of Ca-dependent
%     modulation of ligand sensitivity in cGMP-gated ion channels, The
%     Journal of General Physiology
%    
% HJ ISETBIO Team, 2013

%% Initialize parameters

% Number of isomerizations in a single integration time.
% We make sure these are double, not single.
photons = double(sensorGet(sensor, 'photons'));
if isempty(photons)
    error('Non-adapted cone absorptions (photons) should be pre-computed');
end

% Initialize the parameters for the adaptation model
p = riekeInit;
p.bgPhotons = median(photons(:));

% Now copy fields that are sent in
if ~notDefined('params')
    fields = fieldnames(params);
    for ii=1:length(fields), p.(fields{ii}) = params.(fields{ii}); end
end

%% Start calculation

% Convert to the rate of isomerizations per second
photons   = photons   / sensorGet(sensor, 'exposure time');
bgPhotons = p.bgPhotons / sensorGet(sensor, 'exposure time');

% This is stored in the eye movement structure.
dt = sensorGet(sensor, 'sample time interval');
if isempty(dt), dt = 1e-3; end

% Prior to the onset of the stimulus, there is some adaptation of the
% system.  This function estimates the background current, bgCur, at the
% initial time point by finding the current from the mean response.
bgCur = riekeAdaptSteadyState(bgPhotons,p);

% Compute initial values for the differential equations
opsin   = ones(sensorGet(sensor, 'size')) * bgPhotons / sigma;
PDE     = (opsin + eta) / phi;
Ca      = ones(sensorGet(sensor, 'size')) * bgCur * q / beta;
Ca_slow = Ca;
st      = smax ./ (1 + (Ca / kGc).^n);
cGMP    = st * phi ./ (opsin + eta);

% The units are some kind of current (pico ampere, 10^-12 amps)
% These are time course of the current at each of the photoreceptor sample
% points. 
% The time, dt, is the sample period.
adaptedData = zeros([size(opsin) size(volts, 3)]);

% Simulate differential equations from Fred's PowerPoint slides.
% The adapted data are in units of current (pico amps)
for ii = 1 : size(volts, 3)
    opsin = opsin + dt * (photons(:,:,ii) - sigma * opsin);
    PDE   = PDE   + dt * (opsin + eta - phi * PDE);
    Ca    = Ca    + dt * (q*k * cGMP.^h./(1+Ca_slow/cdark)-beta*Ca);
    st    = smax ./ (1 + (Ca / kGc).^n);
    cGMP  = cGMP  + dt * (st - PDE .* cGMP);
    Ca_slow = Ca_slow - dt * betaSlow * (Ca_slow - Ca);
    adaptedData(:,:,ii) = - k * cGMP.^h ./ (1 + Ca_slow / cdark);
end

end


    