%
% RGCMosaicAnalyzer.visualize.coneExcitationsVsPhotocurrentResponse
%

function coneExcitationsVsPhotocurrentResponse(...
	hFig, ...
	plotTitle, ...
	theConeType, ...
	temporalSupportSeconds, ...
	theSingleConeExcitationsResponse, ...
	coneExcitationsTransformedIntoResponseModulations, ...
	temporalSupportPhotocurrentSeconds, ...
	theConePhotoCurrentDifferentialResponse, ...
  theConeBackgroundPhotoCurrent, ...
  theConeExcitationsSingleConePeriodic, ...
  temporalSupportSecondsPeriodic, ...
  photocurrentResponseTimeAxisPeriodic, ...
  thePcurrentResponsePeriodic, ...
  thePcurrentBackgroundResponseTransient)

	switch (theConeType)
        case cMosaic.LCONE_ID
          theColor = [231 187 192]/255;
        case cMosaic.MCONE_ID
          theColor = [128 207 218]/255;
        case cMosaic.SCONE_ID
          theColor = [0 0 1];
    end

    m1 = max(theSingleConeExcitationsResponse(:));
    m2 = min(theSingleConeExcitationsResponse(:));
    if (~coneExcitationsTransformedIntoResponseModulations)
    	coneResponseMaxModulation = (m1-m2)/(m1+m2);
    else
    	coneResponseMaxModulation = max(abs([m1 m2]));
    end

    dTseconds = (temporalSupportSeconds(2)-temporalSupportSeconds(1))/2;

    if (coneExcitationsTransformedIntoResponseModulations)
    	coneExcitationRateRange = [-1 1];
	    coneExcitationRateTicks = -1:0.1:1;
	    coneExcitationRateTickLabels = cell(1, numel(coneExcitationRateTicks));
	    for i = 1:numel(coneExcitationRateTicks)
	        coneExcitationRateTickLabels{i} = sprintf('%+0.1f', coneExcitationRateTicks(i));
	    end
    else
	    coneExcitationRateRange = [0 40000];
	    coneExcitationRateTicks = 0:5000:40000;
	    coneExcitationRateTickLabels = cell(1, numel(coneExcitationRateTicks));
	    for i = 1:numel(coneExcitationRateTicks)
	        coneExcitationRateTickLabels{i} = sprintf('%2.0fk', coneExcitationRateTicks(i)/1000);
	    end
	    theSingleConeExcitationsResponse = theSingleConeExcitationsResponse/dTseconds ;
	    theConeExcitationsSingleConePeriodic = theConeExcitationsSingleConePeriodic/dTseconds ;
	    m1 = m1 / dTseconds;
	    m2 = m2 / dTseconds;
	end


    photocurrentRange = [-75 -15];
    deltaPhotocurrentRange = [-25 25];

    %photocurrentRange = [-80 -0];
    %deltaPhotocurrentRange = [-45 35]

    photocurrentTicks = -80:5:80;
    timeTicks = 0:100:10000;

    figure(hFig); clf;
    if (~isempty(photocurrentResponseTimeAxisPeriodic))
    	axConeExcitations = subplot(2,3,3);
    	axPhotocurrent= subplot(2,3,6);
    	axConeExcitationsPeriodic = subplot(2,3,[1 2]);
    	axPhotocurrentsPeriodic = subplot(2,3,[4 5]);
    else
    	axConeExcitations = subplot(2,1,1);
    	axPhotocurrent = subplot(2,1,2);
    end


    if (coneExcitationsTransformedIntoResponseModulations)
      	theYaxisLabel = 'cone excitation modulation';
    else
      	theYaxisLabel = 'cone excitation rate (R*/sec)';
    end

    if (~isempty(plotTitle))
      	thePlotTitle = sprintf('%s\nmax response modulation: %2.2f', plotTitle, coneResponseMaxModulation);
    else
      	thePlotTitle = sprintf('max response modulation: %2.2f', coneResponseMaxModulation);
    end

    % The cone excitations response (1 period)
    plotResponseTimeCourse(axConeExcitations, ...
    	true, ...
  		temporalSupportSeconds*1e3, ...
  		theSingleConeExcitationsResponse, ...
  		[], ...
  		theColor, ...
  		0.5*(m1+m2), ...
  		theYaxisLabel, ...
  		thePlotTitle, ...
  		[temporalSupportSeconds(1) temporalSupportSeconds(end)+dTseconds]*1e3, ...
  		timeTicks, ...
  		coneExcitationRateRange, ...
  		coneExcitationRateTicks, ...
  		coneExcitationRateTickLabels ...
  		);


    % The photocurrent response (1 period)
		plotResponseTimeCourse(axPhotocurrent, ...
			false, ...
  		temporalSupportPhotocurrentSeconds*1e3, ...
  		theConePhotoCurrentDifferentialResponse, ...
  		[], ...
  		theColor, ...
  		0.0, ...
  		'differential pCurrent (pAmps)', ...
  		sprintf('(+): %2.2f, (-): %2.2f', max(theConePhotoCurrentDifferentialResponse), min(theConePhotoCurrentDifferentialResponse)), ...
  		[temporalSupportSeconds(1) temporalSupportSeconds(end)+dTseconds]*1e3, ...
  		timeTicks, ...
  		deltaPhotocurrentRange, ...
  		photocurrentTicks, ...
  		sprintf('%2.0f\n', photocurrentTicks) ...
  		);


	% The periodic responses (if we have them)
	if (~isempty(photocurrentResponseTimeAxisPeriodic))

    	% The periodic cone excitations response
    	plotResponseTimeCourse(axConeExcitationsPeriodic, ...
    		true, ...
    		temporalSupportSecondsPeriodic*1e3, ...
    		theConeExcitationsSingleConePeriodic, ...
    		[], ...
    		theColor, ...
    		0.5*(m1+m2), ...
    		theYaxisLabel, ...
    		sprintf('max response modulation: %2.2f', coneResponseMaxModulation), ...
    		[temporalSupportSeconds(1) temporalSupportSeconds(end)+dTseconds]*1e3, ...
    		timeTicks, ...
    		coneExcitationRateRange, ...
    		coneExcitationRateTicks, ...
    		coneExcitationRateTickLabels ...
    		);

    	% The periodic photocurrent response and the transient
	    plotResponseTimeCourse(axPhotocurrentsPeriodic, ...
	    	false, ...
    		photocurrentResponseTimeAxisPeriodic*1e3, ...
    		thePcurrentResponsePeriodic+theConeBackgroundPhotoCurrent, ...
    		thePcurrentBackgroundResponseTransient, ...
    		theColor, ...
    		0.0, ...
    		'pCurrent (pAmps)', ...
    		printf('(+): %2.2f, (-): %2.2f', max(theConePhotoCurrentDifferentialResponse), min(theConePhotoCurrentDifferentialResponse)), ...
    		[temporalSupportSeconds(1) temporalSupportSeconds(end)+dTseconds]*1e3, ...
    		timeTicks, ...
    		photocurrentRange, ...
    		photocurrentTicks, ...
    		sprintf('%2.0f\n', photocurrentTicks) ...
    		);
	end
end


function plotResponseTimeCourse(ax, isStairsPlot, temporalSupport, theResponse, theSecondResponse, theColor, theBaselineResponse, theYaxisLabel, thePlotTitle, xLims, xTicks, yLims, yTicks, yTickLabels)

	if (isStairsPlot)
		stairs(ax,temporalSupport, theResponse, 'Color', 'k', 'LineWidth', 3.0);
		hold(ax, 'on');
		stairs(ax,temporalSupport, theResponse, 'Color', theColor, 'LineWidth', 1.5);
	else
		plot(ax,temporalSupport, theResponse, 'Color', 'k', 'LineWidth', 3.0);
		hold(ax, 'on');
		plot(ax,temporalSupport, theResponse, 'Color', theColor, 'LineWidth', 1.5);
	end

	if (~isempty(theSecondResponse))
		plot(temporalSupport, theSecondResponse, '-', 'Color', 'k', 'LineWidth', 3.0);
		plot(temporalSupport, theSecondResponse, '--', 'Color', theColor, 'LineWidth', 1.5);
	end

	plot(ax, [temporalSupport(1) temporalSupport(end)], theBaselineResponse*[1 1], '--', 'LineWidth', 1.0, 'Color', 'k', 'LineWidth', 1.0);

	ylabel(ax, theYaxisLabel);
	xlabel(ax,'time (msec)');
  xtickangle(ax,90);
  title(ax, thePlotTitle, 'FontWeight', 'Normal');

  set(ax, 'YLim', yLims, 'YTick', yTicks, ...
  	       'YTickLabel', yTickLabels, ...
           'XTick', xTicks, 'XLim', xLims, ...
           'FontSize', 20);
  grid(ax, 'on'); box(ax, 'off');

end
