function f = figureComponents(panelFormat, varargin)

    p = inputParser;
    p.addParameter('darkScheme', false, @islogical);
    % Execute the parser
    p.parse(varargin{:});
    darkScheme = p.Results.darkScheme;

    
    f.markerSize = 16;
    f.lineWidth = 2.0;
    f.LconeColor = [1 0.2 0.6];
    f.MconeColor = [0.2 1 0.4];
    f.SconeColor = [0.6 0.2 0.9];
    f.axisLineWidth = 1.0;

    f.backgroundColor = [1 1 1];
    f.axisColor = [0.3 0.3 0.3];
    f.axisFontSize = 28;
    f.axisFontAngle = 'italic';

    f.titleFontSize = 20;
    f.titleColor = [0.2 0.2 0.2];
    f.titleFontWeight = 'normal';

    f.legendFontSize = 20;
    f.legendBox = 'off';
    f.legendBackgroundAlpha = 0.5;
    f.legendBackgroundColor = [0.9 0.9 0.9];
    f.legendEdgeColor = [0.3 0.3 0.3];
    f.legendLineWidth = 1.0;
    f.labelColor = [0.1 0.1 0.1];
    f.legendTextColor = [0.3 0.3 0.3];
    
    f.axisTickAngle = 0;
    f.axisOffsetFactor = -0.03;
    f.tickDir = 'both';
    f.grid = 'on';
    f.box = 'off';

    if (darkScheme)
         theBackgroundColor = [33 40 42]/255;
         theLighterBackgroundColor = [43 50 52]/255;
         theLabelColor = [0.9 0.9 0.9];
         f.backgroundColor = theLighterBackgroundColor;
         f.titleColor = theLabelColor;
         f.legendBackgroundColor = theBackgroundColor;
         f.legendTextColor = theLabelColor;
         f.axisColor = theLabelColor;
         f.labelColor = theLabelColor;
    end

    f.colorbar.location = 'NorthOutside';
    f.colorbar.orientation = 'horizontal';
    f.colorbar.axisLocation = 'out';
    f.colorbar.fontSize = f.legendFontSize;
    f.colorbar.fontAngle = 'Normal';
    f.colorbar.fontColor = f.labelColor;


    switch (panelFormat)

        case '1x1 standard figure with double y-axes'

            f.reductionFactor = 0.24;
            f.figureSize = [700 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.10, ...
                    'rightMargin',    0.12, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 standard figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '2x2 standard figure'

            f.reductionFactor = 0.24;
            f.figureSize = [1050 980];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 2, ...
                    'colsNum', 2, ...
                    'heightMargin',  0.1, ...
                    'widthMargin',    0.05, ...
                    'leftMargin',     0.11, ...
                    'rightMargin',    0.04, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.02);

        case '1x2 standard figure'

            f.reductionFactor = 0.24;
            f.figureSize = [1050 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 2, ...
                    'heightMargin',  0.1, ...
                    'widthMargin',    0.07, ...
                    'leftMargin',     0.10, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.17, ...
                    'topMargin',      0.04);

        case '1x2 giant figure'

            f.reductionFactor = 0.24;
            f.figureSize = [1792 896];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 2, ...
                    'heightMargin',  0.1, ...
                    'widthMargin',    0.05, ...
                    'leftMargin',     0.05, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.02);

        case '1.5x2 giant figure'

            f.reductionFactor = 0.24;
            f.figureSize = [2240 1408];

            f.tickDir = 'in';

            % left tall plot
            f.subplotPosVectors(1,1).v(1) = 0.01;
            f.subplotPosVectors(1,1).v(2) = 0.07;
            f.subplotPosVectors(1,1).v(3) = 0.5;
            f.subplotPosVectors(1,1).v(4) = 0.45;

            f.subplotPosVectors(2,1).v(1) = 0.01;
            f.subplotPosVectors(2,1).v(2) = 0.54;
            f.subplotPosVectors(2,1).v(3) = 0.5;
            f.subplotPosVectors(2,1).v(4) = 0.44;


            % right top square plot 
            f.subplotPosVectors(1,2).v(1) = 0.59;
            f.subplotPosVectors(1,2).v(2) = 0.545;
            f.subplotPosVectors(1,2).v(3) = 0.4;
            f.subplotPosVectors(1,2).v(4) = 0.4;

             % right botom square plot
            f.subplotPosVectors(2,2).v(1) = 0.59;
            f.subplotPosVectors(2,2).v(2) = 0.075;
            f.subplotPosVectors(2,2).v(3) = 0.4;
            f.subplotPosVectors(2,2).v(4) = 0.4;



        case '1x1 double width figure'

            f.reductionFactor = 0.24;
            f.figureSize = [1400 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.1, ...
                    'rightMargin',    0.1, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 standard square figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 700];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        

        case '1x1 standard wide figure'

            f.reductionFactor = 0.24;
            f.figureSize = [800 700];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.11, ...
                    'topMargin',      0.02);

        case '1x1 standard tall figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 800];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.11, ...
                    'topMargin',      0.02);

        
        case '1x1 standard tall2 figure'

            f.reductionFactor = 0.24;
            f.figureSize = [800 900];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.11, ...
                    'topMargin',      0.02);

        case '1x1 standard very wide figure'

            f.reductionFactor = 0.24;
            f.figureSize = [1200 700];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.1, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.125, ...
                    'topMargin',      0.02);

        case '1x1 standard very tall figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 1200];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.02);

        case '1x1 standard figure no left axis label'

            f.reductionFactor = 0.24;
            f.figureSize = [700 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.03, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 giant square mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [1250 1200];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.06, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.07, ...
                    'topMargin',      0.03);

        case '1x1 giant square mosaic with side plots'

            f.reductionFactor = 0.24;
            f.figureSize = [1250 1200];
            f.tickDir = 'in';

            f.subplotPosVectors(1,1) = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.08, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.07, ...
                    'topMargin',      0.03);

            f.subplotPosVectors(1,1).v(1) = f.subplotPosVectors(1,1).v(1);
            f.subplotPosVectors(1,1).v(2) = f.subplotPosVectors(1,1).v(2);
            f.subplotPosVectors(1,1).v(3:4) = f.subplotPosVectors(1,1).v(3:4) * 0.85;

            % Horizontal plot on the top
            f.subplotPosVectors(1,2).v(1) = f.subplotPosVectors(1,1).v(1);
            f.subplotPosVectors(1,2).v(2) = f.subplotPosVectors(1,1).v(2) + f.subplotPosVectors(1,1).v(4) + 0.04;
            f.subplotPosVectors(1,2).v(3) = f.subplotPosVectors(1,1).v(3);
            f.subplotPosVectors(1,2).v(4) = 0.1;

            % Vertical plot on the right
            f.subplotPosVectors(1,3).v(1) = f.subplotPosVectors(1,1).v(1) + f.subplotPosVectors(1,1).v(3) + 0.04;
            f.subplotPosVectors(1,3).v(2) = f.subplotPosVectors(1,1).v(2);
            f.subplotPosVectors(1,3).v(3) = 0.1;
            f.subplotPosVectors(1,3).v(4) = f.subplotPosVectors(1,1).v(4);

        case '1x1 giant rectangular-wide mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [1250 900];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.05, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.03);

        case '1x1 giant rectangular-wide2 mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [1880 1030];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.025, ...
                    'rightMargin',    0.005, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.03);


        case '1x1 giant rectangular-double wide mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [2500 900];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.025, ...
                    'rightMargin',    0.005, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.03);

        case '1x1 giant rectangular-double wide, double height mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [2500 1550];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.025, ...
                    'rightMargin',    0.005, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.03);

        case '1x1 narrow full height figure'
            f.reductionFactor = 0.24;
            f.figureSize = [800 1200];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.0, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.08, ...
                    'rightMargin',    0.02, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);
            
        case '1x1 full width short height figure'
            f.reductionFactor = 0.24;
            f.figureSize = [1950 900];
            f.tickDir = 'in';

            f.colorbar.location = 'NorthOutside';
            f.colorbar.orientation = 'horizontal';
            f.colorbar.axisLocation = 'out';
            f.colorbar.fontSize = 16;
            f.colorbar.fontAngle = 'Normal';
            f.colorbar.fontColor = f.labelColor;

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.0, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.05, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.10, ...
                    'topMargin',      0.05);

        case '1x1 full width medium height figure'
            f.reductionFactor = 0.24;
            f.figureSize = [1950 1200];
            f.tickDir = 'in';

            f.colorbar.location = 'NorthOutside';
            f.colorbar.orientation = 'horizontal';
            f.colorbar.axisLocation = 'out';
            f.colorbar.fontSize = 16;
            f.colorbar.fontAngle = 'Normal';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.0, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.05, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.10, ...
                    'topMargin',      0.05);

        otherwise
            error('unknown panelFormat: ''%s''.', panelFormat);
    end


end

