function f = figureComponents(panelFormat)

    
    f.markerSize = 16;
    f.lineWidth = 2.0;
    f.LconeColor = [1 0.2 0.6];
    f.MconeColor = [0.2 1 0.4];
    f.SconeColor = [0.6 0.2 0.9];
    f.axisLineWidth = 1.0;

    f.backgroundColor = [1 1 1];
    f.axisColor = [0.3 0.3 0.3];
    f.axisFontSize = 28;
    f.axisFontAngle = 'italic';

    f.titleFontSize = 20;
    f.titleColor = [0.2 0.2 0.2];
    f.titleFontWeight = 'normal';

    f.legendFontSize = 20;
    f.legendBox = 'off';
    
    f.axisTickAngle = 0;
    f.axisOffsetFactor = -0.03;
    f.tickDir = 'both';
    f.grid = 'on';
    f.box = 'off';


    switch (panelFormat)

        case '1x1 standard figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 double width figure'

            f.reductionFactor = 0.24;
            f.figureSize = [1400 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 standard square figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 700];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 standard tall figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 800];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.11, ...
                    'topMargin',      0.01);

        case '1x1 standard very tall figure'

            f.reductionFactor = 0.24;
            f.figureSize = [700 1200];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.15, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.09, ...
                    'topMargin',      0.02);

        case '1x1 standard figure no left axis label'

            f.reductionFactor = 0.24;
            f.figureSize = [700 500];

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.00, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.03, ...
                    'rightMargin',    0.03, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);

        case '1x1 giant square mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [1250 1200];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.04, ...
                    'rightMargin',    0.00, ...
                    'bottomMargin',   0.07, ...
                    'topMargin',      0.03);

        case '1x1 giant rectangular-wide mosaic'
           
            f.reductionFactor = 0.24;
            f.figureSize = [1250 900];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.05, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.04, ...
                    'rightMargin',    0.00, ...
                    'bottomMargin',   0.07, ...
                    'topMargin',      0.03);

        case '1x1 narrow full height figure'
            f.reductionFactor = 0.24;
            f.figureSize = [800 1200];
            f.tickDir = 'in';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.0, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.08, ...
                    'rightMargin',    0.02, ...
                    'bottomMargin',   0.19, ...
                    'topMargin',      0.06);
            
        case '1x1 full width short height figure'
            f.reductionFactor = 0.24;
            f.figureSize = [1950 900];
            f.tickDir = 'in';

            f.colorbar.location = 'NorthOutside';
            f.colorbar.orientation = 'horizontal';
            f.colorbar.axisLocation = 'out';
            f.colorbar.fontSize = 16;
            f.colorbar.fontAngle = 'Normal';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.0, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.05, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.10, ...
                    'topMargin',      0.05);

        case '1x1 full width medium height figure'
            f.reductionFactor = 0.24;
            f.figureSize = [1950 1200];
            f.tickDir = 'in';

            f.colorbar.location = 'NorthOutside';
            f.colorbar.orientation = 'horizontal';
            f.colorbar.axisLocation = 'out';
            f.colorbar.fontSize = 16;
            f.colorbar.fontAngle = 'Normal';

            f.subplotPosVectors = NicePlot.getSubPlotPosVectors(...
                    'rowsNum', 1, ...
                    'colsNum', 1, ...
                    'heightMargin',  0.0, ...
                    'widthMargin',    0.00, ...
                    'leftMargin',     0.05, ...
                    'rightMargin',    0.01, ...
                    'bottomMargin',   0.10, ...
                    'topMargin',      0.05);

        otherwise
            error('unknown panelFormat: ''%s''.', panelFormat);
    end


end

