function mosaicParams = getMosaicParams(mosaicHorizontalEccentricityDegs)
    % Method to obtain the (x,y) eccentricity and (x,y) size of an mRGC
    % mosaic based on some descriptor (for now horizontal eccentricity)

    if (nargin == 0)
        % Ask user which mosaic to use
        mosaicHorizontalEccentricityDegs = MosaicPoolingOptimizer.chooseMosaicToUse();
    end

    switch (mosaicHorizontalEccentricityDegs)
        case 0
            % Mosaic params to employ. This is for the 2.5 deg - centered mosaic
            % which covers the [1 - 4] deg eccentricity range
            mosaicParams = struct(...
                'eccDegs', [0 0], ...
                'sizeDegs', [2 2], ...
                'rgcType', 'ONcenterMidgetRGC');

        case 2.5
            % Mosaic params to employ. This is for the 2.5 deg - centered mosaic
            % which covers the [1 - 4] deg eccentricity range
            mosaicParams = struct(...
                'eccDegs', [2.5 0], ...
                'sizeDegs', [3 3], ...
                'rgcType', 'ONcenterMidgetRGC');

        case 7.0
            % Mosaic params to employ. This is for the 7.0 deg - centered mosaic
            % which covers the [4-10] deg eccentricity range
            mosaicParams = struct(...
                'eccDegs', [7 0], ...
                'sizeDegs', [6 3],...
                'rgcType', 'ONcenterMidgetRGC');

        case -10.0
            mosaicParams = struct(...
                'eccDegs', [-10 0], ...
                'sizeDegs', [6 3], ...
                'rgcType', 'ONcenterMidgetRGC');

       case -16.0
            mosaicParams = struct(...
                'eccDegs', [-16 0], ...
                'sizeDegs', [6 3], ...
                'rgcType', 'ONcenterMidgetRGC', ...
                'maxConeInputsPerRGCToConsiderTransferToNearbyRGCs', 20);


        otherwise
            error('No data for this horizontal eccentricity (%2.1f degs)', mosaicHorizontalEccentricityDegs)
    end
end
