function arbitraryNodesToCompute = gridNodesToOptimize()
    arbitraryNodesToCompute = {};

    s = input('Compute all nodes (1) or speficic ones (2):');
    if (s == 1)
        return;
    else

        % Bad nodes
         arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 13, ...
                'coneType', [cMosaic.MCONE_ID]);

         arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 29, ...
                'coneType', [cMosaic.LCONE_ID cMosaic.MCONE_ID]);


         arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 28, ...
                'coneType', [cMosaic.LCONE_ID]);

        arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 10, ...
                'coneType', [cMosaic.LCONE_ID]);

        arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 8, ...
                'coneType', [cMosaic.MCONE_ID]);


         arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 7, ...
                'coneType', [cMosaic.LCONE_ID cMosaic.MCONE_ID]);

         arbitraryNodesToCompute{numel(arbitraryNodesToCompute)+1} = struct(...
                'number', 6, ...
                'coneType', [cMosaic.MCONE_ID]);
    end
end