function performContrastSTFsAcrossDifferentChromaticities(...
            mosaicParams, rawFiguresRoot, scaledFiguresRoot, varargin)

    % Parse input
    p = inputParser;
    p.addParameter('performSurroundAnalysisForConesExclusiveToTheSurround', true, @islogical);
    p.addParameter('targetRangeForSurroundConeMix', [0.4 0.5], @(x)(isnumeric(x)&&(numel(x)==2)));
    p.addParameter('exportScaledFigureVersionForManuscript', true, @islogical);
    p.parse(varargin{:});
    performSurroundAnalysisForConesExclusiveToTheSurround = p.Results.performSurroundAnalysisForConesExclusiveToTheSurround;
    targetRangeForSurroundConeMix = p.Results.targetRangeForSurroundConeMix;
    exportScaledFigureVersionForManuscript = p.Results.exportScaledFigureVersionForManuscript;

    % Get PDF directory
    [~,~,pdfDirectory] = MosaicPoolingOptimizer.resourceFileNameAndPath('pdfsDirectory', ...
        'mosaicParams', mosaicParams);

    % Load the compute-ready mRGCMosaic
    [theComputeReadyMRGCmosaic, theComputeReadyMRGCMosaicFilePath] = ...
        MosaicPoolingOptimizer.queryUserAndLoadComputeReadyMRGCMosaic(mosaicParams);
    
    % Find the indices of mRGCs whose surround cone mix is within the target range
    mRGCindicesToVisualizeSTFsAcrossChromaticities = MosaicPoolingOptimizer.findMRGCindicesWithDesiredSurroundConeMix(...
            theComputeReadyMRGCmosaic, ...
            targetRangeForSurroundConeMix, ...
            performSurroundAnalysisForConesExclusiveToTheSurround, ...
            rawFiguresRoot, scaledFiguresRoot, exportScaledFigureVersionForManuscript);


    userPrompt = 'Select the optics that were used to compute the mRGC mosaic STF responses';
    measuredResponseType = 'STFresponses';
    
    [theMRGCMosaicAchromaticSTFresponsesFilePath, ...
     theMRGCMosaicLconeIsolatingSTFresponsesFilePath, ...
     theMRGCMosaicMconeIsolatingSTFresponsesFilePath, ...
     opticsParamsForMRGCSTFs] = MosaicPoolingOptimizer.generateFileNamesForContrastedResponses(...
            mosaicParams, measuredResponseType, userPrompt);

    % Prompt user for examined RGC location
    exampleLconeCenterRGCposition = [];
    while (numel(exampleLconeCenterRGCposition) ~= 2)
        exampleLconeCenterRGCposition = input('Enter example L-cone center RGC position (e.g. [0.7 0.7]) :');
    end
    exampleMconeCenterRGCposition = exampleLconeCenterRGCposition;


    MosaicPoolingOptimizer.contrastVisualSTFsAcrossDifferentChromaticities(...
        exampleLconeCenterRGCposition, exampleMconeCenterRGCposition, ...
        theComputeReadyMRGCMosaicFilePath, ...
        theMRGCMosaicAchromaticSTFresponsesFilePath, ...
        theMRGCMosaicLconeIsolatingSTFresponsesFilePath, ...
        theMRGCMosaicMconeIsolatingSTFresponsesFilePath, ...
        opticsParamsForMRGCSTFs, rawFiguresRoot, scaledFiguresRoot, exportScaledFigureVersionForManuscript,  ...
        'examinedRGCindices', mRGCindicesToVisualizeSTFsAcrossChromaticities, ...
        'tickSeparationArcMin', 2.0, ...
        'performSurroundAnalysisForConesExclusiveToTheSurround', performSurroundAnalysisForConesExclusiveToTheSurround, ...
        'generateVideoWithAllExaminedRGCs', false)
 
end