function [stimParams, thePresentationDisplay] = setupSubspaceRFmappingExperiment(inputConeMosaic, ...
        sceneFOVdegs, maxSFcyclesPerDegree)

    wavelengthSupport = inputConeMosaic.wave;

    sceneFOVdegs
    stimSizeDegs = min(sceneFOVdegs)
    maxSFperiodDegs = 1/maxSFcyclesPerDegree;
    minSamplesPerMaxSFperiod = 4;
    pixelSizeDegs = maxSFperiodDegs/minSamplesPerMaxSFperiod
    omega = round(maxSFcyclesPerDegree * stimSizeDegs)
    retinalImageResolutionDegs = pixelSizeDegs

    % Generate a presentation display with a desired resolution
    viewingDistanceMeters = 4;
    stimulusPixelsNum = round(stimSizeDegs/retinalImageResolutionDegs)

    thePresentationDisplay = rfMappingStimulusGenerator.presentationDisplay(...
            wavelengthSupport, pixelSizeDegs, ...
            viewingDistanceMeters);

    % Stim params for the RF mapping
    stimParams = struct(...
            'backgroundLuminanceCdM2', 50.0, ...
            'backgroundChromaticity', [0.301 0.301], ...
            'coneContrasts', [1 1 1], ...
            'contrast', 0.75, ...
            'omega', omega, ...
            'pixelSizeDegs', retinalImageResolutionDegs, ...
            'stimSizeDegs', stimSizeDegs, ...
            'wavelengthSupport', displayGet(thePresentationDisplay, 'wave'), ...
            'viewingDistanceMeters', displayGet(thePresentationDisplay, 'viewing distance') ...
            );

end
