function [stimParams, thePresentationDisplay] = setupSubspaceRFmappingExperiment(inputConeMosaic, ...
        sceneFOVdegs, retinalImageResolutionDegs)

    wavelengthSupport = inputConeMosaic.wave;

    % Generate a presentation display with a desired resolution
    viewingDistanceMeters = 4;
    stimulusPixelsNum = round(max(sceneFOVdegs)/retinalImageResolutionDegs)
    stimSizeDegs = max(sceneFOVdegs);
    pixelSizeDegs = retinalImageResolutionDegs;


    thePresentationDisplay = rfMappingStimulusGenerator.presentationDisplay(...
            wavelengthSupport, pixelSizeDegs, ...
            viewingDistanceMeters);

    % Stim params for the RF mapping
    stimParams = struct(...
            'backgroundLuminanceCdM2', 50.0, ...
            'backgroundChromaticity', [0.301 0.301], ...
            'coneContrasts', [1 1 1], ...
            'contrast', 0.75, ...
            'omega', 11, ...
            'pixelSizeDegs', retinalImageResolutionDegs, ...
            'stimSizeDegs', stimSizeDegs, ...
            'wavelengthSupport', displayGet(thePresentationDisplay, 'wave'), ...
            'viewingDistanceMeters', displayGet(thePresentationDisplay, 'viewing distance') ...
            );

end
