%
% RGCMosaicConstructor.helper.optics.optimized3DStrehlRatioPSF
%
function [theOptimalStrehlRatioOI, theOptimalStrehlRatioPSF, ...
    theOptimalStrehlRatioDefocusAndAstigmatismDiopters, ...
    theOptimalStrehlRatio, StrehlRatio3DFunction] = optimized3DStrehlRatioPSF(...
        examinedDefocusAndAstigmatismDioptersGrid, ...
	    theConeMosaic, oiPositionDegs, opticsParams, wavefrontSpatialSamples, psfUpsampleFactor, ...
	    visualizeStrehlRatioOptimization, contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection, ...
        examinedRefractionErrorDiopters, examinedObliqueAstigmatismDiopters, examinedVerticalAstigmatismDiopters, ...
	    useParfor)


    % Deal with inconsistent capitalization of zernikeDataBase fieldname
    if (isfield(opticsParams, 'zernikeDataBase') && (~isfield(opticsParams, 'ZernikeDataBase')))
        zernikeDataBase = opticsParams.zernikeDataBase;
    else
        zernikeDataBase = opticsParams.ZernikeDataBase;
    end

	% Generate diffraction-limited PSF so that we can compute the Strehl ratio later
	[~, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
			oiPositionDegs, ...
	       'zernikeDataBase', zernikeDataBase, ...
	       'subjectID', 0, ...
	       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
	       'refractiveErrorDiopters', 0.0, ...
           'obliqueAndVerticalAstigmatismErrorsDiopters', [0 0], ...
	       'noLCA', false, ...
	       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
	       'subtractCentralRefraction', false, ...
           'subtractCentralRefraction3D', false, ...
	       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
	       'upsampleFactor', psfUpsampleFactor, ...
	       'warningInsteadOfErrorForBadZernikeCoeffs', false);


	% Find the wavelength at thich the diffraction-limited PSF achieves its peak.
	% Since we have LCA enabled, this should be 550.
	theDiffractionLimitedPSF = psfEnsemble{1,1};
	[peakDiffractionLimitedPSFAmplitude, ...
	 wavelengthIndexOfPeakDiffractionLimitedPSFamplitude, ...
	 wavelengthOfPeakDiffractionLimitedPSFamplitude] = RGCMosaicConstructor.helper.optics.analyzePSF(theDiffractionLimitedPSF, []);
	 assert(wavelengthOfPeakDiffractionLimitedPSFamplitude == 550, 'Diffraction-limited PSF does not peak at 550');

	targetInFocusWavelengthIndex = wavelengthIndexOfPeakDiffractionLimitedPSFamplitude;
	targetInFocusWavelength = wavelengthOfPeakDiffractionLimitedPSFamplitude;
	fprintf('Diffraction-limited PSF peaks at %d nm (which is our in-focus wavelength)\n', targetInFocusWavelength);

	if (visualizeStrehlRatioOptimization) || (contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection)
		% Generate central-diffraction corrected PSF (just for reference to the optimal Strehl ratio PSF)
		
        [~, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
        			oiPositionDegs, ...
			       'zernikeDataBase', zernikeDataBase, ...
			       'subjectID', opticsParams.subjectID, ...
			       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
			       'refractiveErrorDiopters', 0.0, ...
                   'obliqueAndVerticalAstigmatismErrorsDiopters', [0 0], ...
			       'noLCA', opticsParams.noLCA, ...
			       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
			       'subtractCentralRefraction', true, ...
                   'subtractCentralRefraction3D', true, ...
			       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
			       'upsampleFactor', psfUpsampleFactor, ...
			       'warningInsteadOfErrorForBadZernikeCoeffs', false);

		theCentralCorrectionPSF = psfEnsemble{1,1};
	end

	StrehlRatio3DFunction = zeros(size(examinedDefocusAndAstigmatismDioptersGrid,1),1);

	% Search through the defocus values in examinedRefractionErrorDioptersGrid to determine the defocus value
	% for which the ratio of peak PSF amplitude for the current subject to peakDiffractionLimitedPSFAmplitude 
	% (at the wavelengthOfPeakDiffractionLimitedPSFamplitude) is maximal
	if (useParfor)
		parfor iRefractiveError = 1:size(examinedDefocusAndAstigmatismDioptersGrid,1)

            fprintf(2, 'Examining correction %d of %d\n', iRefractiveError, size(examinedDefocusAndAstigmatismDioptersGrid,1));
			StrehlRatio3DFunction(iRefractiveError,1) = localStrehlRatioForDefocus(...
				theConeMosaic, oiPositionDegs, zernikeDataBase, opticsParams, ...
				examinedDefocusAndAstigmatismDioptersGrid(iRefractiveError,:), ...
                wavefrontSpatialSamples, psfUpsampleFactor, ...
                targetInFocusWavelengthIndex, peakDiffractionLimitedPSFAmplitude);

		end % parfor for iRefractiveError
	else
		for iRefractiveError = 1:size(examinedDefocusAndAstigmatismDioptersGrid,1)

            fprintf(2, 'Examining correction %d of %d\n', iRefractiveError, size(examinedDefocusAndAstigmatismDioptersGrid,1));
			StrehlRatio3DFunction(iRefractiveError,1) = localStrehlRatioForDefocus(...
				theConeMosaic, oiPositionDegs, zernikeDataBase, opticsParams, ...
				examinedDefocusAndAstigmatismDioptersGrid(iRefractiveError,:), ...
                wavefrontSpatialSamples, psfUpsampleFactor, ...
                targetInFocusWavelengthIndex, peakDiffractionLimitedPSFAmplitude);
		end
	end
	


    the3DSize(1) = numel(examinedRefractionErrorDiopters);
    the3DSize(2) = numel(examinedObliqueAstigmatismDiopters);
    the3DSize(3) = numel(examinedVerticalAstigmatismDiopters);
    StrehlRatio3Dmap = reshape(StrehlRatio3DFunction,the3DSize);
    [theOptimalStrehlRatio, idx] = max(StrehlRatio3DFunction);
    [i1, i2, i3] = ind2sub(size(StrehlRatio3Dmap), idx);
    theOptimalStrehlRatioDefocusAndAstigmatismDiopters(1) = examinedRefractionErrorDiopters(i1);
    theOptimalStrehlRatioDefocusAndAstigmatismDiopters(2) = examinedObliqueAstigmatismDiopters(i2);
    theOptimalStrehlRatioDefocusAndAstigmatismDiopters(3) = examinedVerticalAstigmatismDiopters(i3);


    fprintf(2,'\nWill employ a defocus correction of %2.3f (Diopters), and O/V astigmatic correction of (%2.3f,%2.3f) (Diopters) for which the Strehl ratio is maximal (%2.3f)\n\n', ...
        theOptimalStrehlRatioDefocusAndAstigmatismDiopters(1), ...
        theOptimalStrehlRatioDefocusAndAstigmatismDiopters(2), ...
        theOptimalStrehlRatioDefocusAndAstigmatismDiopters(3), ...
        theOptimalStrehlRatio);

    
	% Generate the optimal Strehl ratio optics
	[oiEnsemble, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
		oiPositionDegs, ...
       'zernikeDataBase', zernikeDataBase, ...
       'subjectID', opticsParams.subjectID, ...
       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
       'refractiveErrorDiopters', theOptimalStrehlRatioDefocusAndAstigmatismDiopters(1), ...
       'obliqueAndVerticalAstigmatismErrorsDiopters', theOptimalStrehlRatioDefocusAndAstigmatismDiopters(2:3), ...
       'noLCA', opticsParams.noLCA, ...
       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
       'subtractCentralRefraction', false, ...
       'subtractCentralRefraction3D', false, ...
       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
       'upsampleFactor', psfUpsampleFactor, ...
       'warningInsteadOfErrorForBadZernikeCoeffs', false);

	% This is it.
	theOptimalStrehlRatioOI = oiEnsemble{1,1}; 
	theOptimalStrehlRatioPSF = psfEnsemble{1,1};
	
    contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection = visualizeStrehlRatioOptimization;


	if (contrastOptimizedStrehlRatioPSFtoAsMeasuredAndCentralCorrection)
		[~, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
        			oiPositionDegs, ...
			       'zernikeDataBase', zernikeDataBase, ...
			       'subjectID', opticsParams.subjectID, ...
			       'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
			       'refractiveErrorDiopters', 0.0, ...
			       'noLCA', opticsParams.noLCA, ...
			       'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
			       'subtractCentralRefraction', false, ...
                   'subtractCentralRefraction3D', false, ...
			       'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
			       'upsampleFactor', psfUpsampleFactor, ...
			       'warningInsteadOfErrorForBadZernikeCoeffs', false);
		thePSFasMeasured = psfEnsemble{1,1};
		

		hFig = figure(2000);
		clf;
		set(hFig, 'Position', [10 10 1360 1200]);

		XLimsArcMin = 5*[-1 1];
		YLimsArcMin = 5*[-1 1];
		XTicksArcMin = -5:1:5;
		YTicksArcMin = -5:1:5;
		
		colormap(brewermap(1024, '*greys'));

		% The diffraction-limited PSF at the target in-focus wavelength
		ax1 = subplot(2,3,1);
        ax2 = subplot(2,3,2);
        ax3 = subplot(2,3,4);
        ax4 = subplot(2,3,5);

        % A 2D slice of StrehlRatio3Dmap (defocus, oblique astigmatism) at
        % optimal vertical astigmatism
        ax5 = subplot(2,3,3);

        % A 2D slice of StrehlRatio3Dmap (defocus, vertical astigmatism) at
        % optimal oblique astigmatism
        ax6 = subplot(2,3,6);

   

        StrehlRatio2Dslice = squeeze(StrehlRatio3Dmap (:,:,i3));
        % Plot the slice over the defocus x oblique astigmatism plane
        imagesc(ax5,examinedRefractionErrorDiopters, examinedObliqueAstigmatismDiopters, StrehlRatio2Dslice');
        hold(ax5, 'on');
        plot(ax5, theOptimalStrehlRatioDefocusAndAstigmatismDiopters(1), theOptimalStrehlRatioDefocusAndAstigmatismDiopters(2), 'rx', 'LineWidth', 1.5, 'MarkerSize', 20);
        xlabel(ax5, 'defocus (D)');
        ylabel(ax5, 'oblique astigmatism (D)');

        
        StrehlRatio2Dslice = squeeze(StrehlRatio3Dmap (:,i2,:));
        % Plot the slice over the defocus x vertical astigmatism plane
        imagesc(ax6,examinedRefractionErrorDiopters, examinedVerticalAstigmatismDiopters, StrehlRatio2Dslice');
        hold(ax6, 'on');
        plot(ax6, theOptimalStrehlRatioDefocusAndAstigmatismDiopters(1), theOptimalStrehlRatioDefocusAndAstigmatismDiopters(3), 'bs', 'MarkerSize', 20);
        xlabel(ax6, 'defocus (D)');
        ylabel(ax6, 'vertical astigmatism (D)');


		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax1, theDiffractionLimitedPSF, targetInFocusWavelengthIndex, ...
			peakDiffractionLimitedPSFAmplitude, ...
			sprintf('diffraction limited PSF\npeak: %d at \n%d nm (in-focus wavelength)', peakDiffractionLimitedPSFAmplitude, targetInFocusWavelength), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax1, brewermap(1024, '*greys'));
		
		% The optimal Strehl ratio PSF at the target in-focus wavelength
		peakOptimalStrehlRatioPSFAmplitude = RGCMosaicConstructor.helper.optics.analyzePSF(theOptimalStrehlRatioPSF, targetInFocusWavelengthIndex);
		
        RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax2, theOptimalStrehlRatioPSF, targetInFocusWavelengthIndex, ...
			peakOptimalStrehlRatioPSFAmplitude,  ...
			sprintf('(%2.1f,%2.1f) degs PSF \n with optimal Strehl ratio (%2.3f)\npeak: %f at \n%d nm (in-focus wavelength))', ...
				oiPositionDegs(1), oiPositionDegs(2), peakOptimalStrehlRatioPSFAmplitude/ peakDiffractionLimitedPSFAmplitude, peakOptimalStrehlRatioPSFAmplitude, targetInFocusWavelength), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax2, brewermap(1024, '*greys'));

		% The PSF as measured
		[peakPSFasMeasuredAmplitude, wavelengthIndexOfPeakPSFasMeasuredAmplitude, ...
	    wavelengthOfPeakPSFasMeasuredAmplitude] = RGCMosaicConstructor.helper.optics.analyzePSF(thePSFasMeasured, []);
		
		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax3, thePSFasMeasured, wavelengthIndexOfPeakPSFasMeasuredAmplitude, ...
			peakPSFasMeasuredAmplitude, ...
			sprintf('(%2.1f,%2.1f) PSF as measured\npeak: %f \nat %d nm', oiPositionDegs(1), oiPositionDegs(2), peakPSFasMeasuredAmplitude, wavelengthOfPeakPSFasMeasuredAmplitude), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax3, brewermap(1024, '*greys'));

		
		peakCentralCorrectionPSFAmplitude = RGCMosaicConstructor.helper.optics.analyzePSF(theCentralCorrectionPSF, targetInFocusWavelengthIndex);
		StrehlRatioForCentralCorrection = peakCentralCorrectionPSFAmplitude/peakDiffractionLimitedPSFAmplitude;

		RGCMosaicConstructor.helper.optics.visualizePSFatWavelength(ax4, theCentralCorrectionPSF, targetInFocusWavelengthIndex, ...
			peakCentralCorrectionPSFAmplitude, ...
			sprintf('(%2.1f,%2.1f) PSF \n(with central refraction (0,0) correction)\nStrehl ratio: %2.3f\npeak %f \nat %d nm',  oiPositionDegs(1), oiPositionDegs(2), StrehlRatioForCentralCorrection, peakCentralCorrectionPSFAmplitude, targetInFocusWavelength), ...
			'XLimsArcMin', XLimsArcMin, ...
			'YLimsArcMin', YLimsArcMin, ...
			'XTicksArcMin', XTicksArcMin, ... 
			'YTicksArcMin', YTicksArcMin);
		colormap(ax4, brewermap(1024, '*greys'));
		drawnow;	
	end

end

function strehlRatio = localStrehlRatioForDefocus(theConeMosaic, oiPositionDegs, zernikeDataBase, ...
	opticsParams, defocusAndAstigmatismDiopters, ...
    wavefrontSpatialSamples, psfUpsampleFactor, ...
	targetInFocusWavelengthIndex, peakDiffractionLimitedPSFAmplitude)
%% Generate optics for one defocus value and return the Strehl ratio.

[~, psfEnsemble] = theConeMosaic.oiEnsembleGenerate(...
	oiPositionDegs, ...
	'zernikeDataBase', zernikeDataBase, ...
	'subjectID', opticsParams.subjectID, ...
	'pupilDiameterMM', opticsParams.pupilDiameterMM, ...
	'refractiveErrorDiopters', defocusAndAstigmatismDiopters(1), ...
    'obliqueAndVerticalAstigmatismErrorsDiopters', defocusAndAstigmatismDiopters(2:3), ...
	'noLCA', opticsParams.noLCA, ...
	'zeroCenterPSF', opticsParams.zeroCenterPSF, ...
	'subtractCentralRefraction', false, ...
    'subtractCentralRefraction3D', false, ...
	'wavefrontSpatialSamples', wavefrontSpatialSamples, ...
	'upsampleFactor', psfUpsampleFactor, ...
	'warningInsteadOfErrorForBadZernikeCoeffs', false);

theCurrentPSF = psfEnsemble{1,1};
peakCurrentPSFAmplitude = RGCMosaicConstructor.helper.optics.analyzePSF(theCurrentPSF, targetInFocusWavelengthIndex);
strehlRatio = peakCurrentPSFAmplitude/peakDiffractionLimitedPSFAmplitude;

end
