%
% RGCMosaicAnalyzer.compute.mosaicSTFsForStimulusChromaticityAndOptics
%
function mosaicSTFsForStimulusChromaticityAndOptics(...
    theMRGCMosaic, theOI, ...
    STFmeanLuminanceCdM2, ...
    STFbackgroundXYchromaticity, ...
    STFchromaticity, ...
    STFsfSupport, ...
    STFstimulusResolutionDegs, ...
    coneFundamentalsOptimizedForStimPosition, ...
    theInputConeMosaicSTFResponsesFullFileName, ...
    theMRGCMosaicSTFResponsesFullFileName, ...
    visualizeMosaicResponse, ...
    varargin)


    p = inputParser;
    p.addParameter('nonLinearitiesList', [], @(x)(isempty(x))||(iscell(x))||(isstruct(x)));
    p.addParameter('photocurrentParams', [], @(x)(isempty(x))||(iscell(x))||(isstruct(x)));
    p.addParameter('customTemporalFrequencyAndContrast', [], @(x)(isempty(x))||(isstruct(x)));
    p.addParameter('displayType', '', @ischar);
    p.addParameter('displayLuminanceHeadroomPercentage', 1/100, @isscalar);
    p.addParameter('adjustBackgroundChromaticityToEqualizeLandMconeExcitations', false, @islogical);
    p.addParameter('debugInputConeMosaicPcurrentResponse', false, @islogical);    
    p.addParameter('orientationDeltaDegs', 30, @isscalar);
    p.addParameter('spatialPhaseIncrementDegs', 30, @isscalar);
    p.addParameter('computeInputConeMosaicResponses', true, @islogical);
    p.addParameter('computeInputConeMosaicResponsesBasedOnConeExcitations', true, @islogical);
    p.addParameter('computeInputConeMosaicResponsesBasedOnPhotocurrents', true, @islogical);
    p.addParameter('onlyInspectInputConeMosaicResponses', false, @islogical);
    p.addParameter('computeMRGCMosaicResponses', false, @islogical);
    p.addParameter('mRGCsOperateOnBackgroundAdaptedPhotocurrents', false, @islogical);
    p.addParameter('visualizeStimulusSequence', false, @islogical);

    % Execute the parser
    p.parse(varargin{:});
    nonLinearitiesList = p.Results.nonLinearitiesList;
    photocurrentParams = p.Results.photocurrentParams;
    customTemporalFrequencyAndContrast = p.Results.customTemporalFrequencyAndContrast;
    displayType = p.Results.displayType;
    displayLuminanceHeadroomPercentage = p.Results.displayLuminanceHeadroomPercentage;
    adjustBackgroundChromaticityToEqualizeLandMconeExcitations = p.Results.adjustBackgroundChromaticityToEqualizeLandMconeExcitations;
    debugInputConeMosaicPcurrentResponse = p.Results.debugInputConeMosaicPcurrentResponse;
    orientationDeltaDegs = p.Results.orientationDeltaDegs;
    spatialPhaseIncrementDegs = p.Results.spatialPhaseIncrementDegs;
    computeInputConeMosaicResponses = p.Results.computeInputConeMosaicResponses;
    computeInputConeMosaicResponsesBasedOnConeExcitations = p.Results.computeInputConeMosaicResponsesBasedOnConeExcitations;
    computeInputConeMosaicResponsesBasedOnPhotocurrents = p.Results.computeInputConeMosaicResponsesBasedOnPhotocurrents;
    onlyInspectInputConeMosaicResponses = p.Results.onlyInspectInputConeMosaicResponses;
    computeMRGCMosaicResponses = p.Results.computeMRGCMosaicResponses;
    mRGCsOperateOnBackgroundAdaptedPhotocurrents = p.Results.mRGCsOperateOnBackgroundAdaptedPhotocurrents;
    visualizeStimulusSequence = p.Results.visualizeStimulusSequence;


    STFparamsStruct = struct(...
        'backgroundChromaticity', STFbackgroundXYchromaticity, ...
        'backgroundLuminanceCdM2', STFmeanLuminanceCdM2, ...
        'chromaticity', STFchromaticity, ...
        'adjustBackgroundChromaticityToEqualizeLandMconeExcitations', adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
        'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition, ...
        'displayType', displayType, ...
        'displayLuminanceHeadroomPercentage', displayLuminanceHeadroomPercentage, ...
        'resolutionDegs', STFstimulusResolutionDegs, ...                       
        'positionDegs', theMRGCMosaic.eccentricityDegs, ...  
        'sizeDegs', 1.1*max(theMRGCMosaic.inputConeMosaic.sizeDegs), ...
        'sfSupport', STFsfSupport, ...
        'orientationDeltaDegs', orientationDeltaDegs, ...
        'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs);


    RGCMosaicConstructor.helper.simulateExperiment.spatialTransferFunction(...
        theMRGCMosaic, theOI, ...
        STFparamsStruct, ...
        theInputConeMosaicSTFResponsesFullFileName, ...
        theMRGCMosaicSTFResponsesFullFileName, ...
        'nonLinearitiesList', nonLinearitiesList, ...
        'photocurrentParams', photocurrentParams, ...
        'customTemporalFrequencyAndContrast', customTemporalFrequencyAndContrast, ...
        'debugInputConeMosaicPcurrentResponse', debugInputConeMosaicPcurrentResponse, ...
        'computeInputConeMosaicResponses', computeInputConeMosaicResponses, ...
        'mRGCsOperateOnBackgroundAdaptedPhotocurrents', mRGCsOperateOnBackgroundAdaptedPhotocurrents, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations', computeInputConeMosaicResponsesBasedOnConeExcitations, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
        'onlyInspectInputConeMosaicResponses', onlyInspectInputConeMosaicResponses, ...
        'computeMRGCMosaicResponses', computeMRGCMosaicResponses, ...
        'visualizeResponse', visualizeMosaicResponse, ...
        'visualizeStimulusSequence', visualizeStimulusSequence);
end

