%
%
% RGCMosaicAnalyzer.compute.mosaicSTFanalysisForTargetedCellPopulation()
%
%
function mosaicSTFanalysisForTargetedCellPopulation(...
    theMRGCMosaicSTFResponsesFullFileName, ...
    theAnalyzedSTFsFileName, ...
    targetedCenterPurityRange, ...
    targetedCenterConeNumerosityRange, ...
    targetedSurroundPurityRange, ...
    targetedRadialEccentricityRange)

    theMRGCMosaicSTFResponsesFullFileName
    pause
    theData = who('-file', theMRGCMosaicSTFResponsesFullFileName)
    pause
    photocurrentBasedSTFsComputed = ismember('theMRGCMosaicPcurrentBasedResponseTemporalSupportSeconds', theData);

    theNoiseFreeSpatioTemporalMRGCMosaicPcurrentBasedResponses2DSTF = [];
    theMRGCMosaicPcurrentBasedResponseTemporalSupportSeconds = [];

    if (photocurrentBasedSTFsComputed)
        load(theMRGCMosaicSTFResponsesFullFileName, ...
            'theMRGCMosaic', 'stimParams', ...
            'theNoiseFreeSpatioTemporalMRGCMosaicResponses2DSTF', ...
            'theMRGCMosaicResponseTemporalSupportSeconds', ...
            'theNoiseFreeSpatioTemporalMRGCMosaicPcurrentBasedResponses2DSTF', ...
            'theMRGCMosaicPcurrentBasedResponseTemporalSupportSeconds');
    else
        load(theMRGCMosaicSTFResponsesFullFileName, ...
            'theMRGCMosaic', 'stimParams', ...
            'theNoiseFreeSpatioTemporalMRGCMosaicResponses2DSTF', ...
            'theMRGCMosaicResponseTemporalSupportSeconds');
    end

    
    analyzeSTFresponsesForTargetMRGCs(...
        stimParams, ...
        theMRGCMosaic, ...
        theNoiseFreeSpatioTemporalMRGCMosaicResponses2DSTF, ...
        theMRGCMosaicResponseTemporalSupportSeconds, ...
        theNoiseFreeSpatioTemporalMRGCMosaicPcurrentBasedResponses2DSTF, ...
        theMRGCMosaicPcurrentBasedResponseTemporalSupportSeconds, ...
        targetedCenterPurityRange, ...
        targetedCenterConeNumerosityRange, ...
        targetedSurroundPurityRange, ...
        targetedRadialEccentricityRange, ...
        theAnalyzedSTFsFileName);
end

function analyzeSTFresponsesForTargetMRGCs(...
    stimParams, ...
    theMRGCMosaic, ...
    theMRGCMosaicConeExcitationsBasedResponses, ...
    theMRGCMosaicConeExcitationsResponseTemporalSupportSeconds, ...
    theMRGCMosaicPhotocurrentBasedResponses, ...
    theMRGCMosaicPhotocurrentResponseTemporalSupportSeconds, ...
    targetedCenterPurityRange, ...
    targetedCenterConeNumerosityRange, ...
    targetedSurroundPurityRange, ...
    targetedRadialEccentricityRange, ...
    analyzedSTFsFileName)

% Find the RGCs with the desired target properties
[targetRGCindices, theSurroundConePurities, theCenterConeDominances, ...
    theCenterConeNumerosities, theCenterConePurities] = theMRGCMosaic.indicesOfRGCsWithinTargetedPropertyRanges( ...
    targetedCenterConeNumerosityRange, ...
    targetedSurroundPurityRange, ...
    targetedRadialEccentricityRange, ...
    targetedCenterPurityRange);

fprintf('\n\nStats for %d mRGCs (out of a total of %d)\n', numel(targetRGCindices), theMRGCMosaic.rgcsNum)
examinedCenterConePurityRange     = [min(theCenterConePurities(:)) max(theCenterConePurities(:))]
examinedCenterConeDominanceRange  = [min(theCenterConeDominances(:)) max(theCenterConeDominances(:))]
examinedCenterConeNumerosityRange = [min(theCenterConeNumerosities(:)) max(theCenterConeNumerosities(:))]
examinedSurroundConePurityRange   = [min(theSurroundConePurities(:)) max(theSurroundConePurities(:))];
fprintf('\n\n');

% Sort cells according to their center cone numerosity
[~,idx] = sort(theCenterConeNumerosities, 'ascend');

targetRGCindices = targetRGCindices(idx);
theCenterConePurities = theCenterConePurities(idx);
theCenterConeNumerosities = theCenterConeNumerosities(idx);
theCenterConeDominances = theCenterConeDominances(idx);
theSurroundConePurities = theSurroundConePurities(idx);

orientationsNum = size(theMRGCMosaicConeExcitationsBasedResponses,1)
sfsNum = size(theMRGCMosaicConeExcitationsBasedResponses,2)

theExcitationsBasedTargetSTFamplitudeSpectra = zeros(numel(targetRGCindices), orientationsNum, sfsNum);
thePhotocurrentsBasedTargetSTFamplitudeSpectra = zeros(numel(targetRGCindices), orientationsNum, sfsNum);
theExcitationsBasedTargetSTFphaseSpectra = zeros(numel(targetRGCindices), orientationsNum, sfsNum);
thePhotocurrentsBasedTargetSTFphaseSpectra = zeros(numel(targetRGCindices), orientationsNum, sfsNum);

fprintf('Computing STFs for %d target mRGCs', numel(targetRGCindices));

parfor iRGC = 1:numel(targetRGCindices)
    theRGCindex = targetRGCindices(iRGC);

    for iOri = 1:orientationsNum

        [theExcitationsBasedTargetSTFamplitudeSpectra(iRGC, iOri, :), ...
            theExcitationsBasedTargetSTFphaseSpectra(iRGC, iOri, :)] = computeSTFamplitude(...
            theMRGCMosaicConeExcitationsResponseTemporalSupportSeconds, ...
            squeeze(theMRGCMosaicConeExcitationsBasedResponses(iOri, :, :, theRGCindex)), ...
            stimParams.temporalFrequencyHz);

        [thePhotocurrentsBasedTargetSTFamplitudeSpectra(iRGC, iOri, :), ...
            thePhotocurrentsBasedTargetSTFphaseSpectra(iRGC, iOri, :)] = computeSTFamplitude(...
            theMRGCMosaicPhotocurrentResponseTemporalSupportSeconds, ...
            squeeze(theMRGCMosaicPhotocurrentBasedResponses(iOri, :, :, theRGCindex)), ...
            stimParams.temporalFrequencyHz);

    end % iOri
end % for iRGC

save(analyzedSTFsFileName, ...
    'stimParams', ...
    'targetRGCindices', ...
    'theCenterConePurities', ...
    'theCenterConeNumerosities', ...
    'theCenterConeDominances', ...
    'theSurroundConePurities', ...
    'theExcitationsBasedTargetSTFamplitudeSpectra', ...
    'thePhotocurrentsBasedTargetSTFamplitudeSpectra', ...
    'theExcitationsBasedTargetSTFphaseSpectra', ...
    'thePhotocurrentsBasedTargetSTFphaseSpectra');

fprintf('\n\nSaved STFs to %s\n\n', analyzedSTFsFileName);


for iRGC = 1:numel(targetRGCindices)

    if (stimParams.coneContrasts(1) == 1) && ...
       (stimParams.coneContrasts(2) == 0) && ...
       (stimParams.coneContrasts(3) == 0) && ...
       (theCenterConeDominances(iRGC) ~= cMosaic.LCONE_ID)

        % Skip. L-cone isolating stimulus but not L-cone dominated RF center
        continue;
    end

    if (stimParams.coneContrasts(1) == 0) && ...
       (stimParams.coneContrasts(2) == 1) && ...
       (stimParams.coneContrasts(3) == 0) && ...
       (theCenterConeDominances(iRGC) ~= cMosaic.MCONE_ID)

        % Skip. M-cone isolating stimulus but not M-cone dominated RF center
        continue;
    end

    % For non cone-isolating gratings we do the analysis no matter what the RF center dominance


    hFig = figure(1); clf;
    set(hFig, 'Position', [10 10 1100 1100], 'Color', [1 1 1]);
    for iOri = 1:orientationsNum

        ax = subplot(1,orientationsNum,iOri);
        normExcitationsSTF = squeeze(theExcitationsBasedTargetSTFamplitudeSpectra(iRGC, iOri, :));
        normPhotocurrentSTF = squeeze(thePhotocurrentsBasedTargetSTFamplitudeSpectra(iRGC, iOri, :));
        [p1,peakSFindex1] = max(normExcitationsSTF);
        [p2,peakSFindex2] = max(normPhotocurrentSTF);
        if (p1 > p2)
            peakSFindex = peakSFindex1;
        else
            peakSFindex = peakSFindex2;
        end

        factorToMatchLowSFs = normExcitationsSTF(peakSFindex)/normPhotocurrentSTF(peakSFindex);
        plot(ax, stimParams.spatialFrequencyCPD, normExcitationsSTF, 'ko-', 'LineWidth', 1.5, 'MarkerSize', 12);
        hold(ax, 'on');
        plot(ax, stimParams.spatialFrequencyCPD, normPhotocurrentSTF*factorToMatchLowSFs, 'rs-', 'LineWidth', 1.5, 'MarkerSize', 12);
        set(ax, 'XScale', 'log', 'XTick', [0.01 0.03 0.1 0.3 1 3 10 30], 'FontSize', 20, 'YLim', [0 1.0], 'YTick', 0:0.1:2);
        legend(ax, {'cone excitations based', 'photocurrent based'});

        if (theCenterConeDominances(iRGC) == cMosaic.LCONE_ID)
            title(ax,sprintf('%d-cone RF center (L-cone dom.)\nstim. orientation = %d (degs)', ...
                theCenterConeNumerosities(iRGC), stimParams.orientationDegs(iOri)));
        elseif (theCenterConeDominances(iRGC) == cMosaic.MCONE_ID)
            title(ax,sprintf('%d-cone RF center (M-cone dom.)\nstim. orientation = %d (degs)', ...
                theCenterConeNumerosities(iRGC), stimParams.orientationDegs(iOri)));
        elseif (theCenterConeDominances(iRGC) == cMosaic.SCONE_ID)
            title(ax,sprintf('%d-cone RF center (S-cone dom.)\nstim. orientation = %d (degs)', ...
                theCenterConeNumerosities(iRGC), stimParams.orientationDegs(iOri)));
        end

        grid(ax, 'on')
    end % for iOri
    drawnow;
    disp('Hit enter to continue')
    pause
end % for iRGC

end


function [theSTFamplitudeSpectrum, theSTFphaseDegsSpectrum] = computeSTFamplitude(...
    temporalSupportSeconds, allSFresponseTimeSeries, temporalFrequencyHz)

theSFsNum = size(allSFresponseTimeSeries,1);
theSTFamplitude = zeros(1, theSFsNum);
theSTFphaseDegs = zeros(1, theSFsNum);

for iSF = 1:theSFsNum
    theResponseTimeSeries = allSFresponseTimeSeries(iSF,:);
    [theFittedSinusoid, fittedParams] = ...
        RGCMosaicConstructor.helper.fit.sinusoidToResponseTimeSeries(...
        temporalSupportSeconds, theResponseTimeSeries, temporalFrequencyHz, temporalSupportSeconds);

    theSTFamplitudeSpectrum(iSF) = fittedParams(1);
    theSTFphaseDegsSpectrum(iSF) = fittedParams(2);

    debugFit = false;
    if (debugFit)
        figure(44);
        plot(temporalSupportSeconds, theResponseTimeSeries, 'ro', 'MarkerFaceColor', [1 0.5 0.5])
        hold on;
        plot(temporalSupportSeconds, theFittedSinusoid, 'k-', 'LineWidth', 1.0);
        fittedParams
        drawnow
        disp('hit enter to continue')
        pause
    end

end % iSF
end

