%
% RGCMosaicAnalyzer.compute.mosaicTTFsForStimulusChromaticityAndOptics
%
function mosaicTTFsForStimulusChromaticityAndOptics(...
    theMRGCMosaic, theOI, ...
    TTFmeanLuminanceCdM2, ...
    TTFbackgroundXYchromaticity, ...
    TTFchromaticity, ...
    TTFcontrast, ...
    TTFfrequencySupport, ...
    stimulusResolutionDegs, ...
    stimulusPositionDegs, stimulusSizeDegs, stimulusShape, ...
    coneFundamentalsOptimizedForStimPosition, ...
    theInputConeMosaicTTFResponsesFullFileName, ...
    theMRGCMosaicTTFResponsesFullFileName, ...
    visualizeMosaicResponse, ...
    varargin)


    p = inputParser;
    p.addParameter('mRGCNonLinearityParams', [], @(x)(isempty(x))||(isstruct(x)));
    p.addParameter('displayType', '', @ischar);
    p.addParameter('displayLuminanceHeadroomPercentage', 1/100, @isscalar);
    p.addParameter('debugInputConeMosaicPcurrentResponse', false, @islogical);   
    p.addParameter('temporalPhaseIncrementDegs', 30, @isscalar);
    p.addParameter('computeInputConeMosaicResponses', true, @islogical);
    p.addParameter('computeInputConeMosaicResponsesBasedOnConeExcitations', true, @islogical);
    p.addParameter('computeInputConeMosaicResponsesBasedOnPhotocurrents', true, @islogical);
    p.addParameter('inspectInputConeMosaicResponses', false, @islogical);
    p.addParameter('computeMRGCMosaicResponses', false, @islogical);
    p.addParameter('visualizeStimulusSequence', false, @islogical);
    p.addParameter('visualizeStimulusOnMosaic', false, @islogical);

    % Execute the parser
    p.parse(varargin{:});
    mRGCNonLinearityParams = p.Results.mRGCNonLinearityParams;
    displayType = p.Results.displayType;
    displayLuminanceHeadroomPercentage = p.Results.displayLuminanceHeadroomPercentage;
    debugInputConeMosaicPcurrentResponse = p.Results.debugInputConeMosaicPcurrentResponse;
    temporalPhaseIncrementDegs = p.Results.temporalPhaseIncrementDegs;
    computeInputConeMosaicResponses = p.Results.computeInputConeMosaicResponses;
    computeInputConeMosaicResponsesBasedOnConeExcitations = p.Results.computeInputConeMosaicResponsesBasedOnConeExcitations;
    computeInputConeMosaicResponsesBasedOnPhotocurrents = p.Results.computeInputConeMosaicResponsesBasedOnPhotocurrents;
    inspectInputConeMosaicResponses = p.Results.inspectInputConeMosaicResponses;
    computeMRGCMosaicResponses = p.Results.computeMRGCMosaicResponses;
    visualizeStimulusSequence = p.Results.visualizeStimulusSequence;
    visualizeStimulusOnMosaic = p.Results.visualizeStimulusOnMosaic;

    TTFparamsStruct = struct(...
        'backgroundChromaticity', TTFbackgroundXYchromaticity, ...
        'backgroundLuminanceCdM2', TTFmeanLuminanceCdM2, ...
        'chromaticity', TTFchromaticity, ...
        'contrast', TTFcontrast, ...
        'coneFundamentalsOptimizedForStimPosition', coneFundamentalsOptimizedForStimPosition, ...
        'displayType', displayType, ...
        'displayLuminanceHeadroomPercentage', displayLuminanceHeadroomPercentage, ...
        'stimulusResolutionDegs', stimulusResolutionDegs,  ...
        'stimulusPositionDegs', stimulusPositionDegs, ...
        'stimulusSizeDegs', stimulusSizeDegs, ...
        'stimulusShape', stimulusShape, ...
        'positionDegs', theMRGCMosaic.eccentricityDegs, ...  
        'sizeDegs', 1.1*max(theMRGCMosaic.inputConeMosaic.sizeDegs), ...
        'tfSupport', TTFfrequencySupport, ...
        'temporalPhaseIncrementDegs', temporalPhaseIncrementDegs);


    RGCMosaicConstructor.helper.simulateExperiment.temporalTransferFunction(...
        theMRGCMosaic, theOI, ...
        TTFparamsStruct, ...
        theInputConeMosaicTTFResponsesFullFileName, ...
        theMRGCMosaicTTFResponsesFullFileName, ...
        'mRGCNonLinearityParams', mRGCNonLinearityParams, ...
        'debugInputConeMosaicPcurrentResponse', debugInputConeMosaicPcurrentResponse, ...
        'computeInputConeMosaicResponses', computeInputConeMosaicResponses, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations', computeInputConeMosaicResponsesBasedOnConeExcitations, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
        'inspectInputConeMosaicResponses', inspectInputConeMosaicResponses, ...
        'computeMRGCMosaicResponses', computeMRGCMosaicResponses, ...
        'visualizeResponse', visualizeMosaicResponse, ...
        'visualizeStimulusSequence', visualizeStimulusSequence, ...
        'visualizeStimulusOnMosaic', visualizeStimulusOnMosaic);
end